### ISSUE TITLE
secure conversion to ActionContext object for context added to source

### ISSUE THREAD

**Issue by elsdvlee** [comunica/comunica#1003]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

At present a context can be added to a source making a new ActionContext. 
e.g. const context = {sources: [ {value:'path_to_source', context : new ActionContext({'@comunica/bus-context-preprocess:mapping':'path_to_mapping'})}] }
I would like to be able to add a context using a plain object, and count on Comunica to convert this object to a ActionContext, like is done with the other context objects. 
e.g. const context = {sources: [ {value:'path_to_source', context :{'@comunica/bus-context-preprocess:mapping':'path_to_mapping'}}] }

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| €272 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment]
Once this has been implemented, we should definitely document this on https://comunica.dev/docs/query/advanced/context/

**Comment by rubensworks** [comment]
A bounty has been placed on this issue via the Comunica Association (see original post).

**Comment by rubensworks** [comment]
Note to self: this should be documented on the website.
