### ISSUE TITLE
Insert Data query in a local file

### ISSUE THREAD

**Issue by CFerrara98** [comunica/comunica#1005]
#### Question:

Good morning, 
is it possible use comunica in a Node.js webapp to update a **_local turtle file_** with some INSERT DATA queries?

According to the documentation, it seems that this feature is not aviable.
https://comunica.dev/docs/query/getting_started/update_app/

**Comment by jeswr** [comment]
If you want to run a NodeJS application and execute queries (including updates) then you will need to use this configuration of Comunica https://github.com/comunica/comunica/tree/master/engines/query-sparql-file#readme. This supports update queries on local files.


This *will not* work in the browser, as the browser cannot access the local file system for security reasons https://www.howtogeek.com/devops/web-apps-can-interact-with-your-filesystem-now/. If you want to do something from the browser then I would recommend that you would upload the file in the app, load/parse the data into an [N3.js](https://github.com/rdfjs/n3.js) store, and then execute an update query using that as store your source. You can then serialize the updated data and download it.
