### ISSUE TITLE
Feat: Forward `test` data to `run` method

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1006]
#### Issue type:

- :snail: Performance issue 

____
#### Description:

In many cases the `test` method shares computations with the `run` method; [or in some cases are even identical](https://github.com/comunica/comunica/blob/bceec4f8b7985565258fb024a4f43e5f32ff99bb/packages/actor-abstract-mediatyped/lib/ActorAbstractMediaTyped.ts#L22-L48). For performance reasons it would be useful to have a way of forwarding this information to the `run` method to prevent repeated computations.

I suggest the data either be forwarded by forwarding the return value of the test method, or having a special key in the context object where test methods place data.

**Comment by rubensworks** [comment]
That might be useful indeed.
Could also be achieved by adding a second argument to `run` (but this would be a breaking change).

**Comment by rubensworks** [comment]
Will be included in v4.
