### ISSUE TITLE
Feature: Support HTTPS Retries

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1012]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

In order to better support unstable internet connections, Comunica should have a context entry option to enable retries on failed network calls. I would say that the number and frequency of retries should be configurable.

**Comment by rubensworks** [comment]
Good idea!
Would be great in combination with the new HTTP timeout functionality @Tpt is working on #70.
