### ISSUE TITLE
Release minor versions as stable (not alpha)

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1017]
#### Issue type:

- :heavy_plus_sign: Feature request 

All new releases in the last 2 weeks have been marked as alpha (see below screenshot of @comunica/core versions.

@rubensworks could you please make a release that is not marked as alpha.

![image](https://user-images.githubusercontent.com/63333554/176100545-fed851e3-04f9-42c9-868d-3048b2198a99.png)

____

**Comment by rubensworks** [comment]
Preparing release 2.3.0 as we speak! :-)
