### ISSUE TITLE
Comunica browser query example in docs not working

### ISSUE THREAD

**Issue by th0rgall** [comunica/comunica#1028]
#### Issue type:

- :bug: Bug 

____
#### Description:

The example here https://comunica.dev/docs/query/getting_started/query_browser_app/ is not working for me.

See https://codesandbox.io/s/comunica-issue-0hjrx1?file=/index.html
It is a simple HTML file, I copied the example as-is, changing only the script source to a working path.

<img width="1095" alt="Screenshot 2022-07-18 at 17 34 21" src="https://user-images.githubusercontent.com/11543641/179547994-7f4bf8a3-2261-48c5-bcbe-4e20a5c94fa6.png">

____
#### Environment:

The comunica-browser embedded script: https://rdf.js.org/comunica-browser/versions/v2/engines/query-sparql-rdfjs/comunica-browser.js

> 

#### Crash log:

```
MediatorRace.ts:23 Uncaught (in promise) Error: urn:comunica:default:rdf-resolve-quad-pattern/mediators#main mediated over all rejecting actors:
urn:comunica:default:rdf-resolve-quad-pattern/actors#rdfjs-source requires a single source with an rdfjsSource to be present in the context.
Actor urn:comunica:default:rdf-resolve-quad-pattern/actors#federated can only resolve quad pattern queries against a sources array.
    at MediatorRace.ts:23:20
```

**Comment by rubensworks** [comment]
The new link you're using refers to the RDF/JS version of Comunica, which doesn't allow querying from URLs.
You're probably looking for the regular version of Comunica: https://rdf.js.org/comunica-browser/versions/v2/engines/query-sparql/comunica-browser.js

The web page has now been fixed with the correct URL.

**Comment by th0rgall** [comment]
Yes, that fixes it https://codesandbox.io/s/comunica-issue-0hjrx1?file=/index.html

Just had to be careful too that the source URL uses https when running the https-hosted CodeSandbox, but that was easy to detect & fix. Thanks!
