### ISSUE TITLE
"EXISTS found, but no existence hook provided" in Optional block

### ISSUE THREAD

**Issue by ericctsf** [comunica/comunica#1029]
#### Issue type:

- :bug: Bug 

____
#### Description:

The following code test throws "EXISTS found, but no existence hook provided" but should pass
Note that these queries worked in @comunica/actor-init-sparql-rdfjs
Also presumably similar issue to https://github.com/comunica/comunica/issues/650
```
import 'mocha'
import n3 from 'n3'
import { QueryEngine } from '@comunica/query-sparql-rdfjs'
import chai from 'chai'

const sparql = new QueryEngine()

describe('comunica sparql', () => {
  it('Does not support EXISTS sparql keyword', async () => {
    const store = new n3.Store()
    const subject = n3.DataFactory.namedNode('http://subject')
    const predicate = n3.DataFactory.namedNode('http://predicate')
    const object = n3.DataFactory.namedNode('http://object')
    const blank = n3.DataFactory.blankNode()
    const spo = n3.DataFactory.quad(subject, predicate, object)
    const bpo = n3.DataFactory.quad(blank, predicate, object)
    store.addQuads([spo, bpo])
    const quadStream = await sparql.queryQuads(`
      CONSTRUCT {
        ?s ?p ?o.
      }
      WHERE { 
        ?s ?p ?o.
        OPTIONAL {
          FILTER EXISTS {
            ?s2 ?p ?o.
            FILTER (?s != ?s2)
          }
        }
      }
      `,
      { sources: [store] })
    const result_quads = await quadStream.toArray()
    chai.expect(result_quads).to.deep.equal([{
      termType: 'Quad',
      value: '',
      graph: {
        termType: 'DefaultGraph',
        value: '',
      },
      subject: {
        id: 'http://subject',
      },
      predicate: {
        id: 'http://predicate',
      },
      object: {
        id: 'http://object',
      },
    }, {
      termType: 'Quad',
      value: '',
      graph: {
        termType: 'DefaultGraph',
        value: '',
      },
      subject: {
        termType: 'BlankNode',
        value: 'bc_0_n3-01',
      },
      predicate: {
        id: 'http://predicate',
      },
      object: {
        id: 'http://object',
      },
    }])
  })
})

```

____
#### Environment:

 `node ./packages/actor-init-query/bin/query.js -v`--> not part of     "@comunica/query-sparql-rdfjs": "^2.3.0",

#### Crash log:

NA

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| €136 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment]
Ah, I already see the problem. It's similar to the problem we had before indeed.

Passing `this.mediatorQueryOperation` as second argument to [this call](https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-leftjoin/lib/ActorQueryOperationLeftJoin.ts#L39) should fix the problem.

Now that I think of it, the second argument of `ActorQueryOperation.getAsyncExpressionContext` should probably become mandatory, to avoid issues like these in the future.

A PR with a fix for this is definitely welcome! :-)

**Comment by heartpunk** [comment]
As discussed with @rubensworks, I will work on this issue via the Comunica Association.

**Comment by heartpunk** [comment]
I've got the test failing as described above (albeit with no attention to conventions yet), moving on to the proposed fix, and then checking style guides and fixing things up, next.

**Comment by rubensworks** [comment]
@heartpunk Great!

**Comment by heartpunk** [comment]
Brushing up on intricacies of the project to get coverage lifted back up to where it should be. Lil bit to get familiar with here so this might not be quite as quick, but hoping to wrap it up within a few days at worst. Will update as I have questions or progress.

**Comment by heartpunk** [comment]
(Oh, to be clear, the test has failed and now passes. It's just the coverage threshold I need to work on.)

**Comment by rubensworks** [comment]
Hi @heartpunk, just checking in to see how you are progressing on this issue?

**Comment by heartpunk** [comment]
I'd been blocked on it. I left a [comment](https://github.com/comunica/comunica/pull/1046#discussion_r1013012802) inline on the pull request waiting for your attention. I could probably figure this out with a good bit of time put into it, but I'd hoped you might have a pointer.

I tried rebasing the changes in master in last night but got bogged down in conflicts; will give that another go so the branch is more up to date at least.

**Comment by heartpunk** [comment]
Oh oops! I was worried about being too pushy, so I didn't reiterate it. Work trauma has messed with my understanding some communication norms as well as I used to – recalibrating pervasively. Glad we're past it now!

**Comment by rubensworks** [comment]
Hi @heartpunk, how is the work progressing?

**Comment by rubensworks** [comment]
Hi @heartpunk, as per the [bounty process](https://comunica.dev/association/bounty_process/) on timeliness, I'll unassign you from this issue, and close your PR, so that other developers may be able to take up this bounty.

If you still would like to work on this issue, do let me know :-)
