### ISSUE TITLE
resultToString throws stream._fillBuffer is not a function when querying GraphDB solely

### ISSUE THREAD

**Issue by vterzic** [comunica/comunica#1034]
#### Issue type:

- :bug: Bug 

____
#### Description:

`queryEngine.resultToString()` throws error when querying GraphDB solely. Once you add additional source, everything works as expected.

Reproducible code example: https://gist.github.com/vterzic/66d2718fec73f4e842731380533b1ce1
____
#### Environment:

| software         | version
| ---------------- | -------
| Comunica Engine  | 2.3.0 
| node             | v16.13.2
| npm              | 8.1.2
| yarn             | _Yarn is unavailable_
| Operating System | darwin (Darwin 20.5.0)
| GraphDB | 9.10.1 |
#### Crash log:
https://gist.github.com/vterzic/66d2718fec73f4e842731380533b1ce1?permalink_comment_id=4255805#gistcomment-4255805

**Comment by rubensworks** [comment]
@jeswr @jacoscaz This code makes use of the `wrap` function of AsyncIterator.
Do you know if this code does not expose the `_fillBuffer` method anymore?

**Comment by jeswr** [comment]
`wrap` can now bypass the `WrappingIterator` in certain cases (e.g. if it was already an AsyncIterator, it will just return the input). In such cases `_fillBuffer` will not exist.

**Comment by jeswr** [comment]
Not sure why this would be a problem on some sparql endpoints and not others though - it shouldn't change the nature of the iterator

**Comment by jacoscaz** [comment]
Why are we using a private method of `AsyncIterator`, though?

**Comment by rubensworks** [comment]
I'm sure it will also break in many other places :-)

Is there another method we can use to "start" the iterator?

**Comment by rubensworks** [comment]
For reference: https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-sparql-endpoint/lib/ActorQueryOperationSparqlEndpoint.ts#L168-L171

**Comment by jacoscaz** [comment]
Oh I think I understand what is going on. Metadata can only get to the end of the chain once the entire chain begins to read, so we're invoking `_fillBuffer()` to force that even when we haven't actually begun to read items.

Mh... We should probably temporarily fix this by wrapping into a `BufferingIterator` within Comunica (or something like that) and then figure out whether we can decouple metadata propagation.

I'll have a look, I think we can do something relatively simple to address this.

**Comment by rubensworks** [comment]
@jacoscaz Jesse suggested a similar fix (he's sitting next to me), he's going to look into it.

**Comment by jacoscaz** [comment]
Awesome! We probably don't even need `BufferingIterator` but simply to kickstart things by calling `read()` once, buffering the first item, and then simply let subsequent `read()` invocation pass through to the source. LMK if I can help!

**Comment by rubensworks** [comment]
> but simply to kickstart things by calling read() once, buffering the first item

Might be dangerous, as we can loose the first item this way.

**Comment by jacoscaz** [comment]
There's got to be a way to buffer the first item until it's actually needed without incurring in the performance penalty brought by the internal buffering. Something like:

```typescript

import { AsyncIterator, IntegerIterator }  from 'asynciterator';

class KickstartIterator<T> extends AsyncIterator<T> {

  private _source: AsyncIterator<T>;
  private _started: boolean;
  private _first: T | null;

  constructor(source: AsyncIterator<T>) {

    super();

    this._started = false;
    this._first = null;
    this._source = source;
  
    const onSourceReadable = () => {
      if (this._started || this._first) {
        this.readable = true;
        return;
      }
      if ((this._first = source.read()) !== null) {
        this.readable = true;
      }
    };

    source.on('readable', onSourceReadable);

    if (source.readable) {
      onSourceReadable();
    }
  }

  read() {
    let item = null;
    if (this._started) {
      item = this._source.read();
    } else if (this._first) {
      item = this._first;
      this._started = true;
      this._first = null;
    }
    if (item === null) {
      this.readable = false;
    }
    return item;
  }
  

}

const ii = new IntegerIterator({ start: 0, step: 1, end: 9 });
const ki = new KickstartIterator(ii);


ki.on('data', (item) => { console.log('ITEM', item); });
```

I don't have time to test this ATM but the overall approach should work.

**Comment by vterzic** [comment]
Interestingly enough, removing   `'application/sparql-results+json'` mediaType argument from  the `queryEngine.resultToString()` call solves the issue.

**Comment by jeswr** [comment]
FYI there is a fix in the works - we just need to release [some upstream changes](https://github.com/RubenVerborgh/AsyncIterator/pull/80#issuecomment-1207371390) first.
