### ISSUE TITLE
How to convert literal to javascript object

### ISSUE THREAD

**Issue by zeroxbt** [comunica/comunica#1039]
#### Issue type:

- :question: Question 

____
#### Question:

When parsing a literal, is there a way to convert it to the corresponding JS type ? For example I'd like to be able to automatically convert a literal like : 

Literal {
  termType: 'Literal',
  value: '1',
  language: '',
  datatype: NamedNode {
    termType: 'NamedNode',
    value: 'http://www.w3.org/2001/XMLSchema#integer'
  }
}

to number. I was not able to find this in the docs.

**Comment by jeswr** [comment]
You could always use [termToPrimitive](https://github.com/LDflex/LDflex/blob/847a25ae5211264d7d62f0b9875509c8e7f69ade/src/valueUtils.js#L111-L140) from LDflex.

**Comment by zeroxbt** [comment]
Awesome, thanks !

**Comment by rubensworks** [comment]
There's also this library dedicated to this functionality: https://github.com/rubensworks/rdf-literal.js
