### ISSUE TITLE
Convert bnodes to variables internally

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#104]
At the moment, we have to check _if variable or blank node_ in a lot of places. We could simplify a lot of code by simply converting all blank nodes to variables after the query was parsed.

**Comment by rubensworks** [comment]
This issue is more urgent than initially though.

The current behaviour seems to cause issues in the SPARQL quad pattern resolve actor, as it can not handle queries with blank nodes.

**Comment by joachimvh** [comment]
Ah yea, that one. Yea that could be.
