### ISSUE TITLE
No valid SPARQL query results were found. 

### ISSUE THREAD

**Issue by zeroxbt** [comunica/comunica#1052]
#### Issue type:

- :bug: Bug 

____
#### Description:

When executing a query, the error `No valid SPARQL query results were found. ` is **sometimes** thrown. 

The code example and the error message are shown in [this gist](https://gist.github.com/zeroxbt/aea7774bf0f07793ee568350dadf96af).
____
#### Environment:

- Node.js version: 16.15.1
- @comunica/query-sparql version: 2.4.2

#### Crash log:

`No valid SPARQL query results were found.
at PassThrough. (/Users/zeroxbt/projects/project/node_modules/sparqljson-parse/lib/SparqlJsonParser.js:60:44)
at PassThrough.emit (node:events:527:28)
at endReadableNT (node:internal/streams/readable:1345:12)
at processTicksAndRejections (node:internal/process/task_queues:83:21)`

**Comment by rubensworks** [comment]
It's possible that your local endpoint doesn't fully follow the SPARQL JSON results spec, and doesn't always emit a `results` block.
We could work around this in the parser by making it a bit less strict, and not throw always an error when that `results` block is not present: https://github.com/rubensworks/sparqljson-parse.js/blob/f57434677453a9c69785fc082f8cd6c0ab33f277/lib/SparqlJsonParser.ts#L45-L69
Instead, we could only throw if a (new) `strict` option is enabled on the parser.

A PR on this is definitely welcome!

**Comment by zeroxbt** [comment]
I haven't had this issue before, but I recently switched from commonjs to esm and noticed it. Could that be the cause ?

**Comment by rubensworks** [comment]
> I recently switched from commonjs to esm and noticed it

No, it's probably because of some recent changes in the SPARQL/JSON parser, which may have coincided with your CJS/ESM migration.

**Comment by zeroxbt** [comment]
Hi @rubensworks, is there a version I can run where I won't experience this problem ?

**Comment by rubensworks** [comment]
@zeroxbt You could downgrade to the previous minor version.

But the fix is probably very easy though, so if you're up for it, you're welcome to provide a PR with a fix.

**Comment by rubensworks** [comment]
@zeroxbt The issue should be fixed now. Can you confirm on your after after resetting your lockfile+`node_modules` and reinstalling?

**Comment by rubensworks** [comment]
@zeroxbt The issue should be fixed now. Can you confirm on your after after resetting your lockfile+node_modules and reinstalling?

**Comment by zeroxbt** [comment]
It's fixed. Thanks @rubensworks !
