### ISSUE TITLE
Buffer is not defined when using latest rdfjs browser build of Comunica

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1053]
#### Issue type:

- :bug: Bug 

____
#### Description:

I think this is because readable-stream still requires a `buffer` polyfill https://www.npmjs.com/package/readable-stream but that polyfill was removed in https://github.com/comunica/comunica/pull/1023/files.

Pinging @Tpt 
____

**Comment by jeswr** [comment]
This also probably signals that it would be valuable to have a few integration tests for those bundles.

**Comment by Tpt** [comment]
That's interesting. Indeed, we need integration tests for the bundles. What is strange is that I had no problem to run these bundles directly and `buffer` is a dependency of Comunica. How are you building Comunica?

**Comment by rubensworks** [comment]
> That's interesting. Indeed, we need integration tests for the bundles. What is strange is that I had no problem to run these bundles directly and buffer is a dependency of Comunica. How are you building Comunica?

Just like this: https://github.com/comunica/comunica/blob/master/packages/actor-init-query/webpack.config.js
So I guess this is the one you were using as well.

**Comment by jeswr** [comment]
> How are you building Comunica

The issue was discovered in https://fragments.inrupt.com/sparql.html which directly loads https://rdf.js.org/comunica-browser/versions/latest/engines/query-sparql/comunica-browser.js

**Comment by jeswr** [comment]
> A PR on this is welcome! :-)

On it

**Comment by rubensworks** [comment]
Also related: https://github.com/comunica/jQuery-Widget.js/commit/049b4f3828338bfb0b11a998218c7e229513755a
