### ISSUE TITLE
Context preprocessor should set a single source as a destination - not just sources array of length 1

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1058]
#### Issue type:

- :bug: Bug 

____
#### Description:

Proposal - this https://github.com/comunica/comunica/blob/a9eaf5db72f4cd5364cdb0dda9eb5fdb7996a125/packages/actor-context-preprocess-source-to-destination/lib/ActorContextPreprocessSourceToDestination.ts#L20-L27 should become

```ts
// I think this function already exists in the federated quad pattern resolver
// so you could import that
function getSingleSourceContext(context): IDataSource | false {
      let sources: DataSources = context.get(KeysRdfResolveQuadPattern.sources);
      if (sources) {
           if (sources.length === 1) {
               return sources[0];
            }
         } else {
             const source = context.get(KeysRdfResolveQuadPattern.source);
             if (source)
               return source
         }
       return false
}

// the following is the content of the run method - the test method may also need to be updated 
    if (!action.context.get(KeysRdfUpdateQuads.destination)) {
        const source = getSingleSourceContext(action.context);
        if (source)
          return { context: action.context.set(KeysRdfUpdateQuads.destination, source) }
    }
    return action;
```
____

**Comment by rubensworks** [comment]
In the past, we allowed users to specify either `source` or `sources in their context.
This caused a bunch of problems unfortunately, since most of our logic is based on `sources`.
That is why we decided to only work with `sources` for everything above the federated actor,
and with `source` for everything below.
Since the context preprocessing happens before the federated actor, this should therefore work with `sources`.

If you have any input on how this approach can be improved, please let me know :-)

**Comment by jeswr** [comment]
> If you have any input on how this approach can be improved, please let me know :-)

If support for an input `source` as a user input has been dropped; then I suggest that this preprocessing does the following for the case of a sources array of length 1:
 - Set the `source` to be the element of that array.
 - Remove the `sources` key.
 - Set the destination to be the `source` if the destination is not defined.
 
 This should mean that the federated actor is bypassed entirely in this case. I suspect this will 
 
 >  This caused a bunch of problems unfortunately, since most of our logic is based on sources.
 
 I'm not quite sure which logic this is in reference to; but I'm assuming it is mainly logic around the federated actor itself? If lots of other actors are implicated then this will affect my answer above to be "lets reconsider that logic when if/when scoped sources are introduced"

**Comment by rubensworks** [comment]
> but I'm assuming it is mainly logic around the federated actor itself?

Indeed, mainly the federated actor. But there may be other places as well.

I'm open to a change in how this works, but this will probably require a major refactor of things.

**Comment by rubensworks** [comment]
Closing this. Feel free to re-open if you have concrete suggestions.
