### ISSUE TITLE
Bus-context-preprocess not listed in packages

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1062]
#### Issue type:

- :bug: Bug 

____
#### Description:

I can find it as a package on npm (https://www.npmjs.com/package/@comunica/bus-context-preprocess) but not in the pacakges folder here.

____

**Comment by rubensworks** [comment]
It's here? https://github.com/comunica/comunica/tree/master/packages/bus-context-preprocess

**Comment by jeswr** [comment]
Ah was mispelling when searching - my bad!
