### ISSUE TITLE
Handling broken URLs / ontology documents

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1069]
#### Issue type:

- :heavy_plus_sign: Feature request 

It would be good to have a way of defining custom behavior for when a link is broken - for instance trying to retrieve the link via the wayback machine instead (it seems like this package could be used for that https://www.npmjs.com/package/memento-client).

Actually in the case of the wayback machine it may be as simple as appending `http://wayback.archive-it.org/` to the URL.

One way of doing this would be to add custom `dereference` actors that enable this behavior.
____

**Comment by rubensworks** [comment]
Sounds related to the [fallback-based datasources approach discussed recently](https://github.com/comunica/comunica/issues/1061#issuecomment-1247626851).

Note that we already have a memento actor here: https://github.com/comunica/comunica/tree/master/packages/actor-http-memento
