### ISSUE TITLE
Basic authentication for a specific source

### ISSUE THREAD

**Issue by gvanderh** [comunica/comunica#1074]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

const bindingsStream = await myEngine.queryBindings(`SELECT * WHERE { ?s ?p ?o }`, {
  sources: ['http://username:password@example.org/page'],
});

Built-in node fetch (at least recent versions) does not support credentials being passed in an URL for security reasons. Work-arounds are to pass a custom fetch function or use httpAuth on a context (but this applies to all sources). To support querying multiple sources with specific credentials, I would suggest to pass the httpAuth variable per source instead of per context, e.g.

const bindingsStream = await myEngine.queryBindings(`SELECT * WHERE { ?s ?p ?o }`, {
  sources: [ type: 'sparql', value: 'http://example.org/page', httpAuth: 'username:password' ],
});

**Comment by rubensworks** [comment]
This should already be possible using source-specific contexts.

Something like this should work (untested):

```
sources: [ type: 'sparql', value: 'http://example.org/page', context: new ActionContext({ httpAuth: 'username:password' }) ],
```

In any case, some simplifications on passing such sub-contexts are needed (see https://github.com/comunica/comunica/issues/1003)

**Comment by gvanderh** [comment]
Thanks for the fast feedback Ruben!
