### ISSUE TITLE
beforeAllActors and AfterAllActors configuration property

### ISSUE THREAD

**Issue by constraintAutomaton** [comunica/comunica#1079]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

In the configuration files of comunica it is possible to specify that an [actor must be tested before another](https://github.com/comunica/comunica/blob/33de86f086bf3be418545f07aa57f44d1461c28b/packages/core/lib/Actor.ts#L25) in the context of mediation for example [dereference actor](https://github.com/comunica/comunica/blob/master/engines/config-query-sparql/config/dereference/actors.json). But it is not yet possible to defined statement such as `beforeAllActors` or `AfterAllActors` which in some context can be really useful by rendering the configuration file less verbose and more maintainable.

**Comment by rubensworks** [comment]
Yes, good idea. The only practical problem with these is that only a single actor per bus could make use of them.
So our implementation of this should error if it detects that two actors per bus make use of them.
