### ISSUE TITLE
Allow shorthand urls in the command line

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1083]
#### Issue type:

- :heavy_plus_sign: Feature request 

For instance I would like the following to work

```bash
comunica-sparql rubensworks.net \
    "SELECT * WHERE { ?s ?p ?o } LIMIT 100"
```

____

**Comment by rubensworks** [comment]
Not sure I agree. This would make it difficult in cases where one would want to query a local file named `rubensworks.net` (using `comunica-sparql-file`).

**Comment by rubensworks** [comment]
Ok to close this @jeswr?
