### ISSUE TITLE
Optional fails on N3 store

### ISSUE THREAD

**Issue by danielbeeke** [comunica/comunica#1095]
#### Issue type:

- :bug: Bug 

____
#### Description:

Given the following two triples I would expect four bindings as the result of the following query.
```
<http://ex.org/Pluto> <http://ex.org/type> <http://ex.org/Dog>
<http://ex.org/Mickey> <http://ex.org/name> "Lorem ipsum"@nl

```

```
  SELECT * WHERE { 
    ?s ?p ?o .

    OPTIONAL {
      ?s <http://ex.org/name> ?name .
      FILTER(lang(?name) = 'nl')
    }
  }
```
_Expectation_
s, p, o and name

_Actual_
s, p and o

When changing the language filter to something that does not exists I get zero bindings.

See http://danielbeeke.nl/comunica-rdfjs-optional-bug/ for a reproduction.
And the console on https://github.com/danielbeeke/comunica-rdfjs-optional-bug.
____
#### Environment:

I am using N3 and Comunica in a web site.
N3 is fetched as an ESM module.
Comunica is included via a script tag.

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| €544 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment]
Possible a bug in either https://github.com/comunica/comunica/tree/master/packages/actor-rdf-join-optional-bind or https://github.com/comunica/comunica/tree/master/packages/actor-rdf-join-optional-nestedloop

**Comment by rubensworks** [comment]
A bounty has been placed on this issue via the Comunica Association (see original post).

**Comment by danielbeeke** [comment]
I found out where the bindings are dropped.
They are returned in the first place, it goes through all kinds of actors. 
But when almost being returned they are dropped because there is an expression error.

It happens in **ActorQueryOperationLeftJoin**. 
When calling **evaluator.evaluateAsEBV(bindings)** there is an error: **Unbound variable '"?name"'**
So the bug seems to be happening inside **Sparqlee** or **ActorQueryOperationLeftJoin**.

**Comment by danielbeeke** [comment]
Should the bindings object have all the keys but maybe with empty values before being sent to Sparqlee?

**Comment by rubensworks** [comment]
> But when almost being returned they are dropped because there is an expression error.

The fact that there's an expression error is probably the problem then. So this might be a bug in sparqlee.

**Comment by rubensworks** [comment]
> When calling evaluator.evaluateAsEBV(bindings) there is an error: Unbound variable '"?name"'

The bindings object should have a binding for `?name` at this stage I suspect, based on your example data.
So if that is not the case, then the join may be going wrong somehow.

**Comment by danielbeeke** [comment]
```
NamedNode { id: 'http://ex.org/Pluto' } NamedNode { id: 'http://ex.org/type' } NamedNode { id: 'http://ex.org/Dog' } undefined
NamedNode { id: 'http://ex.org/Mickey' } NamedNode { id: 'http://ex.org/name' } Literal { id: '"Lorem ipsum"@nl' } Literal { id: '"Lorem ipsum"@nl' }

```
The first line is dropped. The second line goes on.
The first line / binding is missing the key '?name' should it be added but with an empty value?

**Comment by danielbeeke** [comment]
hmm, the expression if wrong for the binding or.. the binding should indeed be removed and an other actor should add the binding to the end result.

This is the expression:
```JSON
{
  type: 'expression',
  expressionType: 'operator',
  operator: '=',
  args: [
    {
      type: 'expression',
      expressionType: 'operator',
      operator: 'lang',
      args: [Array]
    },
    { type: 'expression', expressionType: 'term', term: [Literal] }
  ]
}

```

This seems to be the expression of the OPTIONAL. The binding that is filtered is the s p o.

**Comment by danielbeeke** [comment]
What I mean with the expression is wrong for the binding is that an evaluator is created:

```JavaScript
            const evaluator = new sparqlee_1.AsyncEvaluator(operationOriginal.expression, config);

```
And then that evaluator is executed:
```
const result = await evaluator.evaluateAsEBV(bindings);
```

The bindings here (in the case of the bindings that are dropped) do not have anything to do with the LANG expression.

**Comment by rubensworks** [comment]
The expression looks like to me though.

> The first line / binding is missing the key '?name' should it be added but with an empty value?

Adding a dummy value seems like a dangerous solution, so I would avoid that.

**Comment by danielbeeke** [comment]
I am wondering about the following comment:

> In many cases, this is a user error, where the user should manually cast the variable to a string.
> In order to help users debug this, we should report these errors via the logger as warnings.

Is that true for my query? I have the impression that my query would be fine:

```SPARQL
SELECT * WHERE { 
  ?s ?p ?o .

  OPTIONAL {
    ?s <http://ex.org/name> ?name .
    FILTER(lang(?name) = 'nl')
  }
}
```

I have created a proposal.
https://github.com/danielbeeke/comunica/commit/13e3ba610fe4e53eb623b407125eaa9f365a3e83

But I have no idea this if this would be an acceptable approach.

I wonder if the evaluateAsEBV should only be executed on the second entry of join. I mean the expression is not valid for `?s ?p ?o`.

**Comment by danielbeeke** [comment]
Cool, I will make a proposal for that, thanks very much!

**Comment by danielbeeke** [comment]
@rubensworks would the approach in the new merge request be in the right direction?

**Comment by rubensworks** [comment]
Looks good at first glance. But we'll only be certain if all the spec tests pass (all CI checks must be green for this).

Btw, do you want to be assigned to this issue so you can claim this bounty upon completion?

**Comment by danielbeeke** [comment]
Yes, I would like to be assigned.
Locally some test that are unrelated do not pass.
Yes Ill make sure we have 100% coverage.

This one fails for me locally:
  ● Requester › convertRequestHeadersToFetchHeaders › works with response headers

Do you know what I should do to make it pass?

**Comment by rubensworks** [comment]
> Do you know what I should do to make it pass?

No idea, it depends on the error you're getting 😅 
But looks unrelated to this PR indeed.

**Comment by danielbeeke** [comment]
Sorry here is the error.
```
 FAIL  packages/actor-http-native/test/Requester-test.ts (20.38 s)
  ● Requester › convertRequestHeadersToFetchHeaders › works with response headers

    expect(received).toEqual(expected) // deep equality

    - Expected  - 5
    + Received  + 1

      Headers {
    -   Symbol(map): Object {
    -     "accept": Array [
    -       "more",
    -     ],
    -   },
    +   Symbol(map): Object {},
      }

      26 |           response.headers = { accept: 'more' };
      27 |           expect(requester.convertRequestHeadersToFetchHeaders(response.headers))
    > 28 |             .toEqual(new Headers({ accept: 'more' }));
         |              ^
      29 |           resolve();
      30 |         });
      31 |       });

      at EventEmitter.<anonymous> (packages/actor-http-native/test/Requester-test.ts:28:14)
      at packages/actor-http-native/lib/Requester.ts:54:20
      at Immediate.<anonymous> (packages/actor-http-native/test/__mocks__/follow-redirects.js:25:22)

  ● Requester › convertRequestHeadersToFetchHeaders › works with response headers

    thrown: "Exceeded timeout of 20000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      19 |
      20 |   describe('convertRequestHeadersToFetchHeaders', () => {
    > 21 |     it('works with response headers', () => {
         |     ^
      22 |       const requester = new Requester();
      23 |       const req = requester.createRequest(url.parse('http://example.com/test'));
      24 |       return new Promise<void>(resolve => {

      at packages/actor-http-native/test/Requester-test.ts:21:5
      at packages/actor-http-native/test/Requester-test.ts:20:3
      at Object.<anonymous> (packages/actor-http-native/test/Requester-test.ts:6:1)

 PASS  packages/actor-init-query/test/QueryEngineFactoryBase-test.ts (51.325 s)


```

**Comment by rubensworks** [comment]
@danielbeeke Thanks for fixing this issue. Feel free to claim the bounty via open collective! :-)
