### ISSUE TITLE
Comunica is limiting 100 results when querying a TPF source

### ISSUE THREAD

**Issue by marcelomachado** [comunica/comunica#1096]
#### Issue type:

- :question: Question 

____
#### Question:

I'm trying to use Comunica inside a javascript application considering a TPF source. However, even when I place a query with a limit greater than 100 I still get 100 results:

```javascript
const bindingsStream = await this.queryEngine.queryBindings('select * {?s ?p ?o} limit 200', {
  sources: [my_tpf_uri]
});
  let count = 1;   
  bindingsStream.on('data', (binding) => {
  console.log(count++) // Last printed number is always 100
  console.log(binding.get('s').value);
  console.log(binding.get('p').value);
  console.log(binding.get('o').value);
});
```
I am using this TPF Docker Image: https://hub.docker.com/r/linkeddatafragments/server
But I also created my own Image based on the TPF Server main (~~master~~) branch: https://hub.docker.com/r/marceloocmachado/ldf-server

I don't know exactly if it is a Comunica or [TPF Server](https://github.com/LinkedDataFragments/Server.js) issue.

**Comment by marcelomachado** [comment]
It seams to be something related to cache. With https://hub.docker.com/r/marceloocmachado/ldf-server image I could reach more than 100 results in my local machine. But with the same image in my openshift cluster the problem remains. Does Comunica save something in files? Is there any way to flush cache?

**Comment by rubensworks** [comment]
It might be a server URL issue. Are you sure the TPF server's base URL is the same as the URL you are giving Comunica?
If not, Comunica will see the first page as a plain RDF document, and not follow next-page links.

You can check this by requesting the Turtle representation of the server URL, and inspecting the subject URL of the hypermedia triples (these must be equal to the URL requested by Comunica).

**Comment by marcelomachado** [comment]
Let me show you what I'm doing. 

In the first image I'm running a TPF-Server locally. I pointed to the DBPedia endpoint.

<img width="1154" alt="Screen Shot 2022-10-10 at 16 18 44" src="https://user-images.githubusercontent.com/5925863/194938583-f1ac01e1-87ba-46c2-aec5-98b4543b3a35.png">

I am doing the same thing in my remote server:
<img width="834" alt="Screen Shot 2022-10-10 at 16 19 16" src="https://user-images.githubusercontent.com/5925863/194938773-b0999b3f-4f65-4776-be7b-fcd1cfe16388.png">

In the following images is me using Comunica in my JS APP to query those TPF-Servers. 

This one is me querying (limit 200) using http://localhost:5006/dbpedia as source. As we can see, it returns 200 results as expected:
<img width="694" alt="Screen Shot 2022-10-10 at 16 23 50" src="https://user-images.githubusercontent.com/5925863/194938914-b799fd9c-aa1c-41a5-9fbc-553e1e947841.png">

This one is me querying (limit 200) my remote server using http://{host}/dbpedia as source. As we can see, it returns only 100 results (whenever there are more than 100 results):
<img width="694" alt="Screen Shot 2022-10-10 at 16 30 07" src="https://user-images.githubusercontent.com/5925863/194939410-b3e62e89-21a5-4ade-aeea-fe16c9aa25fa.png">

**Comment by rubensworks** [comment]
What do the metadata triples of your remote endpoint look like?

E.g., these:
```turtle
<https://fragments.dbpedia.org/#dataset> hydra:member <https://fragments.dbpedia.org/2016-04/en#dataset>.
<https://fragments.dbpedia.org/2016-04/en#dataset> a void:Dataset, hydra:Collection;
    void:subset <https://fragments.dbpedia.org/2016-04/en>;
    hydra:search _:triplePattern.
_:triplePattern hydra:template "https://fragments.dbpedia.org/2016-04/en{?subject,predicate,object}";
    hydra:variableRepresentation hydra:ExplicitRepresentation;
    hydra:mapping _:subject, _:predicate, _:object.
_:subject hydra:variable "subject";
    hydra:property rdf:subject.
_:predicate hydra:variable "predicate";
    hydra:property rdf:predicate.
_:object hydra:variable "object";
    hydra:property rdf:object.
<https://fragments.dbpedia.org/2016-04/en> void:subset <https://fragments.dbpedia.org/2016-04/en>;
    a hydra:PartialCollectionView;
    dcterms:title "Linked Data Fragment of DBpedia 2016-04"@en;
    dcterms:description "Triple Pattern Fragment of the 'DBpedia 2016-04' dataset containing triples matching the pattern { ?s ?p ?o }."@en;
    dcterms:source <https://fragments.dbpedia.org/2016-04/en#dataset>;
    hydra:totalItems "1040358853"^^xsd:integer;
    void:triples "1040358853"^^xsd:integer;
    hydra:itemsPerPage "100"^^xsd:integer;
    hydra:first <https://fragments.dbpedia.org/2016-04/en?page=1>;
    hydra:next <https://fragments.dbpedia.org/2016-04/en?page=2>.
```

The subject of this metadata should be identical to the requested URL.

**Comment by rubensworks** [comment]
See also https://github.com/LinkedDataFragments/Server.js/tree/master/packages/server#optional-set-up-a-reverse-proxy

**Comment by marcelomachado** [comment]
> What do the metadata triples of your remote endpoint look like?
> 
> E.g., these:
> 
> ```turtle
> <https://fragments.dbpedia.org/#dataset> hydra:member <https://fragments.dbpedia.org/2016-04/en#dataset>.
> <https://fragments.dbpedia.org/2016-04/en#dataset> a void:Dataset, hydra:Collection;
>     void:subset <https://fragments.dbpedia.org/2016-04/en>;
>     hydra:search _:triplePattern.
> _:triplePattern hydra:template "https://fragments.dbpedia.org/2016-04/en{?subject,predicate,object}";
>     hydra:variableRepresentation hydra:ExplicitRepresentation;
>     hydra:mapping _:subject, _:predicate, _:object.
> _:subject hydra:variable "subject";
>     hydra:property rdf:subject.
> _:predicate hydra:variable "predicate";
>     hydra:property rdf:predicate.
> _:object hydra:variable "object";
>     hydra:property rdf:object.
> <https://fragments.dbpedia.org/2016-04/en> void:subset <https://fragments.dbpedia.org/2016-04/en>;
>     a hydra:PartialCollectionView;
>     dcterms:title "Linked Data Fragment of DBpedia 2016-04"@en;
>     dcterms:description "Triple Pattern Fragment of the 'DBpedia 2016-04' dataset containing triples matching the pattern { ?s ?p ?o }."@en;
>     dcterms:source <https://fragments.dbpedia.org/2016-04/en#dataset>;
>     hydra:totalItems "1040358853"^^xsd:integer;
>     void:triples "1040358853"^^xsd:integer;
>     hydra:itemsPerPage "100"^^xsd:integer;
>     hydra:first <https://fragments.dbpedia.org/2016-04/en?page=1>;
>     hydra:next <https://fragments.dbpedia.org/2016-04/en?page=2>.
> ```
> 
> The subject of this metadata should be identical to the requested URL.

This is at the end of my last post but instead of turtle it is in n-triples format.

**Comment by rubensworks** [comment]
I don't see the full URL, so I'm not sure they are correct :-)

So you're certain that you are requesting `http://{host}/dbpedia` via Comunica, and not something else? (e.g. not `https://{host}/dbpedia`)

**Comment by marcelomachado** [comment]
> See also https://github.com/LinkedDataFragments/Server.js/tree/master/packages/server#optional-set-up-a-reverse-proxy

I am quite sure it is about some cache (in my server). I was pointing it to my docker image in `marceloocmachado/tpf-server`. But I've  just realized you've published a new docker image after my PR. So, soon I will try to use this new image.

**Comment by marcelomachado** [comment]
> I don't see the full URL, so I'm not sure they are correct :-)
> 
> So you're certain that you are requesting `http://{host}/dbpedia` via Comunica, and not something else? (e.g. not `https://{host}/dbpedia`)

I just replaced the confidential url. But I am sure it is the same

**Comment by marcelomachado** [comment]
> > See also https://github.com/LinkedDataFragments/Server.js/tree/master/packages/server#optional-set-up-a-reverse-proxy
> 
> I am quite sure it is about some cache (in my server). I was pointing it to my docker image in `marceloocmachado/tpf-server`. But I've just realized you've published a new docker image after my PR. So, soon I will try to use this new image.

@rubensworks I've just tested, with this new Docker Image version, in a different cluster and everything worked as expected.   It is really something related to cache on the server that was using the old docker image. 

Anyway, thank you for your help and time.

**Comment by rubensworks** [comment]
Great to hear that it works now :-)
