### ISSUE TITLE
Use @context with prefixes for SPARQL queries

### ISSUE THREAD

**Issue by danielbakas** [comunica/comunica#1099]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

The option to pass a context to a query (much like the `@context` for JSON-LD) to construct the prefixes in `text/turtle`, `application/ld+json` and more formats' queries, and therefore **make every response more compact, lightweight and readable**. 

I believe this would be incredibly valuable to many people (including me), since this would save the need to manually compact every response, which –for large graphs– can represent a **considerable increase in execution time and file size for every single query** 🤯

What do you think? 🤓

**Comment by danielbakas** [comment]
@rubensworks do you think it would be valuable to add this feature request to #performance? 🤓

**Comment by jeswr** [comment]
> The option to pass a context to a query (much like the @context for JSON-LD) to construct the prefixes

For the _query_ you can use prefixes in SPARQL (c.f. https://en.wikibooks.org/wiki/SPARQL/Prefixes)

For the response this only really makes sense on construct queries that are serialised, so it would be a matter of config in the serialise parameter.

> for large graphs– can represent a considerable increase in execution time and file size for every single query

The time to serialize data is most likely negligible compared to the other operations required so I don't think #performance is that appropriate here. The current feature request is probably fine as is if it is asking for a parameter to enable compact syntax on the ttl and jsonld serializers.

**Comment by danielbakas** [comment]
Perfect! I'll cross my fingers and hope you consider it for the response serialization 🤩🙏🏽 Thanks @jeswr!!

**Comment by rubensworks** [comment]
I'm not sure about this one.
If I understand correctly, the user would pass a JSON-LD context together with a SPARQL query, and then the results are compacted (in a serialization-agnostic manner?) using that context.
The problem with this is that the serialized result will build upon an out-of-band context, which will make serialized results not stand on their own. Parsers for those results will have to assume the existence of this out-of-band context.

So based on what I understand, I think this is not something we'll want to support in Comunica. But feel free to come with a more concrete suggestion in case I misunderstood.

(@jeswr feel free to close this issue if you agree)

**Comment by danielbakas** [comment]
> I'm not sure about this one. If I understand correctly, the user would pass a JSON-LD context together with a SPARQL query, and then the results are compacted (in a serialization-agnostic manner?) using that context. The problem with this is that the serialized result will build upon an out-of-band context, which will make serialized results not stand on their own. Parsers for those results will have to assume the existence of this out-of-band context.
> 
> So based on what I understand, I think this is not something we'll want to support in Comunica. But feel free to come with a more concrete suggestion in case I misunderstood.
> 
> (@jeswr feel free to close this issue if you agree)

Hi @rubensworks! I’ll clarify. Passing a context to the query initially would not be necessary. 

What I propose would be more closely related to compacting the result of the query in the form of:
* prefixes in a TTL query
* @context in a JSON-LD query
* etc.

Only so that the output of the query is compact, but it doesn’t require an original context.

Does this make more sense? 😃 @rubensworks @jeswr

**Comment by rubensworks** [comment]
But what do you mean exactly with a TTL query, and a JSON-LD query?

Do you perhaps mean a CONSTRUCT query, where you select the TTL or JSON-LD media type, and then want to compact those?
If so, then yes, a way to define their prefixes and context certainly makes sense.

**Comment by danielbakas** [comment]
Absolutely! Any request where the resulting response can be compacted, like JSON-LD with @context and TTL with prefixes, and certainly like the CONSTRUCT query you mention.

That would be amazing! I apologize if I had some trouble explaining this idea, but this is the feature that I believe would be great for Comunica and valuable to many of us to. What do you think? 🤩🙏🏼

**Comment by rubensworks** [comment]
Ah ok, thanks for the clarification @danielbakas, that definitely makes sense.

And indeed, might be good to open a new issue for this, so we don't have the noisy comments.
You could title it as something like "Define prefixes and context for serialization of CONSTRUCT query results".

**Comment by danielbakas** [comment]
I kept thinking about it. How would Comunica know what prefixes I'm interested about? Namespaces are easy. Comunica might have a repo with a list of common namespaces. 

But what someone needs the response to include a more complex prefix like a path to somewhere?
* `https://example.com/namespace/path/to#resource`
Where the namespace is:
* `https://example.com/namespace/`
but the desired prefix is:
* `https://example.com/namespace/path/to#`

Does this make sense? And if it does, then passing a context to a query constructor would not be such a bad idea right? Comunica could use that initially passed context to compact and add it to the response.

What do you think? @rubensworks 🤓

**Comment by jeswr** [comment]
@danielbakas - not sure if you know already; http://prefix.cc/ is great for looking up namespaces commonly associated to a prefix and http://prefix.cc/reverse is great for the reverse lookup.

You can also get the response as a jsonld context if you want it to be more machine readable .

**Comment by danielbakas** [comment]
Thanks @jeswr! That's a great tool. I'll check it out. In the meantime I'll keep using `jsonld.compact()`

**Comment by rubensworks** [comment]
@danielbakas Yes, the ability to pass this to the serialization method definitely makes sense.

**Comment by danielbakas** [comment]
Awesome! Would that mean creating a new feature request issue?

**Comment by rubensworks** [comment]
Sure!

**Comment by A01657103** [comment]
Awesome! So just to be clear on what to write on the new issue, how does this look:

Issue type:
➕ Feature request
***
Description:
The option to pass a context object to *comunica's serializer method* (much like the @context for JSON-LD) as mentioned in [#1099](https://github.com/comunica/comunica/issues/1099#issuecomment-1296860671).

I believe this would be incredibly valuable to many people (including me), since this would save the need to manually compact every response.

What do you think? 🤓

**Comment by rubensworks** [comment]
Sure, that's fine.

You can use this as title: "Define prefixes and context for serialization of CONSTRUCT query results"

**Comment by danielbakas** [comment]
Awesome! Thanks @rubensworks!
