### ISSUE TITLE
Review README

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#110]
It should make clear what it is, for whom it is intended, how it can be used.

**Comment by rubensworks** [comment]
Did some changes, please let me know if there's anything else you think is missing.

**Comment by RubenVerborgh** [comment]
Going in the right direction!

> Comunica is a highly modular and flexible query engine platform for the Web.

“Linked Data query engine”?

Perhaps append “using the SPARQL language” (which, for now, is true, even if we extend later).

> Federated querying over heterogeneous interfaces

Missing a dot 😈 

> This should be used by Comunica module developers as it is the repository containing all Comunica modules.

Unclear what “This” is.

Also “all” Comunica modules might not be true if people start extending.

> If you want to use Comunica, have a look at the manual or at the Comunica SPARQL Init Actor if you want to execute SPARQL queries.

That's still unsatisfactory for me. I think we should greatly extend, with sections “For people who want to query”, “For people who want to build an application”, “For people who want to customize or extend the query engine”.

Also, the “Init Actor” thingy bugs me. It sounds really complicated. I need to know the notion of actors now, and why it is init. I.e., too much lingo.

I wonder to what extent we should capture the notion that it is a meta-engine, i.e., that various configurations of it can be built.

**Comment by rubensworks** [comment]
> > Comunica is a highly modular and flexible query engine platform for the Web.

> “Linked Data query engine”?
> Perhaps append “using the SPARQL language” (which, for now, is true, even if we extend later).

Are we sure we want to sell it like this?
I purposely did _not_ scope it to anything related RDF/Linked Data in the root README, as it can be used for much more than that.

As I see it, the root README should only talk about the Comunica platform, and the Comunica SPARQL README should only talk about the SPARQL engine.

> That's still unsatisfactory for me. I think we should greatly extend, with sections “For people who want to query”, “For people who want to build an application”, “For people who want to customize or extend the query engine”.

Those sections are present in the Comunica SPARQL README, with the same reason mentioned earlier.

> Also, the “Init Actor” thingy bugs me. It sounds really complicated. I need to know the notion of actors now, and why it is init. I.e., too much lingo.

:+1:, will change it to `Comunica SPARQL` (also for all other init actors).

Note that the package name is still `@comunica/actor-init-sparql`, for consistency with the naming convention of Comunica modules. Changing this to `@comunica/sparql` might be possible, but we might be running into naming conflicts in the future then. (Alternatively, we could make these init actors have unscoped names, such as `comunica-sparql`? This might make sense from a usage-perspective) So I'm not sure about this yet.

> I wonder to what extent we should capture the notion that it is a meta-engine, i.e., that various configurations of it can be built.

Made some new changes (https://github.com/comunica/comunica/commit/5eaf7fc73e19a3fbf89a748d46067cd2764f01e5), this should be clearer now.

**Comment by RubenVerborgh** [comment]
The phrasing in the README is clear to me now. Good work!

**Comment by rubensworks** [comment]
@RubenVerborgh (and also @joachimvh and @mielvds), what do you think about this?:

> Note that the package name is still @comunica/actor-init-sparql, for consistency with the naming convention of Comunica modules. Changing this to @comunica/sparql might be possible, but we might be running into naming conflicts in the future then. Alternatively, we could make these init actors have unscoped names, such as comunica-sparql? This might make sense from a usage-perspective.

**Comment by joachimvh** [comment]
`@comunica/actor-init-sparql` is indeed not quite clear for first-time visitors. Additionally, since all these packages are going to be independent in the npm repository, we might also have to think about discoverability there. But not sure if @comunica/sparql or comunica-sparql is better, are there any packages out there that had a similar problem?

**Comment by rubensworks** [comment]
I know babel also uses scoped package names for most of its modules, but their core (which people actually install) is just an unscoped package AFAIK.

`comunica-sparql` might make most sense if we want to have a consistent naming strategy, for if we intend to release similar prepackaged modules like `comunica-graphql` or `comunica-rdf-parse`.

Alternatively, it's still possible to release it as a new `ldf-client`, but I'm not sure if that's a good idea...

**Comment by mielvds** [comment]
What exactly would te name be in that case? `@comunica/comunica-sparql`? 

I would maybe put bus, actor at the end (if really needed), like `@comunica/sparql-actor`

**Comment by mielvds** [comment]
And maybe it would make sense to take these kind of packages out of the monorepo and give them a dedicated repo.

**Comment by rubensworks** [comment]
@mielvds No, I mean just `comunica-sparql`. (unscoped, so without the `@comunica`)

> I would maybe put bus, actor at the end (if really needed)

I wouldn't do that, that would require renaming _all_ packages we have atm.
We chose that order as it makes it better compatible with the default sorting of folders in file systems and IDEs.

> And maybe it would make sense to take these kind of packages out of the monorepo and give them a dedicated repo.

We would loose a lot of the advantages of the monorepo, such as easy development and CI. I don't really see a problem with them being inside the monorepo.

**Comment by RubenVerborgh** [comment]
Would leave them in the scope in any case. I don't have any other opinions regarding naming, perhaps maybe a suggestion to look for a more descriptive word than `init` (perhaps `bootstrap`). An option is to keep the `actor-init-sparql` naming, and just have a dummy module `sparql` that essentially functions as an alias.

**Comment by rubensworks** [comment]
`init` feels quite descriptive to me, but I guess that's subjective :-)

I guess we have 4 options:
1. **`@comunica/actor-init-sparql`**: leave it as-is, to be consistent with the other package names.
2. **`@comunica/init-sparql`**: slightly shorter and simpler.
3. **`@comunica/actor-bootstrap-sparql`**
4. **`@comunica/bootstrap-sparql`**

My preference goes to option 2.

**Comment by joachimvh** [comment]
I like the solution with just keeping it and using an alias

**Comment by rubensworks** [comment]
Ok, closing this one then.
