### ISSUE TITLE
`comunica-sparql-file`: CONSTRUCT query returns duplicate triples

### ISSUE THREAD

**Issue by sdevalk** [comunica/comunica#1105]
#### Issue type:

- :bug: Bug

____
#### Description:

I'm using `comunica-sparql-file` (CLI, package `@comunica/query-sparql-file`) to query a local RDF file.

The file ("test.ttl") looks like this:

```turtle
@prefix schema: <https://schema.org/> .

<>
  a schema:CreativeWork ;
  schema:additionalType <http://vocab.getty.edu/aat/300026819>,
    <https://data.cultureelerfgoed.nl/term/id/cht/1ea51d41-ca5c-40d3-8a85-362968878b0d> .
```

My query (file "query.rq") looks like this:

```sparql
PREFIX schema: <https://schema.org/>

CONSTRUCT {
  ?s a schema:CreativeWork ;
    schema:additionalType ?additionalType
}
WHERE {
  ?s schema:additionalType ?additionalType
}
```

My command looks like this:

`npx comunica-sparql-file test.ttl -f query.rq`

My output looks like this:

```turtle
<test.ttl> a <https://schema.org/CreativeWork>;
    <https://schema.org/additionalType> <http://vocab.getty.edu/aat/300026819>;
    a <https://schema.org/CreativeWork>;
    <https://schema.org/additionalType> <https://data.cultureelerfgoed.nl/term/id/cht/1ea51d41-ca5c-40d3-8a85-362968878b0d>.
```

`a <https://schema.org/CreativeWork>` appears two times. I was expecting something like this:

```turtle
<test.ttl> a <https://schema.org/CreativeWork>;
    <https://schema.org/additionalType> <http://vocab.getty.edu/aat/300026819>;
    <https://schema.org/additionalType> <https://data.cultureelerfgoed.nl/term/id/cht/1ea51d41-ca5c-40d3-8a85-362968878b0d>.
```
____
#### Environment:

| software         | version
| ---------------- | -------
| Comunica Engine  | 2.4.3
| node             | v18.12.0
| npm              | 8.19.2
| yarn             | 1.22.19
| Operating System | linux (Linux 5.10.76-linuxkit)

#### Crash log:

n/a

**Comment by rubensworks** [comment]
The behaviour here is actually correct according to the SPARQL spec.

You'll notice that if you execute the following query:
```sparql
SELECT * WHERE {
  ?s schema:additionalType ?additionalType
}
```
that you will find to bindings, each having values for `?s` and `?additionalType`.

Both of these bindings will be filled into your CONSTRUCT template
```
  ?s a schema:CreativeWork ;
    schema:additionalType ?additionalType
```
which means that both of these triple patterns will be instantiated twice, which causes `<test.ttl> a <https://schema.org/CreativeWork>` to appear twice.

-----

AFAIK, there is no way to achieve the desired result using just CONSTRUCT queries.

Perhaps some of the recent suggestions for SPARQL 1.2 could help in the future (https://github.com/w3c/sparql-12/issues/33 https://github.com/w3c/sparql-12/issues/160)

**Comment by sdevalk** [comment]
Thanks, @rubensworks!

I've also used the CONSTRUCT + data above in a Virtuoso and Jena instance. These stores return the results without duplicate triples, e.g.:

```
<...> a <http://schema.org/CreativeWork>;
    <http://schema.org/additionalType> <https://data.cultureelerfgoed.nl/term/id/cht/1ea51d41-ca5c-40d3-8a85-362968878b0d>,
                                       <http://vocab.getty.edu/aat/300026819>.
```

I had expected `comunica-sparql-file` to return similar results. But I wasn't aware that this isn't spec-compliant.

**Comment by rubensworks** [comment]
Ahh, that is interesting.

Just thought about this a bit more, and since an RDF dataset is defined as a _set_ of triples, duplicates have no meaning, so they could indeed be removed without a loss of correctness.
So the output of Comunica and Virtuoso/Jena are all correct, but it does it does indeed look a bit nicer without duplicates to humans (but for machines it doesn't matter).

I'll make this issue a feature request to filter duplicate triples. The only downside is that this will result in some memory overhead during serialization.

**Comment by sdevalk** [comment]
@rubensworks Thank you!

One perhaps relevant addition:

If my data file looks like this:

```turtle
@prefix schema: <https://schema.org/> .

<>
  a schema:CreativeWork ;
  schema:additionalType <http://vocab.getty.edu/aat/300026819>,
    <https://data.cultureelerfgoed.nl/term/id/cht/1ea51d41-ca5c-40d3-8a85-362968878b0d> ;
  schema:image [
    a schema:ImageObject ;
    schema:name "Name"
  ] .
```

And my query like this:

```sparql
PREFIX schema: <https://schema.org/>

CONSTRUCT {
  ?s a schema:CreativeWork ;
    schema:additionalType ?additionalType ;
    schema:image ?image .
  ?image schema:name ?imageName .
}
WHERE {
  ?s schema:additionalType ?additionalType ;
    schema:image ?image .
  ?image schema:name ?imageName .
}
```

Then the (shortened) response of Virtuoso and Jena looks like this:

```turtle
<> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://schema.org/CreativeWork> .
<> <https://schema.org/additionalType> <https://data.cultureelerfgoed.nl/term/id/cht/1ea51d41-ca5c-40d3-8a85-362968878b0d> .
<> <https://schema.org/additionalType> <http://vocab.getty.edu/aat/300026819> .
<> <https://schema.org/image> <#a> .
<#a> <https://schema.org/name> "Name" .
```

But the result of Comunica looks like this:

```turtle
<test.ttl> a <https://schema.org/CreativeWork>;
    <https://schema.org/additionalType> <http://vocab.getty.edu/aat/300026819>;
    <https://schema.org/image> _:bc_0_n3-00.
_:bc_0_n3-00 <https://schema.org/name> "Name".
<test.ttl> a <https://schema.org/CreativeWork>;
    <https://schema.org/additionalType> <https://data.cultureelerfgoed.nl/term/id/cht/1ea51d41-ca5c-40d3-8a85-362968878b0d>;
    <https://schema.org/image> _:bc_0_n3-01.
_:bc_0_n3-01 <https://schema.org/name> "Name".
```

There are two (distinct) blank nodes. Which could give the impression that there are two 'images' whereas there is only one.

**Comment by rubensworks** [comment]
> There are two (distinct) blank nodes. Which could give the impression that there are two 'images' whereas there is only one.

It seems strange to me that Virtuoso and Jena convert your blank node to an IRI. This doesn't seem spec-compliant, as explained [here](https://www.w3.org/TR/sparql11-query/#templatesWithBNodes).
Are you aware of any (non-spec-compliant) flag what was used to produce these results?

**Comment by sdevalk** [comment]
Hi @rubensworks, thanks!

Yes, you're right. The Virtuoso and Jena instances that I use convert my blank nodes to IRIs. However, if I run a new, bare bones Jena instance and use the same data and same CONSTRUCT query as before, the result looks like this:

```
@prefix schema: <https://schema.org/> .

<http://localhost:3030/test01/data>
        a                      schema:CreativeWork ;
        schema:additionalType  <https://data.cultureelerfgoed.nl/term/id/cht/1ea51d41-ca5c-40d3-8a85-362968878b0d> , <http://vocab.getty.edu/aat/300026819> ;
        schema:image           [ schema:name  "Name" ] .
```

**Comment by rubensworks** [comment]
That's very interesting.
AFAIK, this isn't what the spec prescribes though.
I guess this might be something that deserves discussion on SPARQL-related mailinglist.

**Comment by rubensworks** [comment]
Merging this issue in #1105

**Comment by ddeboer** [comment]
Hey @rubensworks, it looks like we’re still seeing duplicate triples on the Comunica (file) SPARQL endpoint.

> So the output of Comunica and Virtuoso/Jena are all correct, but it does it does indeed look a bit nicer without duplicates to humans (but for machines it doesn't matter).
> 
> I'll make this issue a feature request to filter duplicate triples. The only downside is that this will result in some memory overhead during serialization.

Was this change actually made to Comunica?

> Merging this issue in #1105

This looks wrong: #1105 is this issue. Did you mean another one?

**Comment by rubensworks** [comment]
@ddeboer Oops, I referenced the wrong issue indeed.
#1300 is probably the correct one.
