### ISSUE TITLE
return type of bindingsStreamToGraphQl is wrong

### ISSUE THREAD

**Issue by mvanbrab** [comunica/comunica#1114]
#### Issue type:

- :bug: Bug 

____
#### Description:
The return type is set to Promise<string>, but it should be Promise<any>.

____
#### Environment:
| software         | version
| ---------------- | -------
| Comunica Engine  | 2.4.3 
| node             | v16.18.1
| npm              | 8.19.2
| yarn             | 1.22.19
| Operating System | linux (Linux 5.15.0-52-generic)

#### Observation:

This line in a Typescript application:
```
const data = (await bindingsStreamToGraphQl((await result.execute()) as BindingsStream, result.context, {materializeRdfJsTerms: true})) as object[];
```
results in this Typscript error:
```
error TS2352: Conversion of type 'string' to type 'object[]' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
```

#### Temporary workaround:
As a workaround, the `as unknown` in between helps:
```
const data = (await bindingsStreamToGraphQl((await result.execute()) as BindingsStream, result.context, {materializeRdfJsTerms: true})) as unknown as object[];
```

**Comment by rubensworks** [comment]
Should be an easy fix, replacing `Promise<string>` with `Promise<any>` in https://github.com/comunica/comunica/blob/b84898f73a1a2c1fc413b51b2facacfd6bb729e4/packages/actor-query-result-serialize-tree/lib/ActorQueryResultSerializeTree.ts#L34-L36.
PR is welcome!

**Comment by mvanbrab** [comment]
I'll do.
