### ISSUE TITLE
Query processing issue with certain FILTERs

### ISSUE THREAD

**Issue by gvanderh** [comunica/comunica#1124]
```
SELECT * WHERE {
    ?o ?p ?s
    FILTER("2021-10-21"^^xsd:dateTime < ?s)
}
```

Entered in the UI, the query above is serialized and sent to the endpoint as follows:

`"query": "SELECT+?o+?p+?s+WHERE+{\n++SELECT+?o+?p+?s+WHERE+{\n++++?o+?p+?s.\n++++FILTER(\"2021-10-21\"^^<http://www.w3.org/2001/XMLSchema#dateTime>+<+?s)\n++}\n}"`

Note the duplicated SELECT WHERE.

**Comment by rubensworks** [comment]
Might be an issue in this actor: https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-sparql-endpoint/lib/ActorQueryOperationSparqlEndpoint.ts

**Comment by rubensworks** [comment]
I just tried it out myself, and it just sends out the correct query as-is, as would be expected.
