### ISSUE TITLE
comunica not working in builded version of Vue application

### ISSUE THREAD

**Issue by smessie** [comunica/comunica#1128]
#### Issue type:

- :bug: Bug 

____
#### Description:

When adding comunica to my Vue application, everything works as long as I start it up the development way with `npm run dev`, but as soon as I try to build it for production with `npm run build` and then serve it with e.g. `npm run preview` the application does not work. 

I have made a minimal reproducible example consisting of a fresh and clean Vue project and the installation of `@comunica/query-sparql-solid `. By just adding `const engine = new QueryEngine()` to the code the application stops working in the builded mode and on page load the error given under crash log below is returned in the browser console.

The issue was first discovered in this project where I started to debug it. https://github.com/smessie/TAS/tree/fix-prod-build (TS project)
For the sake of simplicity I set up a minimal reproducible example as described earlier here: https://github.com/smessie/comunica-vue-test (JS project)

Steps to reproduce:
```
git clone git@github.com:smessie/comunica-vue-test.git
cd comunica-vue-test
npm install
npm run build
npm run preview
```
Try to load the page in the browser and experience the error in the browser console.

____
#### Environment:

Node version: v16.17.1
"@comunica/query-sparql-solid": "^2.4.0"

#### Crash log:

```
Uncaught TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at Kse (ContainerHandlerType.js:2:8)
    at M5 (EntryHandlerContainer.js:7:32)
    at Xu (Util.js:6:33)
    at EntryHandlerPredicate.js:5:16
Kse @ ContainerHandlerType.js:2
M5 @ EntryHandlerContainer.js:7
Xu @ Util.js:6
(anonymous) @ EntryHandlerPredicate.js:5
```

**Comment by rubensworks** [comment]
The stacktrace isn't too helpful unfortunately.
Any way you could provide a de-obfuscated stacktrace?

**Comment by smessie** [comment]
> The stacktrace isn't too helpful unfortunately.
> Any way you could provide a de-obfuscated stacktrace?

Okay, so I've pushed a change to my [comunica-vue-test](https://github.com/smessie/comunica-vue-test) repo enabling source maps and now I get following stack trace.
Does this help you further?

```
Uncaught TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at Kse (ContainerHandlerType.js:2:8)
    at M5 (EntryHandlerContainer.js:7:32)
    at Xu (Util.js:6:33)
    at EntryHandlerPredicate.js:5:16
Kse @ ContainerHandlerType.js:2
M5 @ EntryHandlerContainer.js:7
Xu @ Util.js:6
(anonymous) @ EntryHandlerPredicate.js:5
```

**Comment by rubensworks** [comment]
Looks like it's tripping over this:
`Object.defineProperty(exports, "__esModule", { value: true });`

This is valid CommonJS, so perhaps there's something going wrong during your bundling step.

If you find the solution, please let us know!

**Comment by smessie** [comment]
I really can't find any solution, have been searching for multiple days now. Was hoping you could help somehow.
Only thing I can find is that `exports` is undefined in `ContainerHandlerType.js` of `jsonld-streamer-parser`, but this library is for node, not the web, if I interpret the readme correctly.

**Comment by rubensworks** [comment]
Perhaps @surilindur knows more, he has used Comunica in Vue in the past.

**Comment by renyuneyun** [comment]
Do you not need to set up a fallback `global` variable in your `vite.config.ts`?
It is needed in my case, even for the dev mode. But I'm using `"@comunica/query-sparql": "^2.5.2"`, not the Solid-specifc one (yet).
Though, I also encounter issues when in production mode (#1137).

**Comment by rubensworks** [comment]
For reference, error stacktraces from #1137 by @renyuneyun

Under production mode, I see the following errors in browser console on loading the app's page:

```
Uncaught TypeError: undefined is not a non-null object
    requireContainerHandlerType ContainerHandlerType.js:2
    requireEntryHandlerContainer EntryHandlerContainer.js:7
    requireUtil Util.js:6
    <anonymous> EntryHandlerPredicate.js:5
```

Expanding details gives these extra lines:

```
    ObjectOrReflectDefineProperty self-hosted:2610
    defineProperty self-hosted:2675
    requireContainerHandlerType ContainerHandlerType.js:2
    requireEntryHandlerContainer EntryHandlerContainer.js:7
    requireUtil Util.js:6
    <anonymous> EntryHandlerPredicate.js:5
```

**Comment by rubensworks** [comment]
Forgot to report this over here, but the stacktrace refers to `ContainerHandlerType` in https://github.com/rubensworks/jsonld-streaming-parser.js
But I don't think the actual package is the issue. This one is probably just one of the first ones that is loaded.

**Comment by surilindur** [comment]
The issue seems to be in this part, where `Object.defineProperty` is used on `ContainerHandlerType`, where `ContainerHandlerType` is actually `undefined`, when looking at it with a breakpoint in the debugger tab, even though it is supposed to have been assigned outside the function:
```
// Here is should be assigned, right???
var ContainerHandlerType = {};

var hasRequiredContainerHandlerType;

function requireContainerHandlerType () {
	if (hasRequiredContainerHandlerType) return ContainerHandlerType;
	hasRequiredContainerHandlerType = 1;
        // ContainerHandlerType below says undefined when placing a breakpoint in the debugger
	Object.defineProperty(ContainerHandlerType, "__esModule", { value: true });
```
I will try to look into it, but it should be defined, I guess. It is defined there, and nothing sets it to undefined, I guess.

**Comment by surilindur** [comment]
After trying out a whole lot of options for all the things, setting [strictRequires](https://github.com/rollup/plugins/tree/master/packages/commonjs#strictrequires) to `true` as an option for the Rollup CommonJS plugin (in the Vite config) seems to have fixed the errors for another Vite+Vue+Comunica application:
```
{
  build: {
    commonjsOptions: {
      strictRequires: true
    }
  }
}
```
Apparently `true` should be used when the default auto option does not produce working code. Hopefully this helps someone.

**Comment by smessie** [comment]
Thanks a lot @surilindur! I can confirm that this is working in https://github.com/smessie/comunica-vue-test/commit/9f0e75b16ff39ba796fc9d280d3d47352453b105 as well as in https://github.com/smessie/TAS/commit/569cab73e14232244bad0556cf83315681b141b1.

**Comment by rubensworks** [comment]
Nice finding @surilindur!

It's good that we have a workaround, but eventually it would be good if we have a solution that doesn't require changing any rollup/vite config. But since we have a workaround, this is not super urgent.

**Comment by simonvbrae** [comment]
> This might actually be related to this (fixed) bug: [rubensworks/jsonld-context-parser.js#63](https://github.com/rubensworks/jsonld-context-parser.js/issues/63)

It turned out to be related to this bug, as such it is now fixed.

**Comment by rubensworks** [comment]
Nice, thanks for checking @simonvbrae!
So anyone running into this bug in the future, just delete your lockfile+node_modules, and reinstall to fix the issue.
