### ISSUE TITLE
Cache pre-compiled configuration file?

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#113]
I was reading the following:

> Comunica can either be invoked dynamically using a configuration file, or statically using a pre-compiled configuration file.

Can we keep a cache of pre-compiled configuration files? E.g., hash the contents of a configuration file, check if exists and reuse, if not, write it?

**Comment by rubensworks** [comment]
Sure, we could do that. Might be useful during development to have a watcher on that file that continuously compiles on changes.

Note to self: this could for example be done by storing the config file hash as a comment on the first line of the compiled JS file.

**Comment by rubensworks** [comment]
Closing this, as config compilation is quite fast, and there is not really a need for caching pre-compiled config files anymore, as they are always pre-compiled in the npm releases.

We can open this if the need for it would arise.
