### ISSUE TITLE
`Uncaught TypeError: undefined is not a non-null object` on production build mode (Vue 3 + Vite)

### ISSUE THREAD

**Issue by renyuneyun** [comunica/comunica#1137]
#### Issue type:

- :bug: Bug 

____
#### Description:

I'm developing [a Solid App](https://github.com/renyuneyun/PermiX) using Comunica (`@comunica/query-sparql`), built using Vite.
It works on dev build mode, but not on production mode.

Under production mode, I see the following errors in browser console on loading the app's page:

```
Uncaught TypeError: undefined is not a non-null object
    requireContainerHandlerType ContainerHandlerType.js:2
    requireEntryHandlerContainer EntryHandlerContainer.js:7
    requireUtil Util.js:6
    <anonymous> EntryHandlerPredicate.js:5
```

Expanding details gives these extra lines:

```
    ObjectOrReflectDefineProperty self-hosted:2610
    defineProperty self-hosted:2675
    requireContainerHandlerType ContainerHandlerType.js:2
    requireEntryHandlerContainer EntryHandlerContainer.js:7
    requireUtil Util.js:6
    <anonymous> EntryHandlerPredicate.js:5
```

I'm not sure how to debug further, as the message is quite limited. But based on the name, it could be linked with #1136.
I also saw #1128, but not sure if they are linked.

IIRC, the only special set up I did (and needed for dev mode already) for Comunica is to add the following to `vite.config.ts`:
```
  optimizeDeps: {
    esbuildOptions: {
      // Node.js global to browser globalThis
      define: {
        global: 'globalThis',
      },
    },
  },
```
(Should this be a bug, or at least mentioned, as well? It's not documented, and is a surprise when the document says it should work automatically.)
____
#### Environment:

| software         | version
| ---------------- | -------
| Comunica Engine  | 2.5.1
| node             | v19.0.1
| npm              | 8.19.2
| yarn             | _Yarn is unavailable_
| Operating System | darwin (Darwin 22.1.0)

#### Crash log:

See above

**Comment by rubensworks** [comment]
Closing this in favor of #1128

**Comment by renyuneyun** [comment]
Hi @rubensworks . Just in case you didn't notice: the error messages in this issue is different from the one in #1128, so I opened this separately.
But I'm fine to close it if it indeed reflects the same error.

**Comment by rubensworks** [comment]
I think the errors are the same, your stack traces are just a bit clearer than in #1128 :-)
I'll copy them over there for reference.
