### ISSUE TITLE
Add check for query-sparql-* depencies

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#1139]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

To avoid issues such as https://github.com/comunica/comunica/commit/e3b938940fa30b10bf2aa68a5f6ac3086399873a, we should add a CI check to ensure that all dependencies from the compiled engine configs are available in the package.json file of each engine.
We may be able to tweak our `depcheck` script for this.

@jeswr any thoughts on this?

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| €136 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by jeswr** [comment]
Definitely worthwhile - we could try running depcheck by ensuring that depcheck points to the bundled engine. However, I seem to remember that doing so did not include all the required dependencies - is there a reason to not just add a CI check to make sure the package includes all the dependencies that `@comunica/packager` prescribes?

**Comment by rubensworks** [comment]
A bounty has been placed on this issue via the Comunica Association (see original post).

**Comment by jitsedesmet** [comment]
> all dependencies from the compiled engine configs are available in the package.json file of each engine.

With "the configs" do you refer to: https://github.com/comunica/comunica/tree/master/engines/query-sparql-file/config ?

**Comment by rubensworks** [comment]
> With "the configs" do you refer to: https://github.com/comunica/comunica/tree/master/engines/query-sparql-file/config ?

Those are indeed the configs.
But those configs are compiled to `engine-default.js` files inside each query engine package.
Inside `engine-default.js`, there will be a bunch of imports, which we will have to check to ensure that they are available as dependency.

Note that this `engine-default.js` is not available on git, as it's generated during `yarn run build`.
