### ISSUE TITLE
UTF-8 characters get corrupted when inserting into blazegraph triple store

### ISSUE THREAD

**Issue by zeroxbt** [comunica/comunica#1140]
#### Issue type:

- :bug: Bug 

____
#### Description:

When using comunica to insert triples containing diacritics, the characters get corrupted, while if axios is used the triples are inserted correctly.

For example:

##### Input triples:

`"<urn:uuid:1231231-321-3123-123-123> <http://schema.org/normal> \"Terzic\" ."

  "<urn:uuid:1231231-321-3123-123-123> <http://schema.org/test1> \"Терзић\" ."

  "<urn:uuid:1231231-321-3123-123-123> <http://schema.org/test2> \"Terzić\" ."

  "<urn:uuid:1231231-321-3123-123-123> <http://schema.org/test3> \"特尔日奇\" ."
`

##### Triples in triple store after insertion:

`"<urn:uuid:01231231-0321-3123-0123-000000000123> <http://schema.org/normal> \"Terzic\" ."

  "<urn:uuid:01231231-0321-3123-0123-000000000123> <http://schema.org/test1> \"Ð¢ÐµÑÐ·Ð¸Ñ\" ."

  "<urn:uuid:01231231-0321-3123-0123-000000000123> <http://schema.org/test2> \"TerziÄ\" ."

  "<urn:uuid:01231231-0321-3123-0123-000000000123> <http://schema.org/test3> \"ç¹å°æ¥å¥\" ."`

##### Code used to insert using comunica:
<img width="449" alt="Screenshot 2023-01-16 at 16 48 51" src="https://user-images.githubusercontent.com/89495162/212718357-27fe62b1-4e3a-4acb-ba4d-3c5f4f51a9d8.png">

##### Code used to insert using axios:
<img width="697" alt="Screenshot 2023-01-16 at 16 52 48" src="https://user-images.githubusercontent.com/89495162/212719200-1afddaa9-2423-46e1-8e37-a62f0e469fe9.png">

____

#### Environment:

`"@comunica/query-sparql": "^2.4.3"`

#### Crash log:

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| €544 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment]
I guess this will be a problem in either the parser, or the serializer.

@zeroxbt Could you check what happens if you run the INSERT query through https://github.com/RubenVerborgh/SPARQL.js/ ?

**Comment by rubensworks** [comment]
Ok, all of that looks ok. The other place where things could be going wrong is https://github.com/rubensworks/rdf-string-ttl.js
Could you check what happens when passing those terms to `termToString` of that lib?

**Comment by rubensworks** [comment]
A bounty has been placed on this issue via the Comunica Association (see original post).

**Comment by zeroxbt** [comment]
Hi @rubensworks , sorry for the late reply. Running this code: 

```js
const RdfDataModel = require('rdf-data-model');
const RdfString = require("rdf-string-ttl");

console.log(RdfString.termToString(RdfDataModel.literal('Terzic')));
console.log(RdfString.termToString(RdfDataModel.literal('Терзић')));
console.log(RdfString.termToString(RdfDataModel.literal('Terzić')));
console.log(RdfString.termToString(RdfDataModel.literal('特尔日奇')));
```

prints:

```js
"Terzic"
"Терзић"
"Terzić"
"特尔日奇"
```

**Comment by vterzic** [comment]
Hi @rubensworks, it seems that the issue is not on the Comunica side. I tested the whole `queryEngine.queryVoid()` flow and it turned out that characters are getting corrupted on the Blazegraph side.

To prove this I made identical requests using `node-fetch` (on which Comunica relies under the hood) and `axios` and in both cases characters get corrupted.

```
const fetch = require('node-fetch');
const axios = require("axios");

(async () => {
    // blazegraph - encoding error
    await axios.post('http://localhost:9999/blazegraph/namespace/kb/sparql', `INSERT DATA {
  GRAPH <urn:comunica:test> { <urn:uuid:1231231-321-3123-123-123> <http://schema.org/name> "Terzic" . }
  GRAPH <urn:comunica:test> { <urn:uuid:1231231-321-3123-123-123> <http://schema.org/name> "Terzić" . }
  GRAPH <urn:comunica:test> { <urn:uuid:1231231-321-3123-123-123> <http://schema.org/name> "Терзић" . }
}`, {
        headers: {'Content-Type': 'application/sparql-update'}
    });

    // blazegraph - encoding error
    await fetch('http://localhost:9999/blazegraph/namespace/kb/sparql', {
        method: 'POST',
        body: `INSERT DATA {
  GRAPH <urn:comunica:test> { <urn:uuid:1231231-321-3123-123-123> <http://schema.org/name> "Terzic" . }
  GRAPH <urn:comunica:test> { <urn:uuid:1231231-321-3123-123-123> <http://schema.org/name> "Terzić" . }
  GRAPH <urn:comunica:test> { <urn:uuid:1231231-321-3123-123-123> <http://schema.org/name> "Терзић" . }
}`,
        headers: {'Content-Type': 'application/sparql-update'}
    });

    // blazegraph - encoding ok (different content-type)
    await fetch('http://localhost:9999/blazegraph/namespace/kb/sparql', {
        method: 'POST',
        body: `GRAPH <urn:comunica:test> {
    <urn:uuid:1231231-321-3123-123-123> <http://schema.org/name> "Terzic" .
    <urn:uuid:1231231-321-3123-123-123> <http://schema.org/name> "Terzić" .
    <urn:uuid:1231231-321-3123-123-123> <http://schema.org/name> "Терзић" .
}`,
        headers: {'Content-Type': 'text/x-nquads'}
    });

    // graphDB - encoding ok
//     const res = await fetch('http://localhost:7200/repositories/node0/statements', {
//         method: 'POST',
//         body: `INSERT DATA {
//   GRAPH <urn:comunica:test> { <urn:uuid:1231231-321-3123-123-123> <http://schema.org/name> "Terzic" . }
//   GRAPH <urn:comunica:test> { <urn:uuid:1231231-321-3123-123-123> <http://schema.org/name> "Terzić" . }
//   GRAPH <urn:comunica:test> { <urn:uuid:1231231-321-3123-123-123> <http://schema.org/name> "Терзић" . }
// }`
//     }, {
//         headers: {'Content-Type': 'application/sparql-update'}
//     });
})()

```

The reason why zeroxbt's axios code snippet works is because of the different content-type `text/x-nquads`.

There is an issue on the blazegraph repository that seems to be related https://github.com/blazegraph/database/issues/224.

**Comment by rubensworks** [comment]
Nice detective work @vterzic!
One possible workaround I see for this would be to create a new Comunica actor that is able to transmit update queries as `text/x-nquads` to Blazegraph, but this would require some coding.
The ideal workaround would be a fix of https://github.com/blazegraph/database/issues/224
