### ISSUE TITLE
ActorHttp fail with node.js v19

### ISSUE THREAD

**Issue by constraintAutomaton** [comunica/comunica#1141]
#### Issue type:

- :bug: Bug 

____
#### Description:

When using node.js `v19.3.0` the `@comunica/bus-http/lib/ActorHttp.js` fail with the error 

```js
TypeError: Cannot assign to read only property 'ReadableStream' of object '[object global]'
at Object.<anonymous> (node_modules/@comunica/bus-http/lib/ActorHttp.js:7:23)
at Object.<anonymous> (node_modules/@comunica/bus-http/lib/index.js:17:14)
```
looking at the code we can see the comment 
 [`// TODO: Remove when targeting NodeJS 18+`](https://github.com/comunica/comunica/blob/e3b938940fa30b10bf2aa68a5f6ac3086399873a/packages/bus-http/lib/ActorHttp.ts#L5) 
(it has to be noted that this is the equivalent line of the `ts` file hence the incongruence with the line of the error that is related to the `js` compiled file)

it might be related to the error
____
#### Environment:

- comunica:  [Latest commit on the publication of this issue](https://github.com/comunica/comunica-feature-link-traversal/tree/4ce3abef94f8c7d4bd38a2e6b27d1a9bf34b81da)
- node.js: v19.3.0
- OS: Manjaro Linux Sikaris -- 22.0.0

#### Crash log:
```js
TypeError: Cannot assign to read only property 'ReadableStream' of object '[object global]'
at Object.<anonymous> (node_modules/@comunica/bus-http/lib/ActorHttp.js:7:23)
at Object.<anonymous> (node_modules/@comunica/bus-http/lib/index.js:17:14)
```

**Comment by rubensworks** [comment]
Ok, the fix should be easy.
[This hack](https://github.com/comunica/comunica/blob/master/packages/bus-http/lib/ActorHttp.ts#L6) should be modified slightly to only set `global.ReadableStream` if it has not been defined yet.

@constraintAutomaton do you want to look into this issue, so that we won't run into this problem anymore in the future?

**Comment by constraintAutomaton** [comment]
yes I'm gonna do it.
