### ISSUE TITLE
Comunica not correctly issuing `defaultGraph` parameter to QPF endpoint

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1148]
When I execute the query `SELECT * WHERE { ?s ?p ?o }` over a QPF endpoint the following URLs are fetched in the process

```json
[
  'https://fragments.ap.inrupt.com/qpf?storage=https%3A%2F%2Fstorage.ap.inrupt.com%2F311cdda9-cb55-465b-861d-5b1e4dc6ea38%2F',
  'https://fragments.ap.inrupt.com/qpf?storage=https%3A%2F%2Fstorage.ap.inrupt.com%2F311cdda9-cb55-465b-861d-5b1e4dc6ea38%2F&graph='
]
```

However the [note before the paging section](https://linkeddatafragments.org/specification/quad-pattern-fragments/#paging) would indicate that instead that the graph parameter should have the value http://www.w3.org/ns/sparql-service-description#defaultGraph.

**Comment by rubensworks** [comment]
This may be a slight misinterpretation of the spec.
`http://www.w3.org/ns/sparql-service-description#defaultGraph` should not be used as default graph value, instead, the QPF metadata shoud point to a default graph value via the `http://www.w3.org/ns/sparql-service-description#defaultGraph` predicate. (for example, the LDF server uses `urn:ldf:defaultGraph` as a value for this)
See https://linkeddatafragments.org/specification/quad-pattern-fragments/#metadata for more details.

Feel free to close this issue if this answer makes sense.
