### ISSUE TITLE
How to safely identify the metadata graph

### ISSUE THREAD

**Issue by edwardsph** [comunica/comunica#1150]
I am using a QPF endpoint with a Java client and I am concerned about how to unambiguously identify the controls/metadata graph. The spec examples and examples at https://rdf-play.rubensworks.net/ use different names for this so it can be confusing. My interpretation based on the ESS endpoint and aligning that with the spec is that the overall structure is:
```
<controls> {
  <qpf_dataset> 
    void:subset <qpf_fragment> ; # or hydra:view as predicate (see below)
    hydra:search
      [ hydra:mapping
           [ hydra:property rdf:graph ; hydra:variable "graph" ] ;
        hydra:mapping
           [ hydra:property rdf:subject ; hydra:variable "subject" ] ;
        hydra:mapping
           [ hydra:property rdf:predicate ; hydra:variable "predicate" ] ;
        hydra:mapping
           [ hydra:property rdf:object ; hydra:variable "object" ] ;
        hydra:template "storage_uri{&graph,subject,predicate,object}"
      ] .
  <controls> foaf:primaryTopic <qpf_fragment>	  

  <qpf_page>
    hydra:next    <query_uri&after=1051973> ;
    hydra:previous <query_uri&before=1051955> .

  <qpf_fragment>
    void:subset <qpf_page> ;
    void:triples "10"^^<http://www.w3.org/2001/XMLSchema#long> ;
    foaf:isPrimaryTopicOf <controls>  .
}
# the results follow as  quads
```

The controls graph IRI is unknown and I need to find it for 2 reasons:
1. To get the dataset description, the page and the fragment data
2. So that I can exclude the whole graph it when I stream back the actual results.

I do the equivalent of this query:
```
?fragment void:subset <page_uri> .
?controls foaf:primaryTopic ?fragment .
```
That is a little risky as those triples could theoretically appear within the result data. In fact, when getting the qpf_dataset on the first page of results I did stumble upon the problem of there being two triples with the void:subset predicate so you have to check you are not using the wrong one. The TPF spec suggests that instead of the first void:subset it should be hydra:view - that would at least mean that identifying the control graph requires the hydra namespace and if that is not in the result set then you are safe:
```
?fragment hydra:view <page_uri> .
?controls foaf:primaryTopic ?fragment .
```
Of course a result set describing previous searches and therefore containing hydra data would make it very difficult to find the metadata for this query. I wonder if it would be possible to have a graph name defined in the spec - that would be much easier for clients to handle.

In Comunica and https://rdf-play.rubensworks.net/, I see you have not used hydra:view but have also gone with void:subset.

I think it would be good to make the spec much clearer on the structure of the metadata graph. Could you also make recommendations for unambiguously finding it?

**Comment by rubensworks** [comment]
One of the downsides of the in-band metadata approach of TPF/QPF is indeed that metadata could clash with the actual data from the original dataset.

Regarding the `hydra:view`/`void:subset` issue, I see indeed that the TPF spec says that `hydra:view` MUST be used. However, the examples, and all server implementations I'm aware of use `void:subset`. So I'm not sure if that's a problem in the spec (@RubenVerborgh). (Comunica doesn't recognise `hydra:view`)

In any case, pull requests or suggestions for improvements to the TPF/QPF spec are most welcome on https://github.com/LinkedDataFragments/Website/issues :-)

**Comment by RubenVerborgh** [comment]
> I see indeed that the TPF spec says that `hydra:view` MUST be used. However, the examples, and all server implementations I'm aware of use `void:subset`.

That's weird; we must've changed that at some point, but never followed through.

**Comment by edwardsph** [comment]
@rubensworks Can I just check what the outcome of this was?

My main concern was:
> I think it would be good to make the spec much clearer on the structure of the metadata graph. Could you also make recommendations for unambiguously finding it?

I didn't want a change regarding `hydra:view` to mean the rest of the question was lost? Is there some guidance you can point to which explains how to overcome the risks of the in-band metadata approach? Thanks

**Comment by rubensworks** [comment]
> Is there some guidance you can point to which explains how to overcome the risks of the in-band metadata approach?

In all the years we've been using this approach, we never ran into any problems with this in-band metadata approach (as long as quads were used).
But theoretically, the risk will always exist indeed. There's no way around it AFAIK, aside from not using in-band metadata.

**Comment by edwardsph** [comment]
As a simple solution, I wondered if there could be an option for the requestor to provide the IRI of the metadata graph in the request.

**Comment by rubensworks** [comment]
That may indeed solve some cases, but it would deteriorate cacheability (which is very important for TPF/QPF).

**Comment by edwardsph** [comment]
Good point. Lastly, did you plan to update the docs to replace `void:subset` with `hydra:view`? At present we are supporting both to be safe.

**Comment by rubensworks** [comment]
Supporting both seems like the safest option indeed, since no one is actively working on the specs at the moment.
