### ISSUE TITLE
Filtering in N3 is not working as expected when using VALUES

### ISSUE THREAD

**Issue by danielbeeke** [comunica/comunica#1155]
#### Issue type:

- :bug: Bug 

____
#### Description:

The following query works fine for https://dbpedia.org/sparql but the same structure does not work for Comunica with an N3 store.

```Sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT *
WHERE {
  dbr:Søren_Kierkegaard ?p ?o.
  VALUES ?p { rdfs:label }
  FILTER(lang(?o) = "en")
}
```

Same for:

```Sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT *
WHERE {
  dbr:Søren_Kierkegaard ?p ?o.
  VALUES ?p { rdfs:label }
  FILTER(?o = "Søren Kierkegaard"@en)
}
```

____
#### Environment:

I am running the current stable npm:@comunica/query-sparql@2.6.6 via Deno

**Comment by rubensworks** [comment]
Looks like this is the same bug as in #1146, so I'm closing this in favor of that one.

> I am running the current stable npm:@comunica/query-sparql@2.6.6 via Deno

Oh, Deno, great to hear that this works (aside from this bug).

**Comment by danielbeeke** [comment]
I have tested if this issue is indeed a duplicate of #1146 and it is.
Commenting out the Sparqlee Error at https://github.com/comunica/sparqlee/blob/master/lib/functions/RegularFunctions.ts#L111 fixes the problem.
