### ISSUE TITLE
Cardinalities in startSource get overwritten

### ISSUE THREAD

**Issue by simonvbrae** [comunica/comunica#1156]
#### Issue type:
- :heavy_plus_sign: Feature request

#### Description:
On [this line in the LinkedRdfSourcesAsyncRdfIterator](https://github.com/comunica/comunica/blob/8f9371466a534bdbc385149dc653e3727d5c46b3/packages/actor-rdf-resolve-quad-pattern-hypermedia/lib/LinkedRdfSourcesAsyncRdfIterator.ts#L219) the cardinalities in startsource are overwritten and replaced by the cardinalities in metadata.
As a result, possibly relevant cardinalities are not available in the call to the accumulation mediator on [this line](https://github.com/comunica/comunica/blob/8f9371466a534bdbc385149dc653e3727d5c46b3/packages/actor-rdf-resolve-quad-pattern-hypermedia/lib/LinkedRdfSourcesAsyncRdfIterator.ts#L227).

Branch: feature/adaptive-join

**Comment by rubensworks** [comment]
@simonvbrae Could you manually apply the changes in [LinkedRdfSourcesAsyncRdfIterator.ts](https://github.com/comunica/comunica/commit/8595851f844ccd3734d656a9a0dfd2dd4c0b49fa#diff-32a8ec7495f8e5662ba16e5c6ae47b2884970a4e5e6ac3d66aac5454408131a0) as seen in the linked commit?
These should also solve your problem.
