### ISSUE TITLE
Recursive contruct queries

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1159]
As raised here https://github.com/w3c/sparql-12/issues/39#issuecomment-1435810779 it would be quite nice to be able to execute queries such as

```
CONSTRUCT WHERE {
   ?s ( foaf:knows | ex:aquantance )+ / foaf:name ?o .
}
```

or even just to have a custom query engine that returns the set arcs traversed in a given path.

**Comment by rubensworks** [comment]
Perhaps an experimental implementation might be interesting.
There's a lot of formal and implementation-specific questions that arise in this.
Is this something you want to take up?
(If not, then perhaps we should leave it for the SPARQL 1.2 CG to investigate further first)

**Comment by rubensworks** [comment]
Closing this issue, as we probably won't be able to take this up any time soon.
