### ISSUE TITLE
Use of `destroy` in `RdfJSQuadSource` possible cause of bugs.

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1164]
#### Issue type:

- :bug: Bug 

____
#### Description:

There is a possible incorrect use of `destroy` [here](https://github.com/comunica/comunica/blob/c180fc6c67de7aa5650cdc3ba9ecdf202a1f8356/packages/actor-rdf-resolve-quad-pattern-rdfjs-source/lib/RdfJsQuadSource.ts#L33) as the destruction of a stream which is *forwarded* to other iterators will result in it not emitting an end event and as such cause bugs such as https://github.com/comunica/comunica-feature-link-traversal/issues/95.

I suggest that this be replaced with `it.emit('error', error); it.close()`; it may also be worth be updating [this section](https://github.com/comunica/comunica/blob/c180fc6c67de7aa5650cdc3ba9ecdf202a1f8356/packages/actor-rdf-resolve-quad-pattern-rdfjs-source/lib/RdfJsQuadSource.ts#L58-L69) of `setMetadata` to use the `LazyCardinalityiterator`.

____

**Comment by jeswr** [comment]
I would suggest also replacing the following with `it.emit('error', error); it.close()`:
 - https://github.com/comunica/comunica/blob/c180fc6c67de7aa5650cdc3ba9ecdf202a1f8356/packages/actor-abstract-path/lib/PathVariableObjectIterator.ts#L133
 - https://github.com/comunica/comunica/blob/c180fc6c67de7aa5650cdc3ba9ecdf202a1f8356/packages/actor-rdf-resolve-hypermedia-sparql/lib/RdfSourceSparql.ts#L176
 At the same time I suggest tests be added to make sure that the streams *can be consumed* when necessary in error scenarios.

**Comment by rubensworks** [comment]
Note that `AsyncIterator.destroy()` was introduced to handle exactly these cases.
So if it doesn't do what we want it to do, then this is a design error in AsyncIterator.

The replacement you suggest is not the proper solution I believe, as calling `.close()` will still attempt to flush any buffered contents, while we can stop earlier (which is what `.destroy()` provides).

**Comment by rubensworks** [comment]
@jeswr Now that https://github.com/comunica/comunica-feature-link-traversal/issues/95 has been resolved, ok to close this issue?

**Comment by rubensworks** [comment]
Closing this one. Feel free to re-open if still relevant in the future.
