### ISSUE TITLE
Error: No metadata was found in federated query

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#117]
#### Issue type:

- :bug: Bug

#### Description:

Executing

```
comunica-sparql http://fragments.dbpedia.org/2016-04/en http://data.linkeddatafragments.org/viaf http://data.linkeddatafragments.org/harvard 'PREFIX dbo:    <http://dbpedia.org/ontology/>
PREFIX schema: <http://schema.org/>
PREFIX dc:     <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?person ?name ?book ?title {
  ?person dbo:birthPlace [ rdfs:label "Ghent"@en ].
  ?viafID schema:sameAs ?person;
               schema:name ?name.
  ?book dc:contributor [ foaf:name ?name ];
              dc:title ?title.
}'
```

fails consistently at the same place with

```
 Error: No metadata was found
(node:10747) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It seems that we need both:
a) a global promise rejection handler
b) a fix for this particular bug 😄 

____
#### Environment:

@comunica/actor-init-sparql@1.0.0 on OSX 10.9.5 with Node 8.9.4 and npm 5.6.0

**Comment by pietercolpaert** [comment]
Could be related to https://github.com/comunica/comunica/issues/121

**Comment by RubenVerborgh** [comment]
I doubt it, as it only fails late in the process—but could be related if #15 does not wait until the very last triple before finding controls.

**Comment by rubensworks** [comment]
Fixed in https://github.com/comunica/comunica/commit/3af4bcf639ce88ea9cf56068267441566699107c
