### ISSUE TITLE
Missing results with UNION and FILTER

### ISSUE THREAD

**Issue by dobbelap** [comunica/comunica#1179]
#### Issue type:

- :bug: Bug

#### Description:

when querying over 

```turtle
prefix wws: <http://wws#>.
wws:ent1 wws:p12 wws:ent2.
wws:ent2 wws:p23 wws:ent3.
wws:ent3 wws:p34 "lit4".
@prefix wws: <http://wws#>.
wws:ent1 wws:access_XP wws:userB_node.
wws:ent1 wws:access_TV wws:userB_node.
wws:userB_node wws:userid "userB".
wws:userB_node wws:filter "filterfunction".
wws:userB_node wws:filtercontext "filtercontext".
wws:ent2 wws:access_TV wws:everyone_node.
wws:ent3 wws:access_XP wws:everyone_node.
wws:ent3 wws:access_TV wws:everyone_node.
```

the query

```sparql
prefix wws: <http://wws#> 
select ?e1  where { 
    ?e1 wws:p12 ?e2. 

  {
    ?e1 wws:access_XP wws:everyone_node.
    # ?e1 wws:p12 ?e2. 
  }
  UNION
  {
     ?e1 wws:access_XP ?user_node1.
     ?user_node1 wws:userid "userB".
     ?user_node1 wws:filter ?filterfunction1.
     ?user_node1 wws:filtercontext ?filtercontext1.
     # FILTER clause only succeeds if alternative side has p12 relation ????
     # has to do with ?e1 not bound if no p12 ???
     FILTER (bound(?e1))
  } 
}
```

needs the wws:p12 triple uncommented in the first UNION block before returning the result
e1=uri<http://wws#ent1>

I think this should also work with that triple commented.
(at least roqet from the rasqal library agrees with that)

*** files are added to bug.zip ***

____
#### Environment:

see package-lock.json in bug.zip

| software         | version(s)
| ---------------- | -------
| Comunica Engine  |  "@comunica/query-sparql-file": "^2.6.9"
| node             | v18.15.0
| npm              | 9.5.0
| yarn             | 
| Operating System | windows10 and linux (ubuntu)

[bug.zip](https://github.com/comunica/comunica/files/10999808/bug.zip)

**Comment by rubensworks** [comment]
Does the problem also occur if you remove the FILTER clause?

**Comment by dobbelap** [comment]
> Does the problem also occur if you remove the FILTER clause?
no, it is explicitely triggered by the presence of a FILTER clause.
note that the original query where we discovered the problem had a much more complex filter clause including a user defined function. I just wanted to reduce the query to something more simple (and without user-defined functions) that still had the suspect behaviour. hence the bound(?e1) which looks a bit unnecessary indeed. But it does trigger the behaviour that should be investigated...

**Comment by rubensworks** [comment]
Ok, thanks for the clarification!

@jitsedesmet Could you have a quick look at this one? I suspect this is **not** related to sparqlee, but perhaps you can have a look to confirm this.

**Comment by jitsedesmet** [comment]
I had a quick glance at this issue and I don't think sparqlee is to blame. It seems like sparlee does not handle `UNION` so it would be weird if the effects of one UNION case would effect the result of another case solely by a sparqlee issue.
