### ISSUE TITLE
Slow query over 2 SPARQL endpoints produces no results or errors

### ISSUE THREAD

**Issue by chenkuncloud** [comunica/comunica#1188]
Hi, `comunica/query-sparql` use `FILTER` when querying over multiple sources doesn't get the expected results.

Version: v2.6.10 in docker.

SPARQL Endpoints: https://dbpedia.org/sparql http://linkedgeodata.org/sparql

Using the following SPARQL doesn't get the expected results:
```text
CONSTRUCT {
  ?s ?p ?o .
}
WHERE {
  ?s ?p ?o .
  FILTER ( ?s = <http://dbpedia.org/resource/Resource_Description_Framework> )
}
LIMIT 100
```

But Using the following SPARQL can get the expected result:
```text
CONSTRUCT {
  <http://dbpedia.org/resource/Resource_Description_Framework> ?p ?o .
}
WHERE {
  <http://dbpedia.org/resource/Resource_Description_Framework> ?p ?o .
}
LIMIT 100
```

And I get the expected results when I specify only the `https://dbpedia.org/sparql` endpoints.
```text
CONSTRUCT {
  ?s ?p ?o .
}
WHERE {
  ?s ?p ?o .
  FILTER ( ?s = <http://dbpedia.org/resource/Resource_Description_Framework> )
}
LIMIT 100
```

**Comment by jeswr** [comment]
> Using the following SPARQL doesn't get the expected results:

What are you getting instead?

**Comment by chenkun19960427** [comment]
Hi @jeswr ,I didn't get any return messages.
![image](https://user-images.githubusercontent.com/40781280/228707720-dba88e8b-e4b2-43e4-a627-dd3ad4d3ab4a.png)

**Comment by rubensworks** [comment]
I suspect this is just a performance issue. Your query is essentially pulling in _all_ triples from both endpoints, and doing the filtering client-side.

In any case, when executing the following
```
comunica-sparql https://dbpedia.org/sparql http://linkedgeodata.org/sparql -q "CONSTRUCT {
  ?s ?p ?o .
}
WHERE {
  ?s ?p ?o .
  FILTER ( ?s = <http://dbpedia.org/resource/Resource_Description_Framework> )
}
LIMIT 100" -l debug
```
we can see that the query exec starts, but then it terminates without emitting anything (no error, and no empty results). This is a problem indeed, probably as a consequence of some timeout.
