### ISSUE TITLE
Too many results when rebinding results from sub select statement.

### ISSUE THREAD

**Issue by ajuvercr** [comunica/comunica#1205]
#### Issue type:

- :bug: Bug 

____
#### Description:

Too many results when rebinding results from sub select statement.

Without rebinding 3 results are present
```sparql
SELECT *
WHERE {
  {
    SELECT 
      ?sensor (max(?time) as ?max)
    WHERE {
    ?obj a <http://def.isotc211.org/iso19156/2011/Observation#OM_Observation>;
      <https://data.vlaanderen.be/ns/observaties-en-metingen#Observatie.uitgevoerdDoor> ?sensor;
      <http://def.isotc211.org/iso19156/2011/Observation#OM_Observation.resultTime> ?time .
    } GROUP BY ?sensor 
  }
}
```

[Query online](
https://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fknowledgeonwebscale.github.io%2FMUMO-Primer%2Fdata.jsonld&query=PREFIX%20mumo%3A%20%3Chttp%3A%2F%2Fmumo.be%2F%3E%0A%0ASELECT%20*%0AWHERE%20%7B%0A%20%20%20%0A%20%20%7B%0A%20%20%20%20SELECT%20%0A%20%20%20%20%20%20%3Fsensor%20(max(%3Ftime)%20as%20%3Fmax)%0A%20%20%20%20WHERE%20%7B%0A%20%20%20%20%3Fobj%20a%20%3Chttp%3A%2F%2Fdef.isotc211.org%2Fiso19156%2F2011%2FObservation%23OM_Observation%3E%3B%0A%20%20%20%20%20%20%3Chttps%3A%2F%2Fdata.vlaanderen.be%2Fns%2Fobservaties-en-metingen%23Observatie.uitgevoerdDoor%3E%20%3Fsensor%3B%0A%20%20%20%20%20%20%3Chttp%3A%2F%2Fdef.isotc211.org%2Fiso19156%2F2011%2FObservation%23OM_Observation.resultTime%3E%20%3Ftime%20.%0A%20%20%20%20%7D%20GROUP%20BY%20%3Fsensor%20%0A%20%20%7D%0A%7D%0A
)

Rebinding results in more results, even results that are not expected (not just duplicates).
```sparql
SELECT *
WHERE {
  {
    SELECT 
      ?sensor (max(?time) as ?max)
    WHERE {
    ?obj a <http://def.isotc211.org/iso19156/2011/Observation#OM_Observation>;
      <https://data.vlaanderen.be/ns/observaties-en-metingen#Observatie.uitgevoerdDoor> ?sensor;
      <http://def.isotc211.org/iso19156/2011/Observation#OM_Observation.resultTime> ?time .
    } GROUP BY ?sensor 
  }

  ?obj a <http://def.isotc211.org/iso19156/2011/Observation#OM_Observation>;
     <https://data.vlaanderen.be/ns/observaties-en-metingen#Observatie.uitgevoerdDoor> ?sensor;
     <http://def.isotc211.org/iso19156/2011/Observation#OM_Observation.resultTime> ?max.
}
```

[Query online](https://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fknowledgeonwebscale.github.io%2FMUMO-Primer%2Fdata.jsonld&query=PREFIX%20mumo%3A%20%3Chttp%3A%2F%2Fmumo.be%2F%3E%0A%0ASELECT%20*%0AWHERE%20%7B%0A%20%20%20%0A%20%20%7B%0A%20%20%20%20SELECT%20%0A%20%20%20%20%20%20%3Fsensor%20(max(%3Ftime)%20as%20%3Fmax)%0A%20%20%20%20WHERE%20%7B%0A%20%20%20%20%3Fobj%20a%20%3Chttp%3A%2F%2Fdef.isotc211.org%2Fiso19156%2F2011%2FObservation%23OM_Observation%3E%3B%0A%20%20%20%20%20%20%3Chttps%3A%2F%2Fdata.vlaanderen.be%2Fns%2Fobservaties-en-metingen%23Observatie.uitgevoerdDoor%3E%20%3Fsensor%3B%0A%20%20%20%20%20%20%3Chttp%3A%2F%2Fdef.isotc211.org%2Fiso19156%2F2011%2FObservation%23OM_Observation.resultTime%3E%20%3Ftime%20.%0A%20%20%20%20%7D%20GROUP%20BY%20%3Fsensor%20%0A%20%20%7D%0A%0A%20%20%3Fobj%20a%20%3Chttp%3A%2F%2Fdef.isotc211.org%2Fiso19156%2F2011%2FObservation%23OM_Observation%3E%3B%0A%20%20%20%20%20%3Chttps%3A%2F%2Fdata.vlaanderen.be%2Fns%2Fobservaties-en-metingen%23Observatie.uitgevoerdDoor%3E%20%3Fsensor%3B%0A%20%20%20%20%20%3Chttp%3A%2F%2Fdef.isotc211.org%2Fiso19156%2F2011%2FObservation%23OM_Observation.resultTime%3E%20%3Fmax.%0A%7D%0A)

My use case consists of looking for the last measurement for each sensor and returning its result.

____
#### Environment:

This is both the case online as local.

```
$ comunica-sparql -v
| software         | version
| ---------------- | -------
| Comunica Engine  | 2.6.9 
| node             | v16.20.0
| npm              | 8.19.2
| yarn             | 1.22.19
| Operating System | linux (Linux 5.15.108-1-MANJARO)
```

**Comment by rubensworks** [comment]
Might be a bug in our join algorithm(s).
If so, then it's related to #1179 and #1201.

**Comment by rubensworks** [comment]
@ajuvercr Do you have another dataset we can test with?
I get the following error with your dataset:
```
Failed to load remote context https://raw.githubusercontent.com/KNowledgeOnWebScale/MUMO-Primer/main/context.jsonld: Unsupported JSON-LD media type text/plain
```
