### ISSUE TITLE
Agregates with xsd:date objects do not work

### ISSUE THREAD

**Issue by danielbeeke** [comunica/comunica#1212]
#### Issue type:

- :bug: Bug 

____
#### Description:
The following SPARQL query does not work. 
```SPARQL
prefix : <http://stardog.com/tutorial/>

SELECT (min(?date) as ?minDate) (max(?date) as ?maxDate)
{
    ?album a :Album ;
           :date ?date
}
```
However casting the xsd:date values to a number does work
```SPARQL
prefix : <http://stardog.com/tutorial/>

SELECT (min(year(?date)) as ?minDate) (max(year(?date)) as ?maxDate)
{
    ?album a :Album ;
           :date ?date
}
```

Could this be related?
https://github.com/comunica/sparqlee/pull/71

We will add a log later with the Comunica Logger turned on.
____
#### Environment:

| software         | version
| ---------------- | -------
| Comunica Engine  | 2.6.9 
| node             | v19.1.0
| npm              | 8.19.3
| yarn             | 1.22.19
| Operating System | linux (Linux 5.19.0-23-generic)

**Comment by rubensworks** [comment]
Min/max support for dates is not standard SPARQL 1.1 AFAIK.
But these should be possible now as of 9788c434c9d6496746733f37856046b0ac0bc124 (not released yet).

Could you try using the latest version in `master`?

**Comment by ghsnd** [comment]
This still seems to be an issue using 2.7.0 (also when using xsd:dateTime).

**Comment by rubensworks** [comment]
@jitsedesmet Could you have a look at this one?

**Comment by jitsedesmet** [comment]
Seems like this is something Sparqlee handles wrong. [The spec](https://www.w3.org/TR/sparql11-query/#defn_aggMin) states:
> It makes use of the SPARQL ORDER BY ordering definition.

The aggregator in Sparqlee just uses the `<` operator of JS. I think this issue can easily be resolved by calling one of the functions in `Ordering.ts`. I'll look into this as soon as I can.
