### ISSUE TITLE
Invalid .bin files from repo packages

### ISSUE THREAD

**Issue by joachimvh** [comunica/comunica#122]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

#### Description:
The generated .bin files of other packages in the monorep seem te be unusable.
E.g. `.bin/comunica-run` looks as follows:
```bash
"$basedir/../../../runner-cli/bin/run.js"   "$@"
exit $?
```
while a normal generated .bin file looks something like this:

```bash
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../acorn/bin/acorn" "$@"
  ret=$?
else 
  node  "$basedir/../acorn/bin/acorn" "$@"
  ret=$?
fi
exit $ret
```

Might be a Lerna thing, but it causes me to be unable to use those .bin files.
____
#### Environment:

_Exact versions of the software in your environment, not just *latest*. Only needed for :bug: and :snail:._

| software            | version(s)
| ------------------- | -------
| Comunica Init Actor | `@comunica/actor-init-hello-world` 1.0.0
| Comunica            | 1.0.0
| node                | 8.4.0
| npm                 | 5.7.1
| Operating System    | Windows

**Comment by rubensworks** [comment]
Not sure if I'll be able to help with that, probably a Windows-only issue, as my bins are just symlinks.

**Comment by joachimvh** [comment]
I found out about it because Arne had problems with the bin stuff, so I assumed there's also a problem on Unix. Also, symlinking to the file is different behaviour from what the bin files are supposed to do. As you can see in the example above, that bin file actually calls `node FILE_NAME_HERE` instead of just calling the file as a command. 

Also this is totally low priority, this issue is mostly here so we can remember it when the problem pops up :P

**Comment by joachimvh** [comment]
Update: this is apparently only a problem with comunca-run, all the other .bin files are fine
