### ISSUE TITLE
Breaking update of `lru-cache` dep

### ISSUE THREAD

**Issue by smessie** [comunica/comunica#1227]
#### Issue type:

- :bug: Bug 

____
#### Description:

It seems like the update of the `lru-cache` dependency introduced a breaking change that is not handled well here.

> Yeah, so, some additional care must be taken when wrapping an object in a Proxy if it uses private properties. You can't just pass through get calls for methods to the source object, because if those methods use hard-private properties, they'll end up being called in the this-context of an object whose class didn't define those private properties.
> So, yes, it is a change made to LRUCache that made it incompatible with this sort of usage, but also, it's a shortcoming in the Proxy usage that depends too intimately on the internal details of the object it's wrapping. Ie, it requires that the source object doesn't reference any hard-private properties from public methods, and if you don't reference them from any exposed method, then why are they even there?
> Breaking change on semver major update, sorry, that's how it goes. The consuming code has to change. Frankly, it's a very brittle approach, and lucky that the change happened in a semver major update, since many would not consider the addition of internal private members to be a breaking change at all.

https://github.com/isaacs/node-lru-cache/issues/286#issuecomment-1622251262

____
#### Environment:

Comunica version 2.8.0

#### Crash log:

```
Uncaught (in promise) TypeError: Cannot read from private field
    at __accessCheck (chunk-NNYXQWFV.js?v=093567c1:44:11)
    at __privateGet (chunk-NNYXQWFV.js?v=093567c1:47:3)
    at Proxy.get (index.ts:2147:19)
    at Proxy.run (ActorRdfResolveQuadPatternStringSource.ts:49:40)
    at Proxy.runObservable (Actor.ts:83:37)
    at Proxy.mediate (Mediator.ts:86:18)
    at async FederatedQuadSource.ts:262:18
    at async Promise.all (:5173/index 0)
```

Currently the source code where I encountered this bug is at https://github.com/smessie/TAS and this version is deployed at https://95712320.tas-4d1.pages.dev

**Comment by rubensworks** [comment]
Weird that you have `Proxy` in your stacktrace. Comunica doesn't use any proxies.

Can you reproduce it outside of vue/vite? Perhaps they are injecting proxies somehow?

**Comment by smessie** [comment]
It was a Vue issue in the end.

I had my QueryEngine as a variable in my data:
```js
export default {
  data() {
    return {
      engine: new QueryEngine(),
    };
  }
}
```

However, [Vue sets all the properties in the data option to setters/getters to make them reactive](https://vuejs.org/guide/essentials/reactivity-fundamentals.html#reactive-proxy-vs-original).

So to solve it, I placed `const engine = new QueryEngine();` outside of my data, just under my imports.
Another way to solve, in case you cannot move the engine outside the data object for some reason, is by using `toRaw`.
```js
import {toRaw} from "vue";

toRaw(this.engine).queryBindings(...)
```

**Comment by rubensworks** [comment]
Aha, that makes sense. Thanks for sharing this @smessie, might be useful to other readers of this issue in the future!
