### ISSUE TITLE
`UNION` only passes up a variable binding if it's bound in every branch

### ISSUE THREAD

**Issue by Peeja** [comunica/comunica#1229]
#### Issue type:

- :bug: Bug 

____
#### Description:

As expected, a query of `BIND`s:

```sparql
SELECT
  ?a ?b
WHERE {
  BIND("a1" AS ?a)
  BIND("b1" AS ?b)
}
```

returns one set of bindings with those two values:

```text
1 bindings:
╔══════╤══════╗
║ a    │ b    ║
╟──────┼──────╢
║ "a1" │ "b1" ║
╚══════╧══════╝
```

Also as expected, a union of such queries:

```sparql
SELECT
  ?a ?b
WHERE {
  {
    BIND("a1" AS ?a)
    BIND("b1" AS ?b)
  }
  UNION
  {
    BIND("a2" AS ?a)
    BIND("b2" AS ?b)
  }
}
```

returns one set of bindings for each branch of the `UNION`:

```text
2 bindings:
╔══════╤══════╗
║ a    │ b    ║
╟──────┼──────╢
║ "a1" │ "b1" ║
╟──────┼──────╢
║ "a2" │ "b2" ║
╚══════╧══════╝
```

However, if one of the branches fails to bind one of the variables:

```sparql
SELECT
  ?a ?b
WHERE {
  {
    BIND("a1" AS ?a)
    BIND("b1" AS ?b)
  }
  UNION
  {
    BIND("a2" AS ?a)
  }
}
```

no bindings are returned for that variable, even for a solution where it should be defined:

```text
2 bindings:
╔══════╗
║ a    ║
╟──────╢
║ "a1" ║
╟──────╢
║ "a2" ║
╚══════╝
```

This holds even when there are several branches, and only one leaves the variable undefined:

```sparql
SELECT
  ?a ?b
WHERE {
  {
    BIND("a1" AS ?a)
    BIND("b1" AS ?b)
  }
  UNION
  {
    BIND("a2" AS ?a)
  }
  UNION
  {
    BIND("a3" AS ?a)
    BIND("b3" AS ?b)
  }
}
```

```text
3 bindings:
╔══════╗
║ a    ║
╟──────╢
║ "a1" ║
╟──────╢
║ "a2" ║
╟──────╢
║ "a3" ║
╚══════╝
```

My initial thought was that `?b` is not properly in scope if it's not bound in each branch of the `UNION`, but [the spec says](https://www.w3.org/TR/sparql11-query/#variableScope):

> We define a variable to be _in-scope_ if there is a way for a variable to be in the domain of a solution mapping at that point in the execution of the SPARQL algebra for the query. The definition below provides a way of determing this from the abstract syntax of a query.

Even weirder, `BIND`ing one of the variables _twice_ in a single branch can cause the missing bindings to suddenly appear:

```sparql
SELECT
  ?a ?b
WHERE {
  {
    BIND("a1" AS ?a)
    BIND("b1" AS ?b)
  }
  UNION
  {
    BIND("a2" AS ?a)
    BIND("a3" AS ?a)
  }
}
```

```text
2 bindings:
╔══════╤══════╗
║ a    │ b    ║
╟──────┼──────╢
║ "a1" │ "b1" ║
╟──────┼──────╢
║ "a3" │      ║
╚══════╧══════╝
```

This would seem to be both a potential clue to the bug in question, and a bug in its own right, as (I believe) re-`BIND`ing a variable like this should be illegal: the first `BIND` causes the variable to be in scope, [and](https://www.w3.org/TR/sparql11-query/#variableScope):

> In `BIND (expr AS v)` requires that the variable `v` is not in-scope from the preceeding elements in the group graph pattern in which it is used.

____
#### Environment:

`@comunica/query-sparql-rdfjs` over a single [N3.js](https://github.com/rdfjs/N3.js) `Store`.

**Comment by Peeja** [comment]
Hmm, more experimentation based on that odd case at the end:

```sparql
SELECT
  ?a ?b
WHERE {
  {
    BIND("a1" AS ?a)
    BIND("b1" AS ?b)
  }
  UNION
  {
    BIND("a2" AS ?a)
    BIND("a2" AS ?a)
  }
}
```

```
2 bindings:
╔══════╤══════╗
║ a    │ b    ║
╟──────┼──────╢
║ "a1" │ "b1" ║
╟──────┼──────╢
║ "a2" │      ║
╚══════╧══════╝
```

That is, even re-`BIND`ing one variable with the *same value* each time will cause that branch to no longer prevent the other branches from passing up other variables. Which certainly makes working around this issue easier. 😃

**Comment by rubensworks** [comment]
Sounds related to #1201.
So something _might_ be going wrong inside our selectivity actor again (6984a5af1a01131a4c9855483a6192fb7217d0d5).

**Comment by rubensworks** [comment]
I just looked into this, and all queries (expect for the last one) seem to work as intended to me though.
Can you double-check you're using the latest version of comunica and try again? (I didn't see a version mentioned in the issue)

The latest query not throwing is a problem indeed, which I just fixed.

**Comment by Peeja** [comment]
Oh no, you're right! It's my code that's wrong! 😅 My logging code was assuming every `Bindings` would have the same variables, but that some of the values for those variables could be `null`. But that's not it at all: if a variable is unbound, that `Bindings` doesn't have an entry for it, and when there _is_ an entry, there's always a value. 🤦🏻‍♀️ 

Whelp. Thanks for looking into it, and sorry for taking you on a wild goose chase! 😁

**Comment by rubensworks** [comment]
No worries, thanks for checking :)
