### ISSUE TITLE
Actor inner-multi-smallest should be able to handle undefs in its stream

### ISSUE THREAD

**Issue by maartyman** [comunica/comunica#1231]
#### Issue type:

- :bug: Bug 

____
#### Description:

The `inner-multi-smallest` join actor is able to handle undefined elements in its binding streams. Therefore, it should have the line `canHandleUndefs: true` in its constructor.

____
#### Environment:

The bug occurred with a large query (not going to post it here) where the circumstances were ideal that the `multi-bind` join can't handle the join (see Crash log) and the `multi-smallest` join rejects because the binding stream might have undefined.

#### Crash log:

All join actors reject their test:
`
Error: All actors rejected their test in urn:comunica:default:rdf-join/mediators#main
Actor urn:comunica:default:rdf-join/actors#inner-none can only join zero entries
Actor urn:comunica:default:rdf-join/actors#inner-single can only join a single entry
urn:comunica:default:rdf-join/actors#inner-hash requires 2 join entries at most. The input contained 5.
urn:comunica:default:rdf-join/actors#inner-symmetric-hash requires 2 join entries at most. The input contained 5.
urn:comunica:default:rdf-join/actors#inner-nested-loop requires 2 join entries at most. The input contained 5.
urn:comunica:default:rdf-join/actors#minus-hash can only handle logical joins of type 'minus', while 'inner' was given.
urn:comunica:default:rdf-join/actors#minus-hash-undef can only handle logical joins of type 'minus', while 'inner' was given.
urn:comunica:default:rdf-join/actors#optional-bind can only handle logical joins of type 'optional', while 'inner' was given.
urn:comunica:default:rdf-join/actors#optional-nested-loop can only handle logical joins of type 'optional', while 'inner' was given.
Actor urn:comunica:default:rdf-join/actors#inner-multi-smallest can not join streams containing undefs
Actor urn:comunica:default:rdf-join/actors#inner-multi-bind can not bind on Extend, Group, and Filter operations
Actor urn:comunica:default:rdf-join/actors#inner-multi-empty can not join streams containing undefs
`

**Comment by rubensworks** [comment]
Could you open a PR with a fix for this?
Some of the other multi actors _might_ also require such a change.

**Comment by maartyman** [comment]
Yes!
