### ISSUE TITLE
Comunica Engine JS not resolving promise

### ISSUE THREAD

**Issue by AronBuzogany** [comunica/comunica#1236]
#### Issue type:

- :bug: Bug 

____
#### Description:

For a Web application I am currently working on I use the Comunica Engine to query endpoints. Whilst doing this I have encountered the following issue: 

After any error occurs in the [query](https://comunica.github.io/comunica/classes/_comunica_query_sparql.QueryEngine.html#query) function, all calls to that same function that would cause an error to be thrown do not get resolved. The function doesn't throw an error, nor does is return/stop. If however the query wouldn't cause an error, it gets executed as usually. 

I have also tried to create a new engine for every query, which didn't resolve the issue. 
____
#### Environment:

For my Web application I use ReactJS and I have imported the engine as suggested in [the documentation](https://comunica.dev/docs/query/getting_started/query_app/). I have also made sure the latest version was used with `npm update`  

As an example I have made a small script showing the error (I tried creating a sandbox, but errors got called when importing Comunica):

```js
import { QueryEngine } from "@comunica/query-sparql";

const myQueryEngine = new QueryEngine()

const query = `SELECT ?s ?p ?o WHERE {
                ?s ?p ?o
            }`


function faultyFetch(arg){
    throw new Error("Fetch failed!")
}


try{
    await myQueryEngine.query(query, {sources: ["https://fragments.dbpedia.org/2016-04/en"], fetch: faultyFetch} )
    console.log("The first query didn't cause an error.")
}
catch(error){
    console.log("The first error occured!")
}


try{
    await myQueryEngine.query(query, {sources: ["https://fragments.dbpedia.org/2016-04/en"], fetch: faultyFetch} )
    console.log("The second query didn't cause an error.")
}
catch(error){
    console.log("The seocnd error occured!")
}
``` 
Executing this function with `node script.js -v` returns the following: `The first error occured!`.

I would expect that `The second query didn't cause an error.` or `The seocnd error occured!` would also be logged.

**Comment by AronBuzogany** [comment]
> Does the error always occur in the fetch function? 

I have only experienced this with errors in the fetch function. 

>  If so, caching might be the issue.

It indeed did! Thank you very much

**Comment by rubensworks** [comment]
Great, thanks for checking.

In any case, the fact that erroring requests are incorrectly handled in the cache is still and issue. So I'll keep this issue open.
