### ISSUE TITLE
The binding stream "end event" is not sent given a queries with a filter expression evaluating to false and a limit statement

### ISSUE THREAD

**Issue by constraintAutomaton** [comunica/comunica#1243]
#### Issue type:

- :bug: Bug 

____
#### Description:

To detect if a query has ended the `end` event of a `bindingStream` can be used. However with some queries this event is never triggered. In some cases it does not matter because the program will simply exit when the query has finished its execution. But in others, where some processing has to be done at the end of the query execution or when a timeout is implemented in the program, this can cause problems.

The problem seems to manifest with specific kinds of queries, more precisely when there is a filter expression that is evaluated to false **and** a limit statement **and** when there is an IRI in the query that does not match in the data source.

Example queries with the data source `https://dbpedia.org/resource/Tractatus_de_Intellectus_Emendatione`

---
**Does not work**

```sparql
SELECT * WHERE {
  ?s ?p <http://purl.org/dc/terms/dontExist>
  FILTER(?s>1)
} LIMIT 1
```

```sparql
SELECT * WHERE {
  ?s ?p <http://purl.org/dc/terms/subject>
  FILTER(false)
} LIMIT 1
```

---
**Does work**

```sparql
SELECT * WHERE {
  ?s ?p <http://purl.org/dc/terms/dontExist>
} LIMIT 1
```

```sparql
SELECT * WHERE {
  ?s ?p <http://purl.org/dc/terms/dontExist>
  FILTER(?s>1)
}
```
```sparql
SELECT * WHERE {
  ?s ?p <http://purl.org/dc/terms/dontExist>
  FILTER(false)
}
```

```sparql
SELECT * WHERE {
  ?s ?p <http://purl.org/dc/terms/dontExist>
} LIMIT 1
```
```sparql
SELECT * WHERE {
  ?s ?p <http://dbpedia.org/resource/Category:Works_by_Baruch_Spinoza>
  FILTER(false)
} LIMIT 10
```
```sparql
SELECT * WHERE {
  ?s ?p ?o
  FILTER(false)
} LIMIT 10
```
---
With the link traversal engine, the problem manifests a bit differently

if there are two mismatching triples (with one it works) then the stream does not send the `end` event (the limit statement doesn't seem to matter)

So the constant seems to be unmatching triples and false filter expression.

____
#### Environment:
| software         | version
| ---------------- | -------
| Comunica Engine  | 2.8.2 (dev)
| node             | v20.5.0
| npm              | 9.8.0
| yarn             | 1.22.19
| Operating System | linux (Linux 6.1.44-1-MANJARO)

**Comment by rubensworks** [comment]
It was just a typical `autoStart` problem.

See https://github.com/RubenVerborgh/AsyncIterator/issues/25
