### ISSUE TITLE
Bindings.toString() pushes strings inside of strings

### ISSUE THREAD

**Issue by Certiman** [comunica/comunica#1244]
I am using the `.queryBindings` method to `.on` push the `binding.toString()` in an array for further operation.

But since the function https://github.com/comunica/comunica/blame/3a35163546698575f63760907dc1de4a5f7d3e88/packages/bindings-factory/lib/bindingsToString.ts#L8 does not check if the value is already a string, it seems to place the string value inside of a string. 

This results in objects, with values like `"username": "\"duhouma\"",`. I had hoped to see `"username":"duhouma"`.

Was this the intention?

**Comment by rubensworks** [comment]
Yep, that's intentional.

Stringification of bindings is mainly for debugging purposes.
If you need specific behaviour on certain term types, it's better to use `.get()`.
