### ISSUE TITLE
Authorisation parameters not respected when using CLI comunica-sparql

### ISSUE THREAD

**Issue by sparkling** [comunica/comunica#1250]
#### Issue type:

- :bug: Bug 

____
#### Description:

Issuing this command:
```
comunica-sparql sparql@http://user:password@localhost:12110/datastores/df/sparql "CONSTRUCT {?s ?p ?o} WHERE {?s ?p ?o} LIMIT 20"
```
No authorisation header is set in the request, user and password attributes are silently ignored.
____
#### Environment:
```
| software         | version
| ---------------- | -------
| Comunica Engine  | 2.8.2
| node             | v19.8.1
| npm              | 9.6.6
| yarn             | 1.22.17
| Operating System | darwin (Darwin 22.6.0)
```

**Comment by rubensworks** [comment]
FYI, we're working on Comunica v3, which will focus on improving performance of federated querying across SPARQL endpoints. This should resolve this issue when completed.
