### ISSUE TITLE
Query to http url fails with Node 18+

### ISSUE THREAD

**Issue by gbirke** [comunica/comunica#1252]
#### Issue type:

- :bug: Bug 

____
#### Description:

I've set up a local web server with a turtle file and tried to run a "hello world" query from the command line like this:

    comunica-sparql http://127.0.0.1:6000/example1.ttl -q "SELECT *  WHERE { ?s ?p ?o }" 

When running this with Node 18, I get the error message "fetch error". When I run this in a docker environment with Node 16 (changing the URL from the local IP to the name of the container), the query succeeds.

I can only speculate about why this happens, but looking at my package.lock and node_modules I can  see that it uses version 3.0.6 of `cross-fetch` which is not compatible with Node 18+ So maybe there is something in the dependency tree that forces it to be version 3 instead of version 4.

I've installed the CLI tool with `npm install -g @comunica/query-sparql`

____
#### Environment:

| software         | version
| ---------------- | -------
| Comunica Engine  | 2.8.2 
| node             | v18.17.1
| npm              | 9.6.7
| yarn             | 1.22.19
| Operating System | linux (Linux 6.2.0-26-generic)

#### Crash log:

https://pastebin.com/W5BuHYmP

**Comment by rubensworks** [comment]
Have you tried with a public http server (such as http://fragments.dbpedia.org/2016-04/en), to rule out potential connection issues with your localhost?

**Comment by rubensworks** [comment]
FYI, some of the answers in this thread might help: https://stackoverflow.com/questions/74165121/next-js-fetch-request-gives-error-typeerror-fetch-failed

**Comment by gbirke** [comment]
I have checked with http://fragments.dbpedia.org/2016-04/en and it works. I can reach the URL just fine with `curl` and the command works when I use node 16, so it is something about the Node version. 

This led me to https://stackoverflow.com/a/76059960/130121 and made me try the command with

    npx --node-options '--no-experimental-fetch' comunica-sparql http://127.0.0.1:6000/example1.ttl -q "SELECT *  WHERE { ?s ?p ?o }"

That worked fine with the local URL, so I think there is nothing to do for you here, you may close this ticket.

I also found https://github.com/nodejs/node/issues/46167 but changing my `/etc/hosts` had no effect (also, I used the local IP instead of `localhost` anyway)

**Comment by rubensworks** [comment]
Good to hear you have a workaround @gbirke! I'll keep an eye on https://github.com/nodejs/node/issues/46167, and close this issue here in the meantime.
