### ISSUE TITLE
Integrate expression handling into comunica's bus system

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#1255]
Depends on comunica/sparqlee#131.

To enable developers to override the handling of specific expressions in a dynamic manner, we should create a bus expressions bus in comunica, and let sparqlee handle these via an actor. This will enable overriding expression handling via other actors.

Not sure yet if we should split up sparqlee up into separate actors.

**Comment by jacoscaz** [comment]
Wouldn't splitting up sparqlee into separate actors drastically impact performance?

**Comment by rubensworks** [comment]
This should not have an impact on performance, @jitsedesmet will make sure of that :-)

**Comment by rubensworks** [comment]
Done in https://github.com/comunica/comunica/pull/1439
