### ISSUE TITLE
Make proxy configurable for each source seperately

### ISSUE THREAD

**Issue by AronBuzogany** [comunica/comunica#1275]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

Currently we pass a proxy as a context variable as explained in [documentation](https://comunica.dev/docs/query/advanced/proxying/) (or not if we don't want to use a proxy.) This is than applied to every source in the `sources` field. It would be nice to have some sources use the proxy and others not. Additionally different sources could use different proxies. 

An example of where this could be useful is:

querying 2 sources:

The first source has "bad" CORS headers which return an error when for example querying authenticated with `solid-authn`. 
The second query doesn't do this. 

In this case we would want the first source the be queried through a proxy which resolves the CORS headers and avoids an error being returned by the server. The second source doesn't need to go through the proxy as this would be unnecessary overhead. 

This could possibly be an extension to [source types](https://comunica.dev/docs/query/advanced/source_types/)

Additionally, this feature could be extended to also support other context fields such as `httpRetryCount`, `httpRetryDelay` etc.

**Comment by rubensworks** [comment]
It's not well documented yet, but you can actually pass contexts to sources. See https://github.com/comunica/comunica/issues/1003 for an example.

**Comment by rubensworks** [comment]
Closing, now that #1003 is completed.
