### ISSUE TITLE
BGP match failure with rdf:rest*/rdf:first plus garden path

### ISSUE THREAD

**Issue by ericprud** [comunica/comunica#1285]
#### Issue type:

- :bug: Bug 

____
## Schema:
``` sparql
PREFIX fhir: <http://hl7.org/fhir/>

SELECT ?obsId {

  ?obs
    fhir:id [ fhir:v ?obsId ].

  ?obs fhir:value [
      fhir:coding [ rdf:rest*/rdf:first [
        a <http://snomed.info/id/8517006> ;
      ] ]
    ].
}
```

## Data:
``` Turtle
PREFIX fhir: <http://hl7.org/fhir/>

<http://hl7.org/fhir/Observation/58671>
  fhir:id [ fhir:v "58671" ];
  fhir:value [
    fhir:coding ( [
      a <http://snomed.info/id/8517006>;
    ] )
  ];
  fhir:component ( [
    fhir:value [
      fhir:coding [] # comment this line
    ];
  ] ).
```
gives no results. Commenting the `fhir:coding []` line in the Turtle makes the query work, as does deferring the match on the contents of the BNode:
## Query with deferred match
``` SPARQL
PREFIX fhir: <http://hl7.org/fhir/>

SELECT ?obsId ?p ?o {

  ?obs
    fhir:id [ fhir:v ?obsId ].

  ?obs fhir:value [
      fhir:coding [ rdf:rest*/rdf:first [
        ?p ?o
      ] ]
    ].
  FILTER (?p = <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
       && ?o = <http://snomed.info/id/8517006>)
}
```
## Without collection
It also works if i change the collections to simple properties:
### Query without collection
``` SPARQL
PREFIX fhir: <http://hl7.org/fhir/>

SELECT ?obsId {

  ?obs
    fhir:id [ fhir:v ?obsId ].

  ?obs fhir:value [
      fhir:coding [ fhir:x [
        a <http://snomed.info/id/8517006> ;
      ] ]
    ].
}
```
### Data without collection
``` Turtle
PREFIX fhir: <http://hl7.org/fhir/>

<http://hl7.org/fhir/Observation/58671>
  fhir:id [ fhir:v "58671" ];
  fhir:value [
    fhir:coding [ fhir:x [
      a <http://snomed.info/id/8517006>;
    ] ]
  ];
  fhir:component [ fhir:x [
    fhir:value [
      fhir:coding [] # comment this line
    ];
  ] ].
```

Hypothesis: The SPARQL property path is failing on the `fhir:value` that's inside the `fhir:component` and aborting before trying the outer `fhir:value`.

PS. is there a way to disable the fact that it aborts if you SELECT an unreferenced varaible? That kinda slows down diagnostics.
@cnanjo
____
#### Environment:

"@comunica/query-sparql-rdfjs": "^2.9.0" does't give me any .bins except `comunica-compile-config -> ../@comunica/runner/bin/compile-config`

**Comment by ericprud** [comment]
P.S. if y'all can solve this in a few days, I can use Comunica for a half-day AMIA tutorial

**Comment by rubensworks** [comment]
Looks like it was a problem with incorrect cardinality metadata for some property paths, which caused the optimizer to incorrectly return empty results.

Will publish a new release with a fix in a bit.

**Comment by rubensworks** [comment]
Releasing as 2.10.0.

**Comment by ericprud** [comment]
That fixed it. Many thanks!
