### ISSUE TITLE
Query Issues with Ontop-created SPARQL endpoints

### ISSUE THREAD

**Issue by marcelomachado** [comunica/comunica#1292]
#### Issue type:

- :bug: Bug 

____
#### Description:

[Ontop](https://ontop-vkg.org/) is a Virtual Knowledge Graph system. In essence, it exposes an SPARQL endpoint by leveraging a relational database and a mapping file that instructs how to translate logical tables to RDF.

I'm currently working on executing federated queries across this SPARQL endpoint and others. To achieve this, I'm using Comunica to establish a mixed SPARQL endpoint.

However, I encounter an issue where Comunica states its inability to retrieve the 'query' parameter in { actor: 'urn:comunica:default:dereference/actors#http' }. Despite this error and the prolonged duration, it eventually manages to respond to the query when I tested the federation exclusively considering SPARQL endpoints raised with Ontop.

Conversely, when attempting to federate a SPARQL endpoint raised with Ontop together with the Wikidata SPARQL endpoint, again the same error arises. However, Comunica also throws an exception, causing the process to terminate without providing a response to the query.

Consequently, I suspect there are two underlying issues. Firstly, there might be an error related to the utilization of a SPARQL endpoint created by Ontop, potentially stemming from metadata retrieval or a deviation from specifications during Ontop's endpoint creation. Secondly, complications arise when federating with other data sources.
____
#### Environment:

Comunica Docker Image:
```
comunica/query-sparql@sha256:1cb314d93e04be1e06fad875ea0303e777b46ffb57c2c7554a8aed1135f3ad56
```

Command:

> node  ./bin/http.js sparql@http://query.wikidata.org/sparql sparql@https://my-ontop-instance/sparql --lenient -w 4

Ontop Docker Image:

```
ontop/ontop@sha256:cf7486aeefca41efb76aefef5e373441f8bb9234ef8e6c60b59b26efaa7b26d7
```

An example query would be `select * where {?s ?p ?o} limit 2`

#### Crash log:

Error related to Ontop created SPARQL endpoint: 
```
[2023-11-24T14:58:41.471Z] ERROR: Could not retrieve http://localhost:3000/sparql (HTTP status 500):
Required request parameter 'query' for method parameter type String is not present { actor: 'urn:comunica:default:dereference/actors#http' }
[2023-11-24T14:58:41.473Z] ERROR: urn:comunica:default:rdf-parse/mediators#parse mediated over all rejecting actors:
Unrecognized media type: undefined
Unrecognized media type: undefined
Unrecognized media type: undefined
Unrecognized media type: undefined
Unrecognized media type: undefined
Unrecognized media type: undefined { actor: 'urn:comunica:default:dereference-rdf/actors#parse' }
```

Exception while trying to federate it together with Wikidata:
```
Terminating worker 24 with 1 open connections due to uncaught exception.
TypeError: terminated
at Fetch.onAborted (node:internal/deps/undici/undici:9975:53)
at Fetch.emit (node:events:517:28)
at Fetch.terminate (node:internal/deps/undici/undici:9174:14)
at Object.onError (node:internal/deps/undici/undici:10092:38)
at _Request.onError (node:internal/deps/undici/undici:6344:31)
at errorRequest (node:internal/deps/undici/undici:8852:17)
at TLSSocket.onSocketClose (node:internal/deps/undici/undici:8021:9)
at TLSSocket.emit (node:events:529:35)
at node:net:350:12
at TCP.done (node:_tls_wrap:614:7)Worker 24 died with 15. Starting new worker.
Server worker (72) running on http://localhost:3000/sparql
```

**Comment by rubensworks** [comment]
Federated querying over SPARQL endpoints is being reworked at the moment, so the problems you are running into might be fixed in Comunica v3.
I'm putting this issue on hold until v3 is released, and hopefully the issue resolved itself after that :-)

**Comment by rubensworks** [comment]
Comunica v3.x has been released, which may solve this issue.
I'm closing this issue, but feel free to re-open in case the problem would still occur, in which case we can look at it more closely.
