### ISSUE TITLE
`service` requests out of order on query re-writes with `initialBindings`

### ISSUE THREAD

**Issue by qjhart** [comunica/comunica#1294]
#### Issue type:

- :bug: Bug 

____
#### Description:

When using `initalBindings` on queries. In some cases blocks are rewritten out of order, particularly with the `service` block.

The example shows a service query being rewritten:

```js
import { QueryEngine } from '@comunica/query-sparql';
const myEngine = new QueryEngine();
import { BindingsFactory } from '@comunica/bindings-factory';
import { DataFactory } from 'rdf-data-factory';

const DF = new DataFactory();
const BF = new BindingsFactory();

const service_q=`
select * WHERE {
  service <http://localhost:3030/experts/sparql> {
    graph <http://iam.ucdavis.edu> {
    ?s ?p ?o.
  }}}`


const context= { sources: ['http://localhost:3030/experts/sparql'] };

// https://comunica.dev/docs/query/advanced/context/
const bindings = { initialBindings:
                   BF.fromRecord({
                     o: DF.literal('foo')
                   }) }

//const q1 = await myEngine.queryBindings(service_q, context);
myEngine.queryBindings(service_q, {...bindings, ...context });
```

This doesn't fail, but  sends the following query to the server: 

```sparql
SELECT ?p ?s WHERE {
  GRAPH <http://iam.ucdavis.edu> {
    SERVICE <http://localhost:3030/experts/sparql> { ?s ?p "foo". } } }
```

____
#### Environment:

```bash
$ node_modules/.bin/comunica-sparql -v
```

| software         | version
| ---------------- | -------
| Comunica Engine  | 2.10.0
| node             | v18.13.0
| npm              | 9.5.1
| yarn             | _Yarn is unavailable_
| Operating System | linux (Linux 6.1.0-9-amd64)

Additionally, 

```bash
head node_modules/sparqlalgebrajs/package.json
```

```json
{
  "name": "sparqlalgebrajs",
  "version": "4.3.1",
  "description": "Convert SPARQL to SPARQL algebra",
  "author": "Joachim Van Herwegen",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/joachimvh/SPARQLAlgebra.js"
  },
```

#### Sparqlalgebra

A very simple test of sparqlalgebra, doesn't show this directly:

```bash
alg=$(node_modules/.bin/sparqlalgebrajs 'select * WHERE {
  service <http://localhost:3030/experts/sparql> {
    graph <http://iam.ucdavis.edu> {
    ?s ?p "foo".
  }}} ')
node_modules/.bin/sparqlalgebrajs --reverse "$alg"
SELECT ?p ?s WHERE { SERVICE <http://localhost:3030/experts/sparql> { GRAPH <http://iam.ucdavis.edu> { ?s ?p "foo". } } }
```

**Comment by joachimvh** [comment]
> A very simple test of sparqlalgebra, doesn't show this directly:

The problem does occur in sparqlalgebra if you use the `-q` flag when generating the algebra, as the problem occurs when converting quads with non-default graphs back to a correct SPARQL query. 

Problem is that the library tries to find the biggest "block" it can that has the same graph and wrap that in a GRAPH statement, only stopping when it finds multiple graphs or the edge of a SELECT block. So fix is that it should also stop at the edge of a SERVICE block (and perhaps some other blocks as well).
