### ISSUE TITLE
DELETE/INSERT is deleting the quad but not updating the same value in the data store.

### ISSUE THREAD

**Issue by ShantanuParode** [comunica/comunica#1301]
#### Issue type:

- :bug: Bug 

____
#### Description:

 In case of DELETE/INSERT query, if I am updating a quad with the same value as in datastore, apparently the quad is being deleted but it should update the quad to the same value resulting in no change. 
 
 Following the third example at https://comunica.dev/docs/query/getting_started/update_app/
```
  console.log("initial size = ", store.size); // prints 6

  // for president25, renaming to the same name.
  await myEngine.queryVoid(
    `
    PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
    DELETE { <http://example/president25> foaf:givenName ?name }
    INSERT { <http://example/president25> foaf:givenName ?name }
    WHERE
    {
      <http://example/president25> foaf:givenName ?name
    }`,
    {
      sources: [store],
    }
  );
  console.log("updated size = ", store.size); // prints 5
```

or if I try putting the same name in the query in INSERT

```
  console.log("initial size = ", store.size); // prints 6

  // for president25, renaming to the same name.
  await myEngine.queryVoid(
    `
    PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
    DELETE { <http://example/president25> foaf:givenName ?name }
    INSERT { <http://example/president25> foaf:givenName 'Bill'}
    WHERE
    {
      <http://example/president25> foaf:givenName ?name
    }`,
    {
      sources: [store],
    }
  );
  console.log("updated size = ", store.size); // prints 5

```
in both above cases, 1 quad is removed which is obvious due to the DELETE, but a new quad is not being inserted. 
Why is it so?

GraphDB behaves differently for the same query, it deletes the quad but inserts in back again for the same value. 
____
#### Environment:

`node v18.6.0`
 `"@comunica/query-sparql": "^2.10.2"`
`"n3": "^1.17.2"`

#### Crash log:

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| €272 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment]
Hmm, that seems wrong indeed. It looks like the DELETE may be applying to the INSERT result as well somehow.

**Comment by ShantanuParode** [comment]
interestingly, if I change the 'Bill' to 'William', it behaves correctly and updates the quad as expected. but in case where the same name is being used, it doesn't.

**Comment by rubensworks** [comment]
A bounty has been placed on this issue via the Comunica Association (see original post).

**Comment by karelklima** [comment]
I will fix this.

**Comment by rubensworks** [comment]
@karelklima Great!

If you want to work on this to claim the bounty, could you first email me to discuss some practicals?

**Comment by karelklima** [comment]
As discussed with @rubensworks, I will work on this issue.
