### ISSUE TITLE
[Proxy] https://proxy.linkeddatafragments.org/ seems to be down

### ISSUE THREAD

**Issue by Maximvdw** [comunica/comunica#1302]
The default proxy of all comunica examples (https://proxy.linkeddatafragments.org/)
seems to be down.

This could be intentional, but since it is still the "default" proxy I wanted to report it.

**Comment by rubensworks** [comment]
We temporarily disabled the server this morning. We aim to get it back up an running later this week, but its usage may be slightly altered.

**Comment by Maximvdw** [comment]
Understandable ;) I do use it for some linked data tests that I run in localhost hence why I noticed it.

**Comment by rubensworks** [comment]
> I do use it for some linked data tests that I run in localhost hence why I noticed it.

How exactly are you using this proxy then? Is your code available online somewhere?

Just asking as we may take this kind of usage into account when determining the new API of the proxy.

**Comment by Maximvdw** [comment]
Currently it is mostly based on this function:
https://github.com/SemBeacon/openhps/blob/main/src/SemBeaconService.ts#L257-L265

The two main use cases for me are:
1) Anonymous github
https://github.com/tdurieux/anonymous_github/issues/209
2) URL shorteners that do not forward the CORS policies of the URL that is being shortened

I always make sure to provide the `Accept` header in my requests, so if not done already I think it might already be a good thing to filter on this?

**Comment by rubensworks** [comment]
Thanks for the details! Pretty similar to our use cases :-)

**Comment by rubensworks** [comment]
@Maximvdw The proxy is back online, but is not available for third-party use anymore.
Feel free to contact me (ruben.taelman@ugent.be) in case you want access to this proxy, or it's also possible to serve your own proxy (such as https://github.com/rubensworks/cors-anywhere/).
