### ISSUE TITLE
Improving bindings merge complexities

### ISSUE THREAD

**Issue by maartyman** [comunica/comunica#1305]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

In the literature of solving acyclic conjunctive queries (Yannakakis algorithm), I came across a technique that might be beneficial for comunica. In essence, the complexity (both time and space) of the `merge` method in the bindings-factory is linear to the amount of variables in the bindings. What we could do in comunica is simplify the bindings as soon as possible, in other words: remove the variables that will not be needed at a later time. For example, take the following hypothetical query:
```
SELECT ?v4 WHERE {
 ?v1 :p1 ?v2 .
 ?v2 :p2 ?v3 .
 ?v3 :p3 ?v4 .
}
```
Imagine we first join the two BGP's (`?v1 :p ?v2 .` and `?v2 :p ?v3 .`) and then join the result of this with the third BGP (`?v3 :p ?v4 .`). We actually don't need the variables `?v1` and `?v2` anymore after the first join, we don't need them in the projection and for the second join. Therefore, we could not add them in the join result to speed up this and subsequent merges, and reduce the size of the bindings.

We could achieve this by having a `mergeKey` variant of the `merge` method in the bindings-factory which only merges the keys that are passed as an argument to the `mergeKey` method. In the joins, we could then calculate the variables that are needed for the subsequent operations and pass them to the `mergeKey` method.

I do think that this is not as easy as explained here but improving the time complexity of the `merge` method and shrinking the bindings could be very beneficial for the performance of comunica.

**Comment by rubensworks** [comment]
Thanks for sharing this @maartyman, certainly something that would be interesting to investigate!

I do suspect though that the impact in Comunica might be smaller than in traditional engines, as our Bindings objects are implemented as [immutable](https://www.npmjs.com/package/immutable) objects, which use an efficient copy mechanism. The overhead of unused keys is very small, as they stored stored only once.

**Comment by maartyman** [comment]
Ah, I didn't know this. In that case, the performance increase will be small indeed. It would only help when merging a big binding with many unused keys. But this is already a lot less likely to happen. You can probably close this issue then!

**Comment by rubensworks** [comment]
At second though, I'll close this issue. Will probably not have a significant impact indeed.
