### ISSUE TITLE
Query with multiple `COUNT` clauses returns incorrect result depending on order in projection

### ISSUE THREAD

**Issue by pmaria** [comunica/comunica#1312]
#### Issue type:

- :bug: Bug 

____
#### Description:

Given the following input
```trig
@prefix ex: <http://example.org/> .

<http://foo.org/id/graph/foo> {
  <http://foo.org/id/object/foo>
    ex:foo ex:Foo ;
    ex:bar [] ;
    ex:baz "baz1", "baz2", "baz3" .
}
```

running this  query:
```sparql
SELECT (COUNT(DISTINCT ?s) AS ?subjects) (COUNT(DISTINCT ?o) as ?objects) ?p
FROM <http://foo.org/id/graph/foo>
{
  ?s ?p ?o .
}
GROUP BY ?p
```

results in

![image](https://github.com/comunica/comunica/assets/12606875/f61c867e-c4d0-45f9-9334-71dcbf4db839)

while running this query (object count switched with subject count in projection):

```sparql
SELECT (COUNT(DISTINCT ?o) as ?objects) (COUNT(DISTINCT ?s) AS ?subjects) ?p
FROM <http://foo.org/id/graph/foo>
{
  ?s ?p ?o .
}
GROUP BY ?p
```

results in the expected

![image](https://github.com/comunica/comunica/assets/12606875/9421f0d4-e028-494b-b9d6-3a28cef3e3f5)
____
#### Environment:

| software         | version
| ---------------- | -------
| Comunica Engine  | 2.10.2 
| node             | v21.6.1
| npm              | 10.2.4
| yarn             | _Yarn is unavailable_
| Operating System | linux (Linux 5.15.133.1-microsoft-standard-WSL2)

**NOTE** I'm using `npx comunica-sparql-file-http` on the input file above.

I've tried this on several other SPARQL implementations and these do not show this behavior.

#### Crash log:

none

**Comment by simonvbrae** [comment]
As discussed with @rubensworks I will work on this issue.

**Comment by simonvbrae** [comment]
@jitsedesmet I was told to ping you for my questions related to the expressions code.

One thing that stuck out to me in the case where counts are incorrect is that startTerm [(code)](https://github.com/comunica/comunica/blob/052ac7d24db46a2056b0b7d694d2e8c20b2ede6d/packages/expression-evaluator/lib/evaluators/AsyncAggregateEvaluator.ts#L28) equals the subject of the current binding, rather than the predicate which we are supposed to be counting.

My question is what does startTerm mean?

**Comment by jitsedesmet** [comment]
On the top of my head: start term is basically the value you'd return when put was never called.
So for the count aggregator, this would be `0`, but the sample aggregator does not have a start term (a sample of nothing is simply an error (irc)).

I hope that helps. (I did not really read the issue, so if it didn't, just ping me again :) )
