### ISSUE TITLE
is GROUP_CONCAT supported by comunica?

### ISSUE THREAD

**Issue by kirnerlukas** [comunica/comunica#1313]
#### Issue type:

- :question: Question 

____
#### Question:

I try to perform a simple query that contains a GROUP_CONCAT to concatenate various values of a variable to a list. Printing the query and pasting it into the triple-store interface to query it leads to the expected results. Comunica however fails to execute the query. Therefore, before I open a bug issue, does comunica generally support the GROUP_CONCAT functionality?

**Comment by rubensworks** [comment]
Comunica should be fully spec-compliant wrt GROUP_CONCAT.
So if you think there's a bug somewhere, feel free to open a bug report :-)
