### ISSUE TITLE
Optional keyword does not seem to work

### ISSUE THREAD

**Issue by pietervdvn** [comunica/comunica#1316]
#### Issue type:

- :question: Question 

____
#### Question:

I have two json-lds. They both graphs, each containing a geocoordinate (with `schema.org/geo`). Optionally, they might also contain a 'shape' property defining a `Polygon`.

I'm trying to extract the shape if there is one with a comunica sparql query, which is more or less:

```
SELECT * WHERE {
?parking a <http://schema.mobivoc.org/BicycleParkingStation>.
        GRAPH ?g {
            VALUES ?type { vpt:BicycleLocker vpt:BicycleStand vpt:ResidentBicycleParking vpt:PublicBicycleParking }.
            ?section a ?type.
            
            OPTIONAL {
                ?section schema:geo [
                    a schema:GeoCoordinates ;
                    schema:latitude ?latitude ;
                    schema:longitude ?longitude
                ] }.
            OPTIONAL {
                ?x schema:geo [
                a schema:GeoShape ;
                schema:polygon ?shape
                ]
            }.
       }
}
``` 

However, this result does _not_ give any bindings if there is no geoshape present - even though this is wrapped into an optional.

When using the `link-traversal`-build with `lenient: true` as option, this suddenly works.

You can reproduce this issue; I've made a (more or less) minimal example here:
https://github.com/pietervdvn/sparql-test

**Comment by rubensworks** [comment]
I see you're using Comunica v3. Could you try it out on the latest v2 version (2.10.2) to check if the problem already existed back then? (might be a regression in v3)

**Comment by pietervdvn** [comment]
I used a 2.10 version previously, which had the same symptoms.

**Comment by rubensworks** [comment]
I see. Very surprising that it does work with link traversal though.

Could you check what happens if you move the data to the default graph and remove the GRAPH keyword from the query? Perhaps that's related as well.

**Comment by pietervdvn** [comment]
I added a version without graph-embedding in my minimal test case: https://github.com/pietervdvn/sparql-test

This one works and gives results as expected.

However, I'm reusing data from an upstream provider where I cannot really change the shape of the data they provide...

**Comment by rubensworks** [comment]
Hmm, that's interesting.
Could you try querying the graph-based data in a Turtle format? Because I somehow expect it having to do with JSON-LD parsing, and not the actual query processor.

**Comment by pietervdvn** [comment]
I'm not really sure how to convert this efficiently to TTL. [This website](https://issemantic.net/rdf-converter) ignored everything within the graph.

However, I did a simple test query (` ?s ?p ?. GRAPH ?g { ?sg ?pg ?og }`) and all the expected values are there.

**Comment by rubensworks** [comment]
@pietervdvn Could you try again with the new release (3.2.0)? Several things were changed wrt optionals, so this problem _may_ have fixed itself.

**Comment by pietervdvn** [comment]
At first glance, the bug still seems to be there with 3.2.0.

However, I created a workaround for this and the project is coming to an end, so I won't be following this up anymore.

**Comment by rubensworks** [comment]
Thanks for the script @aljoshakoecher! That will be useful for debugging.
