### ISSUE TITLE
Inserting at non-existing resource throws in V3

### ISSUE THREAD

**Issue by jitsedesmet** [comunica/comunica#1317]
#### Issue type:

- :bug: Bug 

____
#### Description:

Using Version 3, when I query the Community Solid Server over a source that does not yet exist using a `INSERT DATA { ... }` query, I get the following exception:
```
WARN: Metadata extraction for http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#416608218494388 failed: Could not retrieve http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#416608218494388 (HTTP status 404):
<b0> <http://purl.org/dc/terms/title> "NotFoundHttpError" .
<b0> <http://purl.org/dc/terms/description> "" .
 { actor: 'urn:comunica:default:query-source-identify/actors#hypermedia' }
Could not retrieve http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#416608218494388 (HTTP status 404):
<b0> <http://purl.org/dc/terms/title> "NotFoundHttpError" .
<b0> <http://purl.org/dc/terms/description> "" .
```

I do not seem to have this issue on Version 2.

The queries I use are: 
1. For V3: `npx --package=@comunica/query-sparql-file@3.0.1 -c 'comunica-sparql-file http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#416608218494388 -f TEMP.sparql'`
2. For V2: `npx --package=@comunica/query-sparql-file@2.10.2 -c 'comunica-sparql-file http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#416608218494388 -f TEMP.sparql'`

It seems like the issue appears because the `acceptErrors` config item of the `httpDereference` actor is not set in the optimize part of Execute Query Sequential.
While debugging, I also noticed that removing the optimization step in the Execute Actor breaks Comunica? This seems like a weird semantic?

For completeness:

Content of `TEMP.sparql`:
```SPARQL
prefix ns1: <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
    <http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#416608218494388> a ns1:Post ;
        ns1:browserUsed "Chrome" ;
        ns1:content "I want to eat an apple while scavenging for mushrooms in the forest. The sun will be such a blessing." ;
        ns1:creationDate "2024-05-08T23:23:56.830000+00:00"^^xsd:dateTime ;
        ns1:id "416608218494388"^^xsd:long ;
        ns1:hasCreator <http://localhost:3000/pods/00000000000000000096/profile/card#me> ;
        ns1:hasTag <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/tag/Alanis_Morissette>,
            <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/tag/Austria> ;
        ns1:isLocatedIn <http://localhost:3000/dbpedia.org/resource/China> ;
        ns1:locationIP "1.83.28.23" .
}
```

____
#### Environment:

Version 3, output of `npx --package=@comunica/query-sparql-file@3.0.1 -c 'comunica-sparql-file -v'`:
```
| software         | version
| ---------------- | -------
| Comunica Engine  | 3.0.1 (dev)
| node             | v20.11.1
| npm              | 10.2.4
| yarn             | 1.22.22
| Operating System | linux (Linux 6.7.10-200.fc39.x86_64)
```

Version 2, output of `npx --package=@comunica/query-sparql-file@2.10.2 -c 'comunica-sparql-file -v'`:
```
| software         | version
| ---------------- | -------
| Comunica Engine  | 2.10.2 
| node             | v20.11.1
| npm              | 10.2.4
| yarn             | 1.22.22
| Operating System | linux (Linux 6.7.10-200.fc39.x86_64)
```

**Comment by rubensworks** [comment]
> While debugging, I also noticed that removing the optimization step in the Execute Actor breaks Comunica? This seems like a weird semantic?

Yeah, some optimization steps are required indeed.

**Comment by rubensworks** [comment]
For reference, I guess some optimize actors (such as prune-empty-sources) may be attempting to run over an update query, while this only makes sense for read-queries. So we should probably reject these actors in their `test()` if we're executing an update query.

So I guess this should be an easy fix.

**Comment by jitsedesmet** [comment]
My stack is:

```
run(), **ActorDereferenceHttpBase**.ts:98
processTicksAndRejections(), task_queues:95
Async call from await
processTicksAndRejections(), task_queues:95
Async call from await
runObservable(), Actor.ts:83
mediate(), Mediator.ts:90
Async call from await
run(), ActorDereferenceParse.ts:92
runObservable(), Actor.ts:83
mediate(), Mediator.ts:90
Async call from await
getSource(), **QuerySourceHypermedia**.ts:159
getSourceCached(), **QuerySourceHypermedia**.ts:246
getSelectorShape(), **QuerySourceHypermedia**.ts:70
getSelectorShape(), **QuerySourceSkolemized**.ts:34
run(), **ActorOptimizeQueryOperationAssignSourcesExhaustive**.ts:35
runObservable(), Actor.ts:83
mediate(), MediatorCombinePipeline.ts:72
Async call from await
optimize(), **ActorQueryProcessSequential**.ts:99
run(), **ActorQueryProcessSequential**.ts:54
Async call from await
runObservable(), Actor.ts:83
mediate(), Mediator.ts:90
Async call from await
queryOrExplain(), **QueryEngineBase**.ts:135
query(), QueryEngineBase.ts:91
queryOfType(), QueryEngineBase.ts:74
queryVoid(), QueryEngineBase.ts:65
addQuadsToResource(), BaseOperationHandler.ts:73
Async call from await
handleOperation(), InsertResourceHandler.ts:39
Async call from await
main(), index.ts:11
Async call from await
anonymous(), index.ts:20
Module._compile(), loader:1376
m._compile(), index.ts:1618
Module._extensions..js(), loader:1435
require.extensions.<computed>(), index.ts:1621
Module.load(), loader:1207
Module._load(), loader:1023
executeUserEntryPoint(), run_main:135
phase4(), bin.ts:649
bootstrap(), bin.ts:95
main(), bin.ts:55
anonymous(), bin.ts:800
Module._compile(), loader:1376
Module._extensions..js(), loader:1435
Module.load(), loader:1207
Module._load(), loader:1023
executeUserEntryPoint(), run_main:135
anonymous(), run_main_module:28
```

Interesting files:
* ActorDereferenceHttpBase
* QuerySourceHypermedia
* QuerySourceSkolemized
* ActorOptimizeQueryOperationAssignSourcesExhaustive
* ActorQueryProcessSequential

I have tried to throw an error in the test function of `ActorOptimizeQueryOperationAssignSourcesExhaustive` this just results in the `Error: All actors rejected their test in urn:comunica:default:query-operation/mediators#main` error :/ .

I fear that means we'd need to go through some context item of `ActorDereferenceHttpBase` and `ActorOptimizeQueryOperationAssignSourcesExhaustive`  instead?
We could give their constructors a `acceptHttpErrors` param?

**Comment by rubensworks** [comment]
Aha, so it's fetching the selector shape that is causing the problem. That makes sense, because a non-existing resource does not have a selector shape.

We may just need to add a try-catch around [here](https://github.com/comunica/comunica/blob/master/packages/actor-optimize-query-operation-assign-sources-exhaustive/lib/ActorOptimizeQueryOperationAssignSourcesExhaustive.ts#L35-L41) and ignore the error so it falls back to the default case.

(there may be other similar issues in related actors)
