### ISSUE TITLE
How to bundle with Webpack

### ISSUE THREAD

**Issue by ivanbacher** [comunica/comunica#1323]
#### Issue type:

- :question: Question 

____
#### Question:

Whats the correct way to bundle the package with webpack so that the bundle size is not huge? 

![Screenshot 2024-04-10 at 16 35 33](https://github.com/comunica/comunica/assets/5493114/4642eb6e-10b3-413f-b4bd-a649d195c82f)

Thanks

**Comment by rubensworks** [comment]
Are you using a special kind of package manager?
Because I see dependencies such as readable-stream being duplicated a lot, which blows up bundle size.
Package managers such as npm should hoist these dependencies to the root node_modules directory, and thereby deduplicate them.

**Comment by ivanbacher** [comment]
No, just webpack + npm.

I installed this:
```
npm i @comunica/query-sparql
```

Then run `webpack --env production` to build.

This is my webpack config

```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const {BundleAnalyzerPlugin} = require('webpack-bundle-analyzer');
const Dotenv = require('dotenv-webpack');

const cssLoader = 'css-loader';

const sassLoader = {
  loader: 'sass-loader',
  options: {
    sassOptions: {
      includePaths: ['node_modules']
    }
  }
};

const postcssLoader = {
  loader: 'postcss-loader',
  options: {
    postcssOptions: {
      plugins: ['autoprefixer']
    }
  }
};

module.exports = function(env, { analyze }) {
  const production = env.production || process.env.NODE_ENV === 'production';
  return {
    target: 'web',
    mode: production ? 'production' : 'development',
    devtool: production ? undefined : 'eval-cheap-source-map',
    entry: {
      entry: './src/main.js'
    },
    output: {
      clean: true,
      path: path.resolve(__dirname, 'dist'),
      filename: production ? '[name].[contenthash].bundle.js' : '[name].bundle.js'
    },
    resolve: {
      extensions: ['.js'],
      modules: [path.resolve(__dirname, 'src'), path.resolve(__dirname, 'dev-app'), 'node_modules'],
      alias: production ? {
        // add your production aliases here
      } : {
        // add your development aliases here
      }
    },
    devServer: {
      historyApiFallback: true,
      open: !process.env.CI,
      port: 9000
    },
    module: {
      rules: [
        { test: /\.(png|svg|jpg|jpeg|gif)$/i, type: 'asset' },
        { test: /\.(woff|woff2|ttf|eot|svg|otf)(\?v=[0-9]\.[0-9]\.[0-9])?$/i,  type: 'asset' },
        { test: /\.css$/i, use: [ 'style-loader', cssLoader, postcssLoader ] },
        { test: /\.scss$/i, use: [ 'style-loader', cssLoader, postcssLoader, sassLoader ] },
        { test: /\.js$/i, use: ['babel-loader', '@aurelia/webpack-loader'], exclude: /node_modules/ },
        {
          test: /[/\\]src[/\\].+\.html$/i,
          use: '@aurelia/webpack-loader',
          exclude: /node_modules/
        }
      ]
    },
    plugins: [
      new HtmlWebpackPlugin({ template: 'index.html', favicon: 'favicon.ico' }),
      new Dotenv({
        path: `./.env${production ? '' :  '.' + (process.env.NODE_ENV || 'development')}`,
      }),
      analyze && new BundleAnalyzerPlugin()
    ].filter(p => p)
  }
}
```

**Comment by rubensworks** [comment]
And if you look in your node_modules or lockfile, do you see readable-stream duplicated there?

FYI, we usually webpack using a config like this: https://comunica.dev/docs/modify/advanced/browser_builds/#4--building-for-the-browser

**Comment by jacoscaz** [comment]
@ivanbacher as a practical workaround, you can force Webpack to always resolve a specific module to one single version of it using Webpack's `resolve.alias` field like I've done [here](https://github.com/jacoscaz/quadstore-comunica/blob/6d8ccc21e67090e38bc705ef49216bec45ca6d04/engine/webpack.config.base.js#L87) for `rdf-data-factory`. 

That config file contains a number of tricks I've come up with to optimize the size of the resulting bundle, though keep in mind that `quadstore-comunica` consists of the smallest subset of Comunica components required to run SPARQL queries on RDF/JS sources (no RDF parsers, no RDF serializers, no fetching over HTTP, ...).

**Comment by jacoscaz** [comment]
Just to give you an idea of the sizes, NPM reports `quadstore-comunica` as weighing 2.5MB, uncompressed. That's for two different but functionally identical bundles, one for ESM and one for CJS, _unminified_.

[This repo](https://github.com/jacoscaz/quadstore-browser) contains a ready-to-use, browser-side bundle that includes `quadstore`, `quadstore-comunica`, `rdf-data-factory` and the `browser-level` storage backend (using IndexedDB). This bundle, minified, weighs in at ~770kB, uncompressed.

**Comment by ivanbacher** [comment]
Thank you for the quick replies. I will investigate and check out the linked repo.

**Comment by rubensworks** [comment]
FYI, in the next release we'll start publishing a new engine (`@comunica/query-sparql-rdfjs-lite`) that is optimized for bundle size.
Currently, the minified size of this package is 648,88 KB (145,79 KB when gzipped).
This is about as small as you can get without removing required functionality from the SPARQL 1.1 spec (if you don't need everything, it could get much smaller even).
