### ISSUE TITLE
Use `#cancel()` where possible. 

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1351]
#### Issue type:

- :snail: Performance issue 

____
#### Description:

There are instances like [this](https://github.com/comunica/comunica/blob/4d87d7457a0c423fff68a2f2088aefa3d9ad31b8/packages/actor-http-wayback/lib/ActorHttpWayback.ts#L64) in the codebase where it may be possible to `#cancel()` web streams rather than consuming the web stream in full.

**Comment by rubensworks** [comment]
Pretty sure we do this everywhere, so that's probably the only occurrence.
Unless there are other places where you see this?
