### ISSUE TITLE
Blank nodes in update queries do not match arbitrary nodes

### ISSUE THREAD

**Issue by redmer** [comunica/comunica#1352]
#### Issue type:

- :bug: Bug 

____
#### Description:

Using `[]` as a quasi 'any' variable in the WHERE clause works in CONSTRUCT queries, but not in UPDATE queries.

The below update queries work as expected in GraphDB. The [only relevant reference](https://www.w3.org/TR/sparql11-update/#delete_insert_clause) I could find in the spec says _"Blank nodes in the WHERE clause match data in the same way as for any SPARQL Query."_  (I assume referring to that they ["act as variables"](https://www.w3.org/TR/sparql11-query/#QSynBlankNodes))

[A minimal working example](https://gist.github.com/redmer/7354c44a2cb00569f00c7bf80f010bcb) is provided as a Gist.

- [comunica-test-data.ttl](https://gist.github.com/redmer/7354c44a2cb00569f00c7bf80f010bcb#file-comunica-test-data-ttl) contains two two triples.
- [comunica-test-post.ttl](https://gist.github.com/redmer/7354c44a2cb00569f00c7bf80f010bcb#file-comunica-test-post-ttl) contains the expected result.
- Update query [comunica-test-bnode.ru](https://gist.github.com/redmer/7354c44a2cb00569f00c7bf80f010bcb#file-comunica-test-bnode-ru) does not insert any quads in the local RDF/JS store.
- The alternative update query [comunica-test-anyvar.ru](https://gist.github.com/redmer/7354c44a2cb00569f00c7bf80f010bcb#file-comunica-test-anyvar-ru) replaces the `[]` in the WHERE clause with `?anyvar`. This queries successfully inserts two quads into the local RDF/JS Store and shows the expected result.
- For reference, the CONSTRUCT query [comunica-test-bnode.rq](https://gist.github.com/redmer/7354c44a2cb00569f00c7bf80f010bcb#file-comunica-test-bnode-rq) uses `[]` but does match and return two quads. Inserted into the source, it results in the expected result graph.

There is no remarkable logging being done. In a longer, non-minimal example I could provide, the query planner `Determined physical join operator 'inner-multi-empty'`.

```
DEBUG: Pruning 0 source-specific operations { actor: 'urn:comunica:default:optimize-query-operation/actors#prune-empty-source-operations' }
```

____
#### Environment:

| software         | version
| ---------------- | -------
| Comunica Engine  | 3.1.0 
| node             | v20.11.1
| npm              | 10.5.0
| yarn             | 1.22.21
| Operating System | linux (Linux 5.15.146.1-microsoft-standard-WSL2)

**Comment by rubensworks** [comment]
This may be related to #1057

**Comment by rubensworks** [comment]
@joachimvh Do you know if this is being (or should be) handled in sparqlalgebrajs?

**Comment by rubensworks** [comment]
Thanks @joachimvh!

@redmer re-installing with a reset lockfile and node_modules should fix your problem.

**Comment by joachimvh** [comment]
I did not take into account me mentioning this issue like this would immediately close it, so feel free to reopen if necessary 😅.

The problem was that the algebra library did not convert any blank nodes in an update query, as the blank nodes in the INSERT block should remain unchanged. But those in the WHERE block should indeed be interpreted as variables.
