### ISSUE TITLE
[mver]: Replace `Readable` signatures with `AsyncIterator`

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1355]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

See https://github.com/comunica/comunica/pull/1345#pullrequestreview-2070425918

**Comment by rubensworks** [comment]
I looked into this, and it looks like we can not easily do this, since not all actors produce `AsyncIterator`'s (e.g. the RDF serialization actors).
Since everything works just fine with the current interface, let's keep things as-is.
