### ISSUE TITLE
@comunica\mediato r-join-coefficients-fixed

### ISSUE THREAD

**Issue by liuxueting368** [comunica/comunica#1370]
#### Issue type:
Hello, I use [ Comunica ] on multiple heterogeneous link data interface SPARQL query, the following error occurred, I do not know how to solve, and did not find the relevant way, can you give me some tips? ! Thank you so much!

#### Description:

____
#### Crash log:
- :bug: Bug 
PS I:\VKG\VloGraphQueryProcessor-hdt-client-version> npm test

> vlographqueryprocessor-hdt-client-version@1.0.0 test
> node ./bin/www

[
  {
    type: 'file',
    value: 'I:\\VKG\\VloGraphQueryProcessor-hdt-client-version\\uploads\\10.5.0
.2.ttl'
  }
]
I:\VKG\VloGraphQueryProcessor-hdt-client-version\node_modules\@comunica\mediato
r-join-coefficients-fixed\lib\MediatorJoinCoefficientsFixed.js:58
            throw new Error(`All actors rejected their test in ${this.name}\n${
errors.map(error => error.message).join('\n')}`);
                  ^

Error: All actors rejected their test in urn:comunica:default:rdf-join/mediator
s#main
Actor urn:comunica:default:rdf-join/actors#inner-none can only join zero entrie
s
Actor urn:comunica:default:rdf-join/actors#inner-single can only join a single 
entry
urn:comunica:default:rdf-join/actors#inner-hash requires 2 join entries at most
. The input contained 3.
urn:comunica:default:rdf-join/actors#inner-symmetric-hash requires 2 join entri
es at most. The input contained 3.
urn:comunica:default:rdf-join/actors#inner-nested-loop requires 2 join entries 
at most. The input contained 3.
urn:comunica:default:rdf-join/actors#optional-nested-loop can only handle logic
al joins of type 'optional', while 'inner' was given.
urn:comunica:default:rdf-join/actors#minus-hash can only handle logical joins o
f type 'minus', while 'inner' was given.
urn:comunica:default:rdf-join/actors#minus-hash-undef can only handle logical j
oins of type 'minus', while 'inner' was given.
urn:comunica:default:rdf-join/actors#optional-bind can only handle logical join
s of type 'optional', while 'inner' was given.
Could not dereference 'I:\VKG\VloGraphQueryProcessor-hdt-client-version\uploads
\10.5.0.2.ttl'
Could not dereference 'I:\VKG\VloGraphQueryProcessor-hdt-client-version\uploads
\10.5.0.2.ttl'
Could not dereference 'I:\VKG\VloGraphQueryProcessor-hdt-client-version\uploads
\10.5.0.2.ttl'
    at MediatorJoinCoefficientsFixed.mediateWith (I:\VKG\VloGraphQueryProcessor
-hdt-client-version\node_modules\@comunica\mediator-join-coefficients-fixed\lib
\MediatorJoinCoefficientsFixed.js:58:19)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async MediatorJoinCoefficientsFixed.mediateActor (I:\VKG\VloGraphQueryPr
ocessor-hdt-client-version\node_modules\@comunica\core\lib\Mediator.js:64:16)  
    at async MediatorJoinCoefficientsFixed.mediate (I:\VKG\VloGraphQueryProcess
or-hdt-client-version\node_modules\@comunica\core\lib\Mediator.js:78:23)       
    at async ActorQueryOperationJoin.run (I:\VKG\VloGraphQueryProcessor-hdt-cli
ent-version\node_modules\@comunica\bus-query-operation\lib\ActorQueryOperationTyped.js:36:24)
    at async ActorQueryOperationProject.runOperation (I:\VKG\VloGraphQueryProcessor-hdt-client-version\node_modules\@comunica\actor-query-operation-project\lib\ActorQueryOperationProject.js:20:82)  
    at async ActorQueryOperationProject.run (I:\VKG\VloGraphQueryProcessor-hdt-client-version\node_modules\@comunica\bus-query-operation\lib\ActorQueryOperationTyped.js:36:24)
    at async QueryEngine.queryOrExplain (I:\VKG\VloGraphQueryProcessor-hdt-client-version\node_modules\@comunica\actor-init-query\lib\QueryEngineBase.js:151:24)

Node.js v20.11.1

____

**Comment by rubensworks** [comment]
The actual error seems to be this one:

> Could not dereference 'I:\VKG\VloGraphQueryProcessor-hdt-client-version\uploads
\10.5.0.2.ttl'

I suspect your using `@comunica/query-sparql` to query over a local file, while it can only query over HTTP resources.
You'll probably want to use https://www.npmjs.com/package/@comunica/query-sparql-file instead for querying local files.
