### ISSUE TITLE
Add RDFa parsing support

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#138]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

Comunica already supports the parsing of several RDF serializations. We should also add support for parsing RDF inside HTML documents using RDFa.

**Comment by pietercolpaert** [comment]
I made this https://www.npmjs.com/package/rdfa-processor - it’s not perfect but does the job.

**Comment by rubensworks** [comment]
Cool!

What's not perfect about that implementation? Is it something that would cause problems when used within comunica?

PRs are welcome :-)

**Comment by rubensworks** [comment]
> Doesn’t yet follow the RDFJS Sink spec

This would definitely be a blocker.

> I was also thinking that at the same time we should support JSON-LD and N3 snippets in an HTML page at the same time.

Yes, definitely makes sense. We'd probably want to have a `text/html` parsing actor in comunica that delegates all HTML to the RDFa parser, but also identifies these RDF snippets in `<script>` tags and pushes them onto the bus again to parse, ignoring those types that can not be parsed.

I'm just wondering if it would make sense to have this `<script>` identification part of an RDFa parser, which would accept a callback for parsing other types of serializations.

**Comment by rubensworks** [comment]
Additionally, `alternate` links should/could be followed, such as this one:
```
<link rel="alternate" type="text/turtle" href="profile.ttl" />
```

**Comment by rubensworks** [comment]
So here's a plan on what to do after #310 is merged.

#310 registers to the rdf-parse bus as an HTML parser for extracting script tags.
However, we also need to be able to extract RDFa (and other things such as microdata?).
So I suggest the following:


1. Create html-rdf-extract bus.
2. Create rdf-parse-html actor. This actor simply parses an HTML doc, and throws it on the html-rdf-extract bus. It needs a special (new?) mediator (mediator-mediatyped-union?) that takes the union of action results, because multiple actors will be able to extract RDF from HTML.
3. Create rdf-parse-html-script actor, which does basically what the actor from #310 does.
4. Remove the old actor introduced in #310
5. Create rdf-parse-html-rdfa actor, for extracting RDFa.

This architecture enables straightforward extensibility, and things like extracting microdata can be plugged in easily later on.

**Comment by rubensworks** [comment]
For reference, here's a fully spec-compliant parser, which follows the RDFJS interfaces: https://github.com/rubensworks/rdfa-streaming-parser.js
