### ISSUE TITLE
Custom "Patterns" for Query Operation Mediator

### ISSUE THREAD

**Issue by MiaNCSU** [comunica/comunica#1383]
#### Issue type:

- :question: Question 

____
#### Question:

From a custom implemented query operation actor, created using the generate-comunica module, it is possible to send a "context" and a "pattern" to the query operation mediator for evaluation. The query operation mediator then replies with a list of bindings that match this pattern. This is shown below:

`const output = ActorQueryOperation.getSafeBindings(await this.mediatorQueryOperation.mediate({ operation: pattern.input, context }));`

However, I can only send the pattern and context created by the user's query. Where is the function that builds the pattern/context given a query string? I'd like to be able to send the mediator my own queries from within the actor, but this requires that I have the pattern for my query.

**Comment by rubensworks** [comment]
I suspect you are referring to the query parsing actors, such as this one: https://github.com/comunica/comunica/tree/master/packages/actor-query-parse-sparql
