### ISSUE TITLE
Query against local GraphDB: The endpoint failed to provide a binding

### ISSUE THREAD

**Issue by aljoshakoecher** [comunica/comunica#1390]
#### Issue type:

- :question: Question 

____
#### Question:
Hey, I'm trying to query a local GraphDB with a query that contains an optional clause. A variable (`?argValue`) inside that optional clause seems to cause the following error:
```
The endpoint http://localhost:7200/repositories/test-repo failed to provide a binding for argValue.
```

I don't understand this error. The variable is optional, so of course it may happend that there are no bindings for this variable. Am I missing an option here or something?
Here's the code I use to query the endpoint with Comunica. I think that should be good, I mean the query get's executed.
```
const sparqlEndpoint = 'http://localhost:7200/repositories/test-repo';
bindingsStream = await queryEngine.queryBindings(this.queryString, {
  sources: [{
    type: 'sparql',
    value: endpointUrl,
  }],
});
```

And when I execute the query via a direct HTTP request to the SPARQL endpoint, everything works fine and I'm getting results. So why does Comunica fail with this error 🙃 ?

**Comment by rubensworks** [comment]
Oh, that's clearly a bug in our results sanity checker.
Will push out a fix in a bit.

**Comment by aljoshakoecher** [comment]
@rubensworks: Thanks for providing a fix so quickly! But I think the bug still exists. With the latest version 3.2.0 I still get an error for a query that has unbound variables such as
```
SELECT ?x ?y ?z WHERE {
	?x a ?y.
};
```
I still get `The endpoint http://localhost:7200/repositories/test-repo failed to provide a binding for z.`

What's a bit strange is that I get a different error for what seems to  be the same problem. I originally wanted to test this query:
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX CSS: <http://www.w3id.org/hsu-aut/css#>
PREFIX VDI3682: <http://www.w3id.org/hsu-aut/VDI3682#>
SELECT ?capability ?input (COALESCE(?inputType, ?outputType) AS ?type) ?output ?capabilityType ?processType WHERE {
    ?capability a CSS:Capability.
    OPTIONAL{
        ?capability VDI3682:hasInput ?input.
        ?input a ?inputType.
    }
    OPTIONAL{
        ?capability VDI3682:hasOutput ?output.
        ?output a ?outputType.
    }
}
```

The real one is even longer, but I simplified it to understand what's going on. When simplifying it, I forgot ` ?capabilityType` and `?processType` in the variable selection. But normally, this shouldn't be a problem. When firing that query, I got the following, different error:
```
...\node_modules\@comunica\actor-context-preprocess-query-source-skolemize\lib\utils.js:57
        if (term.termType === 'Quad') {
                 ^
TypeError: Cannot read properties of undefined (reading 'termType')
```

I first thought it might be caused by the COALESCE function, but this query works fine if I remove the two unbound variables from the selection. I then used the simple query at the top to check if it's really caused by unbound variables. And yeah, seems to be the case, even though that query results in a different error 🤔

**Comment by rubensworks** [comment]
> With the latest version 3.2.0 I still get an error for a query that has unbound variables such as

That query is not really valid though. Strict SPARQL parsers will fail on it.

> What's a bit strange is that I get a different error for what seems to be the same problem. I originally wanted to test this query:

That seems to be a different problem. Could you open a new bug report for this, together with a way to reproduce this problem? As I don't immediately see why that is failing.

**Comment by aljoshakoecher** [comment]
Yes true. That was an overly simplified example. I will create a new bug report with the real one 👍
