### ISSUE TITLE
Query against local GraphDB: Cannot read properties of undefined (reading 'termType')

### ISSUE THREAD

**Issue by aljoshakoecher** [comunica/comunica#1391]
#### Issue type:

- :bug: Bug 

____
#### Description:

After #1390 got fixed I'm now getting the following (related?) error when trying to execute a SPARQL query against a local GraphDB:
```
TypeError: Cannot read properties of undefined (reading 'termType')
```
What's interesting is that the **same query** on the **same dataset** returns results when firing the query against an N3Store.
I created a Gist that contains a small RDF dataset as well as the query I experienced the issue with. The script executes the query against the N3Store and a local GraphDB instance (dataset needs to be imported manually into the GraphDB repository).
Note that the query uses a property path, OPTIONAL and COALESCE functions, so it's a bit more involved than just a plain graph pattern.
You can find the Gist here: https://gist.github.com/aljoshakoecher/5ff47c37ebffb963cb1f2f529cd8af16
____
#### Environment:

I'm using comunica/query-sparql v3.2.0 with node v20.13.1

**Comment by rubensworks** [comment]
Note to self: this was mentioned in the previous issue:

```
...\node_modules\@comunica\actor-context-preprocess-query-source-skolemize\lib\utils.js:57
        if (term.termType === 'Quad') {
                 ^
TypeError: Cannot read properties of undefined (reading 'termType')
```
