### ISSUE TITLE
Correct way to bind `initialBindings` for `INSERT` queries?

### ISSUE THREAD

**Issue by alex-r-bigelow** [comunica/comunica#1395]
#### Issue type:

- :question: Question 

____
#### Question:

Apologies if this has been answered elsewhere, but I can't seem to find anything relevant here or in the docs.

I'm attempting to bind variables in `INSERT` queries, for example:

---

`myUpdateQuery.sparql`
```sparql
INSERT DATA {
  GRAPH <ex:g> {
    ?s <ex:p> <ex:o> .
  }
}
```

`myScript.ts`
```javascript
import { BindingsFactory } from '@comunica/bindings-factory';
import { BrowserLevel } from 'browser-level';
import { DataFactory } from 'n3';
import { Quadstore } from 'quadstore';
import { Engine } from 'quadstore-comunica';
import myUpdateQuery from 'bundle-text:queries/myUpdateQuery.sparql'; // parcel will import the file as a string

// ...

const store = new Quadstore({
  backend: new BrowserLevel('myDb'),
  dataFactory: DataFactory,
});
const engine = new Engine(store);
const bindingsFactory = new BindingsFactory();

await store.open();

await this.engine.queryVoid(myUpdateQuery, {
  initialBindings: this.bindingsFactory.fromRecord({
    s: this.store.dataFactory.namedNode('ex:mySubject'),
  }),
});
```

However, the above gives the following error:

```
Error: Detected illegal variable in BGP
    at ensureNoVariables (SparqlParser.js:1249:19)
    at Object.anonymous (SparqlParser.js:314:47)
    at Parser.parse (SparqlParser.js:778:36)
    at Parser.parser.parse (sparql.js:36:37)
    at ActorQueryParseSparql.run (bundle.js:6244:37)
    at ActorQueryParseSparql.runObservable (bundle.js:12479:29)
    at MediatorRace.mediate (bundle.js:12910:22)
    at async ActorQueryProcessSequential.parse (bundle.js:6329:38)
    at async ActorQueryProcessSequential.run (bundle.js:6314:38)
    at async QueryEngine.queryOrExplain (bundle.js:1249:28)
```

---

As a workaround, I know that I could just generate the `myUpdateQuery` string with javascript and inject `ex:mySubject` that way, but for my use case, it would be *much* nicer to be able to import clean `SPARQL` from `.sparql` files.

Is this a bug? Not how this was meant to work? Or is there a better way to do this?

**Comment by rubensworks** [comment]
`initialBindings` on insert/delete data queries is indeed not supported.

That's because we bind the `initialBindings` after the query has been parsed.
But this is not possible for such queries, as variables in insert/delete data are illegal according to the SPARQL syntax.

So in order to make this work, we'll probably need a more flexible SPARQL parser that supports injecting these variables at parsing-time.

**Comment by alex-r-bigelow** [comment]
That makes sense; really isn't hard to do stuff like `myUpdateQuery.replaceAll(/\?s/g, '<ex:mySubject>')` in my case; just wanted to check whether `initialBindings` was meant to do that more robustly
