### ISSUE TITLE
Adding a second data source stops certain `SPARQL` queries from returning results with UNION

### ISSUE THREAD

**Issue by GCHQDeveloper81** [comunica/comunica#1397]
#### Issue type:

- :bug: Bug 

____
#### Description:

Apologies if this is a duplicate issue, I've had a look through the open issues and couldn't find anything similar. 

Let's say you have a data source with a single triple in it, like this.

```turtle
@prefix ex: <http://example.org/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

ex:Bob a foaf:Person .
```

If you run the following `SPARQL` (one way to find all the classes in the data source) you get results.

```sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?className
WHERE {
      { ?individual a ?className . }
      UNION
      { ?className a owl:Class . } 
      UNION
      { ?className a rdfs:Class . }
}
LIMIT 100
```
If you then add a second data source, you suddenly get no results. Delete the second data source, the results come back.

Can confirm that this issue has been introduced by version `3.0` - we're running `2.10.2` in production and are not seeing this issue unless we upgrade to 3.x.

Further detail: The issue appears to have something to do with the `UNION` part of the query - if you delete these then results start coming back again regardless of how many data sources you add.

____
#### Environment:

We are running this and seeing the issue in a browser environment (an app hosted out of github pages)  https://gchq.github.io/LD-Explorer/

However you can also see the same issue within your own web environment  https://query.comunica.dev/

If you go to the Comunica "Try Live" environment and run the above `SPARQL` query with the default "DBPedia 2016-04" as the active source, you will see results. Add another data source (such as either of the Rueben's profiles) while changing nothing else, and the results stop coming back.

**Comment by rubensworks** [comment]
I followed your instructions (execute [this query](http://query.linkeddatafragments.org/#transientDatasources=%2F%2Ffragments.dbpedia.org%2F2016-04%2Fen&query=PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0A%0ASELECT%20DISTINCT%20%3FclassName%0AWHERE%20%7B%0A%20%20%20%20%20%20%7B%20%3Findividual%20a%20%3FclassName%20.%20%7D%0A%20%20%20%20%20%20UNION%0A%20%20%20%20%20%20%7B%20%3FclassName%20a%20owl%3AClass%20.%20%7D%20%0A%20%20%20%20%20%20UNION%0A%20%20%20%20%20%20%7B%20%3FclassName%20a%20rdfs%3AClass%20.%20%7D%0A%7D%0ALIMIT%20100), and then run it again after adding a Ruben source), but I couldn't reproduce the problem.
Did I misunderstand something?

**Comment by GCHQDeveloper81** [comment]
Hi @rubensworks, thanks for replying. There needs to be two data sources to see the issue.

* [query with one data source](http://query.linkeddatafragments.org/#transientDatasources=%2F%2Ffragments.dbpedia.org%2F2016-04%2Fen&query=PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0A%0ASELECT%20DISTINCT%20%3FclassName%0AWHERE%20%7B%0A%20%20%20%20%20%20%7B%20%3Findividual%20a%20%3FclassName%20.%20%7D%0A%20%20%20%20%20%20UNION%0A%20%20%20%20%20%20%7B%20%3FclassName%20a%20owl%3AClass%20.%20%7D%20%0A%20%20%20%20%20%20UNION%0A%20%20%20%20%20%20%7B%20%3FclassName%20a%20rdfs%3AClass%20.%20%7D%0A%7D%0ALIMIT%20100)
* [same query with two data sources](https://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fruben.verborgh.org%2Fprofile%2F&transientDatasources=%2F%2Ffragments.dbpedia.org%2F2016-04%2Fen&query=PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0A%0ASELECT%20DISTINCT%20%3FclassName%0AWHERE%20%7B%0A%20%20%20%20%20%20%7B%20%3Findividual%20a%20%3FclassName%20.%20%7D%0A%20%20%20%20%20%20UNION%0A%20%20%20%20%20%20%7B%20%3FclassName%20a%20owl%3AClass%20.%20%7D%20%0A%20%20%20%20%20%20UNION%0A%20%20%20%20%20%20%7B%20%3FclassName%20a%20rdfs%3AClass%20.%20%7D%0A%7D%0ALIMIT%20100)

If you click each of the above, then click "Execute", the first one brings back results and the second one doesn't - but the only difference between them is that the second one has two data sources.

**Comment by rubensworks** [comment]
Oh, I tested on http://query.linkeddatafragments.org/, while your queries were done on https://query.linkeddatafragments.org/, where I can indeed reproduce the problem.

I hope this is "just" a union issue, and not related to some http/https weirdness...
