### ISSUE TITLE
Add RDF/XML support

### ISSUE THREAD

**Issue by pietercolpaert** [comunica/comunica#140]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

RDF/XML files, whether you like it or not, are Linked Data. We should be able to also handle these.

I made this library which might be helpful for that purpose: https://www.npmjs.com/package/rdfxmlprocessor

**Comment by rubensworks** [comment]
Agreed, gave it a lower priority though.

PRs are welcome! :-)
