### ISSUE TITLE
iterate Bindings.keys in same order as SELECT variables

### ISSUE THREAD

**Issue by balhoff** [comunica/comunica#1401]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

This request follows from #1344. Although bindings from variables to values are not inherently ordered, it would be convenient if the iterator through the Bindings keys iterated in the same order as the variables in the SPARQL query (if there was one). For my own application I found a workaround by using `result.metadata().variables`, which does seem to iterate in the desired order.

**Comment by rubensworks** [comment]
Should be possible to implement in the project actor.

**Comment by rubensworks** [comment]
I looked into this, and came to the conclusion that implementing this would result in some performance overhead.
Since keeping track of this is not required in the majority of cases, I therefore decided not to implement this.
Instead, I will document your current workaround on the website.
