### ISSUE TITLE
bindings contains undefined value rather than missing key when querying SPARQL endpoint

### ISSUE THREAD

**Issue by balhoff** [comunica/comunica#1403]
#### Issue type:

- :bug: Bug 

____
#### Description:

If I submit a query to an external SPARQL endpoint, and the query contains an OPTIONAL, when an optional variable is not bound, Comunica will create an entry in a bindings object with that variable as key and with an `undefined` value. I think instead the key should not be present.

I added some logging within `actor-context-preprocess-query-source-skolemize/lib/utils.ts`:

```
export function skolemizeBindings(bindings: RDF.Bindings, sourceId: string): RDF.Bindings {
  bindings.forEach((value, key) => {
    console.log(`${key.value} : ${value?.value}`);
  });
...
```

This outputs:

```
p : http://www.w3.org/1999/02/22-rdf-syntax-ns#type
o : http://wikiba.se/ontology#Item
pLabel : undefined
```

just prior to the crash.

Example: https://query.comunica.dev/#datasources=https%3A%2F%2Ffrink.apps.renci.org%2Fwikidata%2Fsparql&query=PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT%20%3Fp%20%3Fo%20%3FpLabel%0AWHERE%20%7B%0A%20%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ101214733%3E%20%3Fp%20%3Fo%20.%0A%20%20OPTIONAL%20%7B%20%3Fp%20rdfs%3Alabel%20%3FpLabel%20%7D%0A%7D%0A
____
#### Environment:

```
| software         | version
| ---------------- | -------
| Comunica Engine  | 3.2.0 (dev)
| node             | v22.4.1
| npm              | 10.8.1
| yarn             | 1.22.22
| Operating System | darwin (Darwin 23.5.0)
```
#### Crash log:

```
/Users/jim/Documents/Source/comunica-source-annotate/packages/actor-context-preprocess-query-source-skolemize/lib/utils.js:61
        if (term.termType === 'Quad') {
                 ^

TypeError: Cannot read properties of undefined (reading 'termType')
    at /Users/jim/Documents/Source/comunica-source-annotate/packages/actor-context-preprocess-query-source-skolemize/lib/utils.js:61:18
    at /Users/jim/Documents/Source/comunica-source-annotate/packages/bindings-factory/lib/Bindings.js:71:34
    at /Users/jim/Documents/Source/comunica-source-annotate/node_modules/immutable/dist/immutable.js:2479:31
    at /Users/jim/Documents/Source/comunica-source-annotate/node_modules/immutable/dist/immutable.js:2497:18
    at ArrayMapNode.iterate.HashCollisionNode.iterate (/Users/jim/Documents/Source/comunica-source-annotate/node_modules/immutable/dist/immutable.js:2886:13)
    at Map.__iterate (/Users/jim/Documents/Source/comunica-source-annotate/node_modules/immutable/dist/immutable.js:2495:20)
    at Map.forEach (/Users/jim/Documents/Source/comunica-source-annotate/node_modules/immutable/dist/immutable.js:4880:19)
    at /Users/jim/Documents/Source/comunica-source-annotate/node_modules/immutable/dist/immutable.js:2478:13
    at Map.withMutations (/Users/jim/Documents/Source/comunica-source-annotate/node_modules/immutable/dist/immutable.js:2367:5)
    at Map.map (/Users/jim/Documents/Source/comunica-source-annotate/node_modules/immutable/dist/immutable.js:2477:19)
```

**Comment by balhoff** [comment]
Apologies, this is probably a dupe of #1391. I need to search existing issues more carefully!

**Comment by rubensworks** [comment]
> Comunica will create an entry in a bindings object with that variable as key and with an undefined value. I think instead the key should not be present.

That seems to be the problem indeed!

So the fix should be easy to apply here: https://github.com/comunica/comunica/blob/master/packages/actor-query-source-identify-hypermedia-sparql/lib/QuerySourceSparql.ts#L343-L347

And related to that, to fix https://github.com/comunica/comunica/issues/1406, we should remove that check there.
