### ISSUE TITLE
How do I execute SPARQL queries and get JSON format using `@comunica/query-sparql-file`?

### ISSUE THREAD

**Issue by harryli0088** [comunica/comunica#1408]
#### Issue type:

- :question: Question 

____
#### Question:

Hello! I'm wondering what the best way is to use `@comunica/query-sparql-file` in a JS/TS application? I have my own custom Express server that I'm making a SPARQL endpoint for. I'd appreciate any help!

Here is my usage of `@comunica/query-sparql-file` via command line execution:
```js
app.get("/sparql", (req: Request, res: Response) => {
  const { query } = req.query
  if(typeof query === "string") {
    const data = execSync(`comunica-sparql-file my_ttl_file.ttl -q "${query.replaceAll("\n"," ")}"`).toString()
    return res.status(200).send(JSON.parse(data))
  }
  return res.sendStatus(400)
});
```

This is my attempt at using the `@comunica/query-sparql-file` QueryEngine. Do you know what the best way is to get the results as JSON, like the command line execution approach above? Also, is there a way to keep the parsed TTL data in memory, so that I don't need to make a new engine every time?

```js
const QueryEngine = require('@comunica/query-sparql-file').QueryEngine;
const myEngine = new QueryEngine();

async function test() {
  const bindingsStream = await myEngine.queryBindings(`SELECT *  WHERE { ?s ?p ?o } LIMIT 5`, {
    sources: ['my_ttl_file.ttl'],
  });
  
  const bindings = await bindingsStream.toArray();
  //How do I get the results in JSON?
}

test()
```

**Comment by jeswr** [comment]
Does section 8 "Serializing to a specific result format" in https://comunica.dev/docs/query/getting_started/query_app/ provide the functionality that you're after?

**Comment by harryli0088** [comment]
Yes thank you! It works for me. I'm reading this page about caaching https://comunica.dev/docs/query/advanced/caching/. Just to confirm, does the engine cache the data source by default? I would have to pass the `noCache: true` flag manually to stop that behavior, correct?

**Comment by rubensworks** [comment]
That is correct.
