### ISSUE TITLE
no results in federated query when optional pattern has no matches

### ISSUE THREAD

**Issue by balhoff** [comunica/comunica#1410]
#### Issue type:

- :bug: Bug 

____
#### Description:

When there is an optional pattern that has no matches in the database, for example using a predicate that doesn't appear in the data, no results are returned even when they should. This seems to happen only when there is more than one data source (I have tried SPARQL and TPF endpoints).

Here is an example query (note the predicate `rdfs:unknown`, which doesn't appear in any triples in my datasets):

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT *
WHERE {
  <http://www.wikidata.org/entity/Q101214733> ?p ?o .
  OPTIONAL { ?p rdfs:unknown ?pLabel }
}
```

Executing this against one SPARQL source returns 108 results: https://query.comunica.dev/#datasources=https%3A%2F%2Ffrink.apps.renci.org%2Fwikidata%2Fsparql&query=PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT%20*%0AWHERE%20%7B%0A%20%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ101214733%3E%20%3Fp%20%3Fo%20.%0A%20%20OPTIONAL%20%7B%20%3Fp%20rdfs%3Aunknown%20%3FpLabel%20%7D%0A%7D%0A

It also returns 108 results when using a TPF endpoint (thus using Comunica's query engine): https://query.comunica.dev/#datasources=https%3A%2F%2Ffrink.apps.renci.org%2Fldf%2Fwikidata&query=PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT%20*%0AWHERE%20%7B%0A%20%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ101214733%3E%20%3Fp%20%3Fo%20.%0A%20%20OPTIONAL%20%7B%20%3Fp%20rdfs%3Aunknown%20%3FpLabel%20%7D%0A%7D

Executing the query when including an additional SPARQL source returns 0 results: https://query.comunica.dev/#datasources=https%3A%2F%2Ffrink.apps.renci.org%2Fwikidata%2Fsparql;https%3A%2F%2Ffrink.apps.renci.org%2Fsemopenalex%2Fsparql&query=PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT%20*%0AWHERE%20%7B%0A%20%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ101214733%3E%20%3Fp%20%3Fo%20.%0A%20%20OPTIONAL%20%7B%20%3Fp%20rdfs%3Aunknown%20%3FpLabel%20%7D%0A%7D%0A

Using both sources but changing the predicate in the OPTIONAL to one that is used in the data again returns 108 results (even though the optional pattern doesn't match anything and doesn't change the bindings): https://query.comunica.dev/#datasources=https%3A%2F%2Ffrink.apps.renci.org%2Fwikidata%2Fsparql;https%3A%2F%2Ffrink.apps.renci.org%2Fsemopenalex%2Fsparql&query=PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT%20*%0AWHERE%20%7B%0A%20%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ101214733%3E%20%3Fp%20%3Fo%20.%0A%20%20OPTIONAL%20%7B%20%3Fp%20rdfs%3Alabel%20%3FpLabel%20%7D%0A%7D%0A 
____
#### Environment:

Comunica 3.2.1; examples above in the Comunica live demo.

**Comment by rubensworks** [comment]
This sounds similar to https://github.com/comunica/comunica/issues/1316, which was [fixed](c7ca5ae597dbd5948e9b32ff5eb35ee820c48f81), so there's probably some other similar edge-case somewhere.
