### ISSUE TITLE
Purpose of `FragmentSelectorShape`

### ISSUE THREAD

**Issue by Chat-Wane** [comunica/comunica#1425]
#### Issue type:

- :question: Question 

____
#### Question:

Could you clarify the meaning of FragmentSelectorShape ? In my understanding, it's meant to be the interface provided by a source.

The code below would be for a source that only accepts triple patterns, and joins, and projects.
```
protected static readonly SELECTOR_SHAPE: FragmentSelectorShape = {
    type: 'disjunction',
    children: [{
            type: 'operation',
            operation: { operationType: 'type', type: Algebra.types.PATTERN }}, {
            type: 'operation',
            operation: { operationType: 'type', type: Algebra.types.JOIN }}, {
            type: 'operation',
            operation: { operationType: 'type', type: Algebra.types.PROJECT }} ]}
```

However, the codes of various actors seem to contradict this:

-   [`ActorQueryOperation.doesShapeAcceptOperation`](https://github.com/comunica/comunica/blob/b8f69dbf37eee85063bc96e93c780c74e9955555/packages/bus-query-operation/lib/ActorQueryOperation.ts#L231) is recursive for the shape, but is not recursive on the operation. If my shape accepts only triple patterns or joins, and my query has a union inside a join, the function will return `true` and then [`ActorOptimizeQueryOperationAssignSourcesExhaustive`](https://github.com/comunica/comunica/blob/b8f69dbf37eee85063bc96e93c780c74e9955555/packages/actor-optimize-query-operation-assign-sources-exhaustive/lib/ActorOptimizeQueryOperationAssignSourcesExhaustive.ts#L37) will consider it to be a valid (service) subquery for the source, despite the latter not supporting unions.

- [hardcoded `project`](https://github.com/comunica/comunica/blob/b8f69dbf37eee85063bc96e93c780c74e9955555/packages/bus-query-operation/lib/ActorQueryOperation.ts#L254) "disjunction" with "project" are always `true`.

- [ActorOptimizeQueryOperationGroupSources](https://github.com/comunica/comunica/blob/b8f69dbf37eee85063bc96e93c780c74e9955555/packages/actor-optimize-query-operation-group-sources/lib/ActorOptimizeQueryOperationGroupSources.ts#L52) Therefore an endpoint that would accept `project` would group with every other unmarked operator above. Among others, it would group with the unions created by the exhaustive source assignment. 

Is this a bug?
Am I writing the selector wrong?
Is my understanding wrong?

Thank you!

**Comment by rubensworks** [comment]
Yeah, the way "project" operations are used as wildcard in `FragmentSelectorShape` is not ideal in hindsight.
We may want to specify a "wildcard" operation, to that the "project" operation can keep its intended purpose.

We're working on preparing Comunica v4 in the `next/major` branch. I may look into incorporating this change as well.

**Comment by Chat-Wane** [comment]
Ok, this answers a lot of questions already. Thanks ! 

I still have doubts (that come from the large expressivity of selectors): Are they meant to be recursive by default? For instance, if the source accepts `union`, then `union`s of `union` are accepted as well? 

Or should it be explicitely expressed like `Fragment_1 accepts UNION of (Fragment_1)`. I was not able to tell by reading the code, comments, and the unofficial draft.

**Comment by rubensworks** [comment]
> I still have doubts (that come from the large expressivity of selectors): Are they meant to be recursive by default? For instance, if the source accepts union, then unions of union are accepted as well?

Currently, only the top-level operation is checked every time `doesShapeAcceptOperation` is invoked.

But to be honest, this system is not finetuned yet.
It works well for the source types that are supported by Comunica atm,
but it has many shortcomings (as you pointed out) to be sufficient for generic use.
We have plans for generalizing this approach, and allowing `FragmentSelectorShape`'s to be discovered dynamically through hypermedia descriptions.

I'm definitely open to suggestions :-)

**Comment by Chat-Wane** [comment]
Things are definitely clearer now!

> I'm definitely open to suggestions :-)

Well, I think this issue summarizes my suggestions: 
- an operator should not vouch for what's inside it, hence the recursive check (maybe guided by the `FragmentSelectorShape`)?
- `project` should be considered a normal operator

However, fixing these two things would have cascading effects on the group optimizer, and exhaustive assignments; and would open room for other optimizations (e.g. new push-down for sources that allow it). 

> We have plans for generalizing this approach, and allowing FragmentSelectorShape's to be discovered dynamically through hypermedia descriptions.

That's really great! I'll definitely have a use for these features when it comes out.

Again, thanks a lot!

**Comment by rubensworks** [comment]
> That's really great! I'll definitely have a use for these features when it comes out.

If there's anything you'd like to share, I'm definitely curious to hear about your use case.

**Comment by Chat-Wane** [comment]
I would but I can't right now… Hopefully in a near future.

**Comment by rubensworks** [comment]
I just pushed some changes into `next/major` which should cover your cases.
(I only validated the behaviour with some unit tests, as none of the sources that comunica supports by default require recursing into the query operation)

**Comment by Chat-Wane** [comment]
I didn't make a full check yet, but on my few tests, it seemed to work as intended, so thank you for that! I look forward for the 4.0.0!

Only an observation that highlights the need for such a feature in the future:
It seems like when we talk about SPARQL, we only talk about the *latest*, which is why you put a wildcard there. However, even in SPARQL, there is heterogeneity:

- Some endpoints use engines that are/will be discontinued (e.g. Blazegraph for Wikidata). Their interface won't be the latest forever. Switching to an up-to-date engine might be unfeasible.

- Some endpoints use up-to-date engines but lag behind the latest version, by fear of bugs, etc.

So handling shapes is nice (even without talking about federations), to smooth transitions between versions.
In that regards, for real-life-like tests, you could mock SPARQL 1.0 servers that do not handle aggregates.

**Comment by rubensworks** [comment]
> It seems like when we talk about SPARQL, we only talk about the latest, which is why you put a wildcard there. However, even in SPARQL, there is heterogeneity:

Yes, I fully follow you there!

Managing this heterogeneity is [even part of our roadmap](https://comunica.dev/roadmap/#future-oriented-development) :-)

But in order to get there, more work is definitely needed, such as more expressivity in these shapes as you mentioned, but also some kind of smart SPARQL query transpiler, ...
