### ISSUE TITLE
How to read serialized data using SPARQL query

### ISSUE THREAD

**Issue by elmeerr** [comunica/comunica#1427]
#### Issue type:

- :question: Question 

____
#### Question:

Hi, I am 100% new to turtles / linked data and I need to read a TLL file using SPARQL syntax like is done on this tool: https://www.semantechs.co.uk/turtle-editor-viewer/

I tried using the syntax from the docs:
```
const bindingsStream = await myEngine.queryBindings(`...`, {
  sources: [
    {
      type: 'serialized',
      value: '<ex:s> <ex:p> <ex:o>. <ex:s> <ex:p2> <ex:o2>.',
      mediaType: 'text/turtle',
      baseIRI: 'http://example.org/',
    },
  ],
});
````

but when I do:
```
bindingsStream.on('data', (binding) => {
     console.log(binding.toString()); // Quick way to print bindings for testing
});
```

there is no data being logged...don't know what I am missing here. Would it be possible to have some help?

example file: (the content comes as string after a request on a node app)
[2d7a8050-78c8-11ef-a6cb-2f0307a284b0.txt](https://github.com/user-attachments/files/17110204/2d7a8050-78c8-11ef-a6cb-2f0307a284b0.txt)

the query I tried to execute:
```
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX schema: <http://schema.org/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX nie: <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>

SELECT ?position ?agendaTitle ?simplerTitle ?html WHERE {
         ?agendaitem a besluit:Agendapunt ;
                     dct:title ?agendaTitle ;
                     ^prov:wasDerivedFrom ?newsitem ;
                   schema:position ?position .
         ?newsitem a dossier:Stuk ;
                   nie:htmlContent ?html ;
                   dct:title ?simplerTitle ;
                   dct:subject ?theme .
       } ORDER BY ?position
```

Any help would be appreciated.

Thanks in advance.

**Comment by rubensworks** [comment]
I suspect there could be an error occuring during execution.
Error handlers can be attached to the engine as explained here: https://comunica.dev/docs/query/getting_started/query_app/#3-1-consuming-binding-results-as-a-stream

**Comment by elmeerr** [comment]
Hey @rubensworks, thanks for the quick reply and sorry for the late reply, I was busy and did not have time to check this again. I will double check that and come back to you ASAP.

Thanks!

**Comment by elmeerr** [comment]
Hi @rubensworks unfortunately it gives no error. Just does not show anything at all. You can close the issue if you want...I don't think I will have the time to keep looking into this.

Thanks

**Comment by rubensworks** [comment]
Ok, no worries.
