### ISSUE TITLE
How to build the browser version? "yarn browser" gives error message

### ISSUE THREAD

**Issue by larsgsvensson** [comunica/comunica#143]
#### Issue type:

- :question: Question

____
#### Question:

I try to create the browser version by executing `yarn browser` as stated in the [README](https://github.com/comunica/comunica/tree/master/packages/actor-init-sparql#usage-within-browser). However, when I execute `yarn browser` the output is
```
svensson@ldslab:~/comunica$ yarn browser
ver -> 8.11.2
yarn run v1.7.0
error Command "browser" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
What am I doing wrong?
Thanks for any help,
Lars

**Comment by rubensworks** [comment]
Ah, it looks like the README is wrong, the correct command should be `yarn run browser`.

Will fix this soon, thanks for reporting this!

**Comment by larsgsvensson** [comment]
That solves it. Thank you!

**Comment by larsgsvensson** [comment]
Another nit for the README: The file `comunica-browser.js` is _not_ created in the `dist` directory but directly in `packages/actor-init-sparql`. At least on my machine...

**Comment by rubensworks** [comment]
Yes, you're right! :-) Fixed ^

**Comment by larsgsvensson** [comment]
That's what I call prompt support!
