### ISSUE TITLE
QueryEngineFactory is not a constructor

### ISSUE THREAD

**Issue by antoine37120** [comunica/comunica#1438]
#### Issue type:

- :bug: Bug 

____
#### Description:
I use :  
```
  import { QueryEngineFactoryBase } from '@comunica/actor-init-query';
  import { QueryEngine, QueryEngineFactory } from '@comunica/query-sparql';
```
and when call : 
```
const myEngine = await new QueryEngineFactory().create({
        configPath: 'config-comunica/config-solid-single-pod.json', // Relative or absolute path 
    });
```
js consols say me `QueryEngineFactory is not a constructor`

and if I try : 
```
    console.log(QueryEngine) ; // return js class
    console.log(QueryEngineFactory) ; return undefined
```
How to use QueryEngineFactory ?
____
#### Environment:

| software         | version
| ---------------- | -------
| Comunica Engine  | 3.2.1
| node             | v20.14.0
| npm              | 10.7.0
| yarn             | 1.22.22
| Operating System | win32 (Windows_NT 10.0.19045)

#### Crash log:

<img width="764" alt="image" src="https://github.com/user-attachments/assets/201f1921-a53f-4d67-b99a-45bf0037fda7">

**Comment by rubensworks** [comment]
`QueryEngineFactory` only available in Node.js, not in browser environments.
That's because it relies on reading files on the local file system.

If you want to use a custom config in a browser environment, you will have to compile this config to a dedicated engine beforehand, and then use that compiled engine in the browser.
More details: https://comunica.dev/docs/modify/getting_started/custom_init/

I hope this helps :-)

**Comment by tfrancart** [comment]
Thanks @rubensworks !
In the procedure to compile a new engine, do we have a way to test the compiled engine prior to publishing to NPM ? We are not sure of the config we need, so we need to test. 

To give you some context we need a single solid pod config with added linked data traversal features : some resources in the pod are referring to linked data resources outside the pod, and we would like these to be fetched also. Can you confirm this is possible ? Can we instruct the config to follow only certain predicates in the resources read from the Solid Pod ?

**Comment by rubensworks** [comment]
@tfrancart, what you describe is definitely possible. Following custom predicates can be configured like this: https://github.com/comunica/comunica-feature-link-traversal/blob/master/engines/config-query-sparql-link-traversal/config/extract-links/actors/predicates-common.json

There's no need to publish your custom engine to npm. It's just the config compilation part of the tutorial that would be relevant for you. This part could even be included in your current npm package.
But if you want to publish your custom engine as a standalone package, this is definitely possible as well. If you want to do testing before publishing, you could try it out in another package using `npm link` or `yarn link`.

**Comment by tfrancart** [comment]
@rubensworks a 1000 thanks ! we will look into this and let you know. We are trying to integrate a [Sparnatural](https://sparnatural.eu/) with a Solid Pod.

**Comment by rubensworks** [comment]
@tfrancart Good luck! Just remember that the link traversal functionality is experimental, so you may run into bugs :-)

FYI, we're working on Comunica v4, which will probably be released around mid-October.
There will be some (minimal) breaking changes, that may impact your config files.
But I'll include a brief migration guide in the blog post after the release.
