### ISSUE TITLE
Inconsistent Hydra Links Cause Interruption in Data Fetching from Wikidata LDF Endpoint

### ISSUE THREAD

**Issue by mandel59** [comunica/comunica#1461]
#### Issue type:

- :bug: Bug 

____
##### Summary

When fetching paginated data from the Wikidata LDF endpoint, the process is interrupted because the hydra:nextPage links in the response contain inconsistencies in their URL representation. These inconsistencies prevent proper identification of the next page, resulting in incomplete data retrieval.

##### Steps to Reproduce

Run the following command:

```
comunica-sparql -q 'SELECT * WHERE { <http://www.wikidata.org/entity/Q1> ?p ?o }' https://query.wikidata.org/bigdata/ldf
```

##### Expected Behavior

All triples related to entity Q1 are retrieved.

##### Actual Behavior

Only a partial set of triples (172 triples) related to entity Q1 is retrieved.

##### Workaround

This issue originates from a server-side problem, so resolving it at the server level would be ideal. However, due to the inherent ambiguity of URLs, similar link-breaking issues could arise in other implementations. While the server can absorb ambiguity on the object during fetching, ambiguity on the subject must be handled by the client.

As a workaround, I implemented a "loose matching" mechanism. The code for this workaround has been pushed to <https://github.com/mandel59/comunica/tree/workaround-for-wikidata>.

This mechanism accounts for URL differences by ignoring:

- The order of query parameters.
- The presence of irrelevant fragments or trailing slashes.
- Differences between IRIs and URLs with percent-encoded characters.

##### Questions

While this workaround is effective, it is not a standardized solution.

Would it be desirable to incorporate such a fix into Comunica itself?
Are there other areas of link processing where similar loose matching logic might be needed?

____
#### Environment:

```
| software         | version
| ---------------- | -------
| Comunica Engine  | 4.0.2 (dev)
| node             | v20.13.1
| npm              | 10.5.2
| yarn             | 1.22.22
| Operating System | darwin (Darwin 23.6.0)
```

**Comment by rubensworks** [comment]
While I understand the issue, this is definitely something that needs to be fixed on Wikidata's TPF entrypoint.
There are a virtually infinite number of ways in which servers could misexpose things, and it's infeasible to provide workarounds for all of them in client-side engines such as Comunica.
Furthermore, such workarounds can have a negative impact on performance.
In general, Comunica aims to follow the RDF spec wrt [IRI handling](https://www.w3.org/TR/rdf12-concepts/#dfn-iri-equality).

That being said, I'm open to introducing some leniency, if there's evidence of specific servers errors commonly occuring in practise (e.g. like we do for some SPARQL service description errors).

**Comment by rubensworks** [comment]
Thanks for reporting it at Phabricator!

For reference, an easier way to reproduce the problem that does not require installing anything is by using our web client: https://query.comunica.dev/#datasources=https%3A%2F%2Fquery.wikidata.org%2Fbigdata%2Fldf&query=SELECT%20*%20WHERE%20%7B%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ1%3E%20%3Fp%20%3Fo%20%7D
