### ISSUE TITLE
Have a repository or website with Comunica builds

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#147]
#### Issue type:

- :heavy_plus_sign: Feature request
____
#### Description:

Can we have a website and/or GitHub repository (perhaps under the rdfjs organization) that contains ready-to-use Comunica builds for the browser? Perhaps as a CDN even?
Thinking of the full actor-init-sparql engine, as well as #146 for instance.

**Comment by rubensworks** [comment]
Hmm, good idea. The RDFJS organization might indeed be ideal for this, where GitHub can act as our CDN.

Setting this up should be easy, as Travis already browserifies in each build. We could auto-publish the results to a different repo (possibly behind different branches)

**Comment by rubensworks** [comment]
Implemented in ba7bf64a8398030c184d56431482dbddb965b8dd.

More information: https://github.com/rdfjs/comunica-browser

**Comment by RubenVerborgh** [comment]
Just perfect, thanks!
