### ISSUE TITLE
Replace ex:my… in default configuration

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#148]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

I noticed that https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql/config/config-default.json contains quite some things like `ex:myTableSparqlSerializer`.

First, I wonder whether it is necessary that these get IRIs. But I think the answer is yes, because that simplifies reuse and derived configurations.

Second, I wonder whether we should give them better URIs, for example `xyz:defaultTableSparqlSerializer`, and have those dereference. (Related: do the current URLs dereference?)

**Comment by rubensworks** [comment]
Yes, these should dereference.
Once we split up configs (#25), we could make them dereference to the configs themselves.

**Comment by rubensworks** [comment]
Merged this issue into #25.
