### ISSUE TITLE
Client-side filtering does not filter hypermedia controls correctly

### ISSUE THREAD

**Issue by larsgsvensson** [comunica/comunica#152]
#### Issue type:

- :bug: Bug
(from #121)
____
#### Description:

When querying a triple-based server (Server.java) the list of `?s` from the query
```sparql
PREFIX gndo: <http://d-nb.info/standards/elementset/gnd#>
SELECT ?s 
WHERE { ?s a gndo:DifferentiatedPerson }
```
contained `<http://10.69.14.96:8081/authorities#dataset>` three times per page; twice with predicate `http://www.w3.org/1999/02/22-rdf-syntax-ns#type`, once with predicate `http://rdfs.org/ns/void#subset`.
`http://10.69.14.96:8081/authorities#dataset` is the subject of a larger set of triples:
```turtle
<http://10.69.14.96:8081/authorities#dataset>
    a void:Dataset , hydra:Collection ;
    void:subset <http://10.69.14.96:8081/authorities?predicate=http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type&object=http%3A%2F%2Fd-nb.info%2Fstandards%2Felementset%2Fgnd%23DifferentiatedPerson> ;
    hydra:itemsPerPage  "100"^^xsd:long ;
    hydra:search [
        hydra:mapping
            [ hydra:property  rdf:subject ;
              hydra:variable  "subject"
            ] ;
        hydra:mapping
            [ hydra:property  rdf:predicate ;
              hydra:variable  "predicate"
            ] ;
         hydra:mapping
             [ hydra:property  rdf:object ;
               hydra:variable  "object"
             ] ;
          hydra:template  "http://10.69.14.96:8081/authorities{?subject,predicate,object}"
      ] .
```
It seems that only the triples in namespace `hydra` are filtered out.
____
#### Environment:

locally built communica-browser.js

**Comment by rubensworks** [comment]
Thanks for reporting! I'll look into it soon.

**Comment by larsgsvensson** [comment]
Thanks for fixing this. I'll test it as soon as I can build the library...

**Comment by larsgsvensson** [comment]
My original query now returns only `?s` that seem reasonable, so this seems resolved. Thanks @rubensworks!
