### ISSUE TITLE
Move source type identifier lower down the chain

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#193]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

Currently, source type identification happens in a context-preprocess step. It would be more flexible to move this further down the change to the quadpattern-resolve layer, and identify the type there. 

The actor should definitely cache the type, as multiple calls are likely to follow.

**Comment by joachimvh** [comment]
This is actually one place where an argument could be made for having a mutable context...

**Comment by rubensworks** [comment]
Done in #432.
