### ISSUE TITLE
Top-level optional not working as expected.

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#194]
#### Issue type:

- :bug: Bug

____
#### Description:

When executing the following query, no results are found:
```
SELECT * WHERE {
  OPTIONAL {
    ?bla <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Person>.
    ?bla <http://www.w3.org/2000/01/rdf-schema#label> ?name.
  }
}
```

However, when this query is executed with either the TPF client or Virtuoso, the expected results are found. The spec is not clear on this.

Internally, Comunica converts this to a left join, where the left pattern is empty. Should Comunica detect these cases where such an optional is applied, and unwrap it? Or are both the TPF client and Virtuoso doing something wrong?

**Comment by rubensworks** [comment]
@joachimvh Thoughts? (I remember we discussed this offline a while ago, but I forgot the outcome, so it'd be good to have this documented here)

**Comment by joachimvh** [comment]
As discussed offline again, my thoughts are that we should have results (probably misread the spec last time, or we didn't account for this case).
