### ISSUE TITLE
Make public

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#21]
A couple of things that need to be done before we make the project public.

* [x] Support QPF queries: #8 
* [x] Release new major Components.js version: #27
* [x] General code cleanup:
  * [x] Remove todo's
  * [x] Check if some defaultScopeds can be changed to defaults in component files
  * [x] Cleanup tests #12
* [x] SPARQL query support
* [x] Add more information to wiki about architecture
* [x] Improve README.md
* [x] Add contribution guidelines + issue template
* [x] CLA
* [x] Auto-deploy docs to github pages.
* [x] Setup Travis (also add tests for browser compilation)
* [x] Coveralls
* [x] Greenkeeper + [greenkeeper-lockfile](https://github.com/greenkeeperio/greenkeeper-lockfile)
* [x] Publish to npm ~~(first try locally using sinopia)~~.

**Comment by rubensworks** [comment]
All done! 🎉 

The only thing left to do is to make a public announcement :)

**Comment by RubenVerborgh** [comment]
Congrats :party:
