### ISSUE TITLE
Execution plan dumping

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#210]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

We should have a way to dump the full execution plan after it has been executed.

This should include things like:
* Which actor was called by what other actor? And with what parameters?
* How long did each action take?

Example output:
```
{
  "actions": [
    {
      "@id": 1,
      "target": "#sparqlParseActor",
      "action": "select * where {...}",
      "duration": 100,
      "consequences": [ 2 ]
    },
    {
      "@id": 2,
      "target": "#sparqlOperator",
      "action": "s p o",
      "duration": 90,
      "consequences": [ 3 ]
    }
  ]
}
```

Possible source of inspiration: #54, https://jena.apache.org/documentation/query/explain.html

**Comment by mielvds** [comment]
Is there anything architectural blocking this?

**Comment by rubensworks** [comment]
It should be possible to implement this using the new [`ActionObserver`s](https://github.com/comunica/comunica/blob/9807bb935f866eb8bc1970694b297ef04cb9fe94/packages/core/lib/ActionObserver.ts).

**Comment by mielvds** [comment]
Nice, so a possible strategy would be:
- if profiling is enabled, create a `ActionObserver` and call `subscribeObserver` on every bus.
- dump the action input/output in the above format.
- (optional) provide a script that generates a visual representation

**Comment by rubensworks** [comment]
Yep, that should work!

> dump the action input/output in the above format.

My suggested format was something that was quickly written down, so there is room for improvement there.

**Comment by rubensworks** [comment]
A first experimental version of this will be included in Comunica 2.x.
