### ISSUE TITLE
actor-init-sparql-rdfjs error: yRdfRdfJsSourceQuadPatternResolver requires a single source...

### ISSUE THREAD

**Issue by predicador37** [comunica/comunica#216]
#### Issue type:

- :bug: Bug

____
#### Description:

When executing this test code (only the relevant parts are included):

```javascript
 const source = {
      match: function (s, p, o, g) {
        return require('streamify-array')(store.getQuads(s, p, o, g))
      }
    }

// Create our engine, and query it.
// If you intend to query multiple times, be sure to cache your engine for optimal performance.
    const myEngine = newEngine()
    let results = []
    const p = new Promise((resolve, reject) => {
      myEngine.query('SELECT * WHERE {?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://www.w3.org/2002/07/owl#Class> .} LIMIT 100',
        {'sources': [{type: 'rdfjsSource', value: source}]})
        .then(function (result) {
          result.bindingsStream.on('data', function (data) {
            // Each data object contains a mapping from variables to RDFJS terms.
            results.push(data)
          }).on('end', () => {

            results.forEach((item) => {
              console.log(item.get('?s').value)
              console.log(item.get('?p').value)
              console.log(item.get('?o').value)
            })
            resolve(results)
          })
        })
    })
    return expect(p).resolves.toBeTruthy()
  })
```

I get the error:

    Error: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/sparql-queryoperators.json#mediatorResolveQuadPattern mediated over all rejecting actors:
    Error: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql-rdfjs/^1.0.0/config/sets/resolve-rdfjs.json#myRdfRdfJsSourceQuadPatternResolver requires a single source with an rdfjsSource to be present in the context.

This didn't happen with the same test code at commit `ff45932ef5deb1cc727db4bd76d10733b957815b`, for example.
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.1.0 (dev)
| node                | v10.7.0
| npm                 | 6.1.0
| yarn                | 1.9.2
| Operating System    | linux (Linux 4.9.0-7-amd64)

#### Crash log:

    Error: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/sparql-queryoperators.json#mediatorResolveQuadPattern mediated over all rejecting actors:
    Error: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql-rdfjs/^1.0.0/config/sets/resolve-rdfjs.json#myRdfRdfJsSourceQuadPatternResolver requires a single source with an rdfjsSource to be present in the context.

**Comment by rubensworks** [comment]
This may also be fixed with 29779e93098c0f1ac161753f13f9c7be5877ddb9, I'll check this later.

**Comment by rubensworks** [comment]
Ok, needed a small change, but it works now again.

I'll get started on those integration tests now, so that things like this don't break anymore...

**Comment by predicador37** [comment]
Confirmed. It works now! Thanks a lot.
