### ISSUE TITLE
actor-init-sparql example command-line query does not work

### ISSUE THREAD

**Issue by predicador37** [comunica/comunica#217]
#### Issue type:

- :bug: Bug

____
#### Description:

When trying to execute the following command:

`/comunica/packages/actor-init-sparql$ node bin/query.js http://fragments.dbpedia.org/2015-10/en "CONSTRUCT WHERE { ?s ?p ?o } LIMIT 100"`

the following error raises:

```
Error: All actors rejected their test in https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/context-preprocess-rdf-source-identifiers.json#mediatorRdfSourceIdentifier
Error: This actor only handles request with a set valid datetime.
Error: This actor only handles request with a set valid datetime.
Error: This actor only handles request with a set valid datetime.
    at MediatorNumber.mediateWith (/home/predicador/data/code/comunica/packages/mediator-number/lib/MediatorNumber.js:53:19)
```

____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.1.0 (dev)
| node                | v10.7.0
| npm                 | 6.1.0
| yarn                | 1.9.2
| Operating System    | linux (Linux 4.9.0-7-amd64)

**Comment by rubensworks** [comment]
This should be fixed in 29779e93098c0f1ac161753f13f9c7be5877ddb9, which will be merged to master in #208.

**Comment by rubensworks** [comment]
Just checked, and your query works properly again.

**Comment by predicador37** [comment]
Sure it does. Thanks for your speed and good work!
