### ISSUE TITLE
Add support for alternative SPARQL result formats

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#220]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

* [ ] CSV/TSV: https://www.w3.org/TR/2013/REC-sparql11-results-csv-tsv-20130321/
* [x] XML: https://www.w3.org/TR/2013/REC-rdf-sparql-XMLres-20130321/

**Comment by ColinMaudry** [comment]
Hello :)

Any news on the possible addition of CSV output?

Thanks!

**Comment by rubensworks** [comment]
It's not on our roadmap at the moment unfortunately.
But we would definitely accept a PR on this, shouldn't require that much work, happy to give pointers if needed.

**Comment by ColinMaudry** [comment]
For my implementation, since I need CSV, I think I'll catch the output and convert it, but it would perform better if directly implemented.

I know a TS master who may help. Could you give a few pointers on where the magic would happen? I tried to track `resultToString`, but didn't manage to find the spot.

**Comment by rubensworks** [comment]
> Could you give a few pointers on where the magic would happen?

This would require the creation of a new actor (`actor-sparql-serialize-sparql-csv`). [This tutorial](https://github.com/comunica/Tutorial-Comunica-Reduced-Actor) explains the basics around actor creation in Comunica.

The easiest way to get started would be to [clone this repo and setup the dev environment](https://github.com/comunica/comunica#development-setup), and generate the basic files for the new actor using [this generator](https://github.com/comunica/generate-comunica). The generator will prompt for the actor name (`sparql-csv`) and the bus name (`sparql-serialize`). Everything else can remain default.

Finally, the actor will need to be configured into [this config file](https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql/config/sets/sparql-serializers.json#L49-L56).
