### ISSUE TITLE
Abstract configurations

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#25]
In the future, we could provide component sets which provide a certain specific functionality. These sets could provide importable config files (using `owl:imports`) to simplify config files in cases where knowledge of the deeper component levels is not needed.

**Comment by rubensworks** [comment]
Imported from #148.
Additionally, all config parts should be dereferencable (such as `ex:myTableSparqlSerializer`). This will be made possible through #149.

**Comment by rubensworks** [comment]
Follow-up on PR #173.

@joachimvh Related to #149, could you add support in the LSD server for dereferencing config files?
This is the final missing step to make config files fully dereferenceable.

All package.json files can now contains things like this:
```
"lsd:importPaths": {
    "https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/components/": "components/",
    "https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/": "config/"
  },
```

The values in this hash indicate the relative paths that should be exposed.
You can ignore the keys, those are only used by Components.js. But if I did everything correctly, these _should_ dereference to their final location on the LSD server.

**Comment by joachimvh** [comment]
Does this mean the `lsd:components`/`lsd:contexts` keys will disappear is is this another key in addition to those? And the idea is then that all files in those folders (and subfolders) need to be dereferencable through a relative path?

**Comment by rubensworks** [comment]
> Does this mean the lsd:components/lsd:contexts keys will disappear is is this another key in addition to those?

`lsd:components` and `lsd:contexts` will stay, as they have more specific semantics that are required by Components.js.

> And the idea is then that all files in those folders (and subfolders) need to be dereferencable through a relative path?

Yep, that's the idea of `lsd:importPaths`.

**Comment by rubensworks** [comment]
@joachimvh Can you close this issue once support for `lsd:importPaths` has been added to the LSD server?

**Comment by joachimvh** [comment]
Support added [here](https://github.com/LinkedSoftwareDependencies/npm-extraction-server/commit/e762295fc3c408c4091570cc16f70e29865159ae)
