### ISSUE TITLE
Extract abstract configs

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#267]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

Currently, all init-sparql actors extend from `@comunica/actor-init-sparql`. This makes it so that all extensions will always inherit all dependencies from this package, while some may not need it.

To solve this, we should create an abstract package that _only_ contains the config sets and query init logic.

**Comment by joachimvh** [comment]
Some init actors have features that are not in the main init sparql though, specifically resolving rdfjs. This was a problem earlier where @pheyvaer needed features from both and was having some dependency problems when trying to combine them.

**Comment by pheyvaer** [comment]
The dependency problems occurred in the browser. So I build both `actor-init-sparql` and `actor-init-sparql-rdfjs`. This resulted in multiple imports of the same packages in the browser, causing error, also I could not distinguish between the two in my code.

**Comment by rubensworks** [comment]
> So I build both actor-init-sparql and actor-init-sparql-rdfjs

Ah yes, that won't work indeed, because webpack creates unique builds of each module, which can cause conflicts.

A better solution until we fix this would be to start from `actor-init-sparql`, also add the rdfjs source resolver as a dependency, create a custom config file, and compile that for the browser.

**Comment by pheyvaer** [comment]
Yeah, that's how I got it working :smiley:

**Comment by allforabit** [comment]
@pheyvaer Could you give more details on how you got it working? I need to use the rdfjs source with `actor-init-sparql` as well.

**Comment by pheyvaer** [comment]
I've built a custom comunica engine:

1. Use the [config](https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql/config/config-default.json) of `actor-init-sparql`.
2. Add the rdfjs specific elements from the [config](https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql-rdfjs/config/config-default.json) of `actor-init-sparql-rdfjs`.
3. Build the engine via the [Comunica Packager](https://github.com/comunica/comunica/tree/master/packages/packager).

I did [something similar](https://github.com/pheyvaer/graphqlld-on-file/) for execute GraphQL-LD queries on files using Comunica.

**Comment by rubensworks** [comment]
Oh FYI, I plan to add the RDFJS actor to the default actor-init-sparql config in the next major (or minor) release. Workarounds like this won't be needed anymore then.

**Comment by allforabit** [comment]
Thanks very much @pheyvaer I was thinking it was something along those lines and thanks @rubensworks that will make it very straightforward indeed.
