### ISSUE TITLE
Remove dependency on node-web-streams

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#275]
The [node-web-streams](https://www.npmjs.com/package/node-web-streams) dependency is using a [git-based dependency](https://github.com/gwicke/node-web-streams/issues/1), and they don't seem to be keen on using a proper npm-based dependency.
So we should move to another package that does not use any git-based dependencies.

Git-based dependencies seem to cause issues for some people when installing, so we should avoid these kinds of dependencies.

**Comment by michielbdejong** [comment]
This issue has been open for over a year now.

**Comment by mielvds** [comment]
This git dep is no longer the case: https://github.com/jccr/web-streams-node/commit/7f328af427fab6caac3bd019ea787998bafa523b

**Comment by rubensworks** [comment]
That's a different npm package (`web-streams-node`). But it may be possible to switch to that without too much code refactoring.

PRs on this are welcome :-)

**Comment by RubenVerborgh** [comment]
@michielbdejong 

> This issue has been open for over a year now.

Please be aware that we have limited funding. It's a large project that we bring to the open source community, and we welcome their input. Issues that are not related to core functionality and can be solved with engineering methods, such as this one, are low on the priority list; we tend to focus on the things that require our specific expertise.

**Comment by mielvds** [comment]
> That's a different npm package (`web-streams-node`). But it may be possible to switch to that without too much code refactoring.
> 
> PRs on this are welcome :-)

Ah didn't notice! But one is a fork of the other, let me see if I can work up a PR (have some minutes).

**Comment by RubenVerborgh** [comment]
For the time being, we can just webpack its `web-streams-polyfill` dependency away in the browser: https://github.com/inrupt/generator-solid-react/issues/281#issuecomment-559077342

**Comment by mielvds** [comment]
Since the API did not change, the issue was fixed quite fast :p -> #587

**Comment by RubenVerborgh** [comment]
@mielvds great; webpack advice remains though (for size reasons).

**Comment by michielbdejong** [comment]
\o/
