### ISSUE TITLE
Automatic source type identification uses more requests than necessary

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#281]
#### Issue type:

- :snail: Performance issue

____
#### Description:

Automatic source type identification for https://ruben.verborgh.org/profile/ results in 4 requests:
1. GET https://ruben.verborgh.org/profile/
2. HEAD https://ruben.verborgh.org/profile/?query=ASK%20%7B%20%3Fs%20a%20%3Fo%20%7D
3. HEAD https://ruben.verborgh.org/profile/
4. HEAD https://ruben.verborgh.org/profile/

The last 2 requests should be avoidable given the first.
The second should be avoidable if it is executed last.
____
#### Environment:

Current http://query.linkeddatafragments.org/.

**Comment by rubensworks** [comment]
We could solve this by adding an LRU cache onto the HTTP bus.

**Comment by RubenVerborgh** [comment]
Not fully, you need to take into account the different Accept headers.

**Comment by rubensworks** [comment]
Ah right, that was indeed the difficulty. I once started implementing this on the link traversal branch, and then stopped when I realized this, and that it would take some more time.

**Comment by rubensworks** [comment]
Fixed in #432.
