### ISSUE TITLE
LD documents without content type not queryable.

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#286]
#### Issue type:

- :bug: Bug

____
#### Description:

Documents without a Content-Type header value like http://wikiba.se/ontology#label are not queryable. We should provide a fallback-mechanism based on file extensions for such situations, just like we do for querying local files.

**Comment by pietercolpaert** [comment]
an `.owl` file could equally as well be a turtle file, no? I would just try different parsers, starting with the fastest (probably N3), going to slower parsers when the parser gives an error or returns no triples.

**Comment by pietercolpaert** [comment]
And I would also request that a warning is thrown. If you’d be the data owner of this dataset, that you can fix the content-type for faster querying

**Comment by rubensworks** [comment]
Indeed, that could be the fallback to the fallback :-)

I would keep that as a last resort though, as I've noticed some issues with this approach in Components.js. (For example, some N-Triples documents are valid RDF/XML documents...)
