### ISSUE TITLE
TypeError with SPARQL query on TPF endpoint via library

### ISSUE THREAD

**Issue by pheyvaer** [comunica/comunica#292]
#### Issue type:

- :bug: Bug

____
#### Description:

The following query gives an error (`source.destroy is not a function (TypeError)`) when executed via the library directly, but not when using the CLI.

```
SELECT * {
     ?s ?p <http://schema.org/ScholarlyArticle>.
     ?s <http://schema.org/name> ?name.
     ?s <http://schema.org/author> ?author}
```
The full code that I run is 

```javascript
  const newEngine = require('@comunica/actor-init-sparql').newEngine;
  const myEngine = newEngine();

  const query = `SELECT * {
     ?s ?p <http://schema.org/ScholarlyArticle>.
     ?s <http://schema.org/name> ?name.
     ?s <http://schema.org/author> ?author}`;

  myEngine.query(query,
    { sources: [ { type: 'hypermedia', value: 'https://data.pieterheyvaert.com/research' } ] })
    .then(function (result) {
    });
```
Furthermore, when removing either the 2nd or 3rd pattern in the query, it works.
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.3.0 
| node                | v8.12.0
| npm                 | 6.4.1
| yarn                | _Yarn is unavailable_
| Operating System    | linux (Linux 4.15.0-36-generic)

**Comment by rubensworks** [comment]
Oh, that's an interesting one. I'll look into it today.

**Comment by rubensworks** [comment]
That's strange, I don't get that error when I try it myself. And I'm even on an older Node version (v8.11.2) than you...

@joachimvh Could you try this one to see if it fails on your end?

**Comment by rubensworks** [comment]
@pheyvaer Could you provide a complete stacktrace?

**Comment by pheyvaer** [comment]
Stacktrace:
```
source.destroy is not a function (TypeError)
(error stack): TypeError: source.destroy is not a function
at PromiseProxyIterator.TransformIterator._end (/home/pieter/Developer/eleventy-test/node_modules/asynciterator-promiseproxy/node_modules/asynciterator/asynciterator.js:1105:14)
at Immediate.end [as _onImmediate] (/home/pieter/Developer/eleventy-test/node_modules/asynciterator-promiseproxy/node_modules/asynciterator/asynciterator.js:279:36)
at runCallback (timers.js:802:20)
at tryOnImmediate (timers.js:762:5)
at processImmediate [as _immediateCallback] (timers.js:733:5)
```

Also tried it with an older version of Node (8.1.2) but had the same result.

**Comment by joachimvh** [comment]
For me it doesn't error but I also get no output so will have a deeper look

**Comment by rubensworks** [comment]
Ok, so it seems to be an issue with conflicting asynciterator versions. When installing with npm, an old version of asynciterator seems to be included, which doesn't include `destroy`.

**Comment by rubensworks** [comment]
@joachimvh That's because this snippet doesn't actually print anything :-)

**Comment by joachimvh** [comment]
That is a very good point

**Comment by rubensworks** [comment]
For reference, this appeared to be a dependency issue.

`ldf-client` was also a dependency in the application next to `comunica`, which cause `asynciterator` < `2.0.0` to be loaded. This appears to be an npm-specific problem that does not appear when installing with yarn.
