### ISSUE TITLE
Tests contain pointless checks

### ISSUE THREAD

**Issue by wschella** [comunica/comunica#300]
#### Issue type:

- :bug: Bug

____
#### Description:

In some query operation tests (e.g. FilterDirect, LeftJoinNestedLoop) checks like this ` expect(output.metadata()).toMatchObject(Promise.resolve({ totalItems: 3 }));` are made.

These however have no effect, and you can enter any number.
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.4.1 (dev)
| node                | v8.12.0
| npm                 | 6.4.1
| yarn                | 1.10.1
| Operating System    | linux (Linux 4.15.0-34-generic)

**Comment by rubensworks** [comment]
Yeah, that assert doesn't make much sense indeed :-) The metadata should be `await`-ed.
