### ISSUE TITLE
Expose source files so we can use custom Babel settings

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#308]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

Packages are currently only exposing `lib`. Can we also expose `src`, or perhaps a TypeScript-to-JavaScript transpiled version in another folder? And can we expose that folder through a [`module` field](https://github.com/rollup/rollup/wiki/pkg.module)?

The reason is that I'm seeing a performance issue in a library that uses the engine, and the flame graph shows a lot of transpiled generator code. I'd want to check if the same issue also happens without the generator code.

**Comment by rubensworks** [comment]
TIL about the `module` field :-)

Ok, so if I understand correctly, you want this:
* Every packages exposes a `/dist` folder.
* The files in `/dist` are transpiled to ES2015 (?). (currently the JS files in our `/lib` folder are compiled to ES2017)
* `/dist` is exposed via the `module` field.

**Comment by RubenVerborgh** [comment]
The `module` field indeed seems to be for ES2015.
But I'm really interested in having the original sources; perhaps with just the TypeScript converted to JavaScript, but without transpilation of `async` etc. So as in http://2ality.com/2017/04/setting-up-multi-platform-packages.html

**Comment by rubensworks** [comment]
Actually, the `.js` files in our `/lib` folder already are only compiled from TS to JS (ES2017) with minimal transpilation. Those files do indeed still contain `async` etc.

Only our browser version is transpiled to ES2015 with Webpack and Babel. (`comunica-browser.js`)

So I assume the transpiled generator code is present in the browser? Perhaps you can try changing the ES target in the Webpack config file.

**Comment by RubenVerborgh** [comment]
You're right. Weird, it was transpiled for me. I'll check this in more detail.

**Comment by RubenVerborgh** [comment]
> Only our browser version is transpiled to ES2015 with Webpack and Babel. (`comunica-browser.js`)

I presume this was the issue: webpack picks up the `browser` field and uses that version.

> Perhaps you can try changing the ES target in the Webpack config file.

Yes. I wonder what the best choice is. The problem is that this browser field does not have an official definition.

How I use it in solid-auth-client is to provide a packaged version that:
- is a single bundle
- contains only browser dependencies (so no `node-fetch` etc)
- is not minified
- transpiles to ES2017 (i.e., only transpile Babel plugins)

The logic is that it is up to the webpack of the library that uses it to use babel etc. But there is also logic for the opposite, that the using library shouldn't have to care about transpiling.

Perhaps we should just know if there is a major performance difference with regard to built-ins.

**Comment by rubensworks** [comment]
> I presume this was the issue: webpack picks up the browser field and uses that version.

`comunica-browser.js` is not included in the package, and not referenced in the `package.json` file. It is only generated in the monorepo.
The [`browser` field only references `index-browser.js`](https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql/package.json#L175), which is a variant of `index.js`, but without the dependency injection. This simply makes sure that when webpacking/browserifying, that no dependency injection is done (and Components.js is not included in the browser build). No minification and transpiling is done at this point.

When running the browser script, a single minified+transpiled bundle is generated into `comunica-browser.js`. Any performance issues should only occur at this point.

It should be possible to ignore the browser script and just use your own webpack config to create your browser build, and this _should_ work right out-of-the-box with comunica.

**Comment by rubensworks** [comment]
@RubenVerborgh I assume this can be closed?

**Comment by RubenVerborgh** [comment]
Yes, thanks.
