### ISSUE TITLE
When are we using Requester-browser.js and when ActorHttpNodeFetch?

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#313]
#### Issue type:

- :question: Question

____
#### Question:

I was looking at the ActorHttpNodeFetch code, where `fetch` is used, but inside the browser `Requester-browser.js` with good old `XmlHttpRequest` is also used still. When is which used and why?

(This as part of my search process to create a module that uses `solid.auth.fetch` instead of regular `window.fetch`.)

**Comment by RubenVerborgh** [comment]
`fetch` is slower? Interesting, I can't imagine why.

In any case, `Requester-browser.js` does more than just `fetch`, it also solves a Memento -related performance issue. But maybe it is worthwhile to replace `Requester` by `fetch`, and have a browser version of `fetch` doing the Memento stuff.

**Comment by rubensworks** [comment]
> have a browser version of fetch doing the Memento stuff.

Indeed, there's some other stuff in there as well. I wasn't aware of that. We should indeed port this to the fetch version as well.

> But maybe it is worthwhile to replace Requester by fetch

I would keep `actor-http-native` fully `fetch`-free. I can imagine cases where people don't want any `fetch` usages at all, for example when old browsers are targeted. (or performance issues like we had before)

**Comment by RubenVerborgh** [comment]
> for example when old browsers are targeted

I can't imagine us targeting browsers without `fetch`.

> (or performance issues like we had before)

That would be a problem.

I'll create a browser version of the fetch thing.

**Comment by rubensworks** [comment]
> I can't imagine us targeting browsers without fetch.

Not us indeed, but our target audience should be bigger than just us :-)

> I'll create a browser version of the fetch thing.

👍 

Note that our usage of `isomorphic-fetch` automatically handles the usage of `fetch` for browsers when used outside of Node. So any additional logic should be added in `ActorHttpNodeFetch` directly.

**Comment by RubenVerborgh** [comment]
I created #316 so we can see whether `fetch` is the way to go. If it is, I can port this stuff to `fetch`.

> So any additional logic should be added in ActorHttpNodeFetch directly.

Not really, because the Memento logic only applies to browsers.
