### ISSUE TITLE
Unexpected behavior when querying 1 file

### ISSUE THREAD

**Issue by pietercolpaert** [comunica/comunica#343]
#### Issue type:

- :bug: Bug

____
#### Description:

Further debugging will be needed to understand what the issue is exactly. This query sometimes gives no results, and sometimes after a long time a couple of results:

http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fsmart.flanders.be%2Fdata%2Fteam-scheire-c-me.geojson&query=PREFIX%20as%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Factivitystreams%23%3E%0ASELECT%20%3Ftype%20%3Flongitude%20%3Flatitude%20%3Fprecision%20%3Ftime%20WHERE%20%7B%0A%20%20graph%20%3Fg%20%7B%20%0A%20%20%20%20%3Chttps%3A%2F%2Fsmart.flanders.be%2Fdata%2Fteam-scheire-c-me.geojson%231536916797%3E%20a%20%3Ftype%20%3B%0A%20%09as%3Aobject%20%3Fobj%20.%0A%20%20%20%20%3Fobj%20as%3Alongitude%20%3Flongitude%20%3B%20%0A%20%20%20%20%20%20%20%20as%3Alatitude%20%3Flatitude%20%3B%0A%20%20%20%20%20%20%20%20as%3Aradius%20%3Fprecision%20%3B%0A%09%20%20%20%20as%3Apublished%20%3Ftime%20.%0A%20%20%20%20%20%20%20%7D%0A%7D

Nevertheless, this is just 1 Linked Data file over which a SPARQL query needs to be answered

**Comment by rubensworks** [comment]
For reference, this part of the query _does_ work for some reason: http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fsmart.flanders.be%2Fdata%2Fteam-scheire-c-me.geojson&query=PREFIX%20as%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Factivitystreams%23%3E%0ASELECT%20*%20WHERE%20%7B%0A%20%20graph%20%3Fg%20%7B%20%0A%20%20%20%20%3Chttps%3A%2F%2Fsmart.flanders.be%2Fdata%2Fteam-scheire-c-me.geojson%231536916797%3E%20a%20%3Ftype%20%3B%0A%20%09%09as%3Aobject%20%5B%0A%20%20%20%20%20%20%20%20%09as%3Alongitude%20%3Flongitude%0A%20%20%20%20%09%5D.%0A%20%20%20%7D%0A%7D

**Comment by pietercolpaert** [comment]
Possibly a problem with resolution of multiple QPFs of blank nodes?

**Comment by rubensworks** [comment]
Possibly. As far as I know we don't have any example queries with multiple outgoing paths from single bnodes.

**Comment by pietercolpaert** [comment]
Also the fact that we use multiple graphs (because of the JSON-LD/GeoJSON hybrid) might be the culprit here.

**Comment by rubensworks** [comment]
I did some further debugging, and it looks like there were some problems with the query.

1. Incorrect `as:` prefix. The query used `http`, while the data uses `https`.
2. `as:published` predicate exists on the Like, not the object.

So this one works:
http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fsmart.flanders.be%2Fdata%2Fteam-scheire-c-me.geojson&query=PREFIX%20as%3A%20%3Chttps%3A%2F%2Fwww.w3.org%2Fns%2Factivitystreams%23%3E%0ASELECT%20%3Ftype%20%3Flongitude%20%3Flatitude%20%3Fprecision%20%3Ftime%20WHERE%20%7B%0A%20%20graph%20%3Fg%20%7B%20%0A%20%20%20%20%3Chttps%3A%2F%2Fsmart.flanders.be%2Fdata%2Fteam-scheire-c-me.geojson%231536916797%3E%20a%20%3Ftype%20%3B%0A%20%09as%3Aobject%20%3Fobj%20%3B%0A%20%20%20%20as%3Apublished%20%3Ftime%20.%0A%20%20%20%20%3Fobj%20as%3Alongitude%20%3Flongitude%20%3B%20%0A%20%20%20%20%20%20%20%20as%3Alatitude%20%3Flatitude%20%3B%0A%20%20%20%20%20%20%20%20as%3Aradius%20%3Fprecision%20.%0A%20%20%20%20%20%20%20%7D%0A%7D

There is still something wrong though, as the query produces the same result continuously. (A `LIMIT 1` should fix it for now)

**Comment by rubensworks** [comment]
Following up on this remaining issue in #354.

**Comment by rubensworks** [comment]
@pietercolpaert The above query works now as intended in release 1.4.6 🎉
