### ISSUE TITLE
Metadata extracting: extract from URL of current page

### ISSUE THREAD

**Issue by pietercolpaert** [comunica/comunica#345]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

Currently, comunica does not extract metadata that is linked to the response document’s URL.

Feature request to check for:
 * The URL in the document after redirect
 * The URL in the Content-Location header
 * The requested URL

The URL can then be linked to a broader dataset concept via predicates such as: void:subset, dcterms:isPartOf, dcterms:isVersionOf, dcterms:isFormatOf, dcterms:hasFormat, dcterms:hasVersion, dcterms:hasPart, foaf:primaryTopic, foaf:primaryTopicOf.

#### Test case

https://graph.irail.be/sncb/connections

The metadata controls are not extracted correctly in this case. The design pattern that’s used here is as follows:

```turtle
<current_page_url> hydra:next <next_page>
```

**Comment by rubensworks** [comment]
This should be working now with #473.
Please let me know if there are any problems with it.
