### ISSUE TITLE
Query execution doesn't stop on error

### ISSUE THREAD

**Issue by bencomp** [comunica/comunica#351]
When I execute the query

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?subj ?prop ?obj ?class
WHERE {
  ?prop a rdf:Property;
        rdfs:range skos:Concept.
  ?subj ?prop ?obj .
  OPTIONAL { ?obj a ?class . }
  # FILTER (?class != skos:Concept)
}
```
in the [LDF client](http://query.linkeddatafragments.org/) using the LOV and DBpedia 2016-04 datasets, I get an error `Error: Unexpected "<http://securitytoolbox.appspot.com/MASO#Antivirus" on line 126.`. At the same time the 'Stop execution' button becomes a 'Execute query' button again, but the query log (and my laptop fan) suggest the query is still running. I think an error result should stop the query too.

**Comment by rubensworks** [comment]
Thanks for reporting!

This looks like a parsing error in a certain document.

Note to self:
1. Improve the error message, so that it includes the offending document.
2. See if this is an actual problem with the document, or if something is wrong on our end.

**Comment by rubensworks** [comment]
All of the problems above should be fixed now.
