### ISSUE TITLE
Scope blank nodes to original sources when federating

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#355]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

If we are federating over two sources (A and B), and a query over A produces a blank node, then this blank node should _not_ be matched in other sources (B), but only in itself (A).

Concretely, the federated actor should:
* skolemize all incoming blank nodes deterministically (the source identifier should be encoded in this as well),
* de-skolemize blank nodes when creating new sub-queries to sources.
* If a blank node appears in a pattern that originates from a different source than the target source, then an `EmptyIterator` should be returned, as this blank node should not be matched in the target source.

**Comment by RubenVerborgh** [comment]
> If we are federating over two sources (A and B), and a query over A produces a blank node, then this blank node should _not_ be matched in other sources (B), but only in itself (A).

Do we have a reference/citation for that?
Is this the only possible/valid semantics, or would we need a switch between one semantics and the other?

**Comment by rubensworks** [comment]
From Linked Data Management from Andreas Harth:

> Blank nodes cannot be referenced outside of their originating scope (e.g., an RDF document). The labels for blank nodes are thus only significant within a local scope.

I think it's safe to consider a source as such a local scope.

**Comment by RubenVerborgh** [comment]
Agreed, misunderstood the initial statement. Fine with it, no need to make it configurable.
