### ISSUE TITLE
Queries in browser fail due to CORS changes

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#373]
#### Issue type:

- :bug: Bug

____
#### Description:

As of recently, no queries work anymore in Chrome browsers: http://query.linkeddatafragments.org/

> Access to XMLHttpRequest at 'http://fragments.dbpedia.org/2016-04/en' from origin 'http://query.linkeddatafragments.org' has been blocked by CORS policy: Request header field accept is not allowed by Access-Control-Allow-Headers in preflight response.

It appears that only HEAD requests fail.

**Comment by rubensworks** [comment]
The root cause of this problem is Server.js that does not expose the proper fields.

This can be fixed by setting the following in your LDF server config file:
```json
  "response": {
    "headers": {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Headers": "Accept-Datetime,Accept",
      "Access-Control-Expose-Headers": "Content-Location,Link,Memento-Datetime"
    }
  },
```

The addition of `Accept` in the `Access-Control-Allow-Headers` header is important here.

Will make a PR soon to https://github.com/LinkedDataFragments/Server.js/

**Comment by pietercolpaert** [comment]
Apparently it’s because our Accept header is too long. See https://fetch.spec.whatwg.org/#cors-unsafe-request-header-byte

Test case in browser console:
```javascript
// Test 1: works
fetch('https://graph.irail.be/sncb/connections?departureTime=2019-01-27', {headers: new Headers({accept: "application/ld+json"})}).then(async (response)=> { console.log(await response.json())});
// Test 2: fails
fetch('https://graph.irail.be/sncb/connections?departureTime=2019-01-27', {headers: new Headers({accept: "application/trig;q=1.0,application/n-quads;q=0.7,text/turtle;q=0.6,application/n-triples;q=0.3,application/ld+json;q=0.3,text/n3;q=0.2"})}).then(async (response)=> { console.log(await response.json())});
```

**Comment by rubensworks** [comment]
@pietercolpaert Changing the `Access-Control-Allow-Headers` server-side doesn't fix it for you?

**Comment by pietercolpaert** [comment]
My server does not do content negotiation, so why would I have to explicitly allow the accept header? Something that according to the Mozilla docs is a simple header and is always allowed: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers#Directives
