### ISSUE TITLE
Support SPARQL operations

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#39]
The following operations should be supported (assuming the SPARQL algebra types):

* [X] BGP
* [x] Construct
* [x] Describe
* [x] Distinct (sha1 hash-based)
* [x] Graph (not required if sparqlalgebrajs gets called with quad option)
* [x] Join
* [x] Leftjoin (has expression parameter, but can be implemented by calling Filter implementation)
* [X] Pattern
* [X] Project
* [x] Slice
* [x] Union
* [x] Ask

Dependent on Expression implementation:

* [x] Filter
* [x] Orderby
* [x] Expression

Dependent on Expression implementation, but not supported in the current client:

* [x] Aggregate
* [x] Extend
* [x] Group

Not supported in current LDF client (so should not supported right away):

* [x] Reduced
* [x] Values
* [x] Minus

Path-related operators. Not supported in current LDF client (so should not supported right away):

* [x] Alt
* [x] Inv
* [x] Link
* [x] Nps
* [x] OneOrMorePath
* [x] Path
* [x] Seq
* [x] ZeroOrMorePath
* [x] ZeroOrOnePath

**Comment by rubensworks** [comment]
@joachimvh Do you know if _ Expression_ can be checked of as well now?

**Comment by joachimvh** [comment]
No, since we don't fully support all expressions (e.g. aggregations). But neither does TPF. It's just a weird one to place since it's not a specific Operation but a subclass of operations. But we support all Expressions currently supported by TPF afaik

**Comment by rubensworks** [comment]
Ok, good enough for now.

**Comment by rubensworks** [comment]
At the moment, the remaining operators that need support are mainly related to path expressions. We should add support for that in 1.2.0

**Comment by rubensworks** [comment]
At the moment, the only remaining operations are expressions (with aggregrates, extend and group), reduced (trivial) and minus (trivial).

**Comment by rubensworks** [comment]
As of 3c99d91405df107cf7e4c49fc8bdf60b3c7f4600, we do automatic SPARQL (query) compliance testing. Once we pass all tests, then this issue can be closed.

(Note: you can now run `yarn run spec` in `packages/actor-init-sparql` to check compliance. See https://github.com/rubensworks/rdf-test-suite.js for more information on how to run.)

**Comment by rubensworks** [comment]
See #287 for all remaining SPARQL test suite failures.

**Comment by rubensworks** [comment]
All operations are now supported. Their spec-compliance will be tested in #287.
