### ISSUE TITLE
An auto-fast discovery mode

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#392]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

The current `auto` discovery mode requires an extra request. I'm sure there's a good reason for that, and that it cannot be eliminated.

However, we might want an additional `auto-fast` discovery method, which only autodiscovers those interfaces that do not involve an additional request.

**Comment by rubensworks** [comment]
Related to #338.

**Comment by rubensworks** [comment]
Implemented in #473.
