### ISSUE TITLE
comunica-compile-config should return an error code on failure

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#394]
#### Issue type:

- :bug: Bug

____
#### Description:

comunica-compile-config seems to return 0 even if it fails
____

**Comment by rubensworks** [comment]
Note to self: this problem also exists here: https://github.com/LinkedSoftwareDependencies/Components.js/blob/master/bin/compile-config.ts

**Comment by RubenVerborgh** [comment]
Thx, excellent!
