### ISSUE TITLE
Federated query outputs no results

### ISSUE THREAD

**Issue by vj-github** [comunica/comunica#395]
#### Issue type:

- :bug: Bug

____
#### Description:

Launching a federated query outputs no results although there are finite results.

E.g.: 
Sources:
https://www.ebi.ac.uk/rdf/services/sparql
https://sparql.uniprot.org/sparql
Query:
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX core: <http://purl.uniprot.org/core/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ensembl: <http://rdf.ebi.ac.uk/resource/ensembl/>
PREFIX ensemblterms: <http://rdf.ebi.ac.uk/terms/ensembl/>
SELECT ?uniprot_id ?uniprot_uri ?isoform ?seq {
	ensembl:ENSG00000128573 ensemblterms:DEPENDENT ?uniprot_uri .
	?uniprot_uri dc:identifier ?uniprot_id .
	?uniprot_uri core:sequence ?isoform .
	?isoform rdf:value ?seq . 
}

However launching the same query with SERVICE clause works. E.g.,
comunica-sparql https://www.ebi.ac.uk/rdf/services/sparql -f example.txt

example.txt:
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX core: <http://purl.uniprot.org/core/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ensembl: <http://rdf.ebi.ac.uk/resource/ensembl/>
PREFIX ensemblterms: <http://rdf.ebi.ac.uk/terms/ensembl/>
SELECT ?uniprot_id ?uniprot_uri ?isoform ?seq {
	ensembl:ENSG00000128573 ensemblterms:DEPENDENT ?uniprot_uri .
	?uniprot_uri dc:identifier ?uniprot_id .
	SERVICE <http://sparql.uniprot.org/sparql> {
		?uniprot_uri core:sequence ?isoform .
		?isoform rdf:value ?seq . 
	} 
}

The same no-results-issue is also observed for the example in https://gist.github.com/rubensworks/34bb69fa6c83176bce60a5e8a25051e8
____
#### Environment:
| software            | version 
| ------------------- | -------
| Comunica Init Actor | 1.5.4
| node                | v10.15.1
| npm                 | 6.4.1
| yarn                | 1.13.0
| Operating System    | win32 (Windows_NT 10.0.17763) 

and 

| software            | version 
| Comunica Init Actor | 1.5.4                        
| node                | v8.10.0                        
| npm                 | 3.5.2              
| yarn                | _Yarn is unavailable_        
| Operating System    | linux (Linux 4.4.0-17763-Microsoft)

**Comment by rubensworks** [comment]
Thanks for reporting! I suspect this has something to do with SPARQL endpoints specifically. To be investigated.

**Comment by rubensworks** [comment]
Fixed in 2ebef4328a912fdcfaafbd11a667fb89977b8768.
