### ISSUE TITLE
Remove lodash dependencies

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#402]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

Our `lodash` dependencies are taking up a huge chunk of our webpacked bundle size. We are not using them extensively, so we should remove them, and implement their functionality ourselves.

**Comment by rubensworks** [comment]
@joachimvh For reference, sparqlalgebra.js also has a lodash dependency.

**Comment by joachimvh** [comment]
The lodash dependency in sparqlalgebra.js should be removed.
