### ISSUE TITLE
Commit hook for checking consistent comunica dependencies

### ISSUE THREAD

**Issue by wschella** [comunica/comunica#406]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

With 100+ packages, it's somewhat impossible to guarantee consistency manually of package dependencies between comunica packages themselves. E.g. depending on @comunica/core v1.4.0 in one package, while master is already v1.6.0. This mostly is an issue while working on branches.

But it could also be useful to easily check on consistent use of the same version of external packages.

It could also be used to verify component.js configs.

These should all not necessarily be hard failures, but warnings would be nice.

**Comment by rubensworks** [comment]
What problem are you encountering exactly?

Lerna should automatically update _all_ internal versions when a new release is being done. Inconsistent dependency versions for comunica packages that have not been released yet should not be an issue, since those are linked internally in the monorepo.

**Comment by wschella** [comment]
Oh, I was unaware of lerna guaranteeing consistency upon release. NVM then :)
