### ISSUE TITLE
Simple one-triple query fails

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#412]
#### Issue type:

- :bug: Bug

____
#### Description:

```sparql
SELECT *
WHERE {
  ?pub a <http://schema.org/PublicationVolume>
}
```

[Fails on Comunica](http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fruben.verborgh.org%2Fprofile%2F%23me&query=SELECT%20*%0AWHERE%20%7B%0A%20%20%3Fpub%20a%20%3Chttp%3A%2F%2Fschema.org%2FPublicationVolume%3E%0A%7D) (no results), works on [Client.js](http://query.verborgh.org/#transientDatasources=https%3A%2F%2Fdata.verborgh.org%2Fruben&query=SELECT%20*%0AWHERE%20%7B%0A%20%20%3Fpub%20a%20%3Chttp%3A%2F%2Fschema.org%2FPublicationVolume%3E%0A%7D).

**Comment by rubensworks** [comment]
Ah, but you're querying two different things here:
* Client.js queries https://data.verborgh.org/ruben
* Comunica queries https://ruben.verborgh.org/profile/

Setting your TPF source on Comunica works: http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fdata.verborgh.org%2Fruben&query=SELECT%20*%0AWHERE%20%7B%0A%20%20%3Fpub%20a%20%3Chttp%3A%2F%2Fschema.org%2FPublicationVolume%3E%0A%7D

**Comment by RubenVerborgh** [comment]
Okay that was easy 🙂
Minor nit: Comunica keeps on sending 3 HTTP requests every time I try the query. Shouldn't it cache?

**Comment by rubensworks** [comment]
> Minor nit: Comunica keeps on sending 3 HTTP requests every time I try the query. Shouldn't it cache?

Yep, we should look into this at some point, see #281.
