### ISSUE TITLE
Metadata trigger of the QPF actor too greedy

### ISSUE THREAD

**Issue by pietercolpaert** [comunica/comunica#415]
#### Issue type:

- :bug: Bug

____
#### Description:

From the moment a hydra:search is given, the QPF actor is triggered and tries to extract a valid search form according to the TPF spec. However, it is perfectly possible that a search form is given that is unknown to Comunica until now, and should just be ignored if no actor can make use of this.

Test cases: 
 * https://graph.irail.be/sncb/connections
 * https://linked.open.gent/parking?page=2019-03-05T16:00:00

I tried to link this back to a line of code but got a bit lost for the time being.
____
#### Environment:

```
~/Projects/comunica/packages/actor-init-sparql$ ./bin/query.js -v
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.6.3 (dev)
| node                | v8.10.0
| npm                 | 3.5.2
| yarn                | 1.13.0
| Operating System    | linux (Linux 4.15.0-45-generic)
```

#### Crash log:

```
[Error: No Hydra search forms were discovered in the metadata of https://linked.open.gent/parking?page=2019-03-05T10:00:00. You may be missing an actor that extracts this metadata
    at ActorRdfResolveQuadPatternHypermedia.chooseForm (~/Projects/comunica/packages/actor-rdf-resolve-quad-pattern-hypermedia/lib/ActorRdfResolveQuadPatternHypermedia.js:36:19)
```

**Comment by rubensworks** [comment]
Right, we plan on rewriting the heuristical source identification mechanism to solve these problems, see #338.

For now, you can solve this by manually using the `file` source type. (On the CLI, this is done by defining the source as `file@https://graph.irail.be/sncb/connections`)

Closing this in favor of #338.

**Comment by pietercolpaert** [comment]
Aha! Thanks for the clarification and link to the right issue!
