### ISSUE TITLE
Uncaught (in promise) Error: Parse error (macOS)

### ISSUE THREAD

**Issue by alabrazi** [comunica/comunica#425]
#### Issue type:

- :bug: Bug

____
#### Description:
Trying to run the example code:
```
const myEngine=Comunica.newEngine()
const context = {
  sources: [ { type: 'hypermedia', value: 'http://fragments.dbpedia.org/2016-04/en' } ],
  queryFormat: 'graphql',
  "@context": {
    "label": { "@id": "http://www.w3.org/2000/01/rdf-schema#label", "@singular": true },
    "label_en": { "@id": "http://www.w3.org/2000/01/rdf-schema#label", "@language": "en" },
    "writer": { "@id": "http://dbpedia.org/ontology/writer", "@singular": true },
    "artist": { "@id": "http://dbpedia.org/ontology/musicalArtist", "@singular": true },
    "artist_label": { "@singular": true }
  }
};
myEngine.query('{ label writer(label_en: \"Michael Jackson\") artist { label } }',context)
  .then(function (result) { return bindingsStreamToGraphQl(result.bindingsStream, context); })
  .then(console.log);
```

____
#### Environment:
<img width="280" alt="Screenshot 2019-03-15 at 9 26 08" src="https://user-images.githubusercontent.com/7549404/54416768-ffe4b580-4708-11e9-87b9-be61a78c700b.png">
npm packages installed:
  "dependencies": {
    "@babel/runtime": "^7.1.5",
    "@comunica/actor-init-sparql": "^1.6.4",
    "@comunica/actor-sparql-serialize-tree": "^1.6.3",
    "graphql-to-sparql": "^1.5.0",
    "meteor-node-stubs": "^0.4.1",
    "node-gyp": "^3.8.0",
    "rdf-canonize": "^1.0.3",
    "react": "^16.5.0",
    "react-dom": "^16.5.0"
  },

#### Crash log:
https://pastebin.com/ib2V9pMa

**Comment by rubensworks** [comment]
That's weird, it looks like Comunica is parsing the query as SPARQL, while the query format seems to be properly set.

@pheyvaer Since you are using this functionality as well, do you see anything that is going wrong here?

**Comment by pheyvaer** [comment]
No, should work. I haven't had any similar problems before.

**Comment by rubensworks** [comment]
Just had another look at the stacktrace, and it looks like your were running the browser version of actor-init-sparql-rdfjs on version 1.1.2.
Is this intentional @alabrazi? Or did you intend to run via Node.JS?

If you're running in the browser, make sure you use the latest Comunica version (1.6.4).

**Comment by alabrazi** [comment]
@rubensworks 
> Is this intentional @alabrazi? Or did you intend to run via Node.JS?
yes I want to test the  browser library and Node.js one. So far it is not working either way.
changing the version of Comunica to 1.6.4 give the following error:
```
sax.js:1512 Uncaught (in promise) Error
(anonymous) @ sax.js:1512
(anonymous) @ meteor.js?hash=33066830ab46d87e2b249d2780805545e40ce9ba:1223
Promise.then (async)
Promise.then @ promise.js?hash=bba24d028d5028a8e661347ee54d0a72dbdd5967:132
(anonymous) @ main.jsx:30
maybeReady @ meteor.js?hash=33066830ab46d87e2b249d2780805545e40ce9ba:927
loadingCompleted @ meteor.js?hash=33066830ab46d87e2b249d2780805545e40ce9ba:939
```

**Comment by rubensworks** [comment]
@alabrazi Can you provide more information? I.e., what are you trying to do exactly?

**Comment by alabrazi** [comment]
@rubensworks  I am using meteor 1.8 and trying to test a simple query example that is shown in Comunica tutorial . Simply to make it work for now.

I have an issue that is causing errors. I am not able to retrieve the result of the query. 
What I may do later in my project is to query RDFs using GraphQL

**Comment by rubensworks** [comment]
It looks like your were running the browser version of actor-init-sparql-rdfjs on version 1.1.2.
Can you try using the latest version instead? (1.6.4)

**Comment by rubensworks** [comment]
Considering this resolved. Please open an issue if this would not be the case.
