### ISSUE TITLE
SPARQL Update

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#435]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

At the moment, we only support read-only queries.
In the future, we should also add support for [update queries](https://www.w3.org/TR/sparql11-update/).

**Comment by ColinMaudry** [comment]
Obviously that would not work with all data sources, such as HDT that inherently read-only, right? For triplestores and files, that would be useful.

**Comment by rubensworks** [comment]
Indeed, updates would only be possible at specific source types. We'd probably start with supporting remote files via HTTP POST/PATCH/PUT/DELETE, and delegation to remote SPARQL endpoints.

**Comment by jeswr** [comment]
I'm wondering if there is some kind of time frame on having this feature - it would be quite beneficial in some applications that I am currently working on. Specifically, I am looking to be able to update data over SPARQL endpoints, and to update local files written with Turtle syntax.

I'm happy to contribute to the development of this feature if you can point me to what exactly needs to be done.

**Comment by rubensworks** [comment]
We've started update support in this branch: https://github.com/comunica/comunica/tree/feature/update
It's on hold atm due to more urgent work.
But the plan is to get the basics of update supports ready somewhere in the next couple of months.

Update support will probably not be complete in the first version. So once we have this first basis version available, any help do get full update support is definitely welcome!

**Comment by jeswr** [comment]
Oh great! I'll check out that branch.

**Comment by rubensworks** [comment]
Side-note: it's not in a usable state at the moment, so don't get your hopes up too much 😄

**Comment by jeswr** [comment]
No rush in responding to this - I know you guys are busy and I have plenty else to work on ATM as well.

I've started to try and do some work on this branch - can I just confirm that the `mediatorUpdateQuads` as seen here https://github.com/comunica/comunica/blob/ba6d3c711dbc9d6f93f7dfa53e2c656f25b8ab32/packages/actor-query-operation-update-deleteinsert/lib/ActorQueryOperationUpdateDeleteInsert.ts#L41-L46 (which is yet to be implemented) is intended to be used to mediate with the actors performing insert/delete operations (as opposed to modifying the existing `queryOperation` actors).

I noticed that the `mediatorQueryOperation` also occurs earlier in the file but as far as I can tell you intend for this to be used for a select or construct query so as to establish exactly which triples need to be inserted/deleted - is this correct?

**Comment by rubensworks** [comment]
> can I just confirm that the mediatorUpdateQuads as seen here (which is yet to be implemented) is intended to be used to mediate with the actors performing insert/delete operations (as opposed to modifying the existing queryOperation actors).

Indeed, that's the idea at the moment. There will probably be a `rdf-update-quads` bus, which can handle updates against different target types, such as local files, HTTP/LDP servers, SPARQL endpoints, ...

> I noticed that the mediatorQueryOperation also occurs earlier in the file but as far as I can tell you intend for this to be used for a select or construct query so as to establish exactly which triples need to be inserted/deleted - is this correct?

Also correct. some UPDATE queries may first select data from sources.
The idea is that Comunica will retrieve data from _sources_, and store data into _targets_. In most cases, source and target will be the same though, which is most valuable for update queries.

**Comment by jeswr** [comment]
I am the majority of the way through implementing this now (https://github.com/jeswr/comunica/tree/feature/update-j). Just regarding the HTTP/LDP servers; is there a package equivalent to `fetch-sparql-endpoint` that I can use to handle requests with them? Otherwise I'll just have to leave the actor that handles that format out of the branch I am working on (due to my lack of time currently).

**Comment by rubensworks** [comment]
@jeswr Good to see you're making progress!
However, It looks like your implementation does not fully align to what I had in mind architecturally (especially regarding stream joining).
Just FYI, as I said [above](https://github.com/comunica/comunica/issues/435#issuecomment-720075335), it might be safer to await further implementation until I finish a rough basis (in which the main architectural components are in place).
But of course, feel free to continue your work in the meantime if this is urgent for your use case. There may be some parts we could cherry-pick aftwards.

> Just regarding the HTTP/LDP servers; is there a package equivalent to fetch-sparql-endpoint that I can use to handle requests?

Not that I'm aware of. We'll likely have to implement this ourselves.

**Comment by jeswr** [comment]
> However, It looks like your implementation does not fully align to what I had in mind architecturally (especially regarding stream joining).

Makes sense; it seemed a bit off when I was writing it and I don't think I am making best use of the available APIs in the packages you guys have written.

For what we are doing at the moment a it doesn't need to be overly stable so I will do some quick fixes to get that branch to a 'just working' point over the weekend and leave it at that.
