### ISSUE TITLE
Accept header in the browser should be less than 128 chars

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#439]
#### Issue type:

- :bug: Bug

____
#### Description:

Accept headers of 128 chars and longer causes issues in the browser, because CORS is broken.
(Also, the current CORS header contains a weird `0.09000000000000001` value.)

I suggest to simply throw in the towel and shorten our headers. Even though a correct server configuration fixes things, it still brings the overhead of an extra OPTIONS request for no good reason.

**Comment by rubensworks** [comment]
I don't like it, but we don't really have a choice, the WHATWG gods have spoken...
Let's hope a proper resolution is found in the future.

For reference, this will fix #373 

## Proposal for fix:

I would _only_ apply this change when a browser environment is detected. Node.js environments don't do CORS, so this is not something we should change there.

Our supported media types are already sorted by priority.
We should make the accept string as long as possible (<128 chars) based on the media types we have.

> Also, the current CORS header contains a weird 0.09000000000000001 value.

This floating point issue should also be fixed to save some bytes :-)

**Comment by RubenVerborgh** [comment]
@pietercolpaert has a 127-char header in his fetch library, but the difference here is of course that ours is dynamic. There might be some short wins (no space after comma), but I don't see many (not allowed to drop leading zero. Anything more than 3 significant digits seems to be an error BTW.
We might just need to sort them by q-value, and drop the lowest ones until it fits.
