### ISSUE TITLE
\uXXXX should be allowed in SPARQL prefixed names

### ISSUE THREAD

**Issue by cygri** [comunica/comunica#440]
#### Issue type:

- :bug: Bug

____
#### Description:
Communica rejects the following SPARQL query as a syntax error due to the `\u0078` codepoint escape sequence in a prefixed name:
```
PREFIX : <http://example.org/>
SELECT (ex:e\u0078ample AS ?x) {}
```
In SPARQL, “codepoint escape sequences can appear anywhere in the query string” as long as the escaped character is allowed at that point. [Link](https://www.w3.org/TR/sparql11-query/#codepointEscape)

While Communica disagrees with the SPARQL spec here, its behaviour is consistent with the Turtle spec, where numeric escapes are only allowed in string literals. This difference between SPARQL and Turtle is somewhat controversial. Arguably, both specs should say the same thing. And arguably, the Turtle spec makes more sense here. Nevertheless, I wanted to put this disagreement with the spec on the record.
____
#### Environment:
Whatever version runs behind the SPARQL form at http://query.linkeddatafragments.org as of today

**Comment by rubensworks** [comment]
Thanks for reporting this @cygri!

As we use [SPARQL.js](https://github.com/RubenVerborgh/SPARQL.js) for parsing SPARQL queries, this is something that should be fixed there. @RubenVerborgh I'm not that familiar with the internals of SPARQL.js, but do you think such escaped characters would fit into the parser?

**Comment by cygri** [comment]
@rubensworks @RubenVerborgh Before you spend too much time on this, just a heads-up that I'm planning to raise an issue on numeric character escapes in the SPARQL 1.2 CG, and a possible outcome of that issue would be that SPARQL aligns more with Turtle. In that case, the current behaviour of SPARQL.js would already be correct. So maybe just wait and see.

**Comment by rubensworks** [comment]
Sounds good, putting this on hold then.

**Comment by cygri** [comment]
This is related to w3c/sparql-12#77 where I show that Comunica is not alone in following the Turtle spec rather than the SPARQL spec on character escapes, and I argue that Comunica's behaviour is better than what the SPARQL spec currently says.

**Comment by rubensworks** [comment]
Related to https://github.com/RubenVerborgh/SPARQL.js/issues/126

**Comment by rubensworks** [comment]
Closing this issue as wont-fix.
