### ISSUE TITLE
Fixed triples in CONSTRUCT template do not work

### ISSUE THREAD

**Issue by cygri** [comunica/comunica#448]
#### Issue type:

- :bug: Bug

____
#### Description:
This query should produce one triple:
```sparql
PREFIX : <urn:example:>
CONSTRUCT { :s :p :o }
WHERE {}
```
There is one solution (the empty solution), so the template should be instantiated once, producing one triple.

But Comunica returns an empty graph.

The problem appears to be that the triple is completely fixed, that is, contains no variables. This similar query works:
```sparql
PREFIX : <urn:example:>
CONSTRUCT { :s :p ?o }
WHERE { BIND (:o AS ?o) }
```
____
#### Environment:
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.7.0 
| node                | v11.9.0
| npm                 | 6.9.0
| yarn                | _Yarn is unavailable_
| Operating System    | darwin (Darwin 18.5.0)

**Comment by rubensworks** [comment]
One empty solution should be returned for empty WHERE clauses, so something is probably going wrong in the CONSTRUCT actor. I'll look into it soon.
