### ISSUE TITLE
Blank nodes in CONSTRUCT template do not work

### ISSUE THREAD

**Issue by cygri** [comunica/comunica#449]
#### Issue type:

- :bug: Bug

____
#### Description:
This query should produce one triple:
```sparql
PREFIX : <urn:example:>
CONSTRUCT { _:s :p ?o }
WHERE { BIND (:o AS ?o) }
```
But it produces an empty graph.

The problem appears to be the blank node in the subject position of the `CONSTRUCT` template. If it is changed to `:s`, the query works.
____
#### Environment:
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.7.0 
| node                | v11.9.0
| npm                 | 6.9.0
| yarn                | _Yarn is unavailable_
| Operating System    | darwin (Darwin 18.5.0)

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
