### ISSUE TITLE
Support for IRI() and bNode()

### ISSUE THREAD

**Issue by cygri** [comunica/comunica#450]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:
I would like to see the following functions supported:

- [`IRI()`/`URI()`](https://www.w3.org/TR/sparql11-query/#func-iri)
- [`bNode()`](https://www.w3.org/TR/sparql11-query/#func-bnode) (the no-argument form only; the one-argument form is incoherent as described in the spec, and implemented inconsistently in other systems)

Both functions are important when doing data integration with `CONSTRUCT`.

**Comment by rubensworks** [comment]
@wschella is working on implementing this, so this is definitely coming soon! :-)
(These are some of the few functions that have yet to be implemented to achieve full query spec compliance: #287)
