### ISSUE TITLE
Base IRI is not respected for spec tests

### ISSUE THREAD

**Issue by wschella** [comunica/comunica#456]
#### Issue type:

- :bug: Bug

____
#### Description:

The spec tests `yarn run spec-file iri` because the `baseIRI` key is not populated in action context . You can confirm this by logging at <https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql/lib/ActorInitSparql-browser.ts#L106>.

____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.7.3 (dev)
| node                | v8.16.0
| npm                 | 6.4.1
| yarn                | 1.16.0
| Operating System    | linux (Linux 4.15.0-48-generic)

**Comment by rubensworks** [comment]
Just tested this in 1.8.0, and this seems to be working properly now.
