### ISSUE TITLE
Expressions within SELECT clauses do not work

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#463]
#### Issue type:

- :bug: Bug

____
#### Description:

The query

~~~
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT ?date (YEAR(?date) AS ?year) {
  ?s dbo:birthDate ?date.
}
~~~

only returns bindings for `?date`, whereas I expect it to return bindings for both `?date` and `?year`. If the expression isn't supported, I at least expect an error or undefined bindings for `?year`.

In contrast, the following does work:

~~~
SELECT ?date (?date AS ?year) {
~~~

____
#### Environment:

http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fruben.verborgh.org%2Fprofile%2F%23me&query=PREFIX%20dbo%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0ASELECT%20%3Fdate%20(YEAR(%3Fdate)%20AS%20%3Fyear)%20%7B%0A%20%20%3Fs%20dbo%3AbirthDate%20%3Fdate.%0A%7D

**Comment by RubenVerborgh** [comment]
On a related note, should `YEAR` already work?
http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fruben.verborgh.org%2Fprofile%2F%23me&query=PREFIX%20dbo%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0ASELECT%20%3Fdate%20%3Fdate%20%7B%0A%20%20%3Fs%20dbo%3AbirthDate%20%3Fdate.%0A%20%20FILTER(YEAR(%3Fdate)%20%3D%201987)%0A%7D

**Comment by rubensworks** [comment]
The web client is not running the latest version yet, I'll have to merge https://github.com/comunica/jQuery-Widget.js/pull/44 for that.

It's possible that this will be fixed in the new version.
If not, then it's probably a problem in sparqlee, because [`YEAR` should be supported already](https://github.com/comunica/sparqlee#spec-compliance).

**Comment by wschella** [comment]
YEAR is specced to only accept xsd:dateTime, while the query returns xsd:date, so the expressions error (causing them to not be bound). The spec allows extending these definitions in an implementation specific way (as to support xsd:date).
