### ISSUE TITLE
Add CORS proxy

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#465]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

Since we've been having some problems with CORS (#439, #373), the jQuery widget is still failing on a lot of sources that don't set CORS headers, and there are problems with loading mixed schemes (HTTP/HTTPS), we should have a proper workaround.

We could do this by simply setting up a proxy server, such as https://corsproxy.github.io/.

It should be possible to pass custom proxies via the config file.

We may consider only using the CORS proxy if requests fail due to CORS.

**Comment by RubenVerborgh** [comment]
> It should be possible to pass custom proxies via the config file.

People can list their preference for a proxy server in their WebID profile. One the one hand, this helps scalability. On the other hand, it helps privacy/trust from the perspective of the user.

**Comment by rubensworks** [comment]
From offline discussion: the proxy should be passable via the context, instead of the config, so that late-binding is possible.

**Comment by RubenVerborgh** [comment]
Maybe there's even different proxies for different sources, etc. I mean, we don't have to make this too complex, but on the interface level, supporting something like `getProxyFor(source, …)` might make sense.

**Comment by rubensworks** [comment]
Hmm, true. Also needed because some sources may not even need proxying, for example when the CORS headers are properly set on the sources (but this is something that we can only know about _after_ the initial request).
