### ISSUE TITLE
@single does not work with actor-init-sparql

### ISSUE THREAD

**Issue by pheyvaer** [comunica/comunica#479]
#### Issue type:

- :bug: Bug

____
#### Description:

`@single` does not work with the data and query given [here](https://github.com/rubensworks/GraphQL-LD.js/issues/5). An array is returned instead of a single value.

____
#### Environment:
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.3.0 
| node                | v11.3.0
| npm                 | 6.4.1
| yarn                | 1.16.0
| Operating System    | linux (Linux 4.15.0-55-generic)

#### Crash log:
N/A

**Comment by rubensworks** [comment]
> Comunica Init Actor | 1.3.0

Are you sure this version is correct? The `@single` functionality was only introduced since 1.9.0.

**Comment by pheyvaer** [comment]
Indeed my terminal referred to an older version. An old/unused bin folder was included in my PATH.
