### ISSUE TITLE
Various small component naming issues

### ISSUE THREAD

**Issue by RobinDeBaets** [comunica/comunica#487]
#### Issue type:

- :bug: There are various small typos and missing keys in `.jsonld` files

____
#### Description:

- `actor-abstract-bindings-hash`
   - `AbstractBindingHash` is defined the typescript file `AbstractBindingsHash`
  - The `requireElement` value of `AbstractBindingHash` is `ActorAbstractBindingsHash`
- `core`
  - Files lacking `requireElement`:
    - `Mediator.jsonld`
    - `Actor.jsonld`
    - `Logger.jsonld`
    - `ActionObserver.jsonld`
- `logger-bunyan`
  - `Stream.jsonld` is missing `requireElement` with value `BunyanStreamProvider`

**Comment by rubensworks** [comment]
Another example showing why validation is needed :-)
