### ISSUE TITLE
graphql-ld-comunica mixed datasources bug

### ISSUE THREAD

**Issue by driesmarzougui** [comunica/comunica#490]
#### Issue type:

- :bug: Bug

____
#### Description:

When using [GraphQL-LD](https://github.com/rubensworks/graphql-ld.js#readme) with both `SPARQL` and `linkeddatafragment` sources,  an error is thrown.

[Example code](https://pastebin.com/QnrELM79)  
[Output](https://pastebin.com/xAJSmtjb)
____
#### Environment:

* graphql-ld: v1.0.0
* graphql-ld-comunica: v1.0.0

**Comment by rubensworks** [comment]
Note to self: related to the 1.9.0 update where slow metadata from SPARQL endpoints cause an error.

**Comment by rubensworks** [comment]
Related to #553.

**Comment by rubensworks** [comment]
Fixed in #733
