### ISSUE TITLE
comunica-sparql CLI differs from jQuery-Widget.js

### ISSUE THREAD

**Issue by ManuDeBuck** [comunica/comunica#492]
#### Issue type:

- :bug: Bug

____
#### Description:

This [query](https://query.linkeddatafragments.org/#transientDatasources=http%3A%2F%2Ffragments.dbpedia.org%2F2016-04%2Fen;https%3A%2F%2Fruben.verborgh.org%2Fprofile%2F&query=SELECT%20%3Fperson%20%3Fdate%0AWHERE%20%7B%0A%20%20ruben%3Ame%20dbpedia-owl%3AbirthPlace%20%3Fplace%3B%0A%20%20%20%20%20%20%20%20%20%20%20dbpedia-owl%3AbirthDate%20%20%3FdateR.%0A%20%20%3Fperson%20%20dbpedia-owl%3AbirthPlace%20%3Fplace%3B%0A%20%20%20%20%20%20%20%20%20%20%20dbpedia-owl%3AbirthDate%20%20%3Fdate.%0A%20%20FILTER(%3Fdate%20%3E%20%3FdateR)%0A%7D) on [query.linkeddataframents.org](query.linkeddatafragments.org) does return several results, but when executing this query:

```
PREFIX ruben: <https://ruben.verborgh.org/profile/> 
SELECT ?person ?date
WHERE {
  ruben:me dbpedia-owl:birthPlace ?place;
           dbpedia-owl:birthDate  ?dateR.
  ?person  dbpedia-owl:birthPlace ?place;
           dbpedia-owl:birthDate  ?date.
  FILTER(?date > ?dateR)
}
```
on the `comunica-sparql` CLI the result is `[]`, which is (I think) unwanted.
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.9.1 
| node                | v10.16.1
| npm                 | 6.9.0
| yarn                | 1.17.3
| Operating System    | linux (Linux 5.0.0-25-generic)

#### Crash log:

None

**Comment by rubensworks** [comment]
The input query was wrong, this one works:
```sparql
PREFIX ruben: <https://ruben.verborgh.org/profile/#> 
SELECT ?person ?date
WHERE {
  ruben:me dbpedia-owl:birthPlace ?place;
           dbpedia-owl:birthDate  ?dateR.
  ?person  dbpedia-owl:birthPlace ?place;
           dbpedia-owl:birthDate  ?date.
  FILTER(?date > ?dateR)
}
```
