### ISSUE TITLE
actor-init-sparql-file example query is broken

### ISSUE THREAD

**Issue by ManuDeBuck** [comunica/comunica#493]
#### Issue type:

- :bug: Bug

____
#### Description:

When executing the example query

```bash
$ comunica-sparql-file https://ruben.verborgh.org/profile/#me "CONSTRUCT WHERE { ?s ?p ?o } LIMIT 100"
```
the program crashes with the following output: [pastebin](https://hastebin.com/cucusarure.rb)
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.9.1 
| node                | v10.16.1
| npm                 | 6.9.0
| yarn                | 1.17.3
| Operating System    | linux (Linux 5.0.0-25-generic)

#### Crash log:

[pastebin](https://hastebin.com/cucusarure.rb)

**Comment by rubensworks** [comment]
Ah, probably a configuration error. Something like 91a9130b241b19a314a3205d28f098c7a3b43a58 should fix this.
