### ISSUE TITLE
Provide engines 

### ISSUE THREAD

**Issue by ManuDeBuck** [comunica/comunica#494]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

Provide engines such as [sparq-engine.js](https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql/spec/sparql-engine.js) for all of the four pre-built engines (Comunica SPARQL engine does already exist).

- [ ] Comunica SPARQL File: Library to query over local RDF files
- [ ] Comunica SPARQL RDFJS: Library to query over in-memory RDFJS-compliant sources.
- [ ] Comunica SPARQL HDT: Library to query over local HDT files

**Comment by rubensworks** [comment]
Started in https://github.com/comunica/comunica/tree/feature/integration, but blocked by https://github.com/comunica/manifest-ldf-tests/issues/2

**Comment by rubensworks** [comment]
Note to self: make new rdf-test-suite-ldf release once this is done.

**Comment by ManuDeBuck** [comment]
> Started in https://github.com/comunica/comunica/tree/feature/integration, but blocked by [comunica/manifest-ldf-tests#2](https://github.com/comunica/manifest-ldf-tests/issues/2)

This issue is now fixed.

**Comment by rubensworks** [comment]
Nearly there...

One open issue with the test manifest before it can be used: https://github.com/comunica/manifest-ldf-tests/issues/3
