### ISSUE TITLE
Add rdf-test-suite-ldf to lerna

### ISSUE THREAD

**Issue by ManuDeBuck** [comunica/comunica#495]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

Add automatically testing of the [manifes-ldf-tests](https://comunica.github.io/manifest-ldf-tests) using [rdf-test-suite-ldf](https://github.com/comunica/rdf-test-suite-ldf.js) to provide integration testing of Comunica.

**Comment by rubensworks** [comment]
Requires #494.

**Comment by rubensworks** [comment]
Done in https://github.com/comunica/comunica/tree/feature/integration and https://github.com/comunica/comunica-actor-init-sparql-hdt/commit/bb67c014d8a1d7057812a613b801cb08e1bb97da
