### ISSUE TITLE
Query with OPTIONAL gives invalid results

### ISSUE THREAD

**Issue by ManuDeBuck** [comunica/comunica#496]
#### Issue type:

- :bug: Bug

____
#### Description:

The query (which you can find [here](http://query.linkeddatafragments.org/#datasources=http%3A%2F%2Fdata.linkeddatafragments.org%2Fgeonames&query=PREFIX%20gn%3A%20%3Chttp%3A%2F%2Fwww.geonames.org%2Fontology%23%3E%0APREFIX%20w3pos%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2003%2F01%2Fgeo%2Fwgs84_pos%23%3E%0ASELECT%20%3FcountryCode%20%3Fpopulation%20WHERE%20%7B%0A%20%20%3Flocation%20gn%3Aname%20%22Belgium%22%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20gn%3AcountryCode%20%3FcountryCode%20.%0A%20%20OPTIONAL%20%7B%20%3Flocation%20gn%3Apopulation%20%3Fpopulation%20.%20%7D%0A%7D) does not give any result for the `?population`-binding. However, it is clear that some of the `?location`(s) do have a `population` defined (cfr. [this resource](http://data.linkeddatafragments.org/geonames?subject=http%3A%2F%2Fsws.geonames.org%2F5245314%2F)). 

As far as I know, I think some of the results should be provided of an (optional) `?population` binding.

____
#### Environment:

The jQuery-Widget.js environment

#### Crash log:

_None_

**Comment by rubensworks** [comment]
Fixed in #632.
