### ISSUE TITLE
Comunica-sparql-file with proxy fails

### ISSUE THREAD

**Issue by ManuDeBuck** [comunica/comunica#497]
#### Issue type:

- :bug: Bug

____
#### Description:

When executing the command

```bash
$ comunica-sparql-file https://ruben.verborgh.org/profile/\#me "CONSTRUCT WHERE { ?s ?p ?o } LIMIT 100" -p http://proxy.linkeddatafragments.org
```
It fails (with exit code 0 (?)) and the following message:

```bash
{ Error: getaddrinfo ENOTFOUND proxy.linkeddatafragments.orghttps proxy.linkeddatafragments.orghttps:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'proxy.linkeddatafragments.orghttps',
  host: 'proxy.linkeddatafragments.orghttps',
  port: 80 }
(node:24941) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND proxy.linkeddatafragments.orghttps proxy.linkeddatafragments.orghttps:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:24941) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:24941) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.9.0 
| node                | v10.16.1
| npm                 | 6.9.0
| yarn                | 1.17.3
| Operating System    | linux (Linux 5.0.0-25-generic)

**Comment by ManuDeBuck** [comment]
I guess there is something wrong with string concatenation, as you can see in the error message: `Error: getaddrinfo ENOTFOUND proxy.linkeddatafragments.orghttps proxy.linkeddatafragments.orghttps:80`

**Comment by rubensworks** [comment]
The proxy was missing a trailing slash: `http://proxy.linkeddatafragments.org/`.
With that, it works.

Node's error message is just a bit cryptic, but that's another issue.
