### ISSUE TITLE
Use Object.preventExtensions

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#499]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

[`Object.preventExtensions`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/preventExtensions) may give us some minor performance boost.

Some places we could use it:
* Bindings (they are currently immutables, but these don't use this feature yet it seems: https://github.com/immutable-js/immutable-js/pull/1544)
* RDFJS quads and terms (will need to be done in data factories: https://github.com/rdfjs-base/data-model)

**Comment by jatinAroraGit** [comment]
Hey there,
Can I work on this issue ?

**Comment by rubensworks** [comment]
Certainly!
Be sure to let me know if you need any help.

**Comment by rubensworks** [comment]
Since JS engines currently do not optimize frozen objects, there's no reason to implement this.
