### ISSUE TITLE
Hypermedia links next not called

### ISSUE THREAD

**Issue by brechtvdv** [comunica/comunica#502]
#### Issue type:

- :bug: Bug

____
#### Description:

____
#### Environment:

```
./bin/query-dynamic.js -l debug http://fragments.dbpedia.org/2016-04/en "SELECT * WHERE { ?s ?p ?o }"
```
When a file resource is called (e.g. second page of QPF interface), Comunica does not search for the next links.
The actor for fetching hypermedia next-links doesn't get called.

**Comment by rubensworks** [comment]
Apparently this was a regression since 67db04a8f7f028b6bb18302377fb384b94e9a271.
Should be an easy fix.

**Comment by rubensworks** [comment]
This is actually something we should have caught with integration tests.
But since integration tests were only added after this regression was introduced, we didn't.
