### ISSUE TITLE
reasoning and comunica

### ISSUE THREAD

**Issue by mathib** [comunica/comunica#533]
#### Issue type:

- :question: Question

____
#### Question:

Probably a non-trivial question, but are there any options to use reasoning (RDFS/OWL/rules anything) with Comunica?

**Comment by rubensworks** [comment]
Good question!

This is not possible at the moment.
But we definitely plan to add modules to support reasoning.

**Comment by mathib** [comment]
That would be cool! Right now I'm writing ugly SPARQL queries with several UNIONS and in addition I query the Tbox directly. Does Comunica have an option to execute a part of a SPARQL query over one specific source only to speed up the entire query? 

BTW, I did some tests with GraphDB with reasoning on by default. When it's the only source of the query, it will return the results of the query with reasoning. When I add another source, it get a 400 error `Could not retrieve <graphDB source> (400: unknown error)`

**Comment by rubensworks** [comment]
> Does Comunica have an option to execute a part of a SPARQL query over one specific source only to speed up the entire query?

Sure, you can use SPARQL `SELECT` clauses for that.

> When I add another source, it get a 400 error Could not retrieve <graphDB source> (400: unknown error)

Hmm, could you open a separate issue for this?
Make sure to add query and sources, so I can try to reproduce it.
It looks to me like GraphDB is returning a 400 error for some reason, so either Comunica is sending an invalid subquery, or GraphDB is failing somehow.

**Comment by rubensworks** [comment]
Ah, that was a typo, my bad 😖.

**Comment by mielvds** [comment]
@mathib where do you see the reasoning come in? At the side of the query or the side of the sources/data retrieval? I can probably imagine case for both, but I'm asking for prioritizing.

**Comment by mathib** [comment]
@mielvds I'm unsure if I understand you correctly here. For my specific case, it would use the reasoning to simplify the queries I'm writing. I have superproperties and prop chain axioms defined in my TBox to make this easier. If I have 3 sources, I only need reasoning over the content of one of the sources at this point. This is probably also the easiest to implement in initial phases? A combined reasoning process over all the sources might also become expensive rather quickly?

From a user perspective, it seems logical to be able to change the Comunica config per source to "reasoning: true" and a link to the TBox that has to be considered (different external RDF source or already in the Comunica source).

**Comment by jeswr** [comment]
Potentially of use when this issue gets addressed - I've extracted the core of the Hylar inferencing engine into an npm module for my own use (https://github.com/jeswr/hylar-core, https://www.npmjs.com/package/hylar-core) - it works in node and browser applications and maintains support for incremental reasoning (https://github.com/jeswr/hylar-core/blob/2aaa3918c27cea3fcd8d36de6d3a3d73b50e91e8/lib/ReasoningEngine.ts#L60-L68). I also have a (rudimentary) extension of that package (https://github.com/jeswr/sparql-inferenced, https://www.npmjs.com/package/sparql-inferenced)

**Comment by rubensworks** [comment]
@jeswr Oh wow, that's really nice!

No work is planned on this issue AFAIK, so if you're interested, we could have a look together to see how this inferencing engine could fit into a new (optional?) Comunica actor. Many people (including myself) would be very excited to see any level reasoning work here!

**Comment by jeswr** [comment]
Definitely happy to look into it at some stage. 

That said, long term I think it would be better to have an engine capable of doing lazy evaluation of inferences (esp. if doing federated queries or queries over large data sources).

I think that so long as there was a bus that could support an Actor using the Hylar and/or sparql-inferenced reasoners & have the capacity to support lazy reasoners in future it wouldn't be a problem.

To add to other possible things that *could* be supported in regards to reasoners (ie my wish list).
 - Allowing the use of multiple reasoners (for instance if we had the Hylar engine & a reasoner that uses construct queries this would produce the same results as the sparql-inferenced package)
- Support for calls to ML models or other API's to produce inferences - for instance 'inferencing' human actions based on sensor data (I'm currently doing research into this for the purpose of creating better data APIs for BMI devices)

**Comment by rubensworks** [comment]
> Definitely happy to look into it at some stage.

Great! Feel free to ping me via email when you want to discuss this via a call.

> long term I think it would be better to have an engine capable of doing lazy evaluation of inferences

+1. Full materialization would only be usable on very small datasets.

> I think that so long as there was a bus that could support an Actor using the Hylar and/or sparql-inferenced reasoners & have the capacity to support lazy reasoners in future it wouldn't be a problem.

What I had in mind, was some kind of wrapper on top of quad-based sources. For every quad pattern query with raw results, the inferencer could add additional quads. ([Approach similar to this](https://rdfostrich.github.io/article-versioned-reasoning/))
But different approaches will be possible here, so this needs some more thinking I guess.

> Allowing the use of multiple reasoners
> Support for calls to ML models or other API's to produce inferences

That's very exciting stuff indeed!
For query engine users, the ability to select different _levels_ of inferencing would also be very valuable.
