### ISSUE TITLE
Wildcard accept header appending sometimes to eager

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#534]
#### Issue type:

- :bug: Bug

____
#### Description:

The code in https://github.com/comunica/comunica/commit/53c7e7519f6125054ac5e80c79ca4b038f067a18 would cut off the last part of an accept header that perfectly fits into 127 characters, just to make room for the `*/*;q=0.1` it does not need.

Minor thing related to this:

might want to first convert toFixed before comparing to '1.00' because of rounding; and the regex might have `+` instead of `*`.

**Comment by tbaccaer** [comment]
Hi, I would like to fix this bug as a first issue. 

Am I correct in saying that this test captures the bug sufficiently? 
If not, is there something else I should take into account?
```js
it('should not cut off at 127 to make space for an unneeded catch-all', () => {
  const a = Array(60).join('a');
  const b = Array(60).join('b');
  // the expected header has a length of 125, which should fit within 127 but it cuts off instead.
  return expect(actor.mediaTypesToAcceptString({ [a]: 1, [b]: 0.8 }, 127))
    .toEqual(`${a},${b};q=0.8`);
});
```

Running the test gives the following output:

![Screenshot 2020-09-30 at 22 07 07](https://user-images.githubusercontent.com/15344753/94734290-4b9d9500-0369-11eb-97b7-7c95025fc6a0.png)

**Comment by rubensworks** [comment]
@tbaccaer Good to hear you're interested in this issue!

This test case does indeed sum up the issue nicely. AFAIK that's the only thing that is going wrong in the code.
