### ISSUE TITLE
Support SPARQL endpoints without SPARQL service description

### ISSUE THREAD

**Issue by mathib** [comunica/comunica#535]
#### Issue type:

- :bug: Bug

____
#### Description:

I created a small web app that queries multiple RDF sources, incl. a GraphDB SPARQL endpoint. If my only Comunica source is this GraphDB SPARQL endpoint, I get the expected result. When I add another source and execute the query, it returns a 400 ERROR:
`Could not retrieve http://localhost:7200/repositories/test-comunica (400: unknown error)`

As a minimal example, I simply added one triple to the GraphDB:
`inst:ex rdf:type rdfs:class`

Which I query with SPARQL: 
`PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> SELECT * { ?s a ?o }`

When I add another source, e.g. the online SSN ontology, I receive the error:
```
{ type: 'file' , value: 'http://www.w3.org/ns/ssn/' } , 
{ type: 'sparql' , value: 'http://localhost:7200/repositories/test-comunica'}
```

At first, I guessed it was an issue with GraphDB enabling reasoning by default, but I turned it off and the error persists. I'm not sure if Comunica should resolve the SPARQL query if one of the sources has reasoning (i.e. a triplestore with reasoning engine)?

**Comment by rubensworks** [comment]
It looks like GraphDB is either not accepting a query from Comunica, or it does not support the `application/sparql-results+json` accept header.

@mathib Do you by any chance have a public GraphDB instance available to test with? I don't have any experience with GraphDB myself, so setting up will probably take some time.

**Comment by mathib** [comment]
GraphDB does accept queries from Comunica, if it's the only source!

> Do you by any chance have a public GraphDB instance available to test with? I don't have any experience with GraphDB myself, so setting up will probably take some time.

I don't have a public GraphDB instance. I had one on their DBaaS platform, but they closed it down over the summer. It shouldn't be too hard to install GraphDB. They have a free version (which I'm using) and an installer.

**Comment by mathib** [comment]
Did a quick test on my local machine and GraphDB supports `application/sparql-results+json`, but the default is `text/csv`

**Comment by rubensworks** [comment]
> GraphDB does accept queries from Comunica, if it's the only source!

Probably because Comunica sends the full query as-is there's only a single source. Otherwise smaller subqueries are sent.

> It shouldn't be too hard to install GraphDB. They have a free version (which I'm using) and an installer.

Ok. I'll put it on the list, but no guarantees when we'll have time to look into this.

**Comment by rubensworks** [comment]
> Did a quick test on my local machine and GraphDB supports application/sparql-results+json, but the default is text/csv

Hmm, perhaps you can try enabling Comunica's debug-mode (CLI: `-l debug`) to see what requests are being sent to the server.

**Comment by mathib** [comment]
> Hmm, perhaps you can try enabling Comunica's debug-mode (CLI: -l debug) to see what requests are being sent to the server.

I'll check this tonight on my other computer! Currently working on a Windows machine with the CDN and had some trouble using the Comunica CLI here. Thanks for looking into this!

**Comment by mathib** [comment]
Found out Comunica is also available for Docker, so I did some tests with the CLI. This is the output:
```
docker run comunica/actor-init-sparql sparql@http://host.docker.internal:7200/repositories/test-comunica file@http://www.w3.org/ns/ssn/ "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> SELECT * { ?s a ?o }" -l debug
[[2019-09-30T11:33:38.411Z]  INFO: Requesting http://host.docker.internal:7200/repositories/test-comunica { actor:
   'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher' }
[2019-09-30T11:33:38.419Z]  INFO: Requesting http://www.w3.org/ns/ssn/ { actor:
   'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher' }
Error: Could not retrieve http://host.docker.internal:7200/repositories/test-comunica (400: unknown error)
    at ActorRdfDereferenceHttpParse.run (/var/www/@comunica/actor-init-sparql/node_modules/@comunica/actor-rdf-dereference-http-parse/lib/ActorRdfDereferenceHttpParseBase.js:39:19)
(node:1) UnhandledPromiseRejectionWarning: Error: Could not retrieve http://host.docker.internal:7200/repositories/test-comunica (400: unknown error)
    at ActorRdfDereferenceHttpParse.run (/var/www/@comunica/actor-init-sparql/node_modules/@comunica/actor-rdf-dereference-http-parse/lib/ActorRdfDereferenceHttpParseBase.js:39:19)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-09-30T11:33:38.951Z]  INFO: Identified as file source: http://www.w3.org/ns/ssn/ssn.ttl { actor:
   'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/resolve-hypermedia.json#myHypermediaNoneResolver' }

{"?s":"http://www.w3.org/ns/ssn/","?o":"http://purl.org/vocommons/voaf#Vocabulary"},
...
```

**Comment by rubensworks** [comment]
Ah, it looks like things fail at the endpoint discovery phase. So GraphDB must not be exposing a SPARQL service description.

SPARQL service description are not required by the spec, but I thought we had a workaround for that, which appears to be not working properly.

**Comment by SvenLieber** [comment]
Something which seems related using Blazegraph.

**Description**
I have a local Blazegraph instance and loaded data via the UI which then ends up in the default "namespace". According to the [Blazegraph documentation](https://wiki.blazegraph.com/wiki/index.php/REST_API#SPARQL_End_Point) the sparql endpoint should be available at `http://localhost:9999/blazegraph/namespace/kb/sparql`.

However, querying via js with the following source description did not give any result:
```js
const sources = [
        {type: "hypermedia", value: "http://localhost:9999/blazegraph/namespace/kb/sparql"}
    ];
```

I tried to debug it using the `comunica-sparql` commandline tool with debug mode and got the following output
```
[[2019-10-14T17:00:15.448Z]  INFO: Requesting http://localhost:9999/blazegraph/namespace/kb/sparql { actor:
   'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher' }
[2019-10-14T17:00:15.561Z]  INFO: Identified as file source: http://localhost:9999/blazegraph/namespace/kb/sparql { actor:
   'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/resolve-hypermedia.json#myHypermediaNoneResolver' }
]
```

The endpoint seems to be recognized as *file source*.

Changing the *source description* in js from `hypermedia` to `sparql` fixed the issue for my query attempt from javascript.

**Comment by rubensworks** [comment]
Note: querying over endpoints exposed via Comunica also don't work.

**Comment by rubensworks** [comment]
Moved from #620.

-----

#### Issue type:

- :bug: Bug

____
#### Description:

When I execute an ASK query over a SPARQL endpoint (Stardog v6.2.2) and a TTL file, I get a correct response (the ASK correctly checks if the pattern is available in the Stardog db), but when I only query the SPARQL endpoint, I get an error `Unknown SPARQL results content type: application/json`

____
#### Environment:

- tested in  `comunica-sparql` v1.9.4 command line and v1.9.4/1.10/latest CDN via simple front end web app
- Windows 10
- Node v10.15.3



#### Crash log:

```
[2020-03-13T13:06:33.475Z]  INFO: Requesting http://localhost:5820/mydb/query?query=SELECT%20%3Fs%20%3Fp%20%3Fo%20WHERE%20%7B%20ASK%20WHERE%20%7B%20%3Fs%20%3Fp%20%3Fo.%20%7D%20%7D { actor:
   'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher' }
[(node:11492) UnhandledPromiseRejectionWarning: Error: Unknown SPARQL results content type: application/json
    at SparqlEndpointFetcher.<anonymous> (C:\Users\user.name\AppData\Roaming\nvm-new\v10.15.3\node_modules\@comunica\actor-init-sparql\node_modules\fetch-sparql-endpoint\lib\SparqlEndpointFetcher.js:64:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\user.name\AppData\Roaming\nvm-new\v10.15.3\node_modules\@comunica\actor-init-sparql\node_modules\fetch-sparql-endpoint\lib\SparqlEndpointFetcher.js:4:58)
(node:11492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:11492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rubensworks** [comment]
I've added a note in the README:

> Some SPARQL endpoints may be recognised as a file instead of a SPARQL endpoint due to them not supporting SPARQL Service Description, which may produce incorrect results. For these cases, the sparql type MUST be set.

@mathib Can you check if this works for you?

Since many people seem to be running into this problem, we may have to look into implementing a hack that assumes all sources ending with `/sparql` as a SPARQL endpoint. It's not a great solution, but due to the lack of SPARQL SD support in many implementations, this may be the only way we can fix this (without reducing performance).
@RubenVerborgh What do you think about this solution?

**Comment by mathib** [comment]
> I've added a note in the README:
> 
> > Some SPARQL endpoints may be recognised as a file instead of a SPARQL endpoint due to them not supporting SPARQL Service Description, which may produce incorrect results. For these cases, the sparql type MUST be set.
> 
> @mathib Can you check if this works for you?

Similar as said in https://github.com/comunica/comunica/issues/619, I always explicitly set the source type (in this case "sparql") both when using the command line and the CDN, without avail.

**Comment by RubenVerborgh** [comment]
> @RubenVerborgh What do you think about this solution?

Approved; it's a heuristic after all.

**Comment by rubensworks** [comment]
#633 introduces this new heuristic.

For SPARQL endpoints that are not exposed via a `/sparql` URL, and expose no SPARQL service description, `type` will have to be set to `sparql` manually.

**Comment by mathib** [comment]
Is it possible to reopen this issue? I still have the same issues when doing a query with Comunica over a GraphDB SPARQL endpoint and another source (tested with an online RDF file). I explicitly tell Comunica that the first source is a SPARQL endpoint (`sourceType: 'sparql'`) and the second is an RDF file (`sourceType: 'file'`). I'm able to query the same GraphDB source if it's the only source.

When I do the same query over the combination of a Stardog SPARQL endpoint and another source (tested with an online RDF file), the query works.

Tested in the browser version of Comunica (v1.19.0 and 1.17.0). Could not test it on v1.20.0 as the [CDN link](https://rdf.js.org/comunica-browser/versions/1.20.0/packages/actor-init-sparql/comunica-browser.js) does not resolve.

Let me know if I can help with debugging. If you think the issue is still related to GraphDB not emitting a SPARQL service description, I can ask the GraphDB development team to add it.

**Comment by rubensworks** [comment]
@mathib Are you setting the source type via `type` or `sourceType`? It should be `type`.
If so, is there a GraphDB endpoint we can test with? (feel free to mail it to me if you don't want to share it here)

**Comment by mathib** [comment]
oops, sorry for the confusion; I used `sourceType` temporaly in my GUI code to avoid confusion with other parts of the app. I always supply `type` to Comunica. I did some more tests with GraphDB:
- when I supply my local GraphDB as a source to http://query.linkeddatafragments.org/ I'm always unable to query it (probably because the `type` of the source is guessed while it should be stated explicitly). When it's the only source, I get a 400 unknown error in the "query results" part. When another source is added besides GraphDB, I only get the results from the non-GraphDB source while the query keeps on running without adding other results.

In both cases, I get the following in the Chrome browser console:

`XHR failed loading: GET "http://localhost:7200/repositories/test-db".`

and the following in the GraphDB log:

```
12:03:29.864 [repositories/test-db] INFO  c.o.g.sesame.RepositoryController - GET query 3392903
12:03:29.865 [repositories/test-db] INFO  c.o.f.s.GraphDBProtocolExceptionResolver - Client sent bad request (400)
org.eclipse.rdf4j.http.server.ClientHTTPException: Missing parameter: query
	at com.ontotext.graphdb.sesame.RepositoryController.handleRequestInternal(RepositoryController.java:317)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
        ...
```

In my own app, I always supply the `type` of the source explicitly to Comunica. When it's the only source, I see no error in GraphDB log (but I see that the query was processes succesfully) and the query returns the expected results to my app. This is the GraphDB log:

```
12:11:33.509 [repositories/test-db] INFO  c.o.g.sesame.RepositoryController - GET query -73492940
12:11:33.512 [repositories/test-db] INFO  c.o.g.sesame.TupleQueryResultView - Request for query -73492940 is finished
```

When I add another source and do a query over both sources, I get no results and see the same error appearing in the GraphDB log as when using the demo Linked Data Fragments client, while in the Chrome browser console, I see the following:

```
GET http://localhost:7200/repositories/test-db 400
Uncaught (in promise) Error: Could not retrieve http://localhost:7200/repositories/test-db (400: unknown error)
```

And finally, when testing using the Comunica CLI (most recent) via Docker, I get the same 400 unknown error and only the results from the other non-GraphDB source:

```
docker run -it --rm comunica/actor-init-sparql sparql@http://host.docker.internal:7200/repositories/test-db file@https://w3id.org/fog/fog.ttl "SELECT DISTINCT ?o { ?s a ?o }" -l debug
[2021-03-31T10:41:29.668Z]  INFO: Requesting http://host.docker.internal:7200/repositories/test-db { headers:
   { accept:
      'application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/json;q=0.45,text/n3;q=0.35,text/xml;q=0.3,application/xml;q=0.3,image/svg+xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18',
     'user-agent': 'Comunica/actor-http-native (Node.js v10.23.2; linux)' },
  actor:
   'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher' }
[2021-03-31T10:41:29.683Z]  INFO: Requesting https://w3id.org/fog/fog.ttl { headers:
   { accept:
      'application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/json;q=0.45,text/n3;q=0.35,text/xml;q=0.3,application/xml;q=0.3,image/svg+xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18',
     'user-agent': 'Comunica/actor-http-native (Node.js v10.23.2; linux)' },
  actor:
   'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher' }
[Could not retrieve http://host.docker.internal:7200/repositories/test-db (400: unknown error)
Could not retrieve http://host.docker.internal:7200/repositories/test-db (400: unknown error)

[2021-03-31T10:41:30.256Z]  INFO: Identified as file source: https://mathib.github.io/fog-ontology/ontology.ttl { actor:
   'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/resolve-hypermedia.json#myHypermediaNoneResolver' }

{"?o":"http://purl.org/vocommons/voaf#Vocabulary"},
{"?o":"http://www.w3.org/2002/07/owl#Ontology"},
{"?o":"http://www.w3.org/2002/07/owl#Class"},
{"?o":"http://www.w3.org/2002/07/owl#FunctionalProperty"},
{"?o":"http://www.w3.org/2002/07/owl#ObjectProperty"},
{"?o":"http://www.w3.org/2002/07/owl#DatatypeProperty"},
{"?o":"http://xmlns.com/foaf/0.1/Person"}
```

**Comment by rubensworks** [comment]
@mathib is there a GraphDB endpoint we can test with? (feel free to mail it to me if you don't want to share it here)

**Comment by mathib** [comment]
thanks Ruben, the fix works as long as I explicitly mention to Comunica that it's a SPARQL endpoint :)
