### ISSUE TITLE
Changes priority of RDF parsers in actor-init-sparql throws error

### ISSUE THREAD

**Issue by pheyvaer** [comunica/comunica#536]
#### Issue type:

- :bug: Bug

____
#### Description:
The goal is to update the priority of the HTML parser in `actor-init-sparql`. I changed 
```
{
  "@id": "config-sets:rdf-parsers.json#myRdfParserHtml",
  "@type": "ActorRdfParseHtml",
  "priorityScale": 0.2
}
```
in the file `config/sets/rdf-parsers.json`. I've rebuilt the code with `yarn run prepare`. 
When executing `./bin/query.js https://pieterheyvaert.com/#me 'SELECT * WHERE { ?s ?p ?o }'` I get the following errors:
```
[Error: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/rdf-dereference.json#mediatorRdfParseHandle mediated over all rejecting actors:
Error: Unrecognized media type: application/octet-stream
Error: Unrecognized media type: application/octet-stream
Error: Unrecognized media type: application/octet-stream
Error: Unrecognized media type: application/octet-stream
Error: Unrecognized media type: application/octet-stream
    at testResult.reply.then.catch (/home/pieter/Developer/comunica/packages/mediator-race/lib/MediatorRace.js:21:32)
```
The same happens when using `query-dynamic.js` instead of `query.js`.
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.9.2 (dev)
| node                | v11.3.0
| npm                 | 6.10.3
| yarn                | 1.16.0
| Operating System    | linux (Linux 4.15.0-64-generic)

**Comment by rubensworks** [comment]
It looks like your server is returning something with the `application/octet-stream` content type then. Have you tried it on other servers?

**Comment by pheyvaer** [comment]
What is the request when `application/octet-stream` is returned?

**Comment by rubensworks** [comment]
It should be just a regular request with accept header containing `text/html` as lowest priority.

**Comment by pheyvaer** [comment]
By any chance have a quick link to the place where that happens in the code so I can check which specific header that is? 😀

**Comment by rubensworks** [comment]
Here it is: https://github.com/comunica/comunica/blob/master/packages/actor-rdf-dereference-http-parse/lib/ActorRdfDereferenceHttpParseBase.ts#L99

**Comment by rubensworks** [comment]
@pheyvaer There seems to be a problem with conneg on your server:

```bash
$ curl -H 'Accept: application/trig,application/ld+json;q=0.9,application/n-quads;q=0.8,text/turtle;q=0.6,application/n-triples;q=0.5,application/rdf+xml;q=0.5,application/json;q=0.45,text/xml;q=0.3,image/svg+xml;q=0.3,text/n3;q=0.3,application/xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18'  https://pieterheyvaert.com/ -v
```

This returns Turtle content, but with content-type `application/octet-stream`.

**Comment by pheyvaer** [comment]
Yes indeed. That's also what I saw. I'm working on a fix on my side, but wanted to see first if that fixes everything before closing this issue :wink:
