### ISSUE TITLE
Remove usages of private/protected Asynciterator methods

### ISSUE THREAD

**Issue by joachimvh** [comunica/comunica#555]
#### Issue type:

- Enhancement

____
#### Description:

Private/protected (underscore) methods of Asynciterator should not be used by Comunica, as seen [here](https://github.com/comunica/comunica/blob/f6a7b619c6ad8d12ae3220227e10b10fe2a98698/packages/actor-rdf-resolve-quad-pattern-federated/lib/FederatedQuadSource.ts#L196) and in other places to prevent unexpected behaviour. (Was requested by @RubenVerborgh ).

**Comment by RubenVerborgh** [comment]
Note that the JSdoc of AsyncIterator suggests their classification as `protected` or `private`; might be useful to take that over in the TypeScript definitions.

**Comment by rubensworks** [comment]
Sure, but then we'll need a safe public equivalent of `_fillBuffer` to make things work :-)

**Comment by RubenVerborgh** [comment]
But can you tell me what you are trying to do? `_fillBuffer` is an internal matter normally; it ensures that repeated calls to `read` go faster.

**Comment by rubensworks** [comment]
It's been a while since I wrote that code. But if I remember correctly, this was done to ensure that the metadata event is emitted, as this event is constructed once data starts.

Not sure if this can be improved somehow. Perhaps it can with some of the recent changes to how metadata is being represented.

**Comment by RubenVerborgh** [comment]
Yeah, I see high-level what we want to achieve, but there's something fishy about the implementation. We are relying on side effects of filling the buffer to get this done, which is not reliable enough and is a suspected contributor to https://github.com/comunica/comunica/issues/553.
