### ISSUE TITLE
Query execution overhead in browsers compared to Node.js

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#561]
#### Issue type:

- :snail: Performance issue

____
#### Description:

Case:
- A high number of relatively simple queries over an in-memory data store exhibits a performance difference of one magnitude between Node.js and browsers (as discovered in https://github.com/solid/query-ldflex/issues/45). Whereas the individual queries take ~0.9ms in Node.js, they take around 8ms in Firefox or Chrome (which has the same V8 engine as Node).

Clearly, some piece of code must be different in the browser. So first questions:
- What pieces of code are different in the browser and why?
    - Are they the result of transpilation? (in particular async iterators generators perhaps)
    - Are they the result of shimming?
- Which of those pieces cause the performance impact?

In an preliminary investigation, I identified `setImmediate` as such a difference, given that this Node.js-specific function does not exist in the browser. Furthermore, `setImmediate` shim calls showed up in the browser during performance tests. However, the latter can simply be an effect of that fact that we do use a lot of `setImmediate` calls in general, not that they are particularly slow. Relevant points here:

- We seem to use around 60 `setImmediate` calls (in the course of 1ms!) for the very simple one-result queries. Additionally, most of them seem to be sequentially dependent on each other, so batching their execution does not seem like an option.
   - How does this number of calls evolve when there are more results?
   - What causes these calls?
   - Can we reduce this number of calls?

- When shimming `setImmediate` with alternatives such as `Promise.resolve().then` or `setTimeout`, in _both_ Node.js and browsers, a performance difference still seemed to remain.
   - This could indicate that `setImmediate` is not the culprit at all.
   - However, reducing the number of calls to it might still be beneficial.

____
#### Environment:

```
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.9.4
| node                | v12.6.0
| npm                 | 6.9.0
| yarn                | 1.17.3
| Operating System    | darwin (Darwin 18.6.0)
```

**Comment by rubensworks** [comment]
> We seem to use around 60 setImmediate calls (in the course of 1ms!) for the very simple one-result queries.

That's a lot indeed. We can probably reduce that quite a bit as a first attempt at fixing this issue.

> reducing the number of calls to it might still be beneficial.

👍

**Comment by RubenVerborgh** [comment]
It seems in particular that passing of bindings is slow. When translating a high number of query requests info a single query that returns the same total number of bindings, I still see slowdowns.

**Comment by rubensworks** [comment]
Hmm, perhaps it has something to do with immutables and/or asynciterator mapping's.

(I don't remember ever seeing something that could indicate that, but perhaps I missed something)

**Comment by rubensworks** [comment]
Following up in https://github.com/RubenVerborgh/AsyncIterator/issues/13

**Comment by rubensworks** [comment]
Should be fixed in 00ab75acfe60af8572dd7def454be673d724a2e8

**Comment by RubenVerborgh** [comment]
Excellent, now we should test this in the context of https://github.com/solid/query-ldflex/issues/45

**Comment by matthieu-fesselier** [comment]
Very nice to see this fixed!
Do I have an easy way to test this already or do you need to update `LDFlex-Comunica` first?

**Comment by RubenVerborgh** [comment]
@rubensworks Do we have a release yet?

**Comment by rubensworks** [comment]
I want to do some more testing before releasing, given the significant internal changes.
A new release tomorrow or next week should be feasible.
