### ISSUE TITLE
Federation with one source is slower than just one source

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#562]
#### Issue type:

- :snail: Performance issue

____
#### Description:

Calling the query engine with `{ sources: [x] }` is slower than with `{ source: x }`; in my tests up to 12%.

Found as part of https://github.com/solid/query-ldflex/issues/45

____
#### Environment:

```
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.9.4
| node                | v12.6.0
| npm                 | 6.9.0
| yarn                | 1.17.3
| Operating System    | darwin (Darwin 18.6.0)
```

**Comment by rubensworks** [comment]
Some overhead due to the federated actor was to be expected. But 12% is a bit much indeed, we should be able to optimize this.

**Comment by RubenVerborgh** [comment]
Probably just a "if sources.length === 1" kind of thing.

**Comment by rubensworks** [comment]
Sure, but may not be needed if we'd be able to reduce the overhead to ~1%.

**Comment by RubenVerborgh** [comment]
Yeah, and additionally: getting the overhead low will also benefit the multi-source case. I wonder if it's 12% in total or per source.

**Comment by jeswr** [comment]
I'd say this  is likely caused by https://github.com/RubenVerborgh/AsyncIterator/issues/44 given the number of transformations in the Federated components. Might be worth checking this again once that issue is closed.

**Comment by rubensworks** [comment]
The federation actor is gone in v3, so this will not be an issue anymore.
