### ISSUE TITLE
Should GraphQL be included in actor-init-sparql?

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#563]
#### Issue type:

- :question: Question

____
#### Question:

Should GraphQL be included in actor-init-sparql?
It seems confusing name-wise at least.

See https://github.com/RubenVerborgh/LDflex-Comunica/issues/19

**Comment by rubensworks** [comment]
We should indeed move this out into another package (like actor-init-graphqlld) in the future.

See #267.
