### ISSUE TITLE
Use graphy.js parsers

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#582]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

They are faster than N3.js, as per https://github.com/blake-regalia/graphy.js/issues/14.
Just need to keep in mind file size.

**Comment by rubensworks** [comment]
It looks like graphy.js also has serializers. we may also consider using those.
@blake-regalia Any insights on spec-compliance and speed compared to N3.js's serializers?

**Comment by blake-regalia** [comment]
Yes, there are content 'scribers' in the upcoming release that are basically performance flavors of the writers. I've just run some tests on 500k wikidata triples and the graphy scribers are performing about 2.7x faster than N3.js, while graphy writers are closer to 2x.

**Comment by rubensworks** [comment]
Oh nice, that sounds quite significant.

Are there any downsides to these scribers compared to the writers? I assume they are still spec-compliant?

**Comment by blake-regalia** [comment]
The difference is that the writers support more stylized output like configurable indentation, nested blank nodes, collections, etc. They are both Transforms that implement RDFJS Sink -- would  that be the extent of spec-compliance in question?

**Comment by rubensworks** [comment]
> would that be the extent of spec-compliance in question?

Ah, so both are fully spec-compliant. Great 🙂.

We could actually make use of both, one pretty-printing mode, and one performance-mode. We'd have to check how effective that performance-mode would be, as it's possible that the internal query process is the main bottleneck, and is slower than writing.

**Comment by rubensworks** [comment]
Closing due to staleness.
Happy to re-open in case someone is willing to take this up.
