### ISSUE TITLE
Long execution time with OPTIONAL

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#583]
#### Issue type:

- :snail: Performance issue

____
#### Description:

This query is fast:

```sparql
SELECT ?country ?capital ?caplat ?caplong WHERE {
  ?country a <http://dbpedia.org/ontology/Country>.
  ?country <http://dbpedia.org/ontology/capital> ?capital.
  ?capital <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?caplat;
           <http://www.w3.org/2003/01/geo/wgs84_pos#long> ?caplong
}

```

But this closely related query is not:

```sparql
SELECT ?country ?capital ?caplat ?caplong WHERE {
  ?country a <http://dbpedia.org/ontology/Country>.
  OPTIONAL {
    ?country <http://dbpedia.org/ontology/capital> ?capital.
    ?capital <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?caplat;
             <http://www.w3.org/2003/01/geo/wgs84_pos#long> ?caplong
  }
}
```

I takes 150 second before the first results start appearing. Furthermore, since it takes such a long time, I haven't been able to verify that it returns the correct results.

____

**Comment by rubensworks** [comment]
Just thought of it, but this may have to do with the performance of our selected join algorithm(s). We may have to do some experimenting on that.

We could also look into fully integrating optional patterns into our (adaptive left-deep) BGP algorithm.

Olaf's work on OPT+ may also be interesting to investigate.

**Comment by rubensworks** [comment]
Done in #632.

**Comment by rubensworks** [comment]
@RubenVerborgh Your query is a lot faster now 🙂 http://query.linkeddatafragments.org/#transientDatasources=http%3A%2F%2Ffragments.dbpedia.org%2F2016-04%2Fen&query=SELECT%20%3Fcountry%20%3Fcapital%20%3Fcaplat%20%3Fcaplong%20WHERE%20%7B%0A%20%20%3Fcountry%20a%20%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FCountry%3E.%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Fcountry%20%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2Fcapital%3E%20%3Fcapital.%0A%20%20%20%20%3Fcapital%20%3Chttp%3A%2F%2Fwww.w3.org%2F2003%2F01%2Fgeo%2Fwgs84_pos%23lat%3E%20%3Fcaplat%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2003%2F01%2Fgeo%2Fwgs84_pos%23long%3E%20%3Fcaplong%0A%20%20%7D%0A%7D

**Comment by RubenVerborgh** [comment]
Excellent, thanks!
