### ISSUE TITLE
Tag patch versions on npm package

### ISSUE THREAD

**Issue by michielbdejong** [comunica/comunica#591]
Please tag patch version and push to npm. We want to be able to use the fix from #587 to eventually fix https://github.com/inrupt/generator-solid-react/issues/281.

From https://github.com/LDflex/LDflex-Comunica/blob/master/package.json#L30-L31 it seems that the relevant packages are probably https://www.npmjs.com/package/@comunica/actor-http-solid-auth-fetch and @comunica/actor-init-sparql right?

**Comment by rubensworks** [comment]
Sure. I hoped to include some more fixes before the end of this year, but I didn't get that far unfortunately.
Released version 1.10.0 (also includes some new features)

**Comment by michielbdejong** [comment]
Great, that fixed it!
