### ISSUE TITLE
Improve interaction between semver and compiled configs

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#592]
#### Issue type:

- :question: Question

____
#### Question:

The issue raised [here](https://github.com/inrupt/generator-solid-react/issues/281#issuecomment-565216289) was ultimately caused by [comunica-compile-config](https://github.com/LDflex/LDflex-Comunica/blob/78dbb0c6e6d57d3da1840fe118ee1fa3d10c89b5/package.json#L47) generating an explicit dependency tree in which `@comunica/actor-rdf-join-nestedloop` was still listed. But that package became unneeded in a semver-compatible update of its dependent, causing the compiled config to fail.

This means compiled configurations are not semver-compatible.

How do we handle that?

**Comment by rubensworks** [comment]
So we have two types of users of `@comunica/actor-init-sparql`: users that just query, and users that create custom configs. For the former group, our semver strategy works as expected, but apparently not always for the latter.

Ideally, we shouldn't be conflating those two groups of users, which we should do with #267.

Until that is fixed, a good solution may be to require custom config users to bind to specific versions of `@comunica/actor-init-sparql` instead of using tilde ranges.

**Comment by RubenVerborgh** [comment]
> Until that is fixed, a good solution may be to require custom config users to bind to specific versions of `@comunica/actor-init-sparql` instead of using tilde ranges.

That does make sense; I wonder if we can somehow enforce that or check that. As in, can the configuration generator hardcode the version number it was generated for? And then either perform a runtime check (which would involve shipping the version number, that might not be nice, especially not for browserify) or add a `try … catch` around the `requires` and print an error message hinting at version compatibility?

In any case, we should consider printing a warning about fixing version numbers in the generator, and add the version number at least as a top comment to the generated file.

**Comment by rubensworks** [comment]
Yes, that may work. But then we may have to do this version encoding for all packages that are included in the built engines (so basically all `@comunica/*` packages), as Components.js doesn't know the concept of a *root* package.

A check like this would introduce some runtime overhead though, so we may want to move this check to a preinstall check. I think it should be possible to dynamically add such a preinstall hook to packages when Components.js is installed into a package.
