### ISSUE TITLE
Infinitely requesting the same page

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#593]
#### Issue type:

- :bug: Bug

____
#### Description:

A query causes the same page to be requested over and over again, and the query never terminates. (see internal chat in LDF channel)

____
#### Environment:

http://query.linkeddatafragments.org/

**Comment by joachimvh** [comment]
I ran the query and the first 6k requests were all to different pages (with very similar URLs) though maybe it's rather the query algorithm getting stuck in a very inefficient path again

**Comment by rubensworks** [comment]
Ah indeed, I didn't look at the query logs close enough.
So it's not a bug, but an optimization issue.

@svenlieber is this still an issue for you? If not, we can close this.

**Comment by SvenLieber** [comment]
I tested my initial query again with corrected data.
There are still around 5 seconds no results, but then the results come in.
So no issue for me!
