### ISSUE TITLE
ORDER BY with multiple comparators takes only last comparator into account

### ISSUE THREAD

**Issue by ghsnd** [comunica/comunica#598]
#### Issue type:
- :bug: Bug

#### Description:
When a SPARQL query has an `ORDER BY` clause containing multiple comparators, it looks like only the last comparator is used when ordering.

#### Example 1
**input.ttl:**
```turtle
@prefix p: <http://example.org#> .

p:one
  p:name "Bosmans";
  p:givenName "Jos".

p:two
  p:name "Vermeulen";
  p:givenName "Jos".

p:three
  p:name "Vermeulen";
  p:givenName "Brecht".
```

**query.sparql:**
```sparql
PREFIX p: <http://example.org#>

SELECT ?name ?given
WHERE {
  ?person p:name ?name;
          p:givenName ?given .
}
ORDER BY ?given ?name
```

The query was executed as follows:
```
comunica-sparql-file input.ttl -f query.sparql
```

**Result:**
```json
[
{"?name":"\"Bosmans\"","?given":"\"Jos\""},
{"?name":"\"Vermeulen\"","?given":"\"Jos\""},
{"?name":"\"Vermeulen\"","?given":"\"Brecht\""}
]
```

**Expected result:**
```json
[
{"?name":"\"Vermeulen\"","?given":"\"Brecht\""},
{"?name":"\"Bosmans\"","?given":"\"Jos\""},
{"?name":"\"Vermeulen\"","?given":"\"Jos\""}
]
```

#### Example 2
Same input file, same query, only changed the order to: `ORDER BY ?name ?given`:

**Result:**
```json
[
{"?name":"\"Vermeulen\"","?given":"\"Brecht\""},
{"?name":"\"Vermeulen\"","?given":"\"Jos\""},
{"?name":"\"Bosmans\"","?given":"\"Jos\""}
]
```

**Expected result:**
```json
[
{"?name":"\"Bosmans\"","?given":"\"Jos\""},
{"?name":"\"Vermeulen\"","?given":"\"Brecht\""},
{"?name":"\"Vermeulen\"","?given":"\"Jos\""}
]
```
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.10.0 
| node                | v10.16.3
| npm                 | 6.13.6
| Operating System    | linux (Linux 4.15.0-74-generic), Ubuntu 18.04

**Comment by rubensworks** [comment]
I think this could be a problem in either the SPARQL parser, SPARQL algebra, or actor-query-operation-orderby-sparqlee.
