### ISSUE TITLE
ORDER BY doesn't take numeric type into account

### ISSUE THREAD

**Issue by ghsnd** [comunica/comunica#599]
#### Issue type:

- :bug: Bug

____
#### Description:

An `ORDER BY` clause in a SPARQL query doesn't sort `numeric`s numerically.

This might be related to #598 .

____
#### Example

**input.ttl:**
```turtle
@prefix p: <http://example.org#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

p:one p:value "1"^^xsd:integer .
p:two p:value "2"^^xsd:integer .
p:eleven p:value "11"^^xsd:integer .
```

**query.sparql:**
```sparql
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX p: <http://example.org#>

SELECT ?number ?value
WHERE {
  ?number p:value ?value .
} ORDER BY ?value
```
The query was executed as follows:
```
comunica-sparql-file input.ttl -f query.sparql
```

**Result:**
```json
[
{"?number":"http://example.org#one","?value":"\"1\"^^http://www.w3.org/2001/XMLSchema#integer"},
{"?number":"http://example.org#eleven","?value":"\"11\"^^http://www.w3.org/2001/XMLSchema#integer"},
{"?number":"http://example.org#two","?value":"\"2\"^^http://www.w3.org/2001/XMLSchema#integer"}
]
```

**Expected result:**
```json
[
{"?number":"http://example.org#one","?value":"\"1\"^^http://www.w3.org/2001/XMLSchema#integer"},
{"?number":"http://example.org#two","?value":"\"2\"^^http://www.w3.org/2001/XMLSchema#integer"},
{"?number":"http://example.org#eleven","?value":"\"11\"^^http://www.w3.org/2001/XMLSchema#integer"}
]

```

____
#### Environment:
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.10.0 
| node                | v10.16.3
| npm                 | 6.13.6
| Operating System    | linux (Linux 4.15.0-74-generic)

**Comment by rubensworks** [comment]
Thanks for reporting. It looks like lexicographical sorting is happening, while the integer datatype should be detected and preferred for sorting.
