### ISSUE TITLE
Clean build from master fails

### ISSUE THREAD

**Issue by wschella** [comunica/comunica#601]
#### Issue type:

- :bug: Bug

____
#### Description:

When doing a clean install from master (with `yarn install --frozen-lockfile`). The second build will fail (the first succeeds during 'yarn install') with crash log included below. 
____
#### Environment:

```
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.10.0 (dev)
| node                | v10.16.3
| npm                 | 6.9.0
| yarn                | 1.19.0
| Operating System    | linux (Linux 5.3.0-26-generic)
```

#### Crash log:

```
❯ yarn build
yarn run v1.19.0
$ tsc
error TS5055: Cannot write file '/media/wout/Data/Workspace/IDLab/comunica/packages/actor-rdf-metadata-extract-hydra-controls-query/lib/context.d.ts' because it would overwrite input file.

error TS5055: Cannot write file '/media/wout/Data/Workspace/IDLab/comunica/packages/actor-rdf-metadata-extract-hydra-count-query/lib/context.d.ts' because it would overwrite input file.

error TS5055: Cannot write file '/media/wout/Data/Workspace/IDLab/comunica/packages/actor-rdf-metadata-extract-hydra-links-query/lib/context.d.ts' because it would overwrite input file.


Found 3 errors.
```

**Comment by wschella** [comment]
Installed tsc version is `3.7.4`, as it is a dependency of `typedoc` and allowed by the semver of `typescript": "^3.3.1` as specified.

Preliminary investigation tells me:

* issue does not occur with lower (3.3.1) typescript (and thus tsc) versions. 
* if `context.d.ts` files from the error log are removed, the build succeeds once.
* `context.d.ts` files are regenerated from `context.json` files found in those packages

**Comment by wschella** [comment]
Likely related to https://github.com/Microsoft/TypeScript/issues/16749 and https://github.com/microsoft/TypeScript/issues/34761. 

I now wonder why the emitted declaration files are not already a problem. Potentially some special casing in the compiler?

**Comment by rubensworks** [comment]
Thanks for reporting this.
It looks like this can be resolved with some file renaming. To be looked into...

**Comment by wschella** [comment]
Just an FYI, work arounds should now no longer be needed: https://github.com/microsoft/TypeScript/pull/36066

**Comment by rubensworks** [comment]
Seems to be fixed indeed 🎉
