### ISSUE TITLE
Bug in tutorial "Creating a REDUCED actor"

### ISSUE THREAD

**Issue by dreeki** [comunica/comunica#607]
#### Issue type:

- :bug: Bug

____
#### Description:

During the first steps (specifically for the step "node run.js"), an error is thrown. To fix this bug, go to the run.js file and change http from the url to https on line 12 of the screenshot. 
<img width="865" alt="Schermafbeelding 2020-02-17 om 11 22 51" src="https://user-images.githubusercontent.com/22447680/74645684-b1416600-5178-11ea-9553-a1a423f28d78.png">

____

**Comment by rubensworks** [comment]
Right, this should be updated in the tutorial, similar as was done for https://github.com/comunica/Tutorial-Comunica-Querying-Data/issues/5.

**Comment by rubensworks** [comment]
Not applicable anymore now that this tutorial has been deprecated in favor of https://comunica.dev/docs/modify/getting_started/contribute_actor/.
