### ISSUE TITLE
support auth HTTP requests in default Comunica

### ISSUE THREAD

**Issue by mathib** [comunica/comunica#613]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:
It would be nice if the default Comunica query engine also allowed to query Linked Data Fragments that need authentication, e.g. a secured triplestore needing basic auth.

According to question https://github.com/comunica/comunica/issues/612, it should be doable to add a HTTP actor that can handle authenticated HTTP requests, e.g. by starting from [`actor-http-solid-auth-fetch`](https://github.com/comunica/actor-http-solid-auth-fetch).

**Comment by rubensworks** [comment]
For reference, this can be used until we add a concrete package for this: https://github.com/comunica/examples/tree/master/packages/configure-sparql-http-solid

**Comment by jaw111** [comment]
In case this only concerns requests initiated from a client browser, it may be sufficient to modify `Requester-browser.ts` in `actor-http-native` to set `withCredentials` to `true`. That would allow the browser to send the authentication and cookies for the target authority on those cross-origin requests.

If there are concerns that `withCredentials` cannot always be set to `true`, then it could be configurable such that, for example, a user of the jQuery widget is able to choose if credentials are sent by checking a box in the settings.

**Comment by rubensworks** [comment]
Will be added in the next release.
Documentation: https://comunica.dev/docs/query/advanced/basic_auth/
