### ISSUE TITLE
Add option to disable caching

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#618]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

In cases where caching is not wanted, we should allow this to be disabled completely.

For this, we can add a new context entry, which is checked within the relevant actors that do caching.

From the CLI, it should be possible to pass the option `--no-cache`, which defines this context entry.

Optionally, we may also want this feature to cause the `Cache-Control: no-cache` header to be sent in requests.

(In some cases, caching may only be desired within a certain query exec, but not across multiple query execs)

**Comment by rubensworks** [comment]
Thanks for sharing @mrkvon!

An alternative solution would be to call `engine.invalidateHttpCache()` after/before each query execution.

**Comment by mrkvon** [comment]
So, the issue is open only to keep track of the desired `--no-cache` option for CLI, isn't it?

After reading the issue, i wrongly assumed that no cache invalidation is implemented, and didn't even bother looking into documentation... Anyways, thanks for clarifying @rubensworks!

**Comment by rubensworks** [comment]
> So, the issue is open only to keep track of the desired --no-cache option for CLI?

Also that, but also to disable caching to happening in the first place.
This should save a bit on memory consumption during query execution compared to calling `invalidateHttpCache()` after each query exec.
