### ISSUE TITLE
Error when querying a HDT file with a UNION and a FILTER()

### ISSUE THREAD

**Issue by sdevalk** [comunica/comunica#641]
#### Issue type:

- :bug: Bug

____
#### Description:

I want to query a HDT file with a UNION and a FILTER(). However, an error is thrown.

```javascript
import * as Comunica from '@comunica/actor-init-sparql-hdt';
import { LoggerPretty } from '@comunica/logger-pretty';

(async () => {
  const myEngine = Comunica.newEngine();

  const query = `
    CONSTRUCT {
      ?uri a skos:Concept ;
      skos:prefLabel ?prefLabel ;
      skos:altLabel ?altLabel
    }
    WHERE {
      ?uri a schema:Person .
      {
        ?uri schema:name ?prefLabel .
        FILTER(CONTAINS(?prefLabel, "Gogh")) .
      }
      UNION
      {
        ?uri schema:alternateName ?altLabel .
        FILTER(CONTAINS(?altLabel, "Gogh")) .
      }
    }
  `;

  const config = {
    log: new LoggerPretty({ level: 'debug' }),
    sources: [
      {
        type: 'hdtFile',
        value: 'data/artists.hdt',
      },
    ],
  };

  await myEngine.query(query, config);
})();
```

The error:

```
UnhandledPromiseRejectionWarning: Error: The source cannot be changed after it has been set
    at PromiseProxyIterator.TransformIterator._validateSource (/usr/src/app/node_modules/asynciterator/asynciterator.js:1015:11)
    at PromiseProxyIterator.set [as source] (/usr/src/app/node_modules/asynciterator/asynciterator.js:984:10)
    at PromiseProxyIterator.loadSource (/usr/src/app/node_modules/asynciterator-promiseproxy/lib/PromiseProxyIterator.js:17:25)
```

____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.10.0
| node                | v12.0.0
| npm                 | 6.9.0
| yarn                | 1.15.2
| Operating System    | linux (Linux 4.9.184-linuxkit)

**Comment by rubensworks** [comment]
This may be a bug in asynciterator-promiseproxy.
I suspect a race condition in [`loadSource`](https://github.com/rubensworks/asynciterator-promiseproxy.js/blob/master/lib/PromiseProxyIterator.ts#L19-L22).

We should make sure that `this.source` is only set _once_. Because now, it can be set multiple times while the sourceGetter is being resolved.

**Comment by rubensworks** [comment]
Should be fixed now that we the behaviour of asynciterator-promiseproxy has been moved into asynciterator with a proper implementation.

Feel free to re-open should this still be a problem.

**Comment by sdevalk** [comment]
I have just tested it and it works perfectly! 👍🏻
