### ISSUE TITLE
`actor-init-sparql-file` broken?

### ISSUE THREAD

**Issue by sdevalk** [comunica/comunica#648]
#### Issue type:

- :question: Question

____
#### Question:

How can I query a local RDF file using `actor-init-sparql-file`?

If I follow the example in the [README](https://github.com/comunica/comunica/tree/master/packages/actor-init-sparql-file#usage-within-application)...

```javascript
(async () => {
  const newEngine = require('@comunica/actor-init-sparql-file').newEngine;
  const myEngine = newEngine();

  const result = await myEngine.query('SELECT * WHERE { ?s ?p <http://dbpedia.org/resource/Belgium>. ?s ?p ?o } LIMIT 100',
    { sources: ['/path/to/my/file.ttl'] })
  result.bindingsStream.on('data', (data) => console.log(data.toObject()));
})();

```

...the error underneath is returned:

```
Error: Cannot retrieve /path/to/my/file.ttl because it is not an HTTP(S) URL.
    at /usr/src/app/node_modules/@comunica/mediator-race/lib/MediatorRace.js:21:32
```

____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.12.0
| node                | v12.0.0
| npm                 | 6.9.0
| yarn                | 1.15.2
| Operating System    | linux (Linux 4.9.184-linuxkit)

**Comment by rubensworks** [comment]
Hmm, that _should_ work, so it may be a bug.
Could you try instead with `{ sources: [{ type: 'file', value: '/path/to/my/file.ttl' }] }`?

**Comment by sdevalk** [comment]
Thanks! The result, unfortunately, is the same:

```javascript
(async () => {
  const newEngine = require('@comunica/actor-init-sparql-file').newEngine;
  const myEngine = newEngine();

  const result = await myEngine.query('SELECT * WHERE { ?s ?p <http://dbpedia.org/resource/Belgium>. ?s ?p ?o } LIMIT 100',
  { sources: [{ type: 'file', value: '/path/to/my/file.ttl' }] })
  result.bindingsStream.on('data', (data) => console.log(data.toObject()));
})();
```

Yields:

```
Error: Cannot retrieve /path/to/my/file.ttl because it is not an HTTP(S) URL.
    at /usr/src/app/node_modules/@comunica/mediator-race/lib/MediatorRace.js:21:32
```

**Comment by rubensworks** [comment]
That's really weird. The integration tests on this package still seem to pass though. Something to be looked into...

**Comment by andrefs** [comment]
This is happening to me as well. I tried to use relative paths, absolute paths and absolute paths preceded with `file://`.

#### Environment:

| software | version |
| --- | --- |
| Comunica Init Actor | 1.12.1 |
| node | v13.8.0 |
| npm | 6.14.2 |
| yarn | 1.22.4 |
| Operating System | linux (5.6.11-arch1-1) |

**Comment by NIRAS-MHRA** [comment]
Works. Thanks :)

**Comment by andrefs** [comment]
Great! :+1: 

Any idea when a version including this might be released?

**Comment by rubensworks** [comment]
@andrefs We'll probably release somewhere in the next couple of weeks. We're working on several fixes and improvements at the moment that we want to include in the next release.

**Comment by rubensworks** [comment]
1.14.0 has been released with a fix for this.

**Comment by andrefs** [comment]
Seems to be working fine, many thanks! :+1:
