### ISSUE TITLE
Invalid COUNT queries being sent to SPARQL endpoints

### ISSUE THREAD

**Issue by mathib** [comunica/comunica#649]
#### Issue type:

- :bug: Bug

____
#### Description:

The below query over an online TTL file and a Stardog triplestore return the right results (I think), but before that, Comunica sends about 504 unsuccesful "statistical" queries to Stardog that don't seem to make sense to me.

Sources:
```
{ value: 'http://localhost:5820/mydb/query' , type: 'sparql' }
{ value: 'http://myfile.org/file.ttl' , type: 'file' }
```
Query asked to Comunica engine:
```
SELECT * WHERE {
	{ 
                # only this named graph in triplestore + should be send in one piece => SERVICE
		SERVICE <http://localhost:5820/mydb/query> {
			GRAPH <virtual://myvirtgraph> {
				?iel rdf:type bot:Element , ?str .
				?str rdfs:label ?strLabel .
			}
		}
	} UNION {
                # also in TTL file
		?iel rdf:type bot:Element , ?str .
		?str rdfs:label ?strLabel .
	}
        # both in default graph of triplestore and TTL file
	?iel ex:hasRepair ?o .
	?o ?p2 ?o2 .
} 
```
Example GET request send by Comunica containing useless (?) query, since `?var0` can never have any results in this query:
```
http://localhost:5820/mydb/query?query=SELECT ?count WHERE {
  GRAPH <virtual://myvirtgraph> {
    ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o.
    BIND(?var0 AS ?count)
  }
}
```
Only after Comunica has send about 504 similar queries, I get the results related to the `SERVICE` part from my SPARQL endpoint
In fact, I just noticed this delay by looking at the errors from Stardog coming in my browser console. The virtual graph at the Stardog SPARQL endpoint seems pretty brittle when it comes to non-specific queries; all 504 "statistical" queries fail and return a 500 error.

____
#### Environment:
Comunica CDN latest (1.12.0)

**Comment by rubensworks** [comment]
Thanks for reporting!

That count query to the endpoint does indeed look incorrect, so something must be going wrong there.

**Comment by rubensworks** [comment]
@joachimvh Could you have a look at this one? I suspect a bug in sparqlalgebrajs related to query construction of COUNT queries with GRAPH.

See the failing test in 4c104ce60344b3faa85a9abd2889a79af4718c38.
