### ISSUE TITLE
EXISTS found, but no existence hook provided

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#650]
#### Issue type:

- :bug: Bug

____
#### Description:

Error when a BIND-EXISTS is used.

This may either be a bug or a missing feature.

____

#### Crash log:

http://query.linkeddatafragments.org/#datasources=http%3A%2F%2Fldf.nanopubs.lod.labs.vu.nl%2Fnp&query=select%20%3Fa%20%3Fx%20where%20%7B%20%0A%3Fa%20a%20%3Chttp%3A%2F%2Fpurl.org%2Fnanopub%2Fx%2FExampleNanopub%3E%20.%20%0Abind(exists%20%7B%20%3Ft%20a%20%3Fs%20%7D%20as%20%3Fx)%20%0A%7D%20limit%2010%20

> # EXISTS found, but no existence hook provided.

**Comment by wschella** [comment]
This error triggers in sparqlee when no function for resolving `exists` is passed to the evaluator, yet an `exists` is found in the algebra. I'm guessing the code in the bind operator does not pass a existence resolver to sparqlee, as I was under the assumption that `exists` could not occur within a `bind`.

**Comment by rubensworks** [comment]
@wschella So it should be just a matter of injecting an already existing `exists` implementation, right?

**Comment by wschella** [comment]
@rubensworks I think so yes.I think the FilterSparqlee actor has one, and can thus be used as reference.

**Comment by rubensworks** [comment]
@wschella Great, thanks for the pointer!

**Comment by tkuhn** [comment]
Works very nicely, thanks! :)
