### ISSUE TITLE
Document how to contribute

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#651]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

A more in-depth guide should be written on how people can contribute new features (actors). This should explain setting up dev environment, using the generator, writing tests, plugging in the actor, running, ....

**Comment by pheyvaer** [comment]
I wouldn't mind helping out here with reviewing en testing the documentation :smiley:

**Comment by rubensworks** [comment]
Wrote a general contribution guide here: https://comunica.dev/contribute/
And a detailed guide on contributing a new actor here: https://comunica.dev/docs/modify/getting_started/contribute_actor/

@pheyvaer Could you have a look at them? Feel free to suggest changes if needed.

**Comment by pheyvaer** [comment]
Sure! Will do :+1:

**Comment by pheyvaer** [comment]
I checked https://comunica.dev/contribute/ (not the links on this page, should I?)

- Explain what `dev-ready` means.
- Make list of steps under "Issue Strategy".

Will also check https://comunica.dev/docs/modify/getting_started/contribute_actor/ later.

**Comment by rubensworks** [comment]
Thanks! Fixed in https://github.com/comunica/website/commit/1a097244d57e781e26b360c73234411ff8595827.

**Comment by pheyvaer** [comment]
Also had a look at https://comunica.dev/docs/modify/getting_started/contribute_actor/

Remarks: 
- repo root --> repo's root (?)
- Mention that `$ yo comunica:actor-query-operation` is executed in the comunica folder.
- In which folder should the test be run?

**Comment by rubensworks** [comment]
Thanks for the feedback!
