### ISSUE TITLE
@graph in JSON-LD not default graph

### ISSUE THREAD

**Issue by brechtvdv** [comunica/comunica#658]
#### Issue type:

- :bug: Bug

____
#### Description:

My website has a JSON-LD description embedded: https://brechtvdv.github.io/old
When you parse this with the JSON-LD playground, then the triples are in the default graph.

However, with Comunica this returns a blank node graph.
Also RDF play returns a blank node graph.

____
#### Environment:

[playground](https://json-ld.org/playground/#startTab=tab-table&json-ld=%7B%22%40context%22%3A%7B%22foaf%22%3A%22http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%22%2C%22owl%22%3A%22http%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%22%2C%22foaf%3Aknows%22%3A%7B%22%40type%22%3A%22%40id%22%2C%22%40id%22%3A%22http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2Fknows%22%7D%2C%22foaf%3Aimg%22%3A%7B%22%40id%22%3A%22foaf%3Aimg%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22foaf%3Ambox%22%3A%7B%22%40id%22%3A%22foaf%3Ambox%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22license%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fcreativecommons.org%2Fns%23license%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22void%22%3A%22http%3A%2F%2Frdfs.org%2Fns%2Fvoid%23%22%2C%22rdfs%22%3A%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%22%2C%22dcterms%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%22%2C%22dcat%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%22%2C%22ldp%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fldp%23%22%2C%22ldp%3Ainbox%22%3A%7B%22%40type%22%3A%22%40id%22%7D%2C%22solidterms%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fsolid%2Fterms%23%22%2C%22solidterms%3ApublicTypeIndex%22%3A%7B%22%40type%22%3A%22%40id%22%7D%2C%22solidterms%3AprivateTypeIndex%22%3A%7B%22%40type%22%3A%22%40id%22%7D%2C%22pim%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fpim%2Fspace%23%22%2C%22pim%3Astorage%22%3A%7B%22%40type%22%3A%22%40id%22%7D%2C%22foaf%3AprimaryTopic%22%3A%7B%22%40type%22%3A%22%40id%22%7D%2C%22foaf%3Aaccount%22%3A%7B%22%40type%22%3A%22%40id%22%7D%2C%22void%3AinDataset%22%3A%7B%22%40type%22%3A%22%40id%22%7D%2C%22dbo%22%3A%22http%3A%2F%2Fdbpedia.org%2Fontology%2F%22%7D%2C%22%40graph%22%3A%5B%7B%22%40id%22%3A%22https%3A%2F%2Fw3id.org%2Fpeople%2Fbrechtvdv%2F%23me%22%2C%22%40type%22%3A%22foaf%3APerson%22%2C%22owl%3AsameAs%22%3A%22https%3A%2F%2Fbrechtvdv.solid.community%2Fprofile%2Fcard%23me%22%2C%22foaf%3Aname%22%3A%22Brecht%20Van%20de%20Vyvere%22%2C%22foaf%3AgivenName%22%3A%5B%7B%22%40value%22%3A%22Brecht%22%2C%22%40language%22%3A%22nl%22%7D%2C%7B%22%40value%22%3A%22Brecht%22%2C%22%40language%22%3A%22en%22%7D%5D%2C%22foaf%3AfamilyName%22%3A%5B%7B%22%40value%22%3A%22Van%20de%20Vyvere%22%2C%22%40language%22%3A%22nl%22%7D%2C%7B%22%40value%22%3A%22Van%20de%20Vyvere%22%2C%22%40language%22%3A%22en%22%7D%5D%2C%22foaf%3Aimg%22%3A%22https%3A%2F%2Fbrechtvdv.github.io%2Fprofile.jpg%22%2C%22foaf%3Ambox%22%3A%5B%22mailto%3Abrecht.vandevyvere%40ugent.be%22%2C%22mailto%3Abr5cht%40hotmail.com%22%5D%2C%22ldp%3Ainbox%22%3A%22https%3A%2F%2Fbrechtvdv.solid.community%2Finbox%2F%22%2C%22pim%3Astorage%22%3A%5B%22https%3A%2F%2Fbrechtvdv.solid.community%2Fpublic%2F%22%2C%22https%3A%2F%2Fbrechtvdv.solid.community%2F%22%5D%2C%22pim%3ApreferencesFile%22%3A%22https%3A%2F%2Fbrechtvdv.solid.community%2Fsettings%2Fprefs.ttl%22%2C%22solidterms%3ApublicTypeIndex%22%3A%5B%22https%3A%2F%2Fbrechtvdv.solid.community%2Fprofile%2FpublicTypeIndex.ttl%22%2C%22https%3A%2F%2Fbrechtvdv.solid.community%2Fsettings%2FpublicTypeIndex.ttl%22%5D%2C%22solidterms%3AprivateTypeIndex%22%3A%22https%3A%2F%2Fbrechtvdv.solid.community%2Fsettings%2FprivateTypeIndex.ttl%22%2C%22solidterms%3Aaccount%22%3A%22https%3A%2F%2Fbrechtvdv.solid.community%2Fprofile%2Fcard%2F%22%2C%22dbo%3AorcidId%22%3A%220000-0002-7671-6203%22%2C%22foaf%3Aaccount%22%3A%5B%22https%3A%2F%2Ftwitter.com%2Fbrechtvdv%22%5D%2C%22foaf%3Aknows%22%3A%5B%22https%3A%2F%2Fpietercolpaert.be%2F%23me%22%2C%22https%3A%2F%2Fruben.verborgh.org%2Fprofile%2F%23me%22%2C%22https%3A%2F%2Fsven-lieber.org%2Fprofile%23me%22%2C%22https%3A%2F%2Fpieterheyvaert.com%2F%23me%22%2C%22http%3A%2F%2Fwww.rubensworks.net%2F%23me%22%2C%22http%3A%2F%2Fben.de-meester.org%2F%23me%22%2C%22http%3A%2F%2Fcsarven.ca%2F%23i%22%2C%22http%3A%2F%2Fw3id.org%2Fpeople%2Fdylanvanassche%2F%23me%22%5D%7D%2C%7B%22%40context%22%3A%22http%3A%2F%2Fwww.w3.org%2F2006%2Fvcard%2Fns%22%2C%22%40id%22%3A%22https%3A%2F%2Fw3id.org%2Fpeople%2Fbrechtvdv%2F%23me%22%2C%22%40type%22%3A%22Individual%22%2C%22fn%22%3A%22Brecht%20Van%20de%20Vyvere%22%2C%22title%22%3A%22PhD%20researcher%22%2C%22given-name%22%3A%5B%7B%22%40value%22%3A%22Brecht%22%2C%22%40language%22%3A%22nl%22%7D%2C%7B%22%40value%22%3A%22Brecht%22%2C%22%40language%22%3A%22en%22%7D%5D%2C%22family-name%22%3A%5B%7B%22%40value%22%3A%22Van%20de%20Vyvere%22%2C%22%40language%22%3A%22nl%22%7D%2C%7B%22%40value%22%3A%22Van%20de%20Vyvere%22%2C%22%40language%22%3A%22en%22%7D%5D%2C%22hasEmail%22%3A%7B%22%40type%22%3A%22Email%22%2C%22hasValue%22%3A%22mailto%3Abrecht.vandevyvere%40ugent.be%22%7D%2C%22hasAdress%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fdata.vlaanderen.be%2Fid%2Fadres%2F3830588%22%2C%22%40type%22%3A%22Address%22%7D%2C%22hasPhoto%22%3A%22https%3A%2F%2Fbrechtvdv.github.io%2Fprofile.jpg%22%2C%22organization-name%22%3A%22IDLab%22%2C%22role%22%3A%22PhD%20researcher%22%7D%2C%7B%22%40context%22%3A%22https%3A%2F%2Fschema.org%22%2C%22%40id%22%3A%22https%3A%2F%2Fw3id.org%2Fpeople%2Fbrechtvdv%2F%23me%22%2C%22%40type%22%3A%22Person%22%2C%22address%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fdata.vlaanderen.be%2Fid%2Fadres%2F3830588%22%7D%2C%22colleague%22%3A%5B%22https%3A%2F%2Fpietercolpaert.be%2F%23me%22%2C%22https%3A%2F%2Fruben.verborgh.org%2Fprofile%2F%23me%22%2C%22https%3A%2F%2Fsven-lieber.org%2Fprofile%23me%22%2C%22https%3A%2F%2Fpieterheyvaert.com%2F%23me%22%2C%22http%3A%2F%2Fwww.rubensworks.net%2F%23me%22%2C%22http%3A%2F%2Fben.de-meester.org%2F%23me%22%2C%22http%3A%2F%2Fw3id.org%2Fpeople%2Fdylanvanassche%2F%23me%22%5D%2C%22email%22%3A%22mailto%3Abrecht.vandevyvere%40ugent.be%22%2C%22image%22%3A%22https%3A%2F%2Fbrechtvdv.github.io%2Fprofile.jpg%22%2C%22name%22%3A%22Brecht%20Van%20de%20Vyvere%22%2C%22url%22%3A%22https%3A%2F%2Fbrechtvdv.github.io%22%2C%22owns%22%3A%22https%3A%2F%2Fbrechtvdv.solid.community%2Fprofile%2Fcard%23me%22%7D%2C%7B%22%40id%22%3A%22https%3A%2F%2Fbrechtvdv.github.io%2F%23Dataset%22%2C%22%40type%22%3A%22void%3ADataset%22%2C%22dcterms%3Asubject%22%3A%22https%3A%2F%2Fw3id.org%2Fpeople%2Fbrechtvdv%2F%23me%22%2C%22foaf%3AprimaryTopic%22%3A%22https%3A%2F%2Fw3id.org%2Fpeople%2Fbrechtvdv%2F%23me%22%2C%22dcterms%3Adescription%22%3A%22Dataset%20about%20Brecht%20Van%20de%20Vyvere%22%2C%22void%3Adatadump%22%3A%7B%22%40id%22%3A%22https%3A%2F%2Fbrechtvdv.github.io%2F%22%2C%22license%22%3A%22https%3A%2F%2Fcreativecommons.org%2Fpublicdomain%2Fzero%2F1.0%2F%22%2C%22rdfs%3Alabel%22%3A%22Website%20of%20Brecht%20Van%20de%20Vyvere%22%2C%22rdfs%3Acomment%22%3A%22This%20document%20shows%20how%20to%20publish%20personal%20data%20through%20rich%20snippets%20(JSON-LD).%22%2C%22void%3AinDataset%22%3A%22https%3A%2F%2Fbrechtvdv.github.io%2F%23Dataset%22%7D%7D%5D%7D) 

http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fbrechtvdv.github.io%2Fold&query=SELECT%20*%20WHERE%20%7B%0A%20%20GRAPH%20%3Fg%20%7B%0A%20%20%3Fs%20%3Fp%20%3Fo.%0A%20%20%7D%0A%7D&httpProxy=http%3A%2F%2Fproxy.linkeddatafragments.org%2F

https://rdf-play.rubensworks.net/#url=https%3A%2F%2Fbrechtvdv.github.io%2Fold&proxy=https%3A%2F%2Fproxy.linkeddatafragments.org%2F

**Comment by rubensworks** [comment]
Since this JSON-LD is part of HTML, this is intentional and according to what the JSON-LD spec describes. (There's even a spec test for this exact case!)

Essentially, this is because JSON-LD requires all applicable script tag contents to be wrapped in an array, and then this array is parsed as a global JSON-LD document afterwards. This will lead to `@graph` not being related to the default graph anymore.
See more details here: https://www.w3.org/TR/json-ld-api/#x9-5-1-process-html

I agree that it's a bit illogical (I had to build in a special edge-case in my parser to handle this).
