### ISSUE TITLE
Issue using FROM instead of GRAPH with QPF endpoint

### ISSUE THREAD

**Issue by jaw111** [comunica/comunica#665]
#### Issue type:

- :snail: Performance issue

____
#### Description:

I encounter an issue with how queries with a `FROM` clause instead of `GRAPH` clause are executed.

Using this QPF endpoint as a running example: https://data-beta.linkeddatafragments.org/gent

With `GRAPH` clause [link](http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fdata-beta.linkeddatafragments.org%2Fgent&query=PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT%20*%0AWHERE%20%7B%0A%20%20graph%20%3Chttp%3A%2F%2Fschema.org%2F%3E%20%7B%0A%20%20%20%20%3Fs%20a%20rdfs%3AClass%20%3B%0A%20%20%20%20%20%20rdfs%3Alabel%20%3Fo%0A%20%20%7D%0A%7D):

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT *
WHERE {
  graph <http://schema.org/> {
    ?s a rdfs:Class ;
      rdfs:label ?o
  }
}
```

With `FROM` clause [link](http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fdata-beta.linkeddatafragments.org%2Fgent&query=PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT%20*%0AFROM%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0AWHERE%20%7B%0A%20%20%3Fs%20a%20rdfs%3AClass%20%3B%0A%20%20%20%20%20rdfs%3Alabel%20%3Fo%0A%7D):

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT *
FROM <http://schema.org/>
WHERE {
  ?s a rdfs:Class ;
     rdfs:label ?o
}
```

Observing the logs one can see the `GRAPH` form takes the approach to fetch pages matching `http://schema.org/ImageObject http://www.w3.org/1999/02/22-rdf-syntax-ns#type ?type http://schema.org/` then for each `?s` result binding makes a request like `http://schema.org/ImageObject http://www.w3.org/2000/01/rdf-schema#label ?o http://schema.org/`.

Whilst the `FROM` form takes the approach to fetch pages matching `?s predicate: http://www.w3.org/2000/01/rdf-schema#label ?o http://schema.org/` and pages matching `?s http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://www.w3.org/2000/01/rdf-schema#Class http://schema.org/` and effect the join in the client. This leads to some odd behavior for this query as the client will fetch all pages for both patterns. This is an issue when working with larger datasets.

____

**Comment by rubensworks** [comment]
Thanks for reporting.

This is actually known behaviour (#128).
I'll merge this issue into #128, so we can follow up there.
