### ISSUE TITLE
Migrate to asynciterator v3.0.0 for microtasks / better browser performance

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#668]
#### Issue type:

- :snail: Performance issue

____
#### Description:

https://github.com/RubenVerborgh/AsyncIterator/issues/13 established that microtasks would be better for performance.
I have released `asynciterator@v3.0.0-alpha.0` with microtask semantics.

Could you please test and see if it works as expected?
This is a semver.major change, so some tests might need adjusting.

I am also considering switching to `import`/`export` for v3.0.0, although I'm not sure yet.
I don't like how the current export is `AsyncIterator` with several subclasses attached to it, but then again `export` might be overkill. Just checking whether you have any recommendations or suggestions in this regard, or whether it would impact Comunica.

____
#### Environment:

n/a

**Comment by rubensworks** [comment]
> I am also considering switching to import/export for v3.0.0, although I'm not sure yet.

No problems with this on my end. I'll just have to update the typings if you decide to make that change.

If you think that's valuable, we could also integrate the typings file into the asynciterator package. But that's not essential IMO.

**Comment by RubenVerborgh** [comment]
@rubensworks I have now released `asynciterator@v3.0.0-beta.0`, which now has ES6 exports.

Changes w.r.t. typings:
- you already have assumed that classes are exported individually; this remains the same
- the static `wrap` is now an export
- the static `range` has been removed
- the static `STATES` has been removed
- the states themselves (`INIT` etc.) are now exports

I'd be willing to add the types to the repository itself. However, all underscore methods would become `protected`. Would you see issues?

**Comment by RubenVerborgh** [comment]
And `v3.0.0-beta.1` is now written in TypeScript, so it comes with correct types.

**Comment by rubensworks** [comment]
> And v3.0.0-beta.1 is now written in TypeScript, so it ships with correct types.

Nice :-)
Remind me to deprecate the typings at DefinitelyTyped once the v3.0.0 is actually released.

**Comment by RubenVerborgh** [comment]
Was looking at what would be needed for a replacement, and then also noticed https://github.com/rubensworks/asynciterator-promiseproxy.js/blob/master/lib/PromiseProxyIterator.ts

That functionality should now be part of the regular `TransformIterator` in `v3.0.0-beta.2` (https://github.com/RubenVerborgh/AsyncIterator/commit/2b5469858b425b3c76ac2daff8caba2f99cb7281). This includes lazy initialization, by setting `{ autoStart: false }`. I did not make the source loading function public (https://github.com/rubensworks/asynciterator-promiseproxy.js/commit/23030ff10d90ef7f33dcd87edc1aef3ecfde7148 did), but simply calling `read` or registering a data listener should trigger that. Would that be sufficient, @joachimvh?

Any other things you would need?

I also saw https://github.com/rubensworks/asynciterator-union.js/, but that one is an independent feature and seems a bit more involved (perhaps for v3.1 then), whereas the ability to pass a Promise for a source is much more easily added directly to `TransformIterator`, and its effects ripple through to all subclasses.

**Comment by rubensworks** [comment]
> Was looking at what would be needed for a replacement, and then also noticed https://github.com/rubensworks/asynciterator-promiseproxy.js/blob/master/lib/PromiseProxyIterator.ts

Great, another simplification we can do :-)

>  but simply calling read or registering a data listener should trigger that (or just accessing .source). Would that be sufficient, @joachimvh?

This is the relevant piece of code in Comunica that uses this functionality: https://github.com/comunica/comunica/blob/7d6120841e2893f7c12b02ef5cf7fc39c002c1dc/packages/actor-rdf-resolve-quad-pattern-federated/lib/FederatedQuadSource.ts#L267
So accessing `.source` should be sufficient.

It's a bit weird that calling a getter has side-effects though, but I can live with it.

> Any other things you would need?

No, I think we're good. But will confirm once I migrate the Comunica code.

**Comment by RubenVerborgh** [comment]
> It's a bit weird that calling a getter has side-effects though, but I can live with it.

Yeah, we're essentially accessing internal state of the iterator. Consumers are not really supposed to know when it starts doing things. An alternative is to simply wait with resolving the promise (which, now that I think about it, is probably healthier).

> No, I think we're good.

Ah well I started on the union iterator anyways, it looked like fun 🙂

**Comment by rubensworks** [comment]
@RubenVerborgh I started updating to the new asynciterator version.

Do you want me to PR any typings issues I would discover all in one PR?

I'm also wondering if `_push` should not become public (and renamed). For example, `_push` is required [here](https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-extend/lib/ActorQueryOperationExtend.ts#L42-L60) in a transform lambda. We could always move this to a dedicated class if this is what we want, but it would be a bit more verbose.

**Comment by RubenVerborgh** [comment]
> Do you want me to PR any typings issues I would discover all in one PR?

As you wish; what makes most sense.

> I'm also wondering if `_push` should not become public (and renamed).

No externals should push into an iterator.

> For example, `_push` is required [here](https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-extend/lib/ActorQueryOperationExtend.ts#L42-L60) in a transform lambda.

Probably `transform` needs to take a push function as an argument.

**Comment by RubenVerborgh** [comment]
`UnionIterator` is available in `v3.0.0-beta.3`.

It's a different implementation, but passes the same tests (and some more).

**Comment by rubensworks** [comment]
Migration is done in https://github.com/comunica/comunica/tree/refactor/asynciterator-3

All tests pass again, Node performance is about the same, and speed in the browser seems to be at least twice as fast.

Still waiting on the following before merging into master:
* Update to non-beta version of asynciterator
* Release of updated asyncjoin and asyncreiterable once asynciterator is out of beta (which I will do)

Afterwards, some todo's for me:
* Deprecate old TS typings for asynciterator
* Deprecate my asynciterator addon libs

**Comment by RubenVerborgh** [comment]
Very good, thanks so much. Will follow up today!

**Comment by RubenVerborgh** [comment]
> Update to non-beta version of asynciterator

v3.0.0 has been released

**Comment by RubenVerborgh** [comment]
Super, thanks for the hard work!
