### ISSUE TITLE
Passed Headers object is not standards compatible (not iterable)

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#672]
#### Issue type:

- :bug: Bug

____
#### Description:

It appears that we are sending a `Headers` object to the fetcher that is not standards-compatible, namely it is not iterable. See discussion at https://github.com/inrupt/solid-auth-fetcher/issues/176#issuecomment-642319240

My guess is that this is due to our usage of https://www.npmjs.com/package/isomorphic-fetch, which hasn't been updated in 4 years, and might therefore use an old version of the WHATWG fetch polyfill (although that functionality was also [added 4 years ago there](https://github.com/github/fetch/commit/a1b7674b6942d4265ea47b74760a486b2bf5e3da)).

We'd mainly need a test to check if indeed the object is iterable.
____
#### Environment:

current

**Comment by rubensworks** [comment]
We should transition away from `isomorphic-fetch`, I'm sure there are good alternatives by now.
Ideally, this should just be a matter of changing our imports.
