### ISSUE TITLE
Results for MIN() and MAX() aggregates of string literals are not shown

### ISSUE THREAD

**Issue by jaw111** [comunica/comunica#673]
For example in the [query](http://query.linkeddatafragments.org/#transientDatasources=http%3A%2F%2Ffragments.dbpedia.org%2F2016-04%2Fen&query=SELECT%20%3Fname%20(COUNT(%3Ftitle)%20as%20%3Fcount)%20(MIN(%3Ftitle)%20as%20%3Fmin)%20(MAX(%3Ftitle)%20as%20%3Fmax)%20(GROUP_CONCAT(%3Ftitle%3B%20SEPARATOR%3D%22%2C%20%22)%20as%20%3Fconcat)%20(SAMPLE(%3Ftitle)%20as%20%3Fsample)%0AWHERE%20%7B%0A%20%20%3Fmovie%20dbpedia-owl%3Astarring%20%5B%20rdfs%3Alabel%20%22Brad%20Pitt%22%40en%20%5D%3B%0A%20%20%20%20%20%20%20%20%20rdfs%3Alabel%20%3Ftitle%3B%0A%20%20%20%20%20%20%20%20%20dbpedia-owl%3Adirector%20%5B%20rdfs%3Alabel%20%3Fname%20%5D.%0A%20%20FILTER%20LANGMATCHES(LANG(%3Ftitle)%2C%20%20%22EN%22)%0A%20%20FILTER%20LANGMATCHES(LANG(%3Fname)%2C%20%20%22EN%22)%0A%7D%0Agroup%20by%20%3Fname)

```sparql
SELECT ?name (COUNT(?title) as ?count) (MIN(?title) as ?min) (MAX(?title) as ?max) (GROUP_CONCAT(?title; SEPARATOR=", ") as ?concat) (SAMPLE(?title) as ?sample)
WHERE {
  ?movie dbpedia-owl:starring [ rdfs:label "Brad Pitt"@en ];
         rdfs:label ?title;
         dbpedia-owl:director [ rdfs:label ?name ].
  FILTER LANGMATCHES(LANG(?title),  "EN")
  FILTER LANGMATCHES(LANG(?name),  "EN")
}
group by ?name
```

The bindings for `?min` and `?max` are not shown in the results.

**Comment by rubensworks** [comment]
Thanks for reporting!

This is probably a Sparqlee issue.

**Comment by wschella** [comment]
Specifically, this line https://github.com/comunica/sparqlee/blob/master/lib/evaluators/AggregateEvaluator.ts#L184 will throw when the term value is not numeric.

It call's this function: https://github.com/comunica/sparqlee/blob/master/lib/evaluators/AggregateEvaluator.ts#L306.

I think the bindings not showing is intended behavior, as the expressions error. I do wonder what happens with the error. Error handling is done in comunica, in smth like `SparqleeAggregateExpressionActor`.

Or is there any defined behavior for min/max on strings?
