### ISSUE TITLE
Received metadata AFTER the source iterator was ended.

### ISSUE THREAD

**Issue by dreeki** [comunica/comunica#674]
#### Issue type:

- :bug: Bug

____
#### Description:
When querying with a SPARQL endpoint as source, using a GeoSPARQL implementation, the result is inconsistent. Sometimes the query results the correct answer, sometimes it doesn't return an answer at all and only gives the message "Received metadata AFTER the source iterator was ended.". It's even possible that it returns a part of the result with the message "Received metadata AFTER the source iterator was ended.". I was not able to reproduce the error with other datasources and queries. The result can be seen in the image below. The datasource used in the SPARQL endpoint is: the following: "https://gist.github.com/dreeki/e48bbe533a4b1191045b3652ff2c9c81". The implementation of Comunica is pushed at the following link: "https://github.com/dreeki/comunica". The implementation of sparqlee is pushed at the following link: "https://github.com/dreeki/sparqlee". 

<img width="749" alt="Schermafbeelding 2020-06-15 om 15 43 38" src="https://user-images.githubusercontent.com/22447680/84664801-5863bd80-af1f-11ea-989d-3797e741668b.png">

**Comment by rubensworks** [comment]
Thanks for reporting!

I suspect this is related to #553.
