### ISSUE TITLE
Parsing issue with SPARQL query on inverse paths in anonymous node

### ISSUE THREAD

**Issue by jaw111** [comunica/comunica#677]
#### Issue type:

- :bug: Bug

____
#### Description:

There is an odd combination of syntax that is flagged as an error.

```sparql
SELECT *
WHERE {
  ?movie a dbpedia-owl:Film ;
    dbpedia-owl:starring [
      rdfs:label "Brad Pitt"@en ;
      ^dbpedia-owl:starring ?otherMovie
    ] .
}
```

Gives the error:

```
# Parse error on line 21:
...ad Pitt"@en ;      ^dbpedia-owl:starrin
----------------------^
Expecting 'IRIREF', 'PNAME_NS', 'VAR', '}', 'GRAPH', ';', 'a', ']', 'PNAME_LN', '.', got '^'
```

Whilst removing the triple pattern for `a` works just fine:

```sparql
SELECT *
WHERE {
  ?movie
    dbpedia-owl:starring [
      rdfs:label "Brad Pitt"@en ;
      ^dbpedia-owl:starring ?otherMovie
    ] .
}
```

____
#### Environment:

http://query.linkeddatafragments.org/#transientDatasources=http%3A%2F%2Ffragments.dbpedia.org%2F2016-04%2Fen&query=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0ASELECT%20*%0AWHERE%20%7B%0A%20%20%3Fmovie%20a%20dbpedia-owl%3AFilm%20%3B%0A%20%20%20%20dbpedia-owl%3Astarring%20%5B%0A%20%20%20%20%20%20rdfs%3Alabel%20%22Brad%20Pitt%22%40en%20%3B%0A%20%20%20%20%20%20%5Edbpedia-owl%3Astarring%20%3FotherMovie%0A%20%20%20%20%5D%20.%0A%7D

**Comment by rubensworks** [comment]
Thanks for reporting. This seems like a [SPARQL.js](https://github.com/RubenVerborgh/SPARQL.js/) issue.
@RubenVerborgh Could you confirm? We can probably move this issue to the SPARQL.js repo.

**Comment by RubenVerborgh** [comment]
Yes, parser bug (if query is indeed valid).

**Comment by joachimvh** [comment]
(query is valid)

**Comment by rubensworks** [comment]
This issue has been fixed in SPARQL.js a while ago.
