### ISSUE TITLE
Timeout when quering data through js application

### ISSUE THREAD

**Issue by FlorianFV** [comunica/comunica#698]
#### Issue type:

- :bug: Bug

____
#### Description:

Timeout error occurs when quering the engine.

____
#### Environment:

Errormessage when querying the engine through a js application: https://pastebin.com/Z9mfrRE0

#### Crash log:

https://pastebin.com/ts4d6hdm

**Comment by rubensworks** [comment]
_May_ be a regression of https://github.com/comunica/comunica/commit/1a947ad6ac80b849a9817e1bbc8a330d4eea9a0c#diff-cda33388384fee380a1c49be5c86ddcf

**Comment by rubensworks** [comment]
@stephaniech97 This may be related to your recent change to the native HTTP actor. Could you look into this one?

An easy check would be to undo your change, and seeing what happens.

**Comment by rubensworks** [comment]
While I could reproduce this problem myself before, when now looking into it again, the problem does not appear to be reproducible anymore.
I therefore expect this was a temporary issue with our server, unrelated to the recent changes in Comunica.

Should anyone still encounter this problem, no not hesitate to comment here.

**Comment by stephaniech97** [comment]
This issue was first encountered when fixing the test fail in nodejs 14, Closes #680. 8/07/2020. So this was after the changes in  "Add new fetch import to allow iteration of header, Closes #672". (extra information)

**Comment by rubensworks** [comment]
@stephaniech97 So you are encountering this problem again?
What is the query you are using and the error that is shown?

**Comment by stephaniech97** [comment]
I sometimes have the issue just when running all tests when committing. A re-run often does the trick, so not necessarily that i have encountered it during a specific query.

**Comment by rubensworks** [comment]
@stephaniech97 You are experiencing timeouts during test execution, which is different to the HTTP timeouts this issue is about.
