### ISSUE TITLE
Comunica makes network requests without headers on Node.js

### ISSUE THREAD

**Issue by lucaswerkmeister** [comunica/comunica#700]
#### Issue type:

- :bug: Bug

____
#### Description:

I was trying to use [@comunica/actor-init-sparql](https://github.com/comunica/comunica/tree/master/packages/actor-init-sparql) with the [Wikidata LDF service](https://query.wikidata.org/bigdata/ldf). Based on the README, this one-liner should more or less work:

```js
void require( '@comunica/actor-init-sparql' ).newEngine().query( 'SELECT * WHERE { <http://www.wikidata.org/entity/Q42> <http://www.wikidata.org/prop/direct/P31> ?class. }', { sources: [ 'https://query.wikidata.org/bigdata/ldf' ] } ).then( ( { bindingsStream } ) => bindingsStream.on( 'data', data => console.log( data.toObject() ) ), console.error )
```

(It’s not very nice code, but having it as a one-liner was convenient while investigating this issue. The `void` operator avoids printing the returned `Promise` in the REPL.) However, it fails because Wikidata responds with a 403 Forbidden error. I think this is because the request is missing a User-Agent header (which is [required on all Wikimedia sites](https://meta.wikimedia.org/wiki/User-Agent_policy)); when you add some `console.log()`s on request and response objects, it certainly *looks* like the request is including headers (including a default user agent), but buried deeply in Node internal objects you also find this:

```js
    _header: 'GET /bigdata/ldf HTTP/1.1\r\n' +                                                                                                                               
      'Host: query.wikidata.org\r\n' +                                                                                                                                       
      'Connection: close\r\n' +                                                                                                                                              
      '\r\n',
```

That seems to be the actual TCP payload for the HTTP request, and it doesn’t have any custom headers. I *think* this is because the `headers` object which Comunica passes down into Node’s request library ([http](https://nodejs.org/api/http.html)/[https](https://nodejs.org/api/https.html), wrapped in [follow-redirects](https://www.npmjs.com/package/follow-redirects), called in [@comunica/actor-http-native’s Requester](https://github.com/comunica/comunica/blob/d211aef87125a171b52ecc56ccd06a25b3a6a3b7/packages/actor-http-native/lib/Requester.ts)) is an instance of some `Headers` class (probably the one from [node-fetch](https://www.npmjs.com/package/node-fetch)), whereas Node expects a plain object as `headers`; since Node doesn’t recognize the `Headers` object, the request is made without any custom headers.

The following JS code produces the same issue:
```js
const https = require( 'https' );
const { Headers } = require( 'node-fetch' );

https.request(
	'https://query.wikidata.org/bigdata/ldf',
	{
		headers: new Headers( {
			accept: 'application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.5,application/rdf+xml;q=0.5,application/json;q=0.45,text/n3;q=0.35,application/xml;q=0.3,text/xml;q=0.3,image/svg+xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18',
			'user-agent': 'Comunica/actor-http-native (Node.js v14.5.0; linux)',
		} ),
	},
	( { statusCode, req: { _header } } ) => {
		console.log( statusCode );
		console.log( _header );
	},
).end();
```

____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.14.0 
| node                | v14.5.0
| npm                 | 6.14.5
| yarn                | _Yarn is unavailable_
| Operating System    | linux (Linux 5.4.0-40-generic)

**Comment by rubensworks** [comment]
Ouch, probably a regression due to 996d286500c9f71b8eb5c1786017b9c2ea54227f.

@stephaniech97 could you look into this one? Looks like a problem in actor-http-native.

Thanks for reporting!
