### ISSUE TITLE
Question: how to query specific SPARQL endpoints with Comunica?

### ISSUE THREAD

**Issue by sdevalk** [comunica/comunica#704]
#### Issue type:

- :question: Question

____
#### Question:

How can I query the SPARQL endpoints underneath with Comunica?

**Getty vocabularies**
`npx comunica-sparql sparql@http://vocab.getty.edu/sparql -q "SELECT * WHERE { ?s ?p ?o } LIMIT 10"`

Response: `[Invalid SPARQL endpoint (http://vocab.getty.edu/sparql) response: undefined`

A direct call does return results:
`curl -H "Accept: application/sparql-results+json" "http://vocab.getty.edu/sparql?query=SELECT%20%3Fs%20%3Fp%20%3Fo%20WHERE%20%7B%20%3Fs%20%3Fp%20%3Fo.%20%7D%0ALIMIT%2010"`

**Wikidata**
`npx comunica-sparql sparql@https://query.wikidata.org/sparql -q "SELECT * WHERE { ?s ?p ?o } LIMIT 10"`

Response: `[Invalid SPARQL endpoint (https://query.wikidata.org/sparql) response: undefined`

A direct call does return results:
`curl -H "Accept: application/sparql-results+json" "https://query.wikidata.org/sparql?query=SELECT%20%2A%20WHERE%20%7B%3Fs%20%3Fp%20%3Fo%20%7D%20LIMIT%2010"`

**RKDartists**
`npx comunica-sparql sparql@https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/services/rkdartists/sparql -q "SELECT * WHERE { ?s ?p ?o } LIMIT 10"`

Response: `[Unknown SPARQL results content type: application/json`

A direct call does return results:
`curl -H "Accept: application/sparql-results+json" "https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/services/rkdartists/sparql?query=SELECT%20%2A%20WHERE%20%7B%3Fs%20%3Fp%20%3Fo%20%7D%20LIMIT%2010"`

____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.14.0
| node                | v12.18.2
| npm                 | 6.14.5
| yarn                | 1.22.4
| Operating System    | linux (Linux 4.19.76-linuxkit)

**Comment by rubensworks** [comment]
Thanks for reporting. Seems similar to #619 where the specifics of certain endpoints cause problems when Comunica tries to query over them.

**Comment by rubensworks** [comment]
I just tried this with the latest version (1.16.2), and all querying over all three endpoints seem to be working without problems. I suspect a recent change in header handling fixed this problem as well.

Feel free to re-open this issue should you still encounter problems with this.

**Comment by sdevalk** [comment]
Works perfectly! Thanks Ruben!
