### ISSUE TITLE
Query suddenly stops

### ISSUE THREAD

**Issue by pheyvaer** [comunica/comunica#724]
#### Issue type:

- :bug: Bug

____
#### Description:

When using the following command
```
 comunica-sparql https://data.betweenourworlds.org/latest -f my-query.query -c config.json -i graphql -l debug
```
it suddenly stops with this output
```
[2020-08-25T09:00:06.334Z]  INFO: Requesting https://data.betweenourworlds.org/latest {
  actor: 'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher'
}
[2020-08-25T09:00:06.566Z]  INFO: Identified as qpf source: https://data.betweenourworlds.org/latest {
  actor: 'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/resolve-hypermedia.json#myHypermediaQpfResolver'
}
[2020-08-25T09:00:06.568Z]  INFO: Requesting https://data.betweenourworlds.org/latest?predicate=http%3A%2F%2Fschema.org%2Fname {
  actor: 'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher'
}
[2020-08-25T09:00:06.625Z]  INFO: Requesting https://data.betweenourworlds.org/latest?predicate=http%3A%2F%2Fschema.org%2Freview {
  actor: 'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher'
}
[
```
The contents of `my-query.query` is
```
{
  id @single
  name @single
  review @single {
    rating(value: "5")
  }
}

```
and `config.json` is
```
{
  "@context": {
    "schema": "http://schema.org/",
    "review": "schema:review",
    "rating": "schema:reviewRating",
    "value": "schema:ratingValue",
    "name": { "@id": "schema:name", "@language": "en"}
  }
}
```
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.16.2 
| node                | v14.8.0
| npm                 | 6.14.8
| yarn                | 1.21.1
| Operating System    | linux (Linux 4.15.0-112-generic)

**Comment by rubensworks** [comment]
Ouch, that's not good. Did this query work for you before?

**Comment by pheyvaer** [comment]
First time I tried this one. 

Also it seems to work [here](http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fdata.betweenourworlds.org%2Flatest&query=%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%20%40single%0A%20%20%20%20%20%20%20%20%20%20%20%20name%20%40single%0A%20%20%20%20%20%20%20%20%20%20%20%20review%20%40single%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20rating(value%3A%202)%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D&queryContext=%7B%0A%20%20%22%40context%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22schema%22%3A%20%22http%3A%2F%2Fschema.org%2F%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22review%22%3A%20%22schema%3Areview%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22rating%22%3A%20%22schema%3AreviewRating%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22value%22%3A%20%22schema%3AratingValue%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%7B%20%22%40id%22%3A%20%22schema%3Aname%22%2C%20%22%40language%22%3A%20%22en%22%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%7D&resultsToTree=false&queryFormat=graphql). No results are expected.

**Comment by rubensworks** [comment]
I think this is related to #553 (hope it's not though).

**Comment by pheyvaer** [comment]
Using 2 data sources works: 

```
comunica-sparql https://data.betweenourworlds.org/latest http://localhost:8080/ratings.ttl -f my-query.query -c config.json -i graphql -l debug
```
The contents of `ratings.ttl` is
```
@prefix schema: <http://schema.org/> .
@prefix anime: <https://betweenourworlds.org/anime/> .

anime:naruto schema:review [
                           a schema:Review;
                           schema:reviewRating [
                                   schema:bestRating: 5;
                                   schema:worstRating 1;
                                   schema:ratingValue 4
                                   ]
                           ].
```

But the result is not what I expect. Actual result
```
{"?name":"\"Golden Time\"","?id":"https://betweenourworlds.org/anime/golden-time","?review_rating":"_:bc_1_n3-51"},
{"?name":"\"Golden Time\"@en","?id":"https://betweenourworlds.org/anime/golden-time","?review_rating":"_:bc_1_n3-52"},
{"?name":"\"Golden Time\"@ja","?id":"https://betweenourworlds.org/anime/golden-time","?review_rating":"_:bc_1_n3-53"},
{"?name":"\"ゴールデンタイム\"@ja","?id":"https://betweenourworlds.org/anime/golden-time","?review_rating":"_:bc_1_n3-54"}
```
Expect result
```
{"?name":"\"Golden Time\"@en","?id":"https://betweenourworlds.org/anime/golden-time","?review_rating":"_:bc_1_n3-52"}
```

**Comment by rubensworks** [comment]
For reference, minimal example to reproduce:
```
SELECT ?rating WHERE {
  ?df_0 <http://schema.org/reviewRating> ?rating.
  ?rating <http://schema.org/ratingValue> "5".
}
```

**Comment by rubensworks** [comment]
Root cause: https://github.com/RubenVerborgh/AsyncIterator/issues/22

**Comment by rubensworks** [comment]
Fixed in 733
