### ISSUE TITLE
Error "This actor can only parse SPARQL queries"

### ISSUE THREAD

**Issue by andrefs** [comunica/comunica#730]
#### Issue type:

- :bug: Bug

____
#### Description:

Not sure whether I'm doing this wrong or whether this is a new bug.

I can't run any queries using `comunica-sparql-file` because it always returns the following:
```
https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/sparql-init.json#mediatorSparqlParse mediated over all rejecting actors:
This actor can only parse SPARQL queries
```

The same happens with `comunica-sparql-hdt`.

#### MWE

test.nt
```
_:a _:b _:c .
```

Command:
```
$ comunica-sparql-file test.nt -q 'SELECT * WHERE { ?s ?p ?o } LIMIT 10'  -tsimple
```
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.16.2 
| node                | v14.9.0
| npm                 | 6.14.7
| yarn                | 1.22.5
| Operating System    | linux (Linux 3.17.8-200.fc20.x86_64)

**Comment by andrefs** [comment]
Nevermind, several mistakes on my end, sorry :roll_eyes:

**Comment by rubensworks** [comment]
Great to hear you found the problem.

In case anyone else would be reading this, the problem is that `-tsimple` was missing a space: `-t simple`.
