### ISSUE TITLE
Return type of bindings is incorrect

### ISSUE THREAD

**Issue by allforabit** [comunica/comunica#742]
#### Issue type:

- :bug: Bug 

____
#### Description:

This is a small issue but the result after running a query and calling `bindings()` seems to have the incorrect typescript type. It should be a js Map but it's typed as an rdf term.

____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.17.0 
| node                | v14.13.0
| npm                 | 6.14.8
| yarn                | 2.2.2
| Operating System    | win32 (Windows_NT 10.0.18363)

**Comment by rubensworks** [comment]
Thanks for reporting!
