### ISSUE TITLE
Add a way to avoid casting return type of `.query()`

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#746]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

The following pattern seems to occur a lot:
```
const result = <IQueryResultBindings> await this.queryEngine.query(`SELECT * WHERE {...}`, ...)
const bindings = result.bindings();
```

This first cast is not very developer-friendly, so we should provide ways to get rid of it.

# Option 1

Ideally, TypeScript should automatically determine the correct return type.
We may be able to do this using the new [Template Literal Types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#template-literal-types).

This may allow us to do things like _if query starts with SELECT, return type is `IQueryResultBindings`_.

But I'm not sure if this TS feature is expressive enough to handle this.

# Option 2

The following new methods can be added that do an internal cast:
```
const resultBindings: IQueryResultBindings = await this.queryEngine.querySelect(`SELECT * WHERE {...}`, ...);
const resultQuads: IQueryResultQuads = await this.queryEngine.queryConstruct(`CONSTRUCT {...}`, ...);
const resultAsk: IQueryResultBoolean = await this.queryEngine.queryAsk(`ASK {...}`, ...);
```

**Comment by jagij** [comment]
Assuming the code internally knows what type the actual result is, wouldn't it be better to provide a callback object with multiple callbacks? This way, the "right" callback can be called with the correct types, and no casting is needed at all.
Check the Visitor pattern for inspiration.

Example:
```javascript
// other possible callbacks like handleConstruct and handleAsk are not provided, and if the required handler isn't provided the function can just throw an error
const handler = {
handleSelect: (result: IQueryResultBindings) => ...
};
try {
await this.queryEngine.query(`SELECT * WHERE {...}`, handler)
}
catch (err) {
...
}
```

**Comment by rubensworks** [comment]
Thanks for the suggestion @jagij, something to consider indeed.
The only disadvantage I see with this is the inconvenience of nested callbacks when multiple sequential queries need to be executed.

**Comment by rubensworks** [comment]
Done in Comunica 2: https://comunica.dev/docs/query/getting_started/query_app/
