### ISSUE TITLE
await myEngine.query() throws SyntaxError: await is only valid in async function

### ISSUE THREAD

**Issue by bjimmyd** [comunica/comunica#748]
#### Issue type:

- :question: Question 

____
#### Question:

He all, 

I am trying to set up a node js server that will perform sparql queries on a local .ttl file. Problem is that when I launch the server an error occurs: "SyntaxError: await is only valid in async function". The error refers to the line `var result = await myEngine.query(query, statements)`.  I have no clue to what is going on and could not find any usefull information on this error in the github repository or anywhere else online. Can someone help me out?

Full code:

```
const newEngine = require('@comunica/actor-init-sparql').newEngine;
const myEngine = newEngine();

function runSparql(query) {
  var result = await myEngine.query(query, {
    sources: [
      {type: 'file', value: 'statements.ttl'},
    ],
  });
}
```

**Comment by rubensworks** [comment]
Most JS environments do not support top-level awaits.
You'll have to wrap your logic into an async function.
See https://stackoverflow.com/questions/49432579/await-is-only-valid-in-async-function
