### ISSUE TITLE
Bindings are empty, while query and file are working on other applications

### ISSUE THREAD

**Issue by bjimmyd** [comunica/comunica#749]
#### Issue type:

- :question: Question 

____
#### Question:

I am really struggling with getting Comunica to run on my node js project. I have had some errors earlier, but thanks to @rubensworks I was able to fix it. Now the server is running fine and I am able to pass queries to my local .ttl file. However, all queries I run return no results. When I run the same query using comunica in my terminal I do get correct results. 

```
const newEngine = require('@comunica/actor-init-sparql').newEngine;
const myEngine = newEngine();

async function runSparql() {
  query = "select * where { ?s ?p ?o .} limit 100";
  var result = await myEngine.query(query, {
    sources: [{type : 'file', value: 'http://127.0.0.1:4200/server/liveData.ttl'},],
  });
  var bindings = await result.bindings()
  console.log(bindings)  // this prints []
  return bindings
}
```

Please help me once more :) Thanks to all of you in advance!

**Comment by rubensworks** [comment]
That code works on my end. Is your file perhaps empty of invalid?

**Comment by bjimmyd** [comment]
Thanks for your help @rubensworks

I will check wether the file is accessible and valid.

**Comment by bjimmyd** [comment]
I got it now, thanks again @rubensworks
