### ISSUE TITLE
IQueryResultBindings has incorrect type

### ISSUE THREAD

**Issue by alexkreidler** [comunica/comunica#753]
`IQueryResultBindings` in `@comunica/actor-init-sparql/lib/ActorInitSparql-browser.d.ts` has a wrong type for the `bindings` field. It should be

```ts
import { Bindings } from "@comunica/bus-query-operation"
export interface IQueryResultBindings extends IActorQueryOperationOutputBindings {
    /**
     * The collection of bindings after an 'end' event occured.
     */
    bindings: () => Promise<Bindings[]>; // instead of Promise<RDF.Term[]>
}
```
I ran into this after logging the output using `console.log` and `JSON.stringify` and determining that the runtime type was `Map<string, RDF.Term>`

**Comment by rubensworks** [comment]
Thanks for reporting!

This has actually already been reported (and fixed) before: #742.

A new release with a fix for this will be out soon.
