### ISSUE TITLE
Ensure backpressure is maintained in streams

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#759]
#### Issue type:

- :bug: Bug 

____
#### Description:

There seem to be a couple of places where we are not adhering to Node's backpressure conventions with regards to streams.

Concretely, we seem to be creating new streams (such as `Readable`, `PassThrough` and `Transform`), and `push`-ing into them (via a `'data'` handler on another stream). Node handles backpressuring via the return value of `push`, which we are ignoring in this manner.

https://github.com/search?q=repo%3Acomunica%2Fcomunica%20on(%27data&type=code

A better solution would be to simply `pipe` instead of calling `push` on each data element.

Related to https://github.com/rubensworks/rdf-parse.js/commit/269c757935c54b388e1bde076dc29c2afc2e8e7b

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| €1088 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by jeswr** [comment]
As discussed with @rubensworks , I will work on this issue.

**Comment by jacoscaz** [comment]
@jeswr @rubensworks insofar as possible, I would suggest making all internal interfaces between actors use `asynciterator` rather than Node and/or Web streams, which (IMHO) should only be used in public interfaces.

**Comment by rubensworks** [comment]
> I would suggest making all internal interfaces between actors use asynciterator rather than Node and/or Web streams, which (IMHO) should only be used in public interfaces.

I wouldn't do this just yet, since this would cause a breaking change in the API.
Things like RDF parsers and serializers are fine to remain plain streams IMO.
