### ISSUE TITLE
Add centralized docs location for context options

### ISSUE THREAD

**Issue by alexkreidler** [comunica/comunica#760]
I did a search for all `export const KEY_CONTEXT_` in the codebase, and found the following:

```
@comunica/actor-http-memento:datetime
@comunica/actor-http-proxy:httpProxyHandler
@comunica/actor-init-sparql:initialBindings
@comunica/actor-init-sparql:queryFormat
@comunica/actor-init-sparql:singularizeVariables
@comunica/actor-rdf-parse-jsonld:documentLoader
@comunica/actor-rdf-parse-jsonld:strictValues
@comunica/bus-http:include-credentials
@comunica/bus-http:auth
@comunica/bus-query-operation:bgpCurrentMetadata
@comunica/bus-query-operation:bgpParentMetadata
@comunica/bus-query-operation:bgpPatternBindings
@comunica/bus-query-operation:patternParentMetadata
@comunica/actor-init-sparql:baseIRI
@comunica/actor-init-sparql:queryTimestamp
@comunica/bus-query-operation:operation
@comunica/actor-init-sparql:lenient
@comunica/bus-rdf-resolve-quad-pattern:sources
@comunica/bus-rdf-resolve-quad-pattern:source
@comunica/core:log
```

Not every package has adopted the practice of adding their context contributions at the end of each README, and it still would be difficult to get a full accounting of every option by going through each package. 

Thus, I think it would be a good idea to put all of these in a documentation markdown file with their descriptions.

**Comment by rubensworks** [comment]
Thanks for collecting this overview!

> Not every package has adopted the practice of adding their context contributions at the end of each README

In any case, this actually should be done.

> Thus, I think it would be a good idea to put all of these in a documentation markdown file with their descriptions.

This table already aims to do this: https://comunica.dev/docs/query/advanced/context/#2--overview
But it's not complete unfortunately, and only focuses on public context entries by their shortcut.

Perhaps we should just complete that table with _all_ context entries. Additionally, an extra column should be added that shows the full context key (next to its shortcut). (Note that not all context entries have shortcuts)

A PR to https://github.com/comunica/website is definitely welcome!

**Comment by rubensworks** [comment]
Should be resolved with the introduction of `@comunica/context-entries`.

Also, the query context will become type-safe in the next major release.
