### ISSUE TITLE
actor-init-sparql-file interpreting blank nodes as relative IRI's

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#761]
#### Issue type:

- :bug: Bug 

____
#### Description:

When querying over a local file (just a downloaded version of the SHACL ontology); the Sparql Parser in actor-init-sparql-file throws the error 

```
throw new Error('Cannot resolve relative IRI ' + iri + ' because no base IRI was set.');
            ^
Error: Cannot resolve relative IRI bc_0_n3-06 because no base IRI was set.
```
That is just a blank node and not a relative IRI so it should not need to be resolved.
____
#### Environment:

Linux Debian - Node.js v15.1.0

#### Crash log:

Crash Report: https://pastebin.com/D8kG98i3
File being queried (SHACL ontology): https://pastebin.com/6YHenXZ2

**Comment by rubensworks** [comment]
The SPARQL parser seems to be throwing the error, so this is not caused by your RDF file.
Could you share this query? Because this may very well be intended behaviour.

I assume this is related to https://github.com/LDflex/LDflex-Comunica/issues/22 ?

**Comment by jeswr** [comment]
I was working with similar data to https://github.com/LDflex/LDflex-Comunica/issues/22. After a bit more digging it seems the issue is with a `.predicatesOf` method I had added to my fork of LDflex with the way it was using the `finalClause` function.
The resultant query was actually
```
SELECT DISTINCT ?predicate WHERE {
  <bc_0_n3-06> ?predicate ?object.
}
``` 
so the error here makes total sense.
