### ISSUE TITLE
SPARQL endpoint, serialize to specific format 

### ISSUE THREAD

**Issue by nikosgi** [comunica/comunica#762]
#### Issue type:

- :heavy_plus_sign: Feature request
- :question: Question

#### Description:

Is there a flag that can be used when setting up a SPARQL endpoint via the comunica-sparql-http command, that allows serializing to a specific format (e.g 'application/sparql-results+json') 

____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.18.0
| node                | v12.19.0
| npm                 | 6.14.8
| yarn                | _Yarn is unavailable_
| Operating System    | win32 (Windows_NT 10.0.18363)

**Comment by vemonet** [comment]
Use content-negociation:

```bash
curl -X GET "http://nanopub-sparql.137.120.31.102.nip.io/sparql?query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0APREFIX+bl%3A+%3Chttps%3A%2F%2Fw3id.org%2Fbiolink%2Fvocab%2F%3E%0APREFIX+d2s%3A+%3Chttps%3A%2F%2Fw3id.org%2Fd2s%2F%3E%0APREFIX+sio%3A+%3Chttp%3A%2F%2Fsemanticscience.org%2Fresource%2F%3E%0APREFIX+bio2rdf%3A+%3Chttp%3A%2F%2Fbio2rdf.org%2F%3E%0APREFIX+covid%3A+%3Chttp%3A%2F%2Fidlab.github.io%2Fcovid19%23%3E%0APREFIX+dc%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F%3E%0APREFIX+dct%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX+dctypes%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fdcmitype%2F%3E%0APREFIX+foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX+idot%3A+%3Chttp%3A%2F%2Fidentifiers.org%2Fidot%2F%3E%0APREFIX+dcat%3A+%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0APREFIX+void%3A+%3Chttp%3A%2F%2Frdfs.org%2Fns%2Fvoid%23%3E%0APREFIX+void-ext%3A+%3Chttp%3A%2F%2Fldf.fi%2Fvoid-ext%23%3E%0APREFIX+obo%3A+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2F%3E%0APREFIX+ncit%3A+%3Chttp%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23%3E%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX+schema%3A+%3Chttp%3A%2F%2Fschema.org%2F%3E%0APREFIX+omop%3A+%3Chttp%3A%2F%2Fapi.ohdsi.org%2FWebAPI%2Fvocabulary%2Fconcept%2F%3E%0APREFIX+cohd%3A+%3Chttps%3A%2F%2Fw3id.org%2Ftrek%2Fcohd%2F%3E%0ASELECT+DISTINCT+%3Fn00+%3Fn00name+%3Fn01+%3Fn01name+%3Fe00+WHERE+%7B+%0A%3Fn00+a+bl%3ADrug.+%0AOPTIONAL+%7B%3Fn00+bl%3Aname+%3Fn00name+.+%7D%0A%3Fn01+a+bl%3ADisease.+%0AOPTIONAL+%7B%3Fn01+bl%3Aname+%3Fn01name+.+%7D%0A%3Fe00+a+bl%3AAssociation.+%0A%3Fe00+bl%3Asubject+%3Fn00+.+%0A%3Fe00+bl%3Aobject+%3Fn01+.+%0A%7D" -H  "accept: application/sparql-results+json"
```

**Comment by vemonet** [comment]
Fyi @rubensworks this issue might come from the fact that recently (a few weeks ago) it seems like the default result returned by the comunica http SPARQL endpoint is not the standard SPARQL JSON (https://www.w3.org/TR/sparql11-results-json/) result but this weird JSON:

```json
[
{"?n00":"https://identifiers.org/CHEBI:46195","?n01":"https://identifiers.org/MONDO:0021146","?e00":"http://purl.org/np/RAKSeSviwbfaOpyPaXeZL3V_k1krWVUo7NHsXQBRqbhTA#association"},
{"?n00":"https://identifiers.org/CHEBI:46195","?n01":"https://identifiers.org/MONDO:0021146","?e00":"http://purl.org/np/RAgqnTY_98lUN3kbRxzpYinpIUSP5ltzSSVnyqKGdcazU#association"}
]

```

**Comment by vemonet** [comment]
As a consequence querying a Comunica SPARQL endpoint does not work anymore with RDF4J for SELECT queries

Here a snippet that was working before:

```java
SPARQLRepository repo = new SPARQLRepository();
TupleQueryResult selectResults = null;

RepositoryConnection conn = repo.getConnection();

TupleQuery tupleQuery = conn.prepareTupleQuery(queryString);
selectResults = tupleQuery.evaluate();
```

I tried to define the accept header when querying with RDF4J, but it does not seems to work (not sure if it's on RDF4J or Comunica though)

```java
SPARQLRepository repo = new SPARQLRepository();
TupleQueryResult selectResults = null;

Map<String, String> headers = new HashMap<String, String>();
headers.put("accept", "application/sparql-results+json");
repo.setAdditionalHttpHeaders(headers);
RepositoryConnection conn = repo.getConnection();

TupleQuery tupleQuery = conn.prepareTupleQuery(queryString);
selectResults = tupleQuery.evaluate();
```

**Comment by vemonet** [comment]
@rubensworks I found the culprit!

Commit https://github.com/comunica/comunica/commit/cdde3559b51825eaebb686fffe0a9edf7c8ef238

Not sure what was tried here but the vast majority of SPARQL developers work with the standard that has been define 7 years ago by the w3c (https://www.w3.org/TR/sparql11-results-json/), the standard is easy to read for machine and humans and already lightweight so there is no reason to create a new standard for SPARQL Select results

Otherwise we will reimplement all SPARQL query resolution just for Comunica 

https://github.com/comunica/comunica/issues/662

Also note that most RDF libraries are not well implemented and things that should be standard like content-negociation is not supported by all libraries. See my example of RDF4J who does not support redefining Http Headers

**Comment by vemonet** [comment]
https://github.com/comunica/comunica/pull/695

Should Semantic web tools promote well described standard? Or ad hoc JSON format described in a GitHub Pull request?

**Comment by rubensworks** [comment]
Long story short: there were some problems with conneg indeed (f4d672086cc9f1bd620733480c87f3c8e252d6ee).
Up until now, non-determinism could occur when no valid content type was found.

In the latest release (1.18.1), conneg issues are fixed, and content type will fallback to SPARQL JSON (TriG for construct queries).
