### ISSUE TITLE
DESCRIBE of blank node subjects creates quads that cannot be collated

### ISSUE THREAD

**Issue by gsvarovsky** [comunica/comunica#765]
#### Issue type:

- :bug: Bug 

(I think; see below)

____
#### Description:

When using DESCRIBE to emit quads related to a subject which happens to be a blank node, each quad returned uses a different blank node identifier in the subject position.

I think this is because DESCRIBE is implemented [in terms of CONSTRUCT](https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-describe-subject/lib/ActorQueryOperationDescribeSubject.ts), which correctly "requires blank nodes to not be reused within different solution mappings" (https://gitter.im/comunica/Lobby?at=5d92eeaa290b8c354a08328b).

For DESCRIBE this behaviour is certainly counter-intuitive (if not contrary to the spec, which has nothing to say on the matter).

[Example on http://query.linkeddatafragments.org/](http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fruben.verborgh.org%2Fprofile%2F&query=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0Adescribe%20%3Fbnode%20where%20%7B%0A%20%20%3Fbnode%20rdf%3Afirst%20%3Fo%20.%0A%20%20%3Fbnode%20rdf%3Arest%20rdf%3Anil%0A%7D%0Alimit%2010%20)

____
#### Environment:

My actual use-case is via https://github.com/beautifulinteractions/node-quadstore which uses a custom comunica bundle.

**Comment by rubensworks** [comment]
In general, I do not recommend using `DESCRIBE` for anything other than ad-hoc data discovery, because the spec does not define its behaviour fully, and different SPARQL engines may therefore produce different results.
For this reason, I'm a bit hesitant to implement use-case-specific behaviour for `DESCRIBE`.

Could you share some more information on your actual use case? Perhaps we can figure out a way to solve it without depending on `DESCRIBE`.

**Comment by gsvarovsky** [comment]
Hi @rubensworks, thanks for having a look. I agree in principle.

As of this morning I have re-considered my case, to use Skolemization by default (for other reasons too). Sorry to have taken your time, I hope knowing about the defect is better than not!

For reference, my project exposes a SPARQL-like interface itself, which also supports DESCRIBE, so it is inheriting the comunica behaviour. However, my API is JSON-LD, so I was ending up with the following (eliding some details):

1. Insert `{ "name": "George", "height": 6 }`
1. Describe where name is "George" =>
```
[
  { "name": "George" },
  { "height": 6 }
]
```
which is clearly a little weird.

**Comment by rubensworks** [comment]
Good to hear you went for the skolemization route, that's indeed a much safer option compared to bnodes.

This specific case here should (if I remember correctly) in fact be connected to the same bnode. So this may indeed be a problem somewhere in Comunica. Something to investigate.

**Comment by jacoscaz** [comment]
This should probably be re-evaluated considering #803

**Comment by rubensworks** [comment]
I'm assuming this can be closed.
@gsvarovsky Feel free to comment here if you think this should be re-opened.
