### ISSUE TITLE
Could not run config urn:comunica:my

### ISSUE THREAD

**Issue by brechtvdv** [comunica/comunica#771]
#### Issue type:

- :question: Question 

```
> comunica-compile-config config/config-default.json > engine-default.js

Error: Could not run config urn:comunica:my because exactly one valid component type was expected, while 0 were found in the defined types [https://linkedsoftwaredependencies.org/bundles/npm/actor-init-ldes/LDESClient]. Alternatively,
the requireName and requireElement must be provided.
Found: Resource {
  value: 'urn:comunica:my',
  termType: 'NamedNode',
  'http://www.w3.org/1999/02/22-rdf-syntax-ns#type': [
    Resource {
      value: 'https://linkedsoftwaredependencies.org/bundles/npm/actor-init-ldes/LDESClient',
      termType: 'NamedNode'
    }
  ],
  types: [
    Resource {
      value: 'https://linkedsoftwaredependencies.org/bundles/npm/actor-init-ldes/LDESClient',
      termType: 'NamedNode'
    }
  ]
}
All available usable types: [

```
____
#### Question:

```
{
  "@context": [
    "https://linkedsoftwaredependencies.org/bundles/npm/actor-init-ldes/^1.0.0/components/context.jsonld",
    "https://linkedsoftwaredependencies.org/bundles/npm/@comunica/runner/^1.0.0/components/context.jsonld",
    "https://linkedsoftwaredependencies.org/bundles/npm/@comunica/core/^1.0.0/components/context.jsonld"
  ],
  "@id": "urn:comunica:my",
  "@type": "LDESClient"
}

{
  "@context": "https://linkedsoftwaredependencies.org/bundles/npm/actor-init-ldes/^1.0.0/components/context.jsonld",
  "@id": "npmd:actor-init-ldes",
  "@type": "Module",
  "requireName": "./lib/LDESClient",
  "import": [
    "files-ldes:components/Actor/Init/LDESClient.jsonld"
  ]
}

```

```
{
  "@context": [
    "https://linkedsoftwaredependencies.org/bundles/npm/componentsjs/^3.0.0/components/context.jsonld",
    {
      "npmd": "https://linkedsoftwaredependencies.org/bundles/npm/",
      "ldes": "npmd:actor-init-ldes/",
      "files-ldes": "ldes:^1.0.0/",
      "config": "files-ldes:config/config-default.json#",

  "LDESClient": "ldes:LDESClient"
}
  ]
}
```
```
{
  "@context": [
    "https://linkedsoftwaredependencies.org/bundles/npm/actor-init-ldes/^1.0.0/components/context.jsonld",
    "https://linkedsoftwaredependencies.org/bundles/npm/@comunica/bus-rdf-parse/^1.0.0/components/context.jsonld"
  ],
  "@id": "npmd:actor-init-ldes",
  "components": [
    {
      "@id": "ldes:LDESClient",
      "@type": "Class",
      "requireElement": "LDESClient",
      "comment": "An Linked Data Event Stream client.",
      "parameters": [

  ],
  "constructorArguments": [

  ]
}
  ]
}
```

**Comment by rubensworks** [comment]
Do I understand correctly that `LDESClient` should be a custom Comunica engine? Just like `comunica-sparql-file`?

**Comment by brechtvdv** [comment]
Yes, but without a SPARQL query as input
$ actor-init-ldesclient URL

**Comment by brechtvdv** [comment]
Can I skip the init bus like rdf-parse.js?

**Comment by brechtvdv** [comment]
My code is available here: https://github.com/brechtvdv/event-stream-client/tree/main/packages/actor-init-ldes

**Comment by rubensworks** [comment]
I'm wondering in what way you want to use Comunica in your project?
It is not mentioned in any of the dependencies AFAICS.
Am I correct to assume you want to reuse the Comunica architecture (actors, bus, mediator), without the querying parts?

I assume you are getting the error when running this? https://github.com/brechtvdv/event-stream-client/blob/main/packages/actor-init-ldes/package.json#L27
I'm also not sure how you are able to run this, as there are no dependencies listed in your `package.json`, so this should actually not succeed in starting at all.

**Comment by brechtvdv** [comment]
Yes, I want to reuse the actor/bus/mediator architecture. As a first step, I want to start with one actor and gradually decompose into multiple actors. I should be able to give the actor some parameters (like an URL). It will not reuse the querying actors of Comunica.

Yep, the compile step fails. I'm using Yarn workspaces and put all my dependencies in the root:
https://github.com/brechtvdv/event-stream-client/blob/main/package.json#L61
I'm still new to workspaces :)

**Comment by brechtvdv** [comment]
So it's similar like rdf-parse.js: exposing a CLI and lib, and using the Comunica architecture for different features. Now, I'm trying to make it work without a bus and mediator.

**Comment by brechtvdv** [comment]
I could make it work (https://github.com/brechtvdv/event-stream-client/commit/a791c558520c1c0aa56595c599f4c8d0d75d8bf1)!

Things I learned:
- make sure to add an lsd:components entry in your package.json ("lsd:components": "components/components.jsonld")
- publish your package on NPM registry, so linkedsoftwaredependencies.org can publish your context/config files

**Comment by rubensworks** [comment]
Yay 🎉 

For reference, if 

> make sure to add an lsd:components entry in your package.json

is true, then 

> publish your package on NPM registry, so linkedsoftwaredependencies.org can publish your context/config files

should not be needed during development.
