### ISSUE TITLE
Add (symmetric) hash join algorithm that can handle left joins

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#772]
#### Issue type:

- :snail: Performance issue 

____
#### Description:

This query, generated by LDflex for https://github.com/LDflex/LDflex/issues/67, is slow:

```sparql
SELECT ?contains ?preload_0 ?preload_1 WHERE {
  <https://api.community.hubl.world/skills/> <http://www.w3.org/ns/ldp#contains> ?contains.
  OPTIONAL {
    { ?contains <http://www.w3.org/2000/01/rdf-schema#label> ?preload_0. }
    UNION
    { ?contains <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?preload_1. }
  }
}
```
http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fapi.community.hubl.world%2Fskills%2F&query=SELECT%20%3Fcontains%20%3Fpreload_0%20%3Fpreload_1%20WHERE%20%7B%0A%20%20%3Chttps%3A%2F%2Fapi.community.hubl.world%2Fskills%2F%3E%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fldp%23contains%3E%20%3Fcontains.%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%7B%20%3Fcontains%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3Fpreload_0.%20%7D%0A%20%20%20%20UNION%0A%20%20%20%20%7B%20%3Fcontains%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E%20%3Fpreload_1.%20%7D%0A%20%20%7D%0A%7D

The same query without `OPTIONAL` is fast:

```sparql
SELECT ?contains ?preload_0 ?preload_1 WHERE {
  <https://api.community.hubl.world/skills/> <http://www.w3.org/ns/ldp#contains> ?contains.
  {
    { ?contains <http://www.w3.org/2000/01/rdf-schema#label> ?preload_0. }
    UNION
    { ?contains <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?preload_1. }
  }
}
```
http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fapi.community.hubl.world%2Fskills%2F&query=SELECT%20%3Fcontains%20%3Fpreload_0%20%3Fpreload_1%20WHERE%20%7B%0A%20%20%3Chttps%3A%2F%2Fapi.community.hubl.world%2Fskills%2F%3E%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fldp%23contains%3E%20%3Fcontains.%0A%20%20%7B%0A%20%20%20%20%7B%20%3Fcontains%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3Fpreload_0.%20%7D%0A%20%20%20%20UNION%0A%20%20%20%20%7B%20%3Fcontains%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E%20%3Fpreload_1.%20%7D%0A%20%20%7D%0A%7D

At the moment, it would be faster to execute two separate queries (once query 1 without the `OPTIONAL` block, once query 2) and then merge the result.

____
#### Environment:

```
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.17.0
| node                | v14.4.0
| npm                 | 6.14.9
| yarn                | 1.22.4
| Operating System    | darwin (Darwin 18.7.0)
```

**Comment by RubenVerborgh** [comment]
Small correction: the _re-execution_ of the second query is fast; initial execution is not.
The re-execution of the first query is slow.

**Comment by RubenVerborgh** [comment]
Even a simple query without special constructs is slow: http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fapi.community.hubl.world%2Fskills%2F&query=SELECT%20%3Fcontains%20%3Fpreload_0%20WHERE%20%7B%0A%20%20%3Chttps%3A%2F%2Fapi.community.hubl.world%2Fskills%2F%3E%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fldp%23contains%3E%20%3Fcontains.%0A%20%20%20%20%3Fcontains%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3Fpreload_0.%0A%7D

Interestingly, the majority of the time is spent _before_ we get to line 3 of the log:

```
Requesting https://api.community.hubl.world/skills/ {"headers":{"accept":"application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,*/*;q=0.1","user-agent":"Comunica/actor-http-native (Browser-Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:84.0) Gecko/20100101 Firefox/84.0)"},"actor":"https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher"}
Requesting https://cdn.happy-dev.fr/owl/hdcontext.jsonld {"headers":{"accept":"application/ld+json","user-agent":"Comunica/actor-http-native (Browser-Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:84.0) Gecko/20100101 Firefox/84.0)"},"actor":"https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher"}
Identified as file source: https://api.community.hubl.world/skills/ {"actor":"https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/resolve-hypermedia.json#myHypermediaNoneResolver"}
```

Part of it seems to be related to JSON-LD, because a different format is faster:
http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fruben.verborgh.org%2Ftmp%2Fskills.ttl&query=SELECT%20%3Fcontains%20%3Fpreload_0%20WHERE%20%7B%0A%20%20%3Chttps%3A%2F%2Fapi.community.hubl.world%2Fskills%2F%3E%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fldp%23contains%3E%20%3Fcontains.%0A%20%20%20%20%3Fcontains%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3Fpreload_0.%0A%7D

**Comment by rubensworks** [comment]
Probably mostly caused by the fact that we're always using the left-deep leftjoin actor.
The nested-loop variant (or another) may perform better.
But we'd need a new leftjoin bus before we can mediate between them (similar to our join bus).
So this would be a feature request :-)

The parsing overhead is not easily fixable on our end, since the given JSON-LD document seems to be very unfortunately structured, which makes parsing inherently slow. ([Streaming JSON-LD document profile](https://www.w3.org/TR/json-ld11-streaming/#streaming-document-form) could help out here)

**Comment by RubenVerborgh** [comment]
Tagging @matthieu-fesselier for the JSON-LD structure, and also @sylvainlb to see there is perhaps some effort that can be dedicated to this.

**Comment by sylvainlb** [comment]
@balessan may have an idea

**Comment by balessan** [comment]
> The parsing overhead is not easily fixable on our end, since the given JSON-LD document seems to be very unfortunately structured, which makes parsing inherently slow. (Streaming JSON-LD document profile could help out here)

Thanks @rubensworks for the reference, we'll check that and I will find someone to fix the ordering part.

**Comment by RubenVerborgh** [comment]
@balessan You could also do conneg on your side if that is an option. Then it could be cached.

**Comment by balessan** [comment]
> conneg

@RubenVerborgh what do you mean exactly ? Sounds like an unknown word to me :-)

**Comment by RubenVerborgh** [comment]
My bad! Content negotiation.

**Comment by balessan** [comment]
FYI we pushed a solution regarding the JSON-LD structure, which still needs to be deployed. Will let you know.

**Comment by RubenVerborgh** [comment]
> I would like some details from @RubenVerborgh regarding the content negotiation, what are we missing here ?

That

```
curl -H "Accept: text/turtle" https://api.community.hubl.world/skills/
```

returns Turtle indeed.

We support JSON-LD; but JSON-LD is inherently a slower format for RDF than the others.

**Comment by balessan** [comment]
Ok so not a surprise, we have an opened issue on adding [that serialization here](https://git.startinblox.com/djangoldp-packages/djangoldp/issues/349)

**Comment by rubensworks** [comment]
For reference:

This issue can be resolved (once Comunica 2.x is out) by implementing a (symmetric) hash join algorithm that can handle left joins. That is because currently, the query planner will pick a nested loop join, which has complexity `O(n*m)`, while SHJ has `O(n+m)`.

Our current SHJ can only handle inner joins. Once we have an SHJ that can handle left joins, this query here should cause the query planner to select the SHJ, and result in much better performance. (inspiration can be taken from our hash-based minus implementation)
