### ISSUE TITLE
Don't disable stack traces

### ISSUE THREAD

**Issue by Frando** [comunica/comunica#776]
#### Issue type:

- :bug: Bug 

____
#### Description:

comunica disables all stack traces when `process.env.NODE_ENV === 'production'`. This is not something a library should do. As `Error.stackTraceLimit` is a superglobal affeting the whole context (browser page or node.js process), the decision of whether you want stack traces or not should be up to the application, not a library.

#### Enviornment:

Node.js v14, using comunica through [node-quadstore](https://github.com/beautifulinteractions/node-quadstore) v7.

Quadstore intensifies the situation because it ships a bundled version of itself through npm, with the bundler configured to replace `process.env.NODE_ENV === 'production'` with `true`. However, even without that, I wouldn't want my stack traces to always go away if I have `NODE_ENV` set to `production` for other reasons.

**Comment by rubensworks** [comment]
You're right. This is a leftover "hack" from back in the day that should not be here anymore.
I should probably redo the performance evaluations, as I suspect the stacktrace limits won't have a significant impact on performance anymore.
