### ISSUE TITLE
SPARQL MINUS: array.map is not a function

### ISSUE THREAD

**Issue by sdevalk** [comunica/comunica#779]
#### Issue type:

- :bug: Bug 

____
#### Description:

I want to query a source using the MINUS operation:

`npx comunica-sparql sparql@https://data.cultureelerfgoed.nl/PoolParty/sparql/term/id/cht -f cht.rq`

... where file `cht.rq` looks like this:

```sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT *
WHERE {
    ?uri skos:prefLabel ?prefLabel
    FILTER(CONTAINS(LCASE(?prefLabel), "soft enduro"))
    MINUS {
        ?uri skos:broader <https://data.cultureelerfgoed.nl/term/id/cht/522f659d-6dc5-4b64-a244-1ea88701b7ea>
    }
}
```

However, Comunica returns the error underneath:

`array.map is not a function`

____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.19.2
| node                | v12.0.0
| npm                 | 6.9.0
| yarn                | 1.15.2
| Operating System    | linux (Linux 4.19.121-linuxkit)

**Comment by rubensworks** [comment]
Hmm, even without the `FILTER` the same error is produced.
Strange that no full stracktrace is printed.
This might become a tricky one to debug...

**Comment by rubensworks** [comment]
This seems to be a bug in SPARQLAlgebra.js: https://github.com/joachimvh/SPARQLAlgebra.js/issues/75

**Comment by rubensworks** [comment]
Fixed in SPARQLAlgebra.js thanks to @joachimvh.

Reinstalling (deleting your node_modules and lockfile) should do the trick.

**Comment by sdevalk** [comment]
Thanks for the update @rubensworks - the error indeed is gone!
