### ISSUE TITLE
Use weaker query engine interface in bus-rdf-metadata-extract

### ISSUE THREAD

**Issue by brechtvdv** [comunica/comunica#780]
#### Issue type:

- :bug: Bug 

____
#### Description:

I added bus-rdf-metadata-extract to my custom package (yarn add @comunica/bus-rdf-metadata-extract), but when I run "yarn install" it doesn't install @comunica/actor-init-sparql, because this is a peerDependency I guess?. This returns following error when running typescript:
____
#### Crash log:

`node_modules/@comunica/bus-rdf-metadata-extract/lib/ActorRdfMetadataExtractQuery.d.ts:1:38 - error TS2307: Cannot find module '@comunica/actor-init-sparql' or its corresponding type declarations. `

I guess @comunica/actor-init-sparql should be added to devDependencies or dependencies in ´package.json´ of @comunica/bus-rdf-metadata-extract ?

**Comment by rubensworks** [comment]
Making `'@comunica/actor-init-sparql'` an actual or dev dependency might cause some problems, so I would not do that.

What we could do is making the [query engine contract](https://github.com/comunica/comunica/blob/master/packages/bus-rdf-metadata-extract/lib/ActorRdfMetadataExtractQuery.ts#L24) a bit weaker.
This should be possible by moving the query engine interface so a separate types-only interface.

(\cc @jacoscaz, this could also be solved via this `@comunica/types` package)

**Comment by jacoscaz** [comment]
Hi all! Yes, that is precisely what I'm aiming for with `@comunica/types`, having the query engine contract defined as an interface implemented by `ActorInitSparql`.
