### ISSUE TITLE
Fix typedoc documentation

### ISSUE THREAD

**Issue by gertjandemulder** [comunica/comunica#788]
#### Issue type:

- :bug: Bug 

____
#### Description:

The [link to the code documentation](https://comunica.github.io/comunica/) mentioned in the [Comunica Documentation](https://comunica.dev/docs/) results in a  404 "File Not Found".
____
#### Environment:

N.A.
#### Crash log:

N.A.

**Comment by rubensworks** [comment]
Looks like typedoc had some breaking changes [as of its latest update](https://github.com/comunica/comunica/commit/64b57f0a3ffe0a46004a5d4a1cdd990b6e156ec4).

We probably have to change how we invoke it during CI.
