### ISSUE TITLE
Incorrect rewriting of SPARQL query

### ISSUE THREAD

**Issue by sdevalk** [comunica/comunica#790]
#### Issue type:

- :bug: Bug 

____
#### Description:

I want to query Wikidata with Comunica using the command underneath:

```npx comunica-sparql sparql@https://query.wikidata.org/sparql -f wikidata.rq```

...where the contents of file `wikidata.rq` looks like this:

```
SELECT *
WHERE {
  {
    SERVICE <http://wikiba.se/ontology#mwapi> {
      <http://www.bigdata.com/rdf#serviceParam> <http://wikiba.se/ontology#endpoint> "www.wikidata.org";
        <http://wikiba.se/ontology#api> "EntitySearch";
        <https://www.mediawiki.org/ontology#API/language> "nl";
        <https://www.mediawiki.org/ontology#API/search> "Soest".
      ?item <http://wikiba.se/ontology#apiOutputItem> <https://www.mediawiki.org/ontology#API/item>.
    }
    {
      ?item <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q486972>.
    }
    UNION
    {
      ?item <http://www.wikidata.org/prop/direct/P31> ?instanceOf.
      ?instanceOf (<http://www.wikidata.org/prop/direct/P279>+) <http://www.wikidata.org/entity/Q486972>.
    }
    ?item <http://www.w3.org/2000/01/rdf-schema#label> ?prefLabel.
    FILTER(LANG(?prefLabel) = "nl")
  }
}
LIMIT 100
```

The query attempts to find resources that are an instance (http://www.wikidata.org/prop/direct/P31) of "human settlement" (http://www.wikidata.org/entity/Q486972) or a subclass (http://www.wikidata.org/prop/direct/P279), such as "town" (http://www.wikidata.org/entity/Q3957) or "village" (http://www.wikidata.org/entity/Q532).

However, the answers to this query are a bit strange. For example, it not only finds human settlements, but also a painting (http://www.wikidata.org/entity/Q28088063), a beach (http://www.wikidata.org/entity/Q28121875) and a human (http://www.wikidata.org/entity/Q539078).

This is probably caused by the query that Comunica actually sends to Wikidata. The query looks like this:

```
SELECT ?item ?instanceOf ?prefLabel WHERE {
  SERVICE <http://wikiba.se/ontology#mwapi> {
    <http://www.bigdata.com/rdf#serviceParam> <http://wikiba.se/ontology#endpoint> "www.wikidata.org";
      <http://wikiba.se/ontology#api> "EntitySearch";
      <https://www.mediawiki.org/ontology#API/language> "nl";
      <https://www.mediawiki.org/ontology#API/search> "Soest".
    ?item <http://wikiba.se/ontology#apiOutputItem> <https://www.mediawiki.org/ontology#API/item>.
  }
  { ?item <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q486972>. }
  UNION
  { ?item <http://www.wikidata.org/prop/direct/P31> ?instanceOf. }
  UNION
  { ?instanceOf (<http://www.wikidata.org/prop/direct/P279>+) <http://www.wikidata.org/entity/Q486972>. }
  ?item <http://www.w3.org/2000/01/rdf-schema#label> ?prefLabel.
  FILTER((LANG(?prefLabel)) = "nl")
}
LIMIT 100
```

This query contains three UNION parts (rather than the original two). Perhaps due to the `+` operator?

____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.19.2
| node                | v12.0.0
| npm                 | 6.9.0
| yarn                | 1.15.2
| Operating System    | linux (Linux 4.19.121-linuxkit)

**Comment by rubensworks** [comment]
@joachimvh Could this be another problem with `toSparql` in SPARQLAlgebra.js? Perhaps similar to https://github.com/joachimvh/SPARQLAlgebra.js/issues/75?

**Comment by joachimvh** [comment]
Definitely possible, will have a look

**Comment by joachimvh** [comment]
There was indeed a problem when combining a path operator with a union. Should be fixed in v2.5.3

**Comment by rubensworks** [comment]
Awesome, thanks @joachimvh!

@sdevalk feel free to close this issue once you have confirmed it to be working on your end.

**Comment by sdevalk** [comment]
@rubensworks & @joachimvh Thank you very much! I've tried the query again - it now returns the expected results.
