### ISSUE TITLE
No 'end' event on bindingsStream when there are 0 results (only for some queries)

### ISSUE THREAD

**Issue by thomasdevriese** [comunica/comunica#793]
#### Issue type:

- :bug: Bug 

____
#### Description:

When I execute a query which produces 0 results, the `end` event on the bindingsStream of the result is not emitted, causing `result.bindingsStream.on('end', () => {});` to be unusable. This is only the case for some queries. I want to be able to use the `end` event regardless of the number of results, in order to measure the execution time etc.

Reproducible example:

    const newEngine = require('@comunica/actor-init-sparql').newEngine;
    const myEngine = newEngine();
    
    async function sparqlSelect() {
      const result = await myEngine.query(`
      PREFIX snvoc: <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
      SELECT ?person WHERE
      {
        ?person snvoc:firstName "Tom" .
        ?person snvoc:gender "male" .
      }`, {
        sources: ['https://thomasdevriese.solidcommunity.net/public/social/pers00000004398046512167.ttl']
      });
    
      let { data } = await myEngine.resultToString(result, 'stats');
      data.pipe(process.stdout);
    
      result.bindingsStream.on('end', () => {
        console.log("THIS IS NOT PRINTED");
      });
      result.bindingsStream.on('error', (error) => {
        console.error(error);
      });
    }
    sparqlSelect();

Using the query below, does however emit the `end` event, while still producing no results.

    PREFIX snvoc: <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
    SELECT ?person WHERE
    {
      ?person snvoc:firstName "Tom" .
    }

Is there someone who can help me out?
Thanks!
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.19.2
| node                | v14.15.4
| npm                 | 6.14.9
| yarn                | 1.22.10
| Operating System    | win32 (Windows_NT 10.0.18363)

**Comment by rubensworks** [comment]
I suspect this is because you are listening to `bindingsStream` events on two places (in `resultToString` and in your own code), which is probably not what you want to do.

For empty result streams, by the time `resultToString` resolves, your `bindingsStream` will already have emitted its `end` event. So the behaviour here seems intended.

Instead of manually listening to `result.bindingsStream`, you may want to listen to `data` instead.

**Comment by thomasdevriese** [comment]
Perfect, that solved it. Thank you!
