### ISSUE TITLE
@comunica/actor-init-sparql-rdfjs does not correlate blank nodes

### ISSUE THREAD

**Issue by jacoscaz** [comunica/comunica#795]
#### Issue type:

- :bug: Bug

____
#### Description:

The actor implemented in `@comunica/actor-init-sparql-rdfjs` seems unable to correlate blank nodes when querying upon a RDF/JS source. 

The problem can be reproduced by running the test against the following manifest:

```sh
cd packages/actor-init-sparql-rdfjs
 ../../node_modules/.bin/rdf-test-suite-ldf spec/sparql-engine.js http://jacoscaz.com/manifest-ldf-tests/sparql-rdfjs/rdfjs-manifest.ttl -d 200000 -c ../../.rdf-test-suite-ldf-cache/
```

The manifest run a simple `SELECT * FROM { ?s ?p ?o}` query on the following quads:

```turtle
@prefix : <http://example.org/> .

:s1 :p1 _:b1 .
_:b1 :p2 :o2 .
```

The actor returns the following bindings:

```js
 Bindings:  [
  {
    "?s": {  "termType": "NamedNode",  "value": "http://example.org/s1" },
    "?p": { "termType": "NamedNode", "value": "http://example.org/p1" },
    "?o": {
      "termType": "BlankNode", "value": "bc_0_b4_b11",
      "skolemized": { "termType": "NamedNode", "value": "urn:comunica_skolem:source_0:b4_b1" }
    }
  },
  {
    "?s": {
      "termType": "BlankNode", "value": "bc_0_b4_b12",
      "skolemized": { "termType": "NamedNode", "value": "urn:comunica_skolem:source_0:b4_b1" }
    },
    "?p": { "termType": "NamedNode", "value": "http://example.org/p2" },
    "?o": { "termType": "NamedNode", "value": "http://example.org/o2" }
  }
]
```

While the skolemized versions of the two blank nodes are correlated, the labels themselves are not (but they should be!).

I stumbled into this issue while troubleshooting https://github.com/beautifulinteractions/node-quadstore/issues/134 and @rubensworks noted it might be related to https://github.com/comunica/comunica/issues/773 .
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.19.2 (dev)
| node                | v14.15.4
| npm                 | 7.4.1
| yarn                | 1.22.10
| Operating System    | darwin (Darwin 20.3.0)

**Comment by jacoscaz** [comment]
I suspect the issue comes from here: https://github.com/comunica/comunica/blob/3f46a233883b699df87fcee3215516f97e15e346/packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts#L61-L66 .

**Comment by jacoscaz** [comment]
Actually, now that I am looking at this... In https://github.com/beautifulinteractions/node-quadstore/issues/134 , blank nodes in bindings return from the engine do not seem to have the `skolemized` property at all. However, that is indeed present here. Could it be that skolemization is not handled with RDF/JS sources?

**Comment by rubensworks** [comment]
> In beautifulinteractions/node-quadstore#134 , blank nodes in bindings returned by the engine do not seem to have the skolemized property at all.

That's because you're querying over a single `source`, instead of a `sources` array. This means that the federated actor will not be invoked, and the blank node scoping is therefore not needed.
But since the bug also occurs there, I don't think there problem is related to this blank node scoping.

**Comment by jacoscaz** [comment]
> That's because you're querying over a single source, instead of a sources array

Ah, thanks for pointing that out. Looking at the concatenation with `blankNodeCounter` at 

https://github.com/comunica/comunica/blob/3f46a233883b699df87fcee3215516f97e15e346/packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts#L65 

perhaps we could make that an opt-out via a context flag? In the case of blank nodes coming from a persistent source, preventing blank node collisions necessarily needs to be handled in the source itself.

**Comment by jacoscaz** [comment]
Or, we could revise that bit by adding a local cache of previously-encountered blank nodes so that each blank node coming up through the same `bindingsStream` instance is first run though the cache. If a match is found, we return it, otherwise we generate a new concatenation.

**Comment by jacoscaz** [comment]
I've tried changing `ActorQueryOperationProject.ts` to the following: 

```js
    // Make sure that blank nodes with same labels are not reused over different bindings, as required by SPARQL 1.1.
    // Required for the BNODE() function: https://www.w3.org/TR/sparql11-query/#func-bnode
    // When we have a scoped blank node, make sure the skolemized value is maintained.
    let blankNodeCounter = 0;
    const blankNodeCache: Map<string, BlankNode> = new Map();
    bindingsStream = bindingsStream.transform({
      map(bindings: Bindings) {
        blankNodeCounter++;
        return <Bindings> bindings.map(term => {
          if (term && term.termType === 'BlankNode') {
            if (blankNodeCache.has(term.value)) {
              return blankNodeCache.get(term.value);
            }
            const scopedTerm = term instanceof BlankNodeScoped
              ? new BlankNodeScoped(`${term.value}${blankNodeCounter}`, term.skolemized)
              : DF.blankNode(`${term.value}${blankNodeCounter}`)
            ;
            blankNodeCache.set(term.value, scopedTerm);
            return scopedTerm;
          }
          return term;
        });
      },
      autoStart: false,
    });
```

This seems to have fixed the issue while breaking far fewer tests than I had anticipated:

- `packages/actor-init-sparql`
    - `yarn run integration`
        - everything is passing  
    - `yarn run spec`
        - The `BNODE(str)` test . This makes sense and might be fixable by looking at how Comunica deals with `BNODE`. 
    - `yarn run test`
        -  everything is passing
- Comunica's root
    -  `yarn run test-ci` 
        - two tests breaking in `packages/actor-query-operation-project/test/ActorQueryOperationProject-test.ts`, which makes sense as they target the old behaviour and would simply need to be updated

@rubensworks is this something you'd be comfortable with?

**Comment by rubensworks** [comment]
For any changes we make here, we need to make sure that we align with the spec regarding the handling of `BNODE()` across multiple bindings, and the handling of blank nodes in `CONSTRUCT` queries.

This transformation in `ActorQueryOperationProject` was implemented to adhere to both, which as a consequence makes bnodes never correlated across different bindings (which the spec doesn't seem to explicitly require?).

So spec-wise, I think the current implementation is correct (I think). But I agree, it's a bit counter-intuitiuve, so a change to this would be good.

However, I'm not sure if adding a cache to the current transformation is necessary. I think we can just remove the transformation completely, and think about a different way to handle the `BNODE()` edge-case.
Alternatively, we could somehow only let the transformation apply to bnodes produced by `BNODE()`.

In either case, handling the `BNODE()` edge-case won't be trivial.
One solution I see would be to annotate such bnodes with a flag (`singleBindingsScope`?), inheriting this flag upon each transformation (such as for `BlankNodeScoped`), and then only applying our project transformation if this flag is found.

**Comment by jacoscaz** [comment]
> One solution I see would be to annotate such bnodes with a flag (singleBindingsScope?), inheriting this flag upon each transformation (such as for BlankNodeScoped), and then only applying our project transformation if this flag is found.

Interesting strategy, I'll give this a go and hopefully open a PR.

**Comment by rubensworks** [comment]
^ If we do this, it's possible we may have to change some things in sparqlee as well (but not sure).

**Comment by jacoscaz** [comment]
@rubensworks looking at this with fresh eyes, wouldn't adding a cache to the project transformation make for greater separation of concerns between how blank nodes are handled throughout Comunica vs. ensuring the uniqueness of returned blank nodes?

I bet you must have spent a non-trivial amount of time in getting to the current approach of transforming blank nodes in the projection phase of the query and adding a cache in there doesn't alter the overall approach, which seems to me to be more elegant and future-proof than passing per-node flags around. Yes, there is the cost brought in by the additional `TransformIterator` but it's a worthy tradeoff IMHO.

**Comment by rubensworks** [comment]
> wouldn't adding a cache to the project transformation make for greater separation of concerns between how blank nodes are handled throughout Comunica vs. ensuring the uniqueness of returned blank nodes?

I may misunderstand the code, but as I understand it, the cache actually makes the loop have no effect anymore. Every bnode with label `a` will just be mapped now to a new label with constant suffix `x`.
So while before, `a` across different bindings would be mapped to `a1`, `a2`, `a3`, ...
It will now always be mapped to `a1`, `a1`, `a1`, ...

Hence my remark to just remove the loop, and use some kind of internal flag instead.

But please let me know if you think I'm misunderstanding things.

**Comment by jacoscaz** [comment]
@rubensworks no, you are absolutely right, my mistake. All right, will look into the flag-based solution you suggested.

**Comment by jacoscaz** [comment]
@rubensworks I am struggling a bit to wrap my mind about the extent of the changes required to fix this and where flags should be used. May I ask for your feedback on where I am at? Here's a summary of what I have in my head so far...

The guiding principle behind these changes should be to trust RDF/JS sources in their handling of blank nodes, i.e. to trust them in the fact that correlated blank nodes coming in via https://github.com/comunica/comunica/blob/cb8e37e007525a44747c6e38033abf0e63ac5b29/packages/actor-rdf-resolve-quad-pattern-rdfjs-source/lib/RdfJsQuadSource.ts#L21 should, indeed, remain correlated throughout Comunica's pipeline.

The projection transformation at https://github.com/comunica/comunica/blob/cb8e37e007525a44747c6e38033abf0e63ac5b29/packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts#L56-L71 needs to go away as it is the main cause of non-correlatable blank nodes. However, this ought to be offset by changes into how blank nodes are handled WRT `BNODE()` expressions and `CONSTRUCT` queries to maintain adherence to the spec.

The `CONSTRUCT` actor applies its own transformation at https://github.com/comunica/comunica/blob/cb8e37e007525a44747c6e38033abf0e63ac5b29/packages/actor-query-operation-construct/lib/BindingsToQuadsIterator.ts#L108 to ensure blank node uniqueness across different instantiations of the template. This transformation is applied in a way that does not break correlation and thus doesn't look like something that needs changing. 

Handling of the `BNODE` expression happens inside [comunica/sparqlee](https://github.com/comunica/sparqlee), whose evaluators accept a custom blank node generating function as detailed in https://github.com/comunica/sparqlee#bnode . This should make it possible to implement the required changes (if any) without modifications to [comunica/sparqlee](https://github.com/comunica/sparqlee) itself.

It looks to me like a good solution would be to move the transformation that currently lives in `actor-query-operation-project` in `actor-rdf-resolve-quad-pattern-rdfjs-source` or even in `bus-rdf-resolve-quad-pattern`, using a separate cache of transformed blank nodes per each invocation of the `match()` RDF/JS method but a common counter for the added numerical suffix. I _think_ this would maintain correlations while matching the spec. 

WRT to using flags, I haven't been able to figure out how using per-node flags might help with this specific issue as my brain kept going back to the fact that I somehow need to model cross-node relationships.

**Comment by rubensworks** [comment]
Your current thoughts mostly sound correct to me!

> Handling of the BNODE expression happens inside comunica/sparqlee, whose evaluators accept a custom blank node generating function as detailed in https://github.com/comunica/sparqlee#bnode

I forgot about that. Then it's indeed not necessary to make any changes in sparqlee directly.

> It looks to me like a good solution would be to move the transformation that currently lives in actor-query-operation-project in actor-rdf-resolve-quad-pattern-rdfjs-source or even in bus-rdf-resolve-quad-pattern, using a separate cache of transformed blank nodes per each invocation of the match() RDF/JS method but a common counter for the added numerical suffix. I think this would maintain correlations while matching the spec.

If I understand the spec correctly, then this would not fix the problem correctly.

The spec says that `BNODE` should produce bnodes that are [distinct within a single solution mapping](https://www.w3.org/TR/sparql11-query/#func-bnode). This requires us to do a magical operation at the top-level of the query execution to make sure that bnode usages across solution mappings are different (which is what our current transformation in project does).

However, when reading https://github.com/w3c/sparql-12/issues/36 (and more specifically [this comment](https://github.com/w3c/sparql-12/issues/36#issuecomment-479571969)), it seems like there is an understanding that a solution mapping here seems to apply to "a subset of the query plan", instead of a top-level solution mapping. Therefore, we may be able to simplify the implementation (without transformations or flags) by just ensuring bnode uniqueness every time sparqlee's bnode function is called.
But we may need to double-check this in the spec tests.

**Comment by jacoscaz** [comment]
> Your current thoughts mostly sound correct to me!

That's comforting to hear :)

> If I understand the spec correctly, then this would not fix the problem correctly.
> 
>Therefore, we may be able to simplify the implementation (without transformations or flags) by just ensuring bnode uniqueness every time sparqlee's bnode function is called. But we may need to double-check this in the spec tests.

Sounds good, I'll have a further look into the spec and those issues / comments. My idea of moving the current transformation in `actor-rdf-resolve-quad-pattern-rdfjs-source` or in `bus-rdf-resolve-quad-pattern` also doesn't make sense because cross-source blank node collisions are already being prevented by the federated actor in https://github.com/comunica/comunica/blob/eece36c443212546b2a51bc69f2581bf4f23c8a3/packages/actor-rdf-resolve-quad-pattern-federated/lib/FederatedQuadSource.ts#L87-L92 .

So, given all of the above, it looks to me like the only thing to be done here is to modify the handling of `BNODE()` via the custom blank node generator function. This brings me back to the spec:

> The BNODE function constructs a blank node that is distinct from all blank nodes in the dataset being queried and distinct from all blank nodes created by calls to this constructor for other query solutions. If the no argument form is used, every call results in a distinct blank node. If the form with a simple literal is used, every call results in distinct blank nodes for different simple literals, and the same blank node for calls with the same simple literal **within expressions for one solution mapping**.

No-argument `BNODE()` invocations are already using `uuid` to produce unique blank nodes in `sparqlee`, so we would just have to replicate something similar in the custom generator function. 

https://github.com/comunica/sparqlee/blob/07ed934773fb266d81bd8962910bd5ab32229a36/lib/functions/SpecialFunctions.ts#L361-L372

My naive reading of the spec would lead me to think that the custom generator function would have to keep track of the current top-level mapping and keep a per-mapping cache of blank nodes. However, if I understand your comment correctly, it seems like the no-arg behavior would actually work in both the no-arg and the arg case. 

The relevant spec test seems to be the following: https://www.w3.org/2009/sparql/docs/tests/summary.html#functions-bnode01

The very first result set of that test looks as follows:

```xml
<result>
    <binding name="s1">
        <literal>BAZ</literal>
    </binding>
    <binding name="s2">
        <literal>BAZ</literal>
    </binding>
    <binding name="b1">
        <bnode>b0</bnode>
    </binding>
    <binding name="b2">
        <bnode>b0</bnode>
    </binding>
</result>
```

If I am reading this correctly, this does look like `BNODE()` is evaluated against the top-level mapping as the same literal leads to correlated blank nodes. I'm _extremely_ out of my depths here, though.

**Comment by rubensworks** [comment]
> If I am reading this correctly, this does look like BNODE() is evaluated against the top-level mapping as the same literal leads to correlated blank nodes.

I think you're right. I vaguely remembering coming to the same conclusion when making Comunica pass all spec tests.
A bit unfortunate though, as this small detail severely complicates implementation...

Unless you see another solution, I think the most straightforward (minimal impact) solution would be to:
1. Keep our current `bnode` constructor for sparqlee, but _annotate_ the bnode term with a flag. E.g. (`bnode.singleBindingsScope = true`).
2. Keep our current transformation in the project actor, but make it _only_ apply to bnoes that are annotated with `singleBindingsScope`.

Unless you can think of a (hopefully cleaner) solution?

**Comment by jacoscaz** [comment]
One thing that does come to mind is to change the signature of the custom generator function accepted by `sparqlee` to something like this:

```ts
(label: string, context: E.EvalContextSync | E.EvalContextAsync) => BlankNode
```

This would allow the function to keep per-mapping caches of blank nodes. Next step would be implementing the custom function in something like `core`, possibly as the return value of a factory function, and passing it to the various `-sparqlee` actors via the query context.

I _think_ this would be cleaner than a flag-based approach  but I'll readily admit I have been burnt by flags in the past and I might be exceedingly biased against them.

**Comment by rubensworks** [comment]
> change the signature of the custom generator function accepted by sparqlee to something like this:

That might work, depending on how and where this per-mapping caches of blank nodes is created/maintained.

> Next step would be implementing the custom function in something like core

I wouldn't put this in `core`. Perhaps just in `sparqlee` directly? Or in `bus-query-operation` if we can do it in a sparqlee-independent manner.

> I think this would be cleaner than a flag-based approach

Yeah, the flag approach is a hack, so I'm definitely open to cleaner alternatives :-)

**Comment by jacoscaz** [comment]
> That might work, depending on how and where this per-mapping caches of blank nodes is created/maintained.

I guess it would have to be instantiated in the `query()` method https://github.com/comunica/comunica/blob/eece36c443212546b2a51bc69f2581bf4f23c8a3/packages/actor-init-sparql/lib/ActorInitSparql-browser.ts#L132
and added to the context. Once added to the context it should be automatically passed to all actors, buses and mediators. 
The `getExpressionContext` function at https://github.com/comunica/comunica/blob/eece36c443212546b2a51bc69f2581bf4f23c8a3/packages/bus-query-operation/lib/ActorQueryOperation.ts#L176 could then be changed to include the generator function in the expression context, passing it to `sparqlee`.

However... I now realize this only works if bindings do not change (i.e. if I can use them as keys in a `Map` regardless of which actor is calling `sparqlee`) or if there's a fast way to compute a unique hash for each binding.

**Comment by rubensworks** [comment]
> I now realize this only works if bindings do not change (i.e. if I can use them as keys in a Map regardless of which actor is calling sparqlee) or if there's a fast way to compute a unique hash for each binding.

There might be something there, but we just have to make sure that we don't store too much data.
In the worst case, we may be producing infinite result streams, in which case this `Map` should not cause memory issues (that's why the current solution only makes use of counters).

**Comment by jacoscaz** [comment]
In the worst case of infinite result streams this would indeed lead to memory issues. I've dealt with something very similar while working on quadstore's [quad scoping feature](https://github.com/beautifulinteractions/node-quadstore#blank-nodes-and-quad-scoping). In that context I opted to compromise on memory safety. This conversation reminds me I should add some kind of warning in `README.md` about the risks of long-running streams.

In this specific case I can't see any other way to do this beside the flag-based approach.

Speaking of which, I guess the current transformation would presumably need to be changed in order to use the same suffix for all blank nodes within the same bindings object having the `singleBindingsScope` flag. 

How would you deal with the flag from a TS standpoint? Comunica already has its own class for `BlankNodeScoped`, I guess we could have another for `BlankNode` ? This would still mean passing a custom generator to `sparqlee`, though.

**Comment by rubensworks** [comment]
> I guess the current transformation would presumably need to be changed in order to use the same suffix for all blank nodes within the same bindings object having the singleBindingsScope flag.

Yes, some changes may be needed there.

> How would you deal with the flag from a TS standpoint? Comunica already has its own class for BlankNodeScoped, I guess we could have another for BlankNode ?

Yes, something like `BlankNodeBindingsScoped` might work. (`BlankNodeSourceScoped` might have been a better name for `BlankNodeScoped`...)
No need to expose a `skolemized` field here I guess, as that is only needed to link to bnodes from sources, while we are creating brand new bnodes here.
Just the `singleBindingsScope` flag to enable discovery of `BlankNodeBindingsScoped`'s.

> This would still mean passing a custom generator to sparqlee, though.

Yes, indeed.

**Comment by jacoscaz** [comment]
All right! Thank you for your patience, I'll open a PR in the next few days.

**Comment by jacoscaz** [comment]
@rubensworks had to open a PR to `sparqlee` to fix an issue with the handling of the custom `bnode` generator functions: https://github.com/comunica/sparqlee/pull/80 .

**Comment by rubensworks** [comment]
@jacoscaz Heh, good catch!
Let me know when you need a new release of sparqlee, and I'll publish it.

**Comment by jacoscaz** [comment]
If it's not too much of a bother, the sooner the better - if only for the lesser mental overhead of keeping track of all the things I'm modifying in my attempts at sorting this out. Still, no rush.

**Comment by jacoscaz** [comment]
If it's not too much of a bother, the sooner the better. If only for the lower mental overhead of keeping track of all the things I'm modifying in my attempts at sorting this out. Still, no rush.

**Comment by rubensworks** [comment]
Released sparqlee as 1.6.1! :-)

**Comment by jacoscaz** [comment]
@rubensworks Unfortunately, it looks like there's something else that I'll need to change in sparqlee. The back and forth between terms and expressions makes it impossible to preserve the blank node generated by custom `bnode` generator fn. 

The `BNODE()` implementation at https://github.com/comunica/sparqlee/blob/934fd6e93039278f639aad3974cd853b6b3c6afc/lib/functions/SpecialFunctions.ts#L347 transforms the `RDF.BlankNode` instance into an Expression using the term's value alone, loosing the reference to the original blank node.

The `BlankNode` expression at https://github.com/comunica/sparqlee/blob/934fd6e93039278f639aad3974cd853b6b3c6afc/lib/expressions/Term.ts#L43-L61 does a similar thing but in reverse. 

Would you be ok with changing sparqlee so as to keep a reference to the original `BlankNode` __term__ instance within the `BlankNode` __expression__ instance and returning the former in the latter's `.toRDF()` method?

**Comment by jacoscaz** [comment]
Quick update - it works! All 290 tests of the `spec:query` suite are now passing _and_ my own test for correlated blank nodes is passing. Will cleanup a bit and the open PRs to both `sparqlee` and `comunica`...
