### ISSUE TITLE
Run CI on windows and mac

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#798]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

As we have migrated to GitHub Actions to run our CI, it should be easy to run on Windows and Mac as well.
Essentially, we need to add `macos-latest` and `windows-latest` to the test job in our CI.
However, [tests seem to fail](https://github.com/comunica/comunica/runs/2174042973?check_suite_focus=true), which is why it isn't enabled yet.

May be related to #713 and #616.

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| €272 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment]
A bounty has been placed on this issue via the Comunica Association (see original post).

**Comment by jeswr** [comment]
As discuss with Ruben I will work on this issue.
