### ISSUE TITLE
This does not seem to work consistently on more complicated pages

### ISSUE THREAD

**Issue by garpinc** [comunica/comunica#799]
#### Issue type:

- :bug: Bug 

____
#### Description:

This does not seem to work consistently on more complicated pages

When It doesn't work I get this error
ActorQueryOperationBgpLeftDeepSmallest.ts:78 Uncaught (in promise) TypeError: .for is not iterable

Attached below is my test html

Refreshing the page will give inconsistent results.. Sometimes it works and sometimes it doesn't

____

**Comment by garpinc** [comment]
[html.zip](https://github.com/comunica/comunica/files/6192505/html.zip) is the complete file

**Comment by rubensworks** [comment]
This seems to be a library issue on your end.

It looks like the following library breaks things:
> <script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js" type="text/javascript"></script>

Not sure why, but I suspect it's doing some monkey-patching, and thereby breaks standard JS API assumptions, causing issues such as this one.

**Comment by garpinc** [comment]
I would think this is a commonly used api not you?



- Garry



-------- Original message --------
From: Ruben Taelman ***@***.***>
Date: 3/26/21 11:00 AM (GMT-05:00)
To: comunica/comunica ***@***.***>
Cc: garpinc ***@***.***>, Author ***@***.***>
Subject: Re: [comunica/comunica] This does not seem to work consistently on more complicated pages (#799)


This seems to be a library issue on your end.

It looks like the following library breaks things:

<script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js" type="text/javascript"></script>

Not sure why, but I suspect it's doing some monkey-patching, and thereby breaks standard JS API assumptions, causing issues such as this one.

**Comment by rubensworks** [comment]
It's known for breaking other libs: https://stackoverflow.com/questions/12354235/conflict-prototype-js-and-another-library
So I would recommend not using it. There are many other (more modern) libraries that allow you to do the same thing.
