### ISSUE TITLE
Error with -t option

### ISSUE THREAD

**Issue by garpinc** [comunica/comunica#800]
#### Issue type:

- :bug: Bug 

____
#### Description:

Following this example  https://comunica.dev/docs/query/advanced/result_formats/ I get following
comunica-sparql https://fragments.dbpedia.org/2016-04/en "SELECT * WHERE { ?s ?p ?o } LIMIT 100" -t 'application/sparql-results+json'
https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/sparql-init.json#mediatorSparqlSerialize mediated over all rejecting actors:
Unrecognized media type: 'application/sparql-results+json'
Unrecognized media type: 'application/sparql-results+json'
Unrecognized media type: 'application/sparql-results+json'
Unrecognized media type: 'application/sparql-results+json'
Unrecognized media type: 'application/sparql-results+json'
Unrecognized media type: 'application/sparql-results+json'
Unrecognized media type: 'application/sparql-results+json'
Unrecognized media type: 'application/sparql-results+json'
Unrecognized media type: 'application/sparql-results+json'
Actor https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/sparql-serializers.json#myRdfSparqlSerializer can only handle quad streams
____

**Comment by rubensworks** [comment]
Works fine on my end.
Could you try replacing the single quotes with double quotes? Perhaps your OS is interpreting those differently?

**Comment by garpinc** [comment]
Changing it to double quotes works for the above use case however comunica-sparql http://localhost/sapphire217.trig "SELECT * WHERE { GRAPH ?g {?s ?p ?o} } LIMIT 100" -t "application/ld+json" still has same issue
[sapphire217.zip](https://github.com/comunica/comunica/files/6196984/sapphire217.zip)

**Comment by rubensworks** [comment]
@garpinc Does it produce the same error as above? Or are you referring to #799?

**Comment by garpinc** [comment]
comunica-sparql http://localhost/sapphire217.trig "SELECT * WHERE { GRAPH ?g {?s ?p ?o} } LIMIT 100" -t "application/ld+json"
https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/sparql-init.json#mediatorSparqlSerialize mediated over all rejecting actors:
Unrecognized media type: application/ld+json
Unrecognized media type: application/ld+json
Unrecognized media type: application/ld+json
Unrecognized media type: application/ld+json
Unrecognized media type: application/ld+json
Unrecognized media type: application/ld+json
Unrecognized media type: application/ld+json
Unrecognized media type: application/ld+json
Unrecognized media type: application/ld+json
Actor https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/sparql-serializers.json#myRdfSparqlSerializer can only handle quad streams

**Comment by rubensworks** [comment]
Yeah, you can not do that. You're providing a SELECT query, which produces result bindings. `application/ld+json` is an RDF serialization, which only works with CONSTRUCT/DESCRIBE queries.

**Comment by garpinc** [comment]
Ah... Great...  The error message wasn't very descriptive wrt this nor was it described on the webpage describing the functionality

**Comment by rubensworks** [comment]
Yeah, error messages are something that needs some work: https://github.com/comunica/comunica/issues/164

> nor was it described on the webpage describing the functionality

More information on this can be found on the getting started guides:
https://comunica.dev/docs/query/getting_started/query_cli/
https://comunica.dev/docs/query/getting_started/query_app/

**Comment by garpinc** [comment]
Shouldn't this work? If I remove graph clause it does work but not with graph clause

comunica-sparql http://localhost/sapphire217.trig "CONSTRUCT { GRAPH ?g { ?s ?p ?o }} WHERE { GRAPH ?g {?s ?p ?o} }" -t "application/ld+json"
Parse error on line 1:
CONSTRUCT { GRAPH ?g { ?s ?p ?o
------------^
Expecting 'IRIREF', 'PNAME_NS', 'VAR', '(', '}', 'INTEGER', 'NIL', '[', '<<', 'BLANK_NODE_LABEL', 'ANON', 'DECIMAL', 'DOUBLE', 'BOOLEAN', 'STRING_LITERAL1', 'STRING_LITERAL2', 'STRING_LITERAL_LONG1', 'STRING_LITERAL_LONG2', 'INTEGER_POSITIVE', 'DECIMAL_POSITIVE', 'DOUBLE_POSITIVE', 'INTEGER_NEGATIVE', 'DECIMAL_NEGATIVE', 'DOUBLE_NEGATIVE', 'PNAME_LN', got 'GRAPH'

**Comment by rubensworks** [comment]
That's an illegal query, as only triple patterns are allowed in CONSTRUCT clauses: https://www.w3.org/TR/sparql11-query/#construct

**Comment by garpinc** [comment]
Ok.. got it... I was unaware since it works for me.. Turns out that at the  company I work at (cambridgesemantics.com) (we extended sparql to support that.. We tried to get it in the spec at the time but were unsuccessful for whatever reason...

**Comment by garpinc** [comment]
Looks like it will be in sparql 1.2 https://github.com/w3c/sparql-12/issues/31

**Comment by rubensworks** [comment]
Yes, I agree that it's a bit unfortunate that it's not allowed atm in SPARQL.
