### ISSUE TITLE
Data doesn't seem to line up correctly

### ISSUE THREAD

**Issue by garpinc** [comunica/comunica#802]
#### Issue type:

- :bug: Bug 

____
#### Description:

I have an attached file sapphire217.ttl

rates in here are :rates [ dc:title "Winter Rates" ; :pricePerNight 450], [ dc:title "Summer Rates" ; :pricePerNight 380 ], [ dc:title "Christmas & New Year Rates" ; :pricePerNight 575 ] ;

But in resulting output generated by comunica-sparql http://localhost/sapphire217.ttl "CONSTRUCT {  ?s ?p ?o } WHERE { ?s ?p ?o }"

rates come out like:     <http://plushvilla.com#rates> _:bc_0_n3-076, _:bc_0_n3-187, _:bc_0_n3-298;

But the actual rates (which nothing points to) that come out are:
_:bc_0_n3-04241 <http://purl.org/dc/elements/1.1/title> "Winter Rates".
_:bc_0_n3-04342 <http://plushvilla.com#pricePerNight> 450.
_:bc_0_n3-14443 <http://purl.org/dc/elements/1.1/title> "Summer Rates".
_:bc_0_n3-14544 <http://plushvilla.com#pricePerNight> 380.
_:bc_0_n3-24645 <http://purl.org/dc/elements/1.1/title> "Christmas & New Year Rates".
_:bc_0_n3-24746 <http://plushvilla.com#pricePerNight> 575.

____

**Comment by garpinc** [comment]
[sapphire217.zip](https://github.com/comunica/comunica/files/6197941/sapphire217.zip)

**Comment by rubensworks** [comment]
This is a known issue, and something we'll fix soon=. See #795.
