### ISSUE TITLE
Vitejs and Comunica problem

### ISSUE THREAD

**Issue by Melchyore** [comunica/comunica#807]
#### Issue type:

- :bug: Bug 

____
#### Description:

Hello, I have a web app using Vitejs and Vuejs and I want to use Comunica but there's a problem and I think it's related to Nodejs packages... I don't think Vitejs will polyfill Nodejs packages.

This is the error I get:
![image](https://user-images.githubusercontent.com/6685773/114306079-f93cee00-9ada-11eb-9685-fb7956f909bf.png)

And this is the source of the error:
![image](https://user-images.githubusercontent.com/6685773/114306111-0e198180-9adb-11eb-81a7-a3ddbe7e54bc.png)

I tried `yarn add stream` but the error is still there.

PS: I can't use Webpack or Browserify as I'm already using Vite.

Can you help me, please.
____
#### Environment:

Browser

**Comment by rubensworks** [comment]
> I don't think Vitejs will polyfill Nodejs packages.

I would suspect Vitejs would allow you to include polyfills for those missing packages, just like tools such as Webpack enable.

I have no experience with Vitejs, so I'm afraid I can't help you much more than that.

**Comment by Melchyore** [comment]
@rubensworks Thanks for your answer. Indeed, Vitejs doesn't include Nodejs polyfills and adding them is so hard... So I started a new project with Webpack 4 (even Webpack 5 will remove Nodejs shims...).
