### ISSUE TITLE
IQueryResult interface is missing bindingsStream property and probably many others

### ISSUE THREAD

**Issue by Melchyore** [comunica/comunica#809]
#### Issue type:

- :bug: Bug 

____
#### Description:

Hello!

The return type of `query` method is missing properties as `bindingsStream` and propably many others.

![image](https://user-images.githubusercontent.com/6685773/114445557-801fc280-9bd0-11eb-99b0-62146956f9bd.png)

____
#### Environment:

Browser

**Comment by rubensworks** [comment]
You should cast your query result to `IQueryResultBindings`.
More information in #746.

**Comment by fetahokey** [comment]
```
const execQuery = async () => {
  const result = await myEngine.query(
    `
        SELECT ?s ?p ?o WHERE {
          ?s ?p <http://dbpedia.org/resource/Belgium>.
          ?s ?p ?o
        } LIMIT 100`,
    {
      sources: ["http://fragments.dbpedia.org/2015/en"],
    }
  );

  return result;
};

```
 cast your query result to IQueryResultBindings. [ref](https://github.com/comunica/comunica/issues/809#issuecomment-818461659)
 

```
 // 
const result = (await execQuery ()) as IQueryResultBindings;
  result.bindingsStream.on("data", (binding) => {
    console.log(binding.get("?s").value);
    console.log(binding.get("?s").termType);
    console.log(binding.get("?p").value);
    console.log(binding.get("?o").value);
  });

```
