### ISSUE TITLE
Send SPARQL Queries via POST?

### ISSUE THREAD

**Issue by alexkreidler** [comunica/comunica#814]
#### Issue type:

- :question: Question 

____
#### Question:

Does Comunica support quering endpoints using the [SPARQL Protocol](https://www.w3.org/TR/sparql11-protocol/#protocol) POST option?

I have a query that I'd like to send with a large number of IRIs in a sparql `VALUES` block. However, when I query Wikidata or DBPedia, I get a "URL too long" HTTP 414 error because Comunica sends the query as a query parameter.

If Comunica could send the query via POST, I think that would fix the issue. Thanks!

**Comment by rubensworks** [comment]
This is not supported atm, but we probably should support this (and even make POST-based querying the default).
