### ISSUE TITLE
Cannot connect with basic auth to local stain/jena-fuseki docker container

### ISSUE THREAD

**Issue by myonara** [comunica/comunica#815]
#### Issue type:

- :bug: Bug 

____
#### Description:

Following command line is bringing an error:
> comunica-sparql http://admin:simple@localhost:3030/learning1 -q "create graph <http://example.com/test1>"

Following error:

>https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/rdf-update-rdfjs.json#mediatorRdfUpdateHypermedia mediated over all rejecting actors:
Actor https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/rdf-update-rdfjs.json#myRdfUpdateHypermediaPatchSparqlUpdate could not detect a destination with 'application/sparql-update' as 'Accept-Patch' header.

Same error occurs also with both authorisation methods from https://comunica.dev/docs/query/advanced/basic_auth/

Same query is working in the web front end (after logon) of http://localhost:3030/learning1

____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.21.1
| node                | v14.16.1
| npm                 | 7.11.1
| yarn                | _Yarn is unavailable_
| Operating System    | win32 (Windows_NT 10.0.19042)

The docker container is pulled with
docker pull stain/jena-fuseki
The fuseki docker container was started with
docker run -d --name fuseki -p 3030:3030 -e ADMIN_PASSWORD=simple stain/jena-fuseki

**Comment by rubensworks** [comment]
I see you're trying to send a SPARQL update query.
Unfortunately, sending such queries to SPARQL endpoints is not supported yet.
We only support sending read-only queries at the moment.

But such support _is_ planned in the near future though :-)

**Comment by rubensworks** [comment]
Support for this has been implemented in 299848579c6f8d6570a169d7288d36849b806213.
New release with this functionality is coming soon!
