### ISSUE TITLE
Query result not consistent over time

### ISSUE THREAD

**Issue by mvanbrab** [comunica/comunica#817]
#### Issue type:

- :bug: Bug 

____
#### Description:

Execution of the same query does not always return the same result.

Observed while using Comunica in a [Walder](https://github.com/KNowledgeOnWebScale/walder) project,
however for the purpose of this issue **isolated in [this small command line test app](https://github.com/mvanbrab/comunica-test-knows)**. This test app is recommended to reproduce the issue.

Full query input (GrapQL query, JSON-LD context, datasources) and query output available in the **log files** of that test app.

The `contactPoint` entry for ` "id": "https://ben.de-meester.org/#me"` appears/disappears randomly in some query results:
```
          },
          "contactPoint": [
            {
              "id": "https://ben.de-meester.org/#me",
              "mbox": "mailto:<etc>",
              "familyName": "De Meester",
              "givenName": "Ben"
            },
            {
              "id": "https://natadimou.com/#me",
              "mbox": "mailto:<etc>",
```
(This can be seen in the delta between commits of the file **index.log** of the test app too)
____
#### Environment:

Output in the test app of `node ./node_modules/@comunica/actor-init-sparql/bin/query.js -v`:
```
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.21.1 
| node                | v14.16.1
| npm                 | 6.14.12
| yarn                | 1.22.5
| Operating System    | linux (Linux 4.15.0-142-generic)
```

**Comment by mvanbrab** [comment]
Possibly related to #816

**Comment by rubensworks** [comment]
Is this with lenient mode enabled? Because that could explain the inconsistent query results if errors were to occur.

**Comment by mvanbrab** [comment]
yes it is, https://github.com/mvanbrab/comunica-test-knows/blob/28d007b7e44651c56396a54e4d7649764a75b004/index.js#L72

**Comment by rubensworks** [comment]
And do you see any warnings from the Comunica logger showing up when executing this in lenient mode?

**Comment by mvanbrab** [comment]
I'll run again with test app's **--logc debug** for two runs with different output and report here.

**Comment by mvanbrab** [comment]
My observations with **--logc debug** and the mentioned logfiles are available in my [test app](https://github.com/mvanbrab/comunica-test-knows). Read **OBSERVATIONS.md** there or a copy of the relevant part here:

"
## 2020-05-06
Additional loggings with Comunica logging level debug, on request:
- index-logc-debug-1.log, index-logc-debug-2.log: two runs (giving different results), run with commandline `NODE_ENV=production node ./index.js --log verbose --logc debug 2>&1 | tee <logfile>.log`.
- index-logc-debug-3-not-lenient.log: third run with same commandline as above, but code modified to set Comunica's lenient option `false`.

Observations:
- (1) Following differences in output data between first and second run:
  - in first run, `"id": "https://ben.de-meester.org/#me"` is missing from the output of query 30/48.
  - in second run, `"id": "https://ben.de-meester.org/#me"` is missing from the output of query 10/48.
  - in second run, `"id": "https://hvdsomp.info/#i"` is missing from the output of query 47/48.
- (2) Multiple occurrences of `ERROR: socket hang up` in first and second run, not immediately correlated to the missing output given above.
- (3) One occurrence of `ERROR: connect ETIMEDOUT 68.65.123.238:443` in second run, during query 47/48.
- (4) Interesting stacktrace when app ends in third run (Comunica not in lenient mode):
  ```
  (node:2896) UnhandledPromiseRejectionWarning: Error: socket hang up
  at connResetException (internal/errors.js:607:14)
  at TLSSocket.socketOnEnd (_http_client.js:493:23)
  at TLSSocket.emit (events.js:327:22)
  at endReadableNT (internal/streams/readable.js:1327:12)
  at processTicksAndRejections (internal/process/task_queues.js:80:21)
  (Use `node --trace-warnings ...` to show where the warning was created)
  (node:2896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 33264)
  (node:2896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  ```
"

**Comment by rubensworks** [comment]
Thanks for checking @mvanbrab!
So it looks like server errors occur, but do not seem to be correlated with missing results.

For future reference: it would be good to repeat this experiment in a more controlled environment, where we can disable lenient mode, and can rule out remote server issues.

**Comment by rubensworks** [comment]
Does this problem still occur?

**Comment by mvanbrab** [comment]
@rubensworks Yes, still there. I update my test case to your earlier suggestions and made new observations. Details in my test repo at https://github.com/mvanbrab/comunica-test-knows/blob/master/OBSERVATIONS.md#2022-11-15.

In a nutshell: still inconsistent for source https://ben.de-meester.org/; inconsistency preceeded by a `socket hang up` error.

The `socket hang up` error is not thrown back to the app if lenient = true; it is if lenient = false; all as expected.

Perhaps the server conditions for source https://ben.de-meester.org/ have to be looked to in detail?

**Comment by rubensworks** [comment]
> preceeded by a socket hang up error

This reminds me of a problem that @elsdvlee ran into recently.

So this is definitely something that needs to be looked into at someone.

**Comment by mvanbrab** [comment]
As a reminder: updated output in the test app of `node ./node_modules/@comunica/actor-init-sparql/bin/query.js -v`
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.22.3 
| node                | v16.18.1
| npm                 | 8.19.2
| yarn                | 1.22.19
| Operating System    | linux (Linux 5.15.0-52-generic)

So: still in version 1.x

**Comment by rubensworks** [comment]
Could you try using `@comunica/query-sparql` in the 2.x range?

**Comment by mvanbrab** [comment]
I'll make a branch in my test repo for that. This will move away the repo from its original intention: to troubleshoot in an isolated way a behaviour found in Walder, but it'll be a good indication for possible Comunica problem in v2.x. I'll report back here.

**Comment by mvanbrab** [comment]
Unfortunately, it's there with Comunica v2.x as well. See the [observations](https://github.com/mvanbrab/comunica-test-knows/blob/comunicav2/OBSERVATIONS.md#2022-11-16) on  [my migrated test](https://github.com/mvanbrab/comunica-test-knows/blob/comunicav2/index.js).

**Comment by rubensworks** [comment]
Thanks for checking. Good to know the problem still occurs.

**Comment by rubensworks** [comment]
This issue has been fixed in master.
But you should be able to make use of the fix by resetting your lockfile (asynciterator should be 3.8.1).
