### ISSUE TITLE
Implement OPT+ operator

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#825]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

The standard OPTIONAL operator is SPARQL is non-monotonic, which can lead to problem with streaming results. Concretely, intermediary results that do _not_ match with an OPTIONAL block will not be emitted until the whole relevant part of the dataset is handled. In practise, this means that some results will not become available to the user as soon as possible.

The paper ["OPT+: A Monotonic Alternative to OPTIONAL in SPARQL" (by Sijin Cheng and Olaf Hartig)](https://www.researchgate.net/publication/333627321_OPT_A_Monotonic_Alternativeto_OPTIONAL_in_SPARQL)
introduces the OPT+ operator, which makes OPTIONAL monotonic by changing its semantics (`A OPT+ B = (A AND B) UNION A`).

The modified nested loop join algorithm from the paper (others are proposed) seems to achieve the best results.

We can create a modified version (or provide a config option) of our OPTIONAL actor (`actor-query-operation-leftjoin-nestedloop`) that considers this modification.
In essence, this modification means that a result can be emitted twice: once _without_ the optional binding, and once _with_ the optional binding.

Since this modification is not strictly spec-compliant anymore, we should not enable it by default. But having it available can be useful for many use cases, especially when we have many sources (or when we are doing link traversal).

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| €1088 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment]
A bounty has been placed on this issue via the Comunica Association (see original post).

**Comment by jeswr** [comment]
As discussed with @rubensworks , I will work on this issue.
