### ISSUE TITLE
Comunica goes out-of-memory

### ISSUE THREAD

**Issue by MPvHarmelen** [comunica/comunica#826]
#### Issue type:

- :bug: Bug 

____
#### Description:

We're experiencing memory issues where a NodeJS process goes out-of-memory within ~20 seconds. We've managed to create a minimum working example that shows the same behaviour, although it takes a bit longer (depending on your hardware and node-js memory settings):

```js
const { newEngine } = require("@comunica/actor-init-sparql-rdfjs");
async function run() {
  const engine = newEngine();
  while (true) {
    await engine.query("SELECT * WHERE { ?s ?p ?o }", {
      sources: [],
    });
  }
}
run();
```

To test, run:

```sh
NODE_OPTIONS=--max-old-space-size=256 node ./mwe.js
```

(Decreasing the node-js memory is optional. It ensures you don't have to wait too long for the process to crash.)

cc @LaurensRietveld

____
#### Environment:

`node ./node_modules/@comunica/actor-init-sparql/bin/query.js -v` prints

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.21.1 
| node                | v12.22.1
| npm                 | 6.14.12
| yarn                | 1.22.5
| Operating System    | linux (Linux 5.8.0-53-generic)

#### Crash log:
<details>
<summary>Click here to (un)fold the logs</summary>

```
<--- Last few GCs --->

[97485:0x3280eb0]    72871 ms: Mark-sweep 242.4 (261.0) -> 242.4 (250.0) MB, 99.5 / 1.1 ms  (average mu = 0.138, current mu = 0.000) last resort GC in old space requested
[97485:0x3280eb0]    72975 ms: Mark-sweep 242.4 (250.0) -> 242.2 (250.0) MB, 103.3 / 1.2 ms  (average mu = 0.072, current mu = 0.000) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x140de99]
Security context: 0x0890d5f408d1 <JSObject>
    1: set [0x890d5f46691](this=0x3b290c15ed31 <Map map = 0x3a65e180f29>,4294077,0x3b290c15ecc1 <WeakReference map = 0x3a65e1a0739>)
    2: emitInitNative [0x2f0ae50c25a1] [internal/async_hooks.js:~186] [pc=0x20728fc03e01](this=0x072d3c3e1b49 <PromiseWrap map = 0xc25c91dc319>,4294077,0x0f2388e499d1 <String[#7]: PROMISE>,4294071,0x072d3c3e1b49 <PromiseWrap map = 0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0xa1a640 node::Abort() [node]
 2: 0xa1aa4c node::OnFatalError(char const*, char const*) [node]
 3: 0xb9a68e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9aa09 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd57c85  [node]
 6: 0xd685d8 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 7: 0xd2f2cd v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::RootIndex, int, v8::internal::Object, v8::internal::AllocationType) [node]
 8: 0xd2f3c0 v8::internal::Handle<v8::internal::FixedArray> v8::internal::Factory::NewFixedArrayWithMap<v8::internal::FixedArray>(v8::internal::RootIndex, int, v8::internal::AllocationType) [node]
 9: 0xf5e100 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate(v8::internal::Isolate*, int, v8::internal::AllocationType) [node]
10: 0xf5e1b1 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [node]
11: 0xf5e7fb v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::EnsureGrowable(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>) [node]
12: 0x10550c8 v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [node]
13: 0x140de99  [node]
Aborted (core dumped)
```
</details>

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Triply" src="https://nightly.triplydb.com/imgs/logos/logo-lg.svg?v=3" height="25">](https://triply.cc/) |
|  |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment]
Might be related to #816 (promise rejection accumulation).

**Comment by MPvHarmelen** [comment]
By the way, it seemed that having (more) content in a referenced source made it go OOM sooner.

**Comment by rubensworks** [comment]
@MPvHarmelen FYI, based on some (very limited) testing, I noticed that adding a `await new Promise(setImmediate);` after each query call solves the memory issues.
So if this is an urgent issue, you could try this to see if it solves your problem.
(If this only solves the problem on the minimal case, but not on the actual larger queries, then we know that there are actually multiple related problems that cause memory issues)

I suspect adding this fixes the problem as it gives the garbage collector some time to cleanup unresolved promise rejections. This should not be necessary, but may give an indication of the root problem.

**Comment by LaurensRietveld** [comment]
Hi @rubensworks , thanks! Some early checks indeed show this workaround solves the memory issues :+1:

**Comment by rubensworks** [comment]
Great, that's good news.

So in order to fully resolve this issue, we need to:
1. Figure out why the `pendingUnhandledRejections` array keeps growing (#816). I suspect this may be because we're not always catching promise rejections at the right place, which makes Node go into a sub-optimal path.
2. Implement a solution to the problem.

This problem may also be related to the recent `queueMicrotask` changes in AsyncIterator, so @RubenVerborgh may also have some ideas about the cause of this one.

**Comment by RubenVerborgh** [comment]
> This problem may also be related to the recent `queueMicrotask` changes in AsyncIterator, so @RubenVerborgh may also have some ideas about the cause of this one.

Not directly, I think… unless it's in an environment where `queueMicrotask` is unavailable?

**Comment by rubensworks** [comment]
> Not directly, I think… unless it's in an environment where queueMicrotask is unavailable?

It's just in Node.js
I was thinking that it might be related to `queueMicrotask` being "too fast", so that the GC never gets the time to start, while throwing in a random `setImmediate` does give sufficient time.

**Comment by RubenVerborgh** [comment]
Ooh that's a good one. We might want to use the same [trick](https://github.com/RubenVerborgh/AsyncIterator/blob/v3.1.0/taskscheduler.ts#L13) we use in the browser.

**Comment by rubensworks** [comment]
Ah, I forgot about that one.
I'll do some debugging to see if that trick resolves the problems here as well.
If so, I'll send a PR to AsyncIterator to make this the default for Node.js.

**Comment by rubensworks** [comment]
Applying the following does not have any impact on the minimal test case:
```javascript
const setTaskScheduler = require('asynciterator').setTaskScheduler;
let i = 0;
setTaskScheduler((task) => {
  if (++i < 100)
    queueMicrotask(task);
  else {
    i = 0;
    setImmediate(task);
  }
});
```

But since this minimal test case is not very realistic, this behaviour might make sense.

@MPvHarmelen @LaurensRietveld could you check if adding my snippet to your actual use case solves/impacts the problem?

**Comment by RubenVerborgh** [comment]
Also just noticed that there is a bug in the above implementation: we lose the order guarantee, because it is possible that task 101 executes before task 100. https://github.com/RubenVerborgh/AsyncIterator/issues/28

**Comment by LaurensRietveld** [comment]
> Applying the following does not have any impact on the minimal test case:
> 
> ```js
> const setTaskScheduler = require('asynciterator').setTaskScheduler;
> let i = 0;
> setTaskScheduler((task) => {
>   if (++i < 100)
>     queueMicrotask(task);
>   else {
>     i = 0;
>     setImmediate(task);
>   }
> });
> ```
> 
> But since this minimal test case is not very realistic, this behaviour might make sense.
> 
> @MPvHarmelen @LaurensRietveld could you check if adding my snippet to your actual use case solves/impacts the problem?

Just checked, and this seems to work as well :+1:

**Comment by rubensworks** [comment]
PR with fix created at https://github.com/RubenVerborgh/AsyncIterator/pull/29
