### ISSUE TITLE
SPARQL endpoint over file

### ISSUE THREAD

**Issue by ddeboer** [comunica/comunica#839]
#### Issue type:

- :question: Question 

____
#### Question:

Should it be possible to use `comunica-sparql-http` to expose a SPARQL endpoint based on a local RDF file?

```
comunica-sparql-http file.ttl
Server running on http://localhost:3000/sparql

Server worker (5706) running on http://localhost:3000/sparql
```

When I query this endpoint from the Comunica client, the server outputs:

```
[200] POST to /sparql
      Requested media type: application/sparql-results+json
      Received query query: SELECT ?s ?p ?o WHERE { ?s ?p ?o. }
[500] Server error in results: Could not dereference 'file.ttl'
```

If this is not possible, what would be a good way to start a simple SPARQL server in my app’s local integration tests?

**Comment by rubensworks** [comment]
You have to use `@comunica/actor-init-sparql-file` and `comunica-sparql-file-http` for doing that. More information can be found here: https://comunica.dev/docs/query/getting_started/query_cli_file/

**Comment by ddeboer** [comment]
But that’s for querying. My question is about running a SPARQL endpoint (https://comunica.dev/docs/query/getting_started/setup_endpoint/) based on an RDF file.

**Comment by rubensworks** [comment]
That should be possible with the `comunica-sparql-file-http` tool after installing `@comunica/actor-init-sparql-file`.

**Comment by ddeboer** [comment]
Thanks! Documented the feature in comunica/website#17.
