### ISSUE TITLE
@comunica-actor-init-sparql not working with webpack build (EmberJS)

### ISSUE THREAD

**Issue by Youssef-98** [comunica/comunica#847]
#### Issue type:

- :bug: Bug 

____
#### Description:

I'm working on a small EmberJS project in where I try to use comunica-actor-init-sparql in order to use some sparql queries and use this data to show on a leaflet map. I installed `ember-auto-import` in order to install normal  npm packages like this one and it installed perfectly fine. However, when I try to import the `newEngine()` function like so: `import { newEngine } from '@comunica/actor-init-sparql';` in `app/components/map.js`, I get a webpack build error which says that this npm package returns an error to ember-auto-import.

Is this an issue with the npm package not working in a webpack build? Or is it something I'm missing on my side of things?

You can see the installed dependency in my package.json file and I even get an auto correct from intellisense which shows all the usable functions from this npm package. My repo can be found and pulled at: [https://github.com/Youssef-98/ember-comunica-project](url). The error log can be found in the root of the project.
____

#### Crash log:
https://github.com/Youssef-98/ember-comunica-project/blob/master/error.dump.346ec0e46598d45841a9c7eb27d03ea5.log](url)

**Comment by rubensworks** [comment]
> Error: webpack returned errors to ember-auto-import

You'll probably want to check the webpack output to see what is going wrong.

I suspect you're using Webpack 5, which doesn't include polyfills for Node anymore by default.
So you'll have to configure these in your Webpack config.

**Comment by Youssef-98** [comment]
> > Error: webpack returned errors to ember-auto-import
> 
> You'll probably want to check the webpack output to see what is going wrong.
> 
> I suspect you're using Webpack 5, which doesn't include polyfills for Node anymore by default.
> So you'll have to configure these in your Webpack config.

Added this to my `ember-cli-config.js` which did resolve the errors in my terminal, but the function to test a query doesn't work sadly. I used the demo function from the docs but now I get following error in devtools: 
![image](https://user-images.githubusercontent.com/79165502/128848751-50b1216e-c017-4d2c-886e-c158a6dac556.png)

**Comment by rubensworks** [comment]
That's a weird error...

Could you try reproducing in a normal Node.js setup? I suspect something is being misconfigured in your ember setup that causes external libs to misbehave.

**Comment by Youssef-98** [comment]
I'm checking the webpack output with the `AUTO_IMPORT_VERBOSE=true ember serve` command in the terminal which now gives me the following error:

```
WARNING in ./node_modules/sax/lib/sax.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\Youssef\Desktop\ember-leaflet-tracker\node_modules\sax\lib'
 @ ./node_modules/sax/lib/sax.js
 @ ./node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js
 @ ./node_modules/rdfxml-streaming-parser/index.js
 @ ./node_modules/@comunica/actor-rdf-parse-rdfxml/lib/ActorRdfParseRdfXml.js
 @ ./node_modules/@comunica/actor-rdf-parse-rdfxml/index.js
 @ ./node_modules/@comunica/actor-init-sparql/engine-default.js
 @ ./node_modules/@comunica/actor-init-sparql/index-browser.js
 @ C:/Users/Youssef/AppData/Local/Temp/broccoli-21580ns56ZeIp4dFq/cache-346-bundler/staging/app.js
 @ multi C:/Users/Youssef/AppData/Local/Temp/broccoli-21580ns56ZeIp4dFq/cache-346-bundler/staging/l.js C:/Users/Youssef/AppData/Local/Temp/broccoli-21580ns56ZeIp4dFq/cache-346-bundler/staging/app.js

ERROR in ./node_modules/@comunica/actor-http-native/lib/Requester-browser.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\Youssef\Desktop\ember-leaflet-tracker\node_modules\@comunica\actor-http-native\lib'
 @ ./node_modules/@comunica/actor-http-native/lib/Requester-browser.js 16:17-34
 @ ./node_modules/@comunica/actor-http-native/lib/ActorHttpNative.js
 @ ./node_modules/@comunica/actor-http-native/index.js
 @ ./node_modules/@comunica/actor-init-sparql/engine-default.js
 @ ./node_modules/@comunica/actor-init-sparql/index-browser.js
 @ C:/Users/Youssef/AppData/Local/Temp/broccoli-21580ns56ZeIp4dFq/cache-346-bundler/staging/app.js
 @ multi C:/Users/Youssef/AppData/Local/Temp/broccoli-21580ns56ZeIp4dFq/cache-346-bundler/staging/l.js C:/Users/Youssef/AppData/Local/Temp/broccoli-21580ns56ZeIp4dFq/cache-346-bundler/staging/app.js

```

Is this a module needed for comunica to work with webpack?

**Comment by rubensworks** [comment]
I don't think I can help you out much more, seems like an Ember/Webpack configuration issue. Perhaps asking this question on one of their fora can help?

**Comment by Youssef-98** [comment]
> I don't think I can help you out much more, seems like an Ember/Webpack configuration issue. Perhaps asking this question on one of their fora can help?

No problem. I greatly apprectiate your help!
