### ISSUE TITLE
Remove dependency on Node.js APIs

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#857]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

Currently, when trying to bundle Comunica via tools such as Webpack (>= 5.x) requires users to manually configure polyfills for Node.js built-ins. We should make this process easier by not directly depending on Node.js built-ins, and instead use libraries such as `readable-stream`.

This will also require some changes to several dependencies, such as RDF parsers.

We should ensure that no such Node.js built-in dependencies are added in the future, either via a linter rule if that exists, or via a webpack process during CI.

We should make sure that we don't see any performance degradations because of this.

**The end-result of this issue should be that we can run webpack 5 on @comunica/query-sparql without having to configure any polyfills.**

Also add `"sideEffects": false` to package.json where applicable.

Related to :

* https://github.com/rubensworks/jsonld-streaming-parser.js/issues/78
* https://github.com/rubensworks/rdfa-streaming-parser.js
* https://github.com/rubensworks/microdata-rdf-streaming-parser.js
* https://github.com/rdfjs/rdfxml-streaming-parser.js
* https://github.com/rubensworks/rdf-dereference.js/issues/32
* *And possibly several others*

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| *Variable budget* |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment]
For people running into this issue with Webpack 5, in the meantime you can use: https://www.npmjs.com/package/node-polyfill-webpack-plugin

**Comment by Tpt** [comment]
As discussed with @rubensworks, I will work on this issue via the Comunica Association.

**Comment by Tpt** [comment]
@jacoscaz Thank you!

**Comment by rubensworks** [comment]
This might be a good replacement for stream: https://www.npmjs.com/package/readable-stream

**Comment by Tpt** [comment]
Thank you!

> Given https://github.com/nodejs/readable-stream/issues/448, I suspect that readable-stream works out-of-the-box in Webpack.
However, the [readme indicates otherwise](https://www.npmjs.com/package/readable-stream#user-content-usage-in-browsers).
So we will have to double-check this.

Even if it would work out of the box, our dependencies depend on `readable-stream` v1, v2 and v3 but not v4. So we would still have to migrate them to something.

> jsonld-streaming-serializer (and other parsers and serializers): Is in our control, feel free to submit a PR to migrate to `readable-stream`.

Sure!

> `web-streams-node`: This has always been a tricky one. Happy with hacky workarounds as well, since this one won't be needed anymore in Node 18.

I believe that `readable-stream-node-to-web` should be a drop in replacement without hard dependency on `stream`. But I need to check again.

> `xml`: A browser-safe alternative may exist for this.

I am going to have a look at it.

**Comment by rubensworks** [comment]
> Even if it would work out of the box, our dependencies depend on readable-stream v1, v2 and v3 but not v4. So we would still have to migrate them to something.

Indeed, we'll have to make sure all of them reach v4.

> I believe that readable-stream-node-to-web should be a drop in replacement without hard dependency on stream. But I need to check again.

Be aware that this one has been last published 5 years ago, so it may be unmaintained.

**Comment by Tpt** [comment]
> Be aware that this one has been last published 5 years ago, so it may be unmaintained.

Indeed. But it's currently a dependency of `web-streams-node` so it won't make things worst imho.
