### ISSUE TITLE
Implement ZeroOrOne path expressions with 2 variables

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#863]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

This has not been implemented yet apparently.
Probably because doing it in a performant manner is non-trivial.
Related to #709.

**Comment by danielbeeke** [comment]
I encountered this error sometimes while trying to do things with collections:

```
?s rdf:rest*/rdf:first? ?o
```

@rubensworks if given pointers would you think I could give it a try? I could maybe start with a version that is not super performant.

**Comment by rubensworks** [comment]
@danielbeeke This would be the location that requires implementation of this: https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-path-zero-or-one/lib/ActorQueryOperationPathZeroOrOne.ts#L44

Note that path-related logic can get quite complex, so I would not recommend getting into this as your first contribution in comunica. (but you're welcome to try of course :-) )
