### ISSUE TITLE
Error when using GROUP_CONCAT with variables occurring only in OPTIONAL clauses

### ISSUE THREAD

**Issue by jacoscaz** [comunica/comunica#866]
#### Issue type:

- :bug: Bug

____
#### Description:

The usage of `GROUP_CONCAT` when selecting a variable that only occurs in an optional clause can result in the error `Error: Variables '?c,?src' are used in the projection result, but are not assigned.`.

Example query:

```sparql
  PREFIX ov: <http://open.vocab.org/terms/>
  SELECT ?c
  (GROUP_CONCAT(distinct(CONCAT(?l,"@",lang(?l)));separator="|") as ?l)
  ?src
  
  WHERE
  {
    ?c a owl:Class.
    OPTIONAL {?c rdfs:label ?l.}
    OPTIONAL {?src ov:defines ?c.}
  }
```

Can be easily reproduced at [query.linkeddatafragments.org](http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fwww.rubensworks.net%2F&query=PREFIX%20ov%3A%20%3Chttp%3A%2F%2Fopen.vocab.org%2Fterms%2F%3E%0A%20%20SELECT%20%3Fc%0A%20%20(GROUP_CONCAT(distinct(CONCAT(%3Fl%2C%22%40%22%2Clang(%3Fl)))%3Bseparator%3D%22%7C%22)%20as%20%3Fl)%0A%20%20%3Fsrc%0A%20%20%0A%20%20WHERE%0A%20%20%7B%0A%20%20%20%20%3Fc%20a%20owl%3AClass.%0A%20%20%20%20%3Fc%20rdfs%3Alabel%20%3Fl.%0A%20%20%20%20%3Fsrc%20ov%3Adefines%20%3Fc.%0A%20%20%7D).

This also seems to happen with `MINUS` queries such as:

```sparql
PREFIX ex: <http://www.w3.org/2009/sparql/docs/tests/data-sparql11/negation#>
SELECT * {
  ?animal a ex:Animal MINUS {
    optional {
    ?animal a ?type
    FILTER(?type = ex:Reptile || ?type = ex:Insect)
    }
  }
}
```

A very minor change [here](https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-project/lib/ActorQueryOperationProject.ts#L35-L40) might be all that is needed to fix this.

____
#### Environment:

This happened using `@comunica/actor-init-sparql^1.22.2` as bundled in `quadstore-comunica@9.2.0-alpha.0` and was first reported in https://github.com/beautifulinteractions/node-quadstore/issues/142 .

**Comment by pwin** [comment]
using Comunica in ``` http://semantechs.co.uk/turtle-editor-viewer/ ``` I am getting an error
```
Variables '?dept' are used in the projection result, but are not assigned.
```
when using the following query

```
prefix : <http://ns/>
select * {
?x a :Personnel  ; 
:name ?name  ; 
:ssn ?ssn
  .
  FILTER EXISTS {
         :_Person_2 :hrManages ?dept.
         ?x :memberOf ?dept.
       }
}
```

on this data

```
@prefix : <http://ns/>  .

:_Person_1 a :Personnel
; :ssn "111-11-1111"; 
:name "Bob S"; 
:memberOf :_Dept_A
.

:_Person_2 a :Personnel;
 :ssn "222-22-2222"; 
:name "Jane E";
:memberOf :_Dept_A;
:hrManages :_Dept_A
.

:_Person_3 a :Personnel; 
:ssn "333-33-3333"; 
:name "Ajit S"; 
:memberOf :_Dept_B; 
:hrManages :_Dept_B
.
```

the error is in

```
        // Error if there are variables that are not bound in the input stream.
        const missingVariables = variables.filter(variable => !output.variables.includes(variable) &&
            variable !== '*');
        if (missingVariables.length > 0) {
            throw new Error(`Variables '${missingVariables}' are used in the projection result, but are not assigned.`);
        }

```

**Comment by rubensworks** [comment]
Thanks @pwin. @joachimvh just pointed me out that #914 seems to be the cause of this issue.

**Comment by jacoscaz** [comment]
@rubensworks can this be closed?

**Comment by rubensworks** [comment]
I think so, yes. Could you confirm that this works now on your end?

**Comment by jacoscaz** [comment]
Confirmed!
