### ISSUE TITLE
Describe query for blank node not working as expected

### ISSUE THREAD

**Issue by ahka01** [comunica/comunica#870]
#### Issue type:

- :bug: Bug 

____
#### Description:

While using `DESCRIBE` query to retrieve the triples linked to a `blank node`, the returned triples seems to be erroneous. In the returned results, triples that should have similar subjects (i.e the same blank node uri), they're becoming different uri.

Example:

consider the following triples:
```ttl
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix ex: <http://example.com/> .

ex:a a ex:b;
    ex:c ex:d;
    ex:e [
        a ex:f;
        ex:v ex:m ;
    ]
.
```
and the following `DESCRIBE` query:
```sparql
DESCRIBE ?o {
    ?s ?p ?o .
        FILTER(isBlank(?o)) 
}
```

____
#### Environment:
The current results with current version `1.20.0` looks like this:
```
subject                      predicate                                            object                                                                                         
--------------------------------------------------------------------------------------------------------------
bc_0_n3-00            http://www.w3.org/1999/02/22-rdf-syntax-ns#type            http://example.com/f                                                                                 
bc_0_n3-01              http://example.com/v                                     http://example.com/m  
```

#### Expected output:
What to expect, might looks like:
```
subject                      predicate                                            object                                                                                         
--------------------------------------------------------------------------------------------------------------
bc_0_n3            http://www.w3.org/1999/02/22-rdf-syntax-ns#type            http://example.com/f                                                                                 
bc_0_n3             http://example.com/v                                      http://example.com/m  
```

**Comment by ahka01** [comment]
Hi,

it is still giving the same behavior in version `2.0.6`. The returned table of the example above is the same. Trying it on other example led also to something similar. When the subject node is a black node, it comes back with different names, for the related triples.

Thanks and regards

**Comment by constraintAutomaton** [comment]
I'm interested in tackling it.

**Comment by rubensworks** [comment]
Great! Let me know if you need any input @constraintAutomaton :-)
