### ISSUE TITLE
Perform joins based on dictionary-encoded triples

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#873]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

Dictionary encoding is often used to improve performance of comparing terms with each other.
During the processing of joins, term comparison have to be done a lot, so the ability to dictionary-encode terms will have a big impact on performance.

Open question: This will probably only be possible if joining in a single source.

We have to make sure that term id's are inherited from the store, and are built using a dictionary that optimizes .equals (and a join hash?) => allow sources to provide term hashes/ids?

Related to #756.

**Comment by jacoscaz** [comment]
This is of _extreme_ interest for persistence and query optimization as well. Quadstore has its own serialization strategy, which I bootstrapped from what used to be N3's own strategy, the two of them likely having diverged over time. It'd be terrific to find a way to share dictionary encoding at all layers of a RDF/JS software stack, with such encoding keeping lexicographical and value-based ordering aligned.

**Comment by rubensworks** [comment]
Just did a small microbenchmark (on Node 18) to see what theoretical performance boost we could get by simulating some NLJs:

```javascript
const numbers = [];
const strings = [];
const SIZE = 100000;

for (let i = 0; i < SIZE; i++) {
    numbers[i] = Math.floor(Math.random() * 1000);
}
for (let i = 0; i < SIZE; i++) {
    strings[i] = `abc${Math.floor(Math.random() * 1000)}`;
}

function loop(array, size) {
    const eq = [];
    for (let i = 0; i < size; i++) {
        for (let j = 0; j < size; j++) {
            if (array[i] === array[j]) {
                eq.push(i);
            }
        }
    }
    return eq;
}

function measure(size) {
    console.time('numbers');
    console.log(loop(numbers, size).length);
    console.timeEnd('numbers');

    console.time('strings');
    console.log(loop(strings, size).length);
    console.timeEnd('strings');
}

measure(SIZE); // warmup
measure(SIZE);

```

Output:
```
numbers: 11.725s
strings: 3:22.287 (m:ss.mmm)
```

Multiple runs and sizes seems to indicate we can get up to 10x~20x times faster using dict encoding.
For Hash Joins, the performance boost will probably exist as well, but I suspect it will be smaller.

**Comment by rubensworks** [comment]
So I just did _a lot_ of experimenting and testing, and I was not able to come up with something that had any significant performance impact.
So while a microbenchmark definitely shows a benefit for dictionary encoding, this doesn't appear to have a significant impact within a full query engine (using the V8 engine).
String interning seems to be pretty performant in V8.
Hence, I propose closing this issue, as we don't need to make the code unnecessarily complex without any clear performance benefits.

For future reference, these branches were used for testing:
- https://github.com/comunica/comunica/tree/feature/dict-encoding
- https://github.com/rubensworks/rdf-stores.js/tree/feature/datafactory-encoded

Here's the difference in execution times on WatDiv: (Current is the dictionary-encoded version)
<img width="1120" alt="Screenshot 2024-05-23 at 13 51 24" src="https://github.com/comunica/comunica/assets/440384/4a3d0788-797e-4569-acd0-d0c39d616fa0">
