### ISSUE TITLE
Implement brTPF

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#881]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

With our current architecture, implementing support for brTPF should be fairly simple, and may open the door for interesting new research on federation across heterogeneous sources.

Sources:
* Hartig, Olaf, and Carlos Buil Aranda. "Reducing the Network Load of Triple Pattern Fragments by Supporting Bind Joins." International Semantic Web Conference (Posters & Demos). 2016.

Related to #335

**Comment by pietercolpaert** [comment]
How would one discover the fact that an interface supports BrTPF? Should we specify that somewhere?

**Comment by rubensworks** [comment]
At first glance, it doesn't appear to be described in the [brTPF paper](https://arxiv.org/pdf/1608.08148.pdf). But perhaps we should investigate the implementation to see if they have any special hypermedia controls.
