### ISSUE TITLE
How can I use the .well-know/genid for skolemization?

### ISSUE THREAD

**Issue by phochste** [comunica/comunica#890]
#### Issue type:

- :question: Question 

____
#### Question:

I see that some bindings return a skolemized version of blank nodes. E.g. when querying

```
@prefix : <http://example.org/> .

:s1 :p1 _:b1 .
_:b1 :p2 :o2 .
```

with `SELECT * FROM { ?s ?p ?o}` gives:

```
 Bindings:  [
  {
    "?s": {  "termType": "NamedNode",  "value": "http://example.org/s1" },
    "?p": { "termType": "NamedNode", "value": "http://example.org/p1" },
    "?o": {
      "termType": "BlankNode", "value": "bc_0_b4_b11",
      "skolemized": { "termType": "NamedNode", "value": "urn:comunica_skolem:source_0:b4_b1" }
    }
  },
 ...
```

In the RDF spec there is way to create Skolem IRI-s that are recognizable outside the boundaries (of the comunica system) using a well-known IRI (RFC5785) with the registered `genid`. See also [RDF 1.1 Concepts](https://www.w3.org/TR/rdf11-concepts/#section-skolemization).

How can I do that in Comunica? I would like all my bindings automatically use that well-known IRI.

**Comment by rubensworks** [comment]
Unfortunately, this is not really something that a client-side engine such as Comunica can do.
Such IRIs should be minted by authoritative servers.
If clients would do this, the IRI minting strategy could be different.
