### ISSUE TITLE
querying Allegrograph SPARQL endpoint fails

### ISSUE THREAD

**Issue by mathib** [comunica/comunica#891]
#### Issue type:

- :bug: Bug 

____
#### Description:

I tried to execute a simple SELECT query over a single source, being a SPARQL endpoint (no auth). I provided the `type` parameter set to `sparql` to the Comunica query engine, as I believe there might not be any SPARQL endpoint description available.

Doing the same query with the same `accept` (application/sparql-results+json) and `content-type` (application/x-www-form-urlencoded) headers as in the Comunica logs, but now in Postman, does return the correct results (response body will contain application/sparql-results+json content and the response header will say application/sparql-results+json;charset=UTF-8).

If no `Accept` header is given, the response body will contain application/sparql-results+json content by default, but the response header will say application/json;charset=UTF-8. 

If needed, I can provide the SPARQL endpoint link for testing in a PM.

____
#### Environment:

Windows 10 - node.js application
@comunica/actor-init-sparql@1.22.3
SPARQL endpoint: assume Allegrograph (behind a proxy)

#### Crash log:

```[2021-11-19T09:47:35.455Z]  INFO: Requesting https://myendpoint.org/sparql {
  headers: {
    accept: 'application/sparql-results+json;q=1.0,application/sparql-results+xml;q=0.7',
    'content-length': '69',
    'content-type': 'application/x-www-form-urlencoded',
    'user-agent': 'Comunica/actor-http-node-fetch (Node.js v16.4.1; win32)'
  },
  method: 'POST',
  actor: 'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher'
}
[myroot\myfolder\node_modules\fetch-sparql-endpoint\lib\SparqlEndpointFetcher.js:89
            throw new Error('Unknown SPARQL results content type: ' + contentType);
                  ^

Error: Unknown SPARQL results content type: text/html
    at SparqlEndpointFetcher.fetchBindings (myroot\myfolder\node_modules\fetch-sparql-endpoint\lib\SparqlEndpointFetcher.js:89:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on Readable instance at:
    at SimpleTransformIterator.<anonymous> (myroot\myfolder\node_modules\@comunica\actor-sparql-serialize-json\lib\ActorSparqlSerializeJson.js:29:52)
    at SimpleTransformIterator.emit (node:events:394:28)
    at TransformIterator.destinationEmitError (myroot\myfolder\node_modules\asynciterator\dist\asynciterator.cjs:1055:23)
    at TransformIterator.emit (node:events:394:28)
    at myroot\myfolder\node_modules\asynciterator\dist\asynciterator.cjs:959:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by rubensworks** [comment]
I've successfully used Comunica over Allegrograph before (with forced type), so I'm surprised that this is not working.

> Error: Unknown SPARQL results content type: text/html

This seems to indicate that the server is producing an (HTML-formatted) error message. Can you see anything within the Allegrograph logs?

It might also be interesting to execute your query using http://query.linkeddatafragments.org/ (endpoint URL prefixed with `sparql@`), and observe the executed HTTP requests using the browser's debug tools.

> SPARQL endpoint: assume Allegrograph (behind a proxy)

May also be a problem with the proxy.

**Comment by mathib** [comment]
I was able to locate the issue with our backend. It had something to do with the proxy service failing when multiple values (with or without ´q´) are entered in the Accept header of an HTTP request. Thanks for your feedback!
