### ISSUE TITLE
Mark resulting quad stream in IActorRdfDereferenceOutput interface as Readable

### ISSUE THREAD

**Issue by julianrojas87** [comunica/comunica#893]
#### Issue type:

- :bug: Bug 

____
#### Description:
The resulting quad stream defined by the [`IActorRdfDereferenceOutput`](https://github.com/comunica/comunica/blob/593a28050b0cef45d5d521744018112c507e8566/packages/bus-rdf-dereference/lib/ActorRdfDereference.ts#L108) interface is defined as an `RDF.Stream`, which is a subset of a Node.js stream and does not include methods like `pipe()`, causing Typescript issues when handling the object as stream instead of as a EventEmitter.

Marking the resulting quad stream as a `Readable` too will prevent these issues:
```js
import { Readable } from 'stream';
import type * as RDF from '@rdfjs/types';
...
export interface IActorRdfDereferenceOutput extends IActorOutput {
    ...
    /**
     * The resulting quad stream.
     */
    quads: RDF.Stream & Readable;
    ...
}
```

____
#### Environment:
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.22.3 (dev)
| node                | v16.13.0
| npm                 | 8.1.0
| yarn                | 1.22.4
| Operating System    | linux (Linux 5.4.0-90-generic)

**Comment by rubensworks** [comment]
Fixed in Comunica 2.
