### ISSUE TITLE
Result stream of actor-init-sparql-rdfjs never ends in case of specific SPARQL patterns

### ISSUE THREAD

**Issue by ssstolk** [comunica/comunica#901]
#### Issue type:

- :bug: Bug 

____
#### Description:

Executing a SPARQL query in the browser, using the actor-init-sparql-rdfjs package and an N3.Store, fails to end its stream in case of specific SPARQL patterns. When a query contains the "DISTINCT" keyword or the "ORDER BY" clause, for instance, the JSON result stream provides the header, but is not continued (or 'end'ed) beyond it. Once those keywords or patterns are removed from the SPARQL query, however, the query yields results and the stream indeed 'end's.

To circumvent this problem, I currently remove or adjust the following patterns from a SPARQL query, programmatically, whenever actor-init-sparql-rdfjs is used instead of a call to the URL of a triplestore SPARQL endpoint. I have had to add these last two patterns since the upgrade from a version from a year ago, or so, to the latest version.

```
query = this.removeSubClassOfPaths(query);
query = this.expandPropertyPaths(query);
query = this.removeUnionsWithZeroOrMorePropertyPath(query);
query = this.removeOrderBy(query);
query = this.removeDistinct(query);
```

As it stands, this comunica package does not indicate which SPARQL patterns will fail to provide an appropriate response. For developers, it would be very welcome to receive an error or a warning whenever a query is executed using this package that is known to not be handled correctly. (Or, alternatively, for the query to be adjusted by the package to ensure it will still run, which I now do in my own code, with a message informing of the change). Considering different patterns may work or not work in different versions of this package (i.e., the last two patterns are new in causing issues), such warnings can at least prevent developers from bug hunting for a day or two.

Offtopic: Being able to use an RDF store in the browser is simply superb. My thanks to you for having developed this marvelous library!

____
#### Environment:

    "@comunica/actor-init-sparql-rdfjs": "^1.22.3",
    "asynciterator": "^3.2.1",
    "n3": "^1.11.2",

**Comment by rubensworks** [comment]
I'm glad you're enjoying Comunica!

I'm not sure if I fully understand the problem.
So the RDF/JS engine never ends its result stream when the query contains an `ORDER BY` or `DISTINCT`?

If a result stream doesn't end, either the query is very slow, or an error has occurred and isn't caught.
Are you listening to the `'error'` event on the [result stream](https://comunica.dev/docs/query/getting_started/query_app/#3-1-consuming-binding-results-as-a-stream)?
Perhaps sharing a minimal reproducible case might help to debug this problem.

> For developers, it would be very welcome to receive an error or a warning whenever a query is executed using this package that is known to not be handled correctly.

That's what the `'error'` event should do :-)

**Comment by ssstolk** [comment]
Yes, that is the issue. The 'error' event on the stream is never triggered, though, and the query should (apart from the ORDER BY or DISTINCT, apparently) not pose an issue in terms of length/speed. If I remove these keywords or clauses, the query returns results speedily (i.e., I certainly don't have to wait minutes for the two result hits). With ORDER BY or DISTINCT, it seems to run for indefinite length.

**Comment by rubensworks** [comment]
May be related to #872.

**Comment by ssstolk** [comment]
Do not think they are related. In the example below, the "console.log(resultString);" is never reached when the query contains the DISTINCT keyword. The line above it is reached, though. Console logs that I temporarily added to the stream events indicate what I mentioned above. The headers of the JSON result are already provided, but not the results. If I remove the DISTINCT keyword and run it on the same Store, there is not a hitch.

```
        let queryOutput, error;
        try {
            queryOutput = (await this.engine.query(query, 
                { sources: [ { type: 'rdfjsSource', value: this.store } ] })) as IActorQueryOperationOutput;
        }
        catch (e) {
            error = e;
        }
        
        if (!queryOutput) {
            console.log("Sparql request failed on local storage\r\n" + error);
            return EmptySparqlJsonResult;
        }

        const result = await this.engine.resultToString(queryOutput, 'application/sparql-results+json');
        const resultString = await this.streamToString(result.data);
        console.log(resultString);  
```
```
    protected streamToString (stream: NodeJS.ReadableStream): Promise<string> {
        const chunks: Buffer[] = [];
        return new Promise((resolve, reject) => {
            stream.on('error', reject);
            stream.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
            stream.on('close', () => resolve(Buffer.concat(chunks).toString('utf8')));
            stream.on('data', chunk => { chunks.push(chunk); });
        })
    }
```

**Comment by MadsHolten** [comment]
I'm also experiencing some weird behavior when querying an N3 Store. To confirm that this is where the problem lies, I have tried serializing the store to ttl and query that, which works.

The following query gives me correct results (749 bindings in my example file):
```sparql
SELECT * WHERE { ?s a ?class }
```

But when I extend the pattern, the result is no longer correct. The following query returns only 4 results although it should return 749*4:
```sparql
SELECT * WHERE { ?s a ?class ; ?p ?o }
```

The results I do get, correspond to all additional bindings that relate to the first *?s*. Then the execution stops. In my example:
```
?s ?cl ?p ?o
:0%24B7CWCb97LujYsg0EZSIF bot:Interface rdf:type bot:Interface
:0%24B7CWCb97LujYsg0EZSIF bot:Interface ex:expressID 38820
:0%24B7CWCb97LujYsg0EZSIF bot:Interface bot:interfaceOf :2OBrcmyk58NupXoVOHUtgP
:0%24B7CWCb97LujYsg0EZSIF bot:Interface bot:interfaceOf :0%24B7CWCb97LujYsg0EZSIF
```

I also experience that the stream never ends.

**Comment by rubensworks** [comment]
Query processing has changed quite a bit in Comunica 2, could you retry again to see if the problem still occurs?

If it still occurs, could you provide a minimal reproducible example for us to fix the problem?
