### ISSUE TITLE
Utility type for Medator<Actor<...>...> pattern

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#902]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

The pattern `Medator<Actor<...>...>` is quite common and a little cumbersome when writing a bunch of new packages. I'm thinking it would be useful to have the following utility type in `@comunica/types` that captures this pattern (though I'm not sure if I have chosen the best name for it).

```ts
type Mediated<I extends IAction, O extends IActorOutput, T extends IActorTest = IActorTest> = Mediator<Actor<I, T, O>, I, T, O>;
```

The result being that

```ts
public readonly mediatorRdfParse: Mediator<Actor<IActionRdfParse, IActorTest, IActorRdfParseOutput>,
  IActionRdfParse, IActorTest, IActorRdfParseOutput>;
```
becomes
```ts
public readonly mediatorRdfParse: Mediated<IActionRdfParse, IActorRdfParseOutput>;
```

If you think it is appropriate I'm happy to create a PR that adds this type and upgrade the rest of the codebase to use it.

**Comment by rubensworks** [comment]
I've added something similar in the `next/major` branch quite recently: https://github.com/comunica/comunica/commit/d160c8f074e98bf0e857a9a530322a7f54dcd807
So this will land in the next major release.
Would this meet your needs?

**Comment by jeswr** [comment]
Ah nice! I'll follow that pattern of exporting a custom mediator type in the [reasoning packages](https://github.com/comunica/comunica-feature-reasoning/tree/experimental-development/packages) I am working on.
