### ISSUE TITLE
breaking feature: generic dereference bus

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#909]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

Extending discussion in #907 .

Now that there only appear to be 3 dereference actors (fallback, file and http) this should be more straightforward (I'm assuming actor-rdf-dereference-paged-next is deprecated rather than moved to another package location).

A rough implementation would be:

The `bus-dereference` package would be similar to `bus-rdf-dereference` with the exception of the output being a Readable stream of `string`s rather than `quad`s.

`actor-rdf-dereference-fallback` would become `actor-dereference-fallback` with almost no other changes

`actor-rdf-dereference-file` would become `actor-dereference-file`
Rather than having `mediaMappings` provided in the constructor, this would instead be provided as an input parameter on the `run` and `test` calls (This change would actually happen in `ActorRdfDereferenceMediaMappings`).

`actor-rdf-dereference-http` would become `actor-dereference-http`
Same change with `mediaMappings` as input and a 'hook' to a `ParseMediatypes` call.
Though I feel like there has to be a better way of doing this than providing a hook to a function call.

Then any usages of `mediatorRdfDereference` can be replaced with a composition of `mediatorDereference` and `mediatorRdfParse`.

**Comment by rubensworks** [comment]
> The bus-dereference package would be similar to bus-rdf-dereference with the exception of the output being a Readable stream of strings rather than quads.

Perhaps this should be a generic type so that the user can still fill in that it will return a stream of quads?

> Same change with mediaMappings as input and a 'hook' to a ParseMediatypes call.
> Though I feel like there has to be a better way of doing this than providing a hook to a function call.

An async callback may be a good solution indeed (probably 2 will be needed).

I initially had something in mind where the new dereference actors would become abstract, and accept an abstract parsing mediator in its constructor, so that the dereference actors could be instantiated multiple times for different parsing mediators. But I actually think your solution is simpler, and more flexible.

**Comment by jeswr** [comment]
> Perhaps this should be a generic type so that the user can still fill in that it will return a stream of quads?
Sure I'll do this for the draft PR - it shouldn't affect the rest of the implementation much anyway; but what would be the use case for this?

> An async callback may be a good solution indeed (probably 2 will be needed).
Ok - I'll draft a PR with this approach, and can move to your alternative if any problems arise.

**Comment by rubensworks** [comment]
> Sure I'll do this for the draft PR - it shouldn't affect the rest of the implementation much anyway; but what would be the use case for this?

Perhaps I'm misunderstanding this, but the generics would be used to enable something roughly  like:

```
export interface IDereferenceActionOutput<T> {
  results: Stream<T>;
}
```

This could then be filled in with `RDF.Quad`, `ShExShape`, `EntailmentRule`, ...

In case I misunderstood things, feel free to just make the draft PR as you had in mind. Might be easier to discuss based on that.
