### ISSUE TITLE
breaking: Sparql Queryoperators Set

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#910]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

For the reasoning [sparql-queryoperators](https://github.com/comunica/comunica-feature-reasoning/blob/alpha/packages/actor-init-sparql-reasoning/config/sets/sparql-queryoperators.json) the config is identical to that of `actor-init-sparql` except for the [quad pattern operator](https://github.com/comunica/comunica-feature-reasoning/blob/b939ae60ce5a1167e70a13c70523fa0b59ac2e66/packages/actor-init-sparql-reasoning/config/sets/sparql-queryoperators.json#L184-L192) with the rest of the file copy/pasted.

Similarly this appears to be the case in link traversal [sparql-queryoperators](https://github.com/comunica/comunica-feature-link-traversal/blob/master/packages/actor-init-sparql-link-traversal/config/sets/sparql-queryoperators.json) which as far as I can tell simply adds `ActorQueryOperationBgpTraversal`.

To prevent this repetition I think each operator in that it would be useful if the config were defined in its own "subset" file, e.g. `config-sets:subsets/sparql-queryoperators/ask.json` etc.

And then the  `sparql-queryoperators` file would look something like:

```jsonld
{
  "@context": [...],
  "@id": "urn:comunica:my",
  "import": [
    "config-sets:subsets/sparql-queryoperators/ask.json",
    "config-sets:subsets/sparql-queryoperators/service.json",
    "config-sets:subsets/sparql-queryoperators/slice.json",
    ...
  ]
}
```

**Comment by rubensworks** [comment]
Perfect timing, I was just about to look into refactoring the configs today :-)
