### ISSUE TITLE
Projection can contain out of scope variables

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#914]
#### Issue type:

- :bug: Bug 

____
#### Description:

This is just an issue to keep track of https://github.com/joachimvh/SPARQLAlgebra.js/issues/89

**Comment by joachimvh** [comment]
This is fixed in v4.0.2

**Comment by rubensworks** [comment]
Thanks @joachimvh!
For readers of this issue, resetting your lockfile and reinstalling should fix the problem.
