### ISSUE TITLE
Package production bundle with `init` actors

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#916]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

Packages like React include a [production build](https://unpkg.com/react@16.7.0/umd/react.production.min.js) - this means that they can be directly loaded from sites like [unpkg](https://unpkg.com/) into applications.

It would be useful if the comunica init actors did this so they could be directly required into code.

**USE CASE:**

A team that I am currently working with is trying to build SOLID apps using the [flutter framework](https://api.flutter.dev/index.html) (and in turn the [dart language](https://dart.dev/)) - I'm working on making packages like Comunica and LDflex available to our front end developers.

I am doing this by loading bundled versions of these packages into the applications' webpage, and then creating some wrappers in dart that interact with the Javascript API's (hopefully I will be able to release a generic open-source solution for this at some point).

**Comment by rubensworks** [comment]
We have a CDN with browser builds available for all versions here: https://github.com/rdfjs/comunica-browser
Does that solve your case?

**Comment by jeswr** [comment]
Looks like it should do the trick - thanks!

Any chance of including `actor-init-sparql-solid` in there once v2.0.0 is released - I've been having some troubles packaging it up (created issue with details in that repo).

**Comment by rubensworks** [comment]
Sure, we can definitely do that!
