### ISSUE TITLE
Refactor `promiseEventEmitter`

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#925]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

Just an issue to track https://github.com/comunica/comunica/pull/922#discussion_r802383063 so it doesn't get lost in the PR

**Comment by rubensworks** [comment]
I guess the helper is so simple, that we don't need to fill up our issue tracker for it, so let's close this one, and just fix it if the need ever exists.
