### ISSUE TITLE
Encryption components

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#929]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

This issue is here to track the Comunica side of https://github.com/solid/community-server/issues/1133.

I also wanted to propose a rough 'roadmap' for the implementation of this feature:
- (1) Build a naive parser and serializer which pass the input/output streams through the encrypt/decrypt functions from a library like https://www.npmjs.com/package/string-crypto (unfortunately I'm struggling to find any libraries that work on streams so the stream would have to be stringified each time), and then negotiate to the standard RDF parser/seralizer actors.
 It should be possible to build this on top of the existing rdf-parse and rdf-serialize actors; I don't *think* there is a need to introduce specific decrypted-rdf-parse and decrypted-rdf-serialize components, but I could be wrong.
  I'd say this should be done initially in a separate repo and build upon Comunica 2.x.x once that is released.
- (2) Look into RDF specific encryption techniques like those mentioned in https://github.com/solid/community-server/issues/1133#issuecomment-1031299375

**Comment by rubensworks** [comment]
> It should be possible to build this on top of the existing rdf-parse and rdf-serialize actors; I don't think there is a need to introduce specific decrypted-rdf-parse and decrypted-rdf-serialize components, but I could be wrong.
I'd say this should be done initially in a separate repo and build upon Comunica 2.x.x once that is released.

👍

**Comment by rubensworks** [comment]
Since this issue doesn't require any impl in comunica, I'm assuming this can be closed.
