### ISSUE TITLE
Better type inference in ActionContext

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#933]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

It would be nice to not have to explicitly specify the type of the output in the `.get` rather than just having types enforced; i.e.

```ts
const MY_KEY = new ActionContextKey<boolean>('my-key');
const context = new ActionContext();
// This is currently inferred as unkonwn, I would want this to be inferred as a boolean
const value = context.get(MY_KEY);
```

This should be possible by making use of `infer` with the implementation looking something like

```ts
type IContextKeyValueType<Type> = Type extends (IActionContextKey<infer X> | ActionContextKey<infer X>) ? X : null
function get<V, K extends IActionContextKey<V>>(k: K): IContextKeyValueType<K> | undefined;
```

**Comment by rubensworks** [comment]
Yes, definitely! PR is certainly welcome. Can probably be done in a backward-compat manner I guess.

**Comment by rubensworks** [comment]
Yeah, I also spent some time on getting this to work a while ago, but gave up because it was taking up too much time (and there were more urgent things waiting for me then).
