### ISSUE TITLE
generate READMES

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#935]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

Similar to how the components folder is auto-generated, would it make sense to also have the README's autogenerated at some point in the future?

**Comment by rubensworks** [comment]
They can already mostly be generated using the generator tool, so the manual effort should already be minimal.
Perhaps a way to regenerate them when changes are made in the package might be valuable indeed.
