### ISSUE TITLE
Add option to set default graph to the union graph

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#936]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

By default, the default graph will be all triples that are not contained in a named graph. But it might also make sense to add a config option to change this behaviour so that _all_ triples are contained in the default graph, even if they exist in another named graph.

We can probably do this via a config/context option to quad query operation actor, or by creating a new dedicated actor for this.

This would also require exposing the proper service description option when setting up a SPARQL endpoint: https://www.w3.org/TR/sparql11-service-description/#sd-uniondefaultgraph

**Comment by jeswr** [comment]
It may be worth giving some more fine-grained control at the same time by also allowing one to specify set of named graphs that map to the default graph (or any other graph for that matter).

The main usecase I am thinking of for this is to enable inter-graph reasoning/querying.

**Comment by rubensworks** [comment]
@jeswr That might be valuable indeed.
(FYI, this behaviour can already be achieved using the `FROM` syntax within SPARQL queries)
