### ISSUE TITLE
Propagate removal of data listeners on AsyncIterator

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#950]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

If we have a SPARQL query with a LIMIT, it is noticable that that engine will continue running for a little bit.
This is because Comunica produces a bunch of chained AsyncIterators, some of which have a buffer.
Even if you slice an AsyncIterator for a given LIMIT, the upstream AsyncIterators with buffers will still keep on filling this buffer for a while.
We should look into somehow propagating this information upstream.

This can be especially problematic in the context of link traversal, where you may have a LIMIT 1 query. If the documents you traverse over only contains the required data once, the query engine will in fact keep on traversing indefinitely, because it tries to fill the internal buffer, even though it will never find additional information, and it never even will need it.

We could for example achieve this by adding something like `iterator.close({ propagate: true })` to AsyncIterator.

@RubenVerborgh Perhaps you may have some thoughts on this?

**Comment by RubenVerborgh** [comment]
I think `destroy` has the desired effect? It has a corresponding `destroySource` constructor parameter.

**Comment by rubensworks** [comment]
> I think destroy has the desired effect? It has a corresponding destroySource constructor parameter.

Right, that would work indeed.

@RubenVerborgh What would your recommendation be in the case of our limit-actor?
Currently, we implement `LIMIT` via this `.transform` call with ` limit` value: https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-slice/lib/ActorQueryOperationSlice.ts#L67
Should Comunica listen to the `'end'` event, and invoke `.destroy()`? Or should AsyncIterator be modified so that it invokes `.destroy()` once the limit is reached? (a similar issue arises for `toArray` with limit)

**Comment by RubenVerborgh** [comment]
> Should Comunica listen to the `'end'` event, and invoke `.destroy()`?

This, or:

> Or should AsyncIterator be modified so that it invokes `.destroy()` once the limit is reached?

But with a `destroy: true` option then, I think.

---

Unless we change policy on AsyncIterator and always destroy the source iterator from the derived one, unless `destroySource` is set.

**Comment by rubensworks** [comment]
> Or should AsyncIterator be modified so that it invokes .destroy() once the limit is reached?
> But with a destroy: true (destroySource: true?) option then, I think.

Ok, that seems like the cleanest option.

----

> Unless we change policy on AsyncIterator and always destroy the source iterator from the derived one, unless destroySource is set.

I just checked the code again, and it looks like this may be the intended behaviour: https://github.com/RubenVerborgh/AsyncIterator/blob/08d47ccb1f26f0bb15defb7f921ae0b495506554/asynciterator.ts#L1040

(would only apply to `.transform()`, `.toArray()` not (yet))
