### ISSUE TITLE
Delete the ActorRDFParse class (and possibly rename ActorRdfParseFixedMediaTypes -> ActorRDFParse)

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#959]
#### Description:

[The class](https://github.com/comunica/comunica/blob/4c66bfaa44f73786bc7403504e5fe571181430c7/packages/bus-rdf-parse/lib/ActorRdfParse.ts#L27-L34) is not actually used anywhere [other than this test suite](https://github.com/comunica/comunica/blob/4c66bfaa44f73786bc7403504e5fe571181430c7/packages/bus-rdf-parse/test/ActorRdfParse-test.ts#L1-L19) so there isn't really any point in having it as far as I see.

**Comment by rubensworks** [comment]
I looked into it some more, and I think we should keep it, in case developers would want to add parsers that have no prior defined media types (e.g. parsing that is handled through some external service).
