### ISSUE TITLE
Locks for Update Queries

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#960]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

It may be useful to introduce the concept of an optional update lock - which is used to indicate whether a source is currently being updated. In the context of reasoning we have similar locks, and it would be useful to have the ability to lock updates when performing incremental reasoning, so that inferences can be produced in a more controlled environment.

**Comment by rubensworks** [comment]
Related to #810.
