### ISSUE TITLE
GraphDB endpoints not playing nicely with Comunica

### ISSUE THREAD

**Issue by appliedgraphs** [comunica/comunica#962]
#### Issue type:

- :bug: Bug 

____
#### Description:

I think this one is very closely related to [#535](https://github.com/comunica/comunica/issues/535) but I've struggled to apply anything from that issue.  The problem is that when trying to query a GraphDB endpoint, I see that Comunica thinks it is a file.  In #535, Ruben mentions using a _type_ parameter but from the CLI's help, I only see `--inputType` and `--outputType`.   I have a feeling this is staring me right in the face but I can't seem to close the gap!

`comunica-sparql http://localhost:7200/repositories/myrepo \
-q "SELECT * WHERE { ?s ?p ?o } LIMIT 100"`

Gets me the error:

`[2022-03-18T17:17:57.032Z]  INFO: Identified as file source: http://localhost:7200/repositories/myrepo { actor: 'urn:comunica:default:rdf-resolve-hypermedia/actors#none' }
Could not retrieve http://localhost:7200/repositories/myrepo (HTTP status 400):
Missing parameter: query`

____
#### Environment:

| software         | version
| ---------------- | -------
| Comunica Engine  | 2.0.6 
| node             | v16.14.2
| npm              | 8.5.0
| yarn             | _Yarn is unavailable_
| Operating System | darwin (Darwin 21.2.0)

**Comment by rubensworks** [comment]
Can you try forcing the source type with `comunica-sparql sparql@http://localhost:7200/repositories/myrepo \ -q "SELECT * WHERE { ?s ?p ?o } LIMIT 100"`?

**Comment by appliedgraphs** [comment]
Works!  I knew it was going to be simple.  Did I miss this in the docs somewhere, Ruben?

**Comment by rubensworks** [comment]
Yeah, this is considered an advanced feature, so that's why you may not have seen it before.
It's explained here: https://comunica.dev/docs/query/advanced/source_types/

**Comment by appliedgraphs** [comment]
Thanks a ton for the insanely quick help.
