### ISSUE TITLE
Using a local installation of comunica with `yarn link`

### ISSUE THREAD

**Issue by remodietlicher** [comunica/comunica#964]
#### Issue type:

- :question: Question 

____
#### Question:

I want to link against a local installation of comunica in one of my projects so that I can quickly investigate and hopefully resolve issues that might come up. I'm fairly new to the JavaScript ecosystem which is why I suspect I got something fundamentally wrong. It looks like the best way to use a local installation of a package is using `yarn link`. However, when I try to do that, I get an error. Here is the simplest thing I could think of to highlight what I want to achieve:

1. clone comunica (git@github.com:comunica/comunica.git)
2. build comunica (`yarn install` in the base directory as suggested by the readme) - is this necessary?
3. `cd engines/query-sparql`
4. `yarn link`
5. clone my test-repo (outside of comunica): https://github.com/remodietlicher/node-comunica-test
6. In there: yarn link @comunica/query-sparql
7. yarn install
8. yarn build - fails with https://pastebin.com/Kxh7Mndn

This process somehow still produces a `main.js` file which seems to run fine (`node main.js`). When getting `@comunica/query-sparql` from npm (`yarn add @comunica/query-sparql`), I do not get any errors when building my project (`yarn build`).

Can someone explain what's going on here or, even better, guide me on how to set this up properly?

**Comment by rubensworks** [comment]
It looks like your tsconfig settings are much stricter than comunica's, which causes your compiler to complain about things in the linked comunica project. One solution may be to (temporarily) alter your tsconfig file to match with comunica's. It may be possible to also somehow exclude `.ts` files from comunica during compilation of your project, but not sure how to do that exactly.

**Comment by remodietlicher** [comment]
That's what I thought aswell, so I copied over the tsconfig.json from comunica (https://github.com/comunica/comunica/blob/master/tsconfig.json) to my project (https://github.com/remodietlicher/node-comunica-test/blob/master/tsconfig.json). From your answer I gather that the overall approach should nevertheless work? I'm a bit confused on how to use comunica due to it's "meta-query-engine"-nature. Can I just link to an individual engine/package?

**Comment by rubensworks** [comment]
> That's what I thought aswell, so I copied over the tsconfig.json from comunica (https://github.com/comunica/comunica/blob/master/tsconfig.json) to my project

Does this solve your problem?

In any case, we may want to make the default tsconfig settings of comunica a bit stricter, so it works out-of-the-box in most projects when linking.

> I'm a bit confused on how to use comunica due to it's "meta-query-engine"-nature. Can I just link to an individual engine/package?

Yes, you should be able to link in separate comunica packages/engines into your project.

**Comment by jacoscaz** [comment]
Whenever I need to work with a local version of Comunica (as opposed to one from NPM) I tend to link all of it into whatever project I am working on as documented at https://github.com/belayeng/quadstore-comunica#linking-comunica . This is probably not great but it did help with dependency issues that do not show up when using NPM packages.

**Comment by remodietlicher** [comment]
Thanks for your answers and sorry for my late reply.

@rubensworks , I checked the tsconfig.json files before submitting the error. The error is what I get when I use the same config as comunica.

@jacoscaz thanks for sharing, I will definitely give this a try and report back here!

**Comment by rubensworks** [comment]
Considering this resolved. Feel free to re-open if this is not the case.
