### ISSUE TITLE
Let Greenkeeper watch all packages

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#97]
Currently, Greenkeeper only watches the root package.json dependencies.

They are however [working on monorepo support](https://github.com/greenkeeperio/greenkeeper/issues/594), so we should keep an eye on that.

**Comment by RubenVerborgh** [comment]
Are we sure this is not going to turn into a massive headache? I've seen repos where 70% of commits are by Greenkeeper, might be a total nightmare with monorepos.

**Comment by rubensworks** [comment]
No idea tbh, I have no experience with Greenkeeper myself. I heard good things about it, which is why I wanted to try it here.

I suggest to definitely try Greenkeeper on the root package for a while. We can probably extrapolate that experience then for the whole monorepo (for when it will be supported).

**Comment by rubensworks** [comment]
Monorepo support has been added: https://github.com/greenkeeperio/greenkeeper/issues/594#event-1665976999

https://greenkeeper.io/docs.html#monorepo

**Comment by RubenVerborgh** [comment]
I'm not sure you want greenkeeper. I think regular npm audit should be fine.

**Comment by rubensworks** [comment]
The problem is that we are using yarn lockfiles, and we configured yarn as the main package manager, so we can't use npm audit out-of-the-box. Not sure how npm audit would easily work in monorepos.

I have yet to encounter any problems with greenkeeper. So I'd like to give it a try :-) Disabling it again is just a click away.

**Comment by RubenVerborgh** [comment]
I just dislike the mess of automated commits it creates, but your call of course!

**Comment by rubensworks** [comment]
First PR of non-root packages has been processed, no problems so far. Let's see how it progresses in the future.

(Also improved the automatic commit messages a bit: https://github.com/comunica/comunica/commit/4624f070567dcf7c09faa25088a08c78f475ec64)
