### ISSUE TITLE
Make sure that bindstreams are not started until streams are read

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#970]
#### Issue type:

- :snail: Performance issue 

____
#### Description:

A potential source of performance degredation / unnecessary network requests (mainly for complex queries and reasoning components, or queries with no results), is if the collection of data from a source, before the first element of a bindingStream is read. This is because in the case of some joins, there may be results that produce no results. Once this fact has been established, the remaining bindingStreams to be joined; can be closed before they retrieve data from the source.

In addition to this, I would suggest an `actor-rdf-join-inner-empty` actor that uses metadata to detect if any of the incoming `bindingStream`s have an exact zero cardinality (in the test method), and outputs an empty binding stream.

**Comment by rubensworks** [comment]
All of the things you describe _should_ be happening already (with `autoStart: false`). If this is not the case, then there is probably going something wrong somewhere.

> In addition to this, I would suggest an actor-rdf-join-inner-empty actor that uses metadata to detect if any of the incoming bindingStreams have an exact zero cardinality (in the test method), and outputs an empty binding stream.

`actor-rdf-join-inner-multi-empty` should do the same thing.

**Comment by rubensworks** [comment]
Considering this resolved. Feel free to re-open if this is not the case.
