### ISSUE TITLE
Feat: Performance testing

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#971]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

Draft bounty description for https://github.com/RubenVerborgh/AsyncIterator/issues/62 - to add performance testing to Comunica, and critical upstream packages via CI/CD.

I would imagine that in general, the workflow would update a file of test results if there is a performance improvement, and error if there is a performance degredation.

Also see https://github.com/SolidLabResearch/Challenges/issues/23

Acceptance Criteria:
 - Performance benchmarks (via workflows) when *pull requests are made to the main branch* and *new commits are made to the main branch* on each of the engine configurations that is published against various queries, including those defined in https://github.com/comunica/rdf-test-suite-ldf.js.
    - Tests should be made with respect to various sources (files, in-memory, (mocked) remote etc); bonus marks for testing against different in-memory sources (N3, Graphy, QuadStore etc.)
    - Bonus marks for doing this in other Comunica repos such as https://github.com/comunica/comunica-feature-reasoning/ and https://github.com/comunica/comunica-feature-link-traversal
    - Bonus marks for testing specific actor packages; such as joins, and caching actors
 - Fine-grained benchmarks on all commonly used patterns in the [AsyncIterator](https://github.com/RubenVerborgh/AsyncIterator) package; especially those that [target recent optimization work](https://github.com/RubenVerborgh/AsyncIterator/issues/44). This includes
    - Use of each single transformation available on the `AsyncIterator` (i.e. `map`/`filter`/`skip`/`limit`/`transform` etc.); tested transforming `Buffered` and `Synchronous` sources; on both large and small amounts of data
    - Testing chaining of various composed transformations on `AsyncIterator` (i.e. `iterator.map(...).map(...).filter(...).transform(...)` etc.); tested transforming `Buffered` and `Synchronous` sources; on both large and small amounts of data.
    - Testing other utility operators like `union` with Synchronous and Buffered sources with large and small amounts of data.
- CI/CD workflows for the [existing performance tests](https://github.com/rdfjs/N3.js/tree/main/perf) of [n3.js](https://github.com/rdfjs/n3.js)  

All of the above benchmarks should be performed on all Maintained/Active/Current [versions of node](https://nodejs.org/en/about/releases/). A bonus would be to also perform evaluations on the SpiderMonkey engine (used by Firefox).  
 
Pointers:
 - https://github.com/benchmark-action/github-action-benchmark may be a good tool to achieve this

**Comment by rubensworks** [comment]
Having something like this that shows performance differences across different releases would be very valuable:

![](https://pbs.twimg.com/media/FVzYeORXsAEOTCl?format=jpg&name=large)

Found via https://twitter.com/Danlark1/status/1539344322281328641

**Comment by rubensworks** [comment]
@jeswr Could you split this issue so we can place bounties on the separate parts?
