### ISSUE TITLE
Link Traversal

### ISSUE THREAD

**Issue by jaxoncreed** [comunica/comunica#978]
#### Issue type:

- :question: Question 

____
#### Question:

Hey all, I asked @RubenVerborgh if Comunica has link traversal, and he said it did, but I can't find any documentation on that.

I tried to set up a SPARQL query in the editor to prove that it supports link traversal (http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fjackson.solidcommunity.net%2Fprofile%2Fcard%23me&query=SELECT%20%3Ffriend%20%3FfriendName%20WHERE%20%7B%0A%09%3Chttps%3A%2F%2Fjackson.solidcommunity.net%2Fprofile%2Fcard%23me%3E%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2Fknows%3E%20%3Ffriend.%0A%20%20%20%20%3Ffriend%20%3Chttp%3A%2F%2Fwww.w3.org%2F2006%2Fvcard%2Fns%23fn%3E%20%3FfriendName.%0A%7D), but it doesn't seem to traverse links.

In the query above, I provide my Solid Profile as the sole datasource, and I ask for the name of all my friends (via foaf:knows). The only name that comes up is my own name because I'm my own friend and my name is stored in the same document. But all my other friends have names in their own documents. Maybe I misunderstood what "link traversal" meant, but I would expect it to see the linked files and fetch them as well.

Is there a feature I need to enable to do link traversal? Is this a feature that has yet to be built? If so, is it within the scope of Comunica?

**Comment by RubenVerborgh** [comment]
Then you have not seen https://comunica.github.io/comunica-feature-link-traversal-web-clients/builds/default/#datasources=https%3A%2F%2Fjackson.solidcommunity.net%2Fprofile%2Fcard%23me&query=SELECT%20%3Ffriend%20%3FfriendName%20WHERE%20%7B%0A%09%3Chttps%3A%2F%2Fjackson.solidcommunity.net%2Fprofile%2Fcard%23me%3E%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2Fknows%3E%20%3Ffriend.%0A%20%20%20%20%3Ffriend%20%3Chttp%3A%2F%2Fwww.w3.org%2F2006%2Fvcard%2Fns%23fn%3E%20%3FfriendName.%0A%7D 😉

**Comment by jaxoncreed** [comment]
Wow! That's super cool. Do you know where the documentation on how to enable that feature is?

**Comment by RubenVerborgh** [comment]
Super, let us know if you have further questions!

**Comment by rubensworks** [comment]
@jaxoncreed Here's an overview page with all the information: https://comunica.dev/research/link_traversal/

Just a warning: this is all very experimental still, so breaking changes may occur at any point in time.
