### ISSUE TITLE
2 update spec tests failing silently

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#989]
#### Issue type:

- :bug: Bug 

____
#### Description:

See https://github.com/comunica/comunica/runs/6121871670?check_suite_focus=true#step:11:358

**Comment by rubensworks** [comment]
That seems problematic.
But the weird thing is that it only seems to occur in that run.
Locally it works fine, and also in the other runs it seems.

**Comment by jeswr** [comment]
So looking at recent runs of the workflows - it seems that 156/156 of the spec tests are consistently passing.

My concern lies in the fact that if we start to fail spec tests again - then this *will not* trigger a failing CI/CD test. I think the requirement for this issue to be closed is an update to the [CI workflow](https://github.com/comunica/comunica/blob/0ad833f8f32f7e3c2de1b22a0424da027656bf6a/.github/workflows/ci.yml#L45-L48) that results in the job failing if *any* spec or integration tests are unsuccessful.

I suspect the best solution will be to create a PR for [rdf-test-suite](https://github.com/rubensworks/rdf-test-suite.js/) which has the script exit with a code 1 if one or more spec tests are failing.

**Comment by rubensworks** [comment]
>  it seems that 156/156 of the spec tests are consistently passing.

Yay 😅 

> I suspect the best solution will be to create a PR for [rdf-test-suite](https://github.com/rubensworks/rdf-test-suite.js/) which has the script exit with a code 1 if one or more spec tests are failing.

Luckily, @Tpt recently fixed this: https://github.com/rubensworks/rdf-test-suite.js/commit/72bea155644508eafd0e10397d73744b8a6cf910
So I'm assuming it's safe to close this issue for now.

**Comment by jeswr** [comment]
Ah perfect!
