### ISSUE TITLE
Querying graphdb results in a lot of requests

### ISSUE THREAD

**Issue by zeroxbt** [comunica/comunica#994]
#### Issue type:

- :bug: Bug 

____
#### Description:

Query to GraphDB results in a lot of requests.

Code example with screenshot of the logs: https://gist.github.com/zeroxbt/6cfede66e5104471d303b69372ebb51f

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| €272 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment]
You're setting the source type correctly, so I don't immediately see what is going wrong here.

What happens when you remove the `destination` from your context?

**Comment by zeroxbt** [comment]
Hi @rubensworks, thanks for the fast response. Removing the `destination` key from the context object solved the issue. I had this since I used the same context for storing datasets in GraphDB. Should I then have two different context objects depending on the type of query ?

**Comment by rubensworks** [comment]
Aha, great to hear that this fixes to problem.
(it's still a bug though, so we should leave this issue open)

> I had this since I used the same context for storing datasets in GraphDB. Should I then have two different context objects for the two different type of queries ?

If the endpoint for updating is the same (URL) as the one for querying, then you don't have to define a separate `destination` in your context. It is a different, then you will indeed require the context as you have defined it.

But in any case, it's definitely possible that different queries have different contexts.

**Comment by rubensworks** [comment]
For reference, the following actor should pass the test method, but it's not: https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-sparql-endpoint/lib/ActorQueryOperationSparqlEndpoint.ts#L57-L77

**Comment by andrewzhurov** [comment]
This is an interesting case, thanks for bringing it up, @zeroxbt.

A brief sum up.
We have two distinct sparql endpoints, one's for querying for data, other's for updates.
In a local setup of GraphDB, by default, they are:
```
http://localhost:7200/repositories/<repository>
http://localhost:7200/repositories/<repository>/statements
```
We set them as source and destination.

In order for Comunica to execute an update query it needs to query data from the source and update data via the destination. We can't get over the need for this orchestration.

However, there is always space for optimisations.=)
In case we have just one sparql endpoint (which is also the case when source and destination are the same) - Comunica could hand off query to it entirely, this clever optimisation is brought to us by the forementioned actor. This wouldn't apply in our case, as we have two distinct endpoints.

It seems to me, we also could hand off query to source endpoint even when there is a distinct destination endpoint set, given this query only gets data and does not do an update. This would apply in our case, as our query does not perform an update.

Another optimisation, given it's not as crazy as it looks from a glance and generally makes sense, could be, given we have an update query, decompose it onto a select query, which can be handed over to sparql source endpoint, and update query, which will be executed by Comunica with results of select query.

Or so it seems to me, would love to hear thoughts of domain-savvy folks on it. @rubensworks, what do you think?

**Comment by rubensworks** [comment]
> We have two distinct sparql endpoints, one's for querying for data, other's for updates.

Ah, I wasn't aware that GraphDB did this. In that case, it does indeed make sense that Comunica processes things this way, since it can not know that those endpoints refer to the same dataset.
@zeroxbt Can you confirm that this is indeed the case?
If so, then this is not a bug, and the issue can therefore be closed.

Thanks for the findings @andrewzhurov!

> It seems to me, we also could hand off query to source endpoint even when there is a distinct destination endpoint set, given this query only gets data and does not do an update. This would apply in our case, as our query does not perform an update.

> Another optimisation, given it's not as crazy as it looks from a glance and generally makes sense, could be, given we have an update query, decompose it onto a select query, which can be handed over to sparql source endpoint, and update query, which will be executed by Comunica with results of select query.

> Or so it seems to me, would love to hear thoughts of domain-savvy folks on it. @rubensworks, what do you think?

Those optimizations would indeed be good to have. This is what would be achieved through #609. This would require some big breaking changes though.

**Comment by rubensworks** [comment]
Considering this a non-issue then.
