### ISSUE TITLE
Lazily generate logger data

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#996]
#### Issue type:

- :snail: Performance issue 

____
#### Description:

[Some logging data](https://github.com/comunica/comunica/blob/5b2dd7af8d6d5a546f3b7d92b5b374bb93ba374e/packages/mediator-join-coefficients-fixed/lib/MediatorJoinCoefficientsFixed.ts#L84-L93) can have non-negligble computational cost, or contain blocking `await`s. As such it would be useful to lazily generate this data so that it is *only generated* when the relevant logging level is enabled. This could be implemented by making the data parameter in the logger a callback.

____

**Comment by rubensworks** [comment]
We already have a callback to only generate data if a logger is active: https://github.com/comunica/comunica/blob/5b2dd7af8d6d5a546f3b7d92b5b374bb93ba374e/packages/core/lib/Actor.ts#L118-L123

However, what we don't have yet indeed, is a way to only generate data if the relevant logger level is active.

Not sure how easy it would be to implement the latter though, as it may require some changes thay may be incompatible with the winston logger library.

**Comment by rubensworks** [comment]
Considering this resolved. Feel free to re-open if this is not the case.
