### ISSUE TITLE
Migrate away from lerna

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#997]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

Since [lerna](https://github.com/lerna/lerna) is not being maintained anymore, we look into migrating to another tool to manage our monorepo. (https://github.com/lerna/lerna/issues/2703)

The only functionality we really depend on is the publishing part.

Related to #931

Some migration options:

- https://medium.com/autodesk-tlv/lerna-has-gone-which-monorepo-is-right-for-a-node-js-backend-fc075cad51b0
- https://yarnpkg.com/features/workspaces#publishing-workspaces (#931)
- https://github.com/ghiscoding/lerna-lite
- https://rushjs.io/
- https://github.com/google/wireit
- Pnpm
- Turborepo

**Comment by jacoscaz** [comment]
As Comunica is a long-term project, I would suggest using `npm` (or `yarn`) alone with the `workspace` feature and possibly coming up with a publishing script of our own. I do realize that this sounds like a lot of effort but I've repeatedly made this choice in the past and I've always seen it pay dividends after a couple of years.

**Comment by rubensworks** [comment]
> I would suggest using npm (or yarn) alone with the workspace feature

👍 to workspaces.

> possibly coming up with a publishing script of our own

Not sure about this one. At the very least, we need some logic to order packages by dependency relationships (e.g. so that core comes first, then types, ...). Once we have such as script, anything else is trivial, and we can implement this ourselves. But if possible, I would try to avoid reinventing the wheel, and reuse some existing tool to determine such package ordering.

Since many monorepos exist, I don't expect us to have many issues in finding a proper tool we can use.

**Comment by jacoscaz** [comment]
Comunica does have a complex dependency tree, indeed. In fact, it's by far the most complex of all the monorepos I've worked on and what I am suggesting might indeed be counter-productive.

> Since many monorepos exist, I don't expect us to have many issues in finding a proper tool we can use.

My concern is not with the absence of one such tool but, rather, with its long-term stability and maintenance. As a general guideline, I think the fewer dependencies we have, the better off we are in the long term. But you're right, there's a point after which you're literally reinventing the wheel and that would clearly be going too far.

**Comment by rubensworks** [comment]
Don't get me wrong, I'm definitely open to something self-baked, but the only problem with that is the time-effort that might be required for it. (but if you're up to it, feel free :-) )

**Comment by rubensworks** [comment]
Oh interesting. Looks like we'll have to update 🙂

**Comment by juristr** [comment]
yeah definitely let me know how that goes. This is a 5.1 beta but we're going to have a stable probably around mid June sometimes.

**Comment by rubensworks** [comment]
Closing this, now that lerna is actively being maintained again.
