### ISSUE TITLE
Make `ResolveQuadPattern` actors only require a `RDF.BaseQuad` as a pattern

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#999]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

The type in https://github.com/comunica/comunica/blob/fb76e4c44a886638ac066fd4db7bfd852eef7915/packages/bus-rdf-resolve-quad-pattern/lib/ActorRdfResolveQuadPattern.ts#L32 be `RDF.BaseQuad` since it contains all the information needed, and `Algebra.Pattern` extends from this type.

The current type is causing a few annoyances when trying to use this bus in reasoning components.

**Comment by rubensworks** [comment]
In #609, I was actually thinking of going into the opposite direction, and changing the type to `Algebra.Operation`.

So not sure about this change. I guess it's feasible to convert a quad to a pattern using the algebra's factory?

**Comment by rubensworks** [comment]
@jeswr Do you agree with closing this issue? Or is it something you can't work around?

**Comment by jeswr** [comment]
IIRC it can be worked around
